### ISSUE TITLE
Wrong indenting level of if case 

### ISSUE THREAD

**Issue by gragera** [nicklockwood/SwiftFormat#1]
First of all, this tool looks very good, nice job! :)

I found this issue while executing the tool in a fairly large codebase

<img width="418" alt="screen shot 2016-08-22 at 23 31 07" src="https://cloud.githubusercontent.com/assets/287089/17872483/8aadfafc-68c0-11e6-8e17-7e016170a889.png">

I think the image is pretty much self-explanatory, the original if is in the right place

Regards,

**Comment by nicklockwood** [comment]
Heh, I didn't know "if case" was a thing! I'll add a new test for it. Thanks!

**Comment by nicklockwood** [comment]
Fixed in 0.2
