### ISSUE TITLE
`case some(Void)` is formatted as `case someVoid`

### ISSUE THREAD

**Issue by tgrapperon** [nicklockwood/SwiftFormat#1002]
Hello,
I've encountered the following formatting when updating some enum's associated value type while debugging:
```swift
enum Enum {
  case some(Void)
}
```
is formatted as
```swift
enum Enum {
  case someVoid
}
```
This seems triggered by `Void` as `some(Int)` stays the same as expected.
SwiftFormat 0.48.11 (1) on Xcode.

**Comment by nicklockwood** [comment]
@tgrapperon fixed in 0.48.12
