### ISSUE TITLE
Xcode 13.0 warning no such SDK: macosx

### ISSUE THREAD

**Issue by xianglibytecenture** [nicklockwood/SwiftFormat#1009]
How should I update this script?
```
cd BuildTools
SDKROOT=macosx
#swift package update #Uncomment this line temporarily to update the version used to the latest matching your BuildTools/Package.swift file
swift run -c release swiftformat "$SRCROOT"
```

**Comment by rlziii** [comment]
I believe you should replace:

`SDKROOT=macosx`

with:

`SDKROOT=(xcrun --sdk macosx --show-sdk-path)`

Hopefully the documentation will be updated soon with this (or a similar) fix.
