### ISSUE TITLE
Comments not sorted alongside enum case when using sortedSwitchCases

### ISSUE THREAD

**Issue by nagra** [nicklockwood/SwiftFormat#1012]
Hi,

I noticed comments on sorted alongside enum case when using sortedSwitchCases.
This issues is similar to the one caused when using wrapEnumCases:
https://github.com/nicklockwood/SwiftFormat/issues/1011

Before:
```
switch self {
    case
        .one, // one
        .two, // two
        .four, // four
        .three: // three
            return "string"
}
```

After:
```
switch self {
    case
        .four, // one
        .one, // two
        .three, // four
        .two: // three
            return "string"
}
```
Thanks,
Kam

**Comment by nicklockwood** [comment]
@nagra can you include an example for this? Thanks.

**Comment by nagra** [comment]
@nicklockwood I've updated the original description 🙂.
