### ISSUE TITLE
Backtick is removed for `Self`

### ISSUE THREAD

**Issue by abeintopalo** [nicklockwood/SwiftFormat#102]
Hi,

First, I'd like to thank you for this awesome tool. I use it in project build phase and it is really good. :)

I'm coming from Objective-C background and I missed the Self keyword in classes. So, I usually use a pattern like this in my classes:

```
class ClassWithALongClassName  {
   typealias `Self` = ClassWithALongClassName

   static let someConstant = 5

   func someFunction() {
       var someVar = Self.someConstant
   }

...
}
```

So, could you please patch SwiftFormat tool not to remove backticks for Self.

Thank you

BTW: I was using version 0.25.1

**Comment by nicklockwood** [comment]
@abeintopalo fixed in 0.25.2. Thanks!
