### ISSUE TITLE
Question: what's the rule name of replacing `struct` with `enum`?

### ISSUE THREAD

**Issue by superarts** [nicklockwood/SwiftFormat#1034]
I see there's a rule that changes class type from `struct` to `enum` if there are no properties inside. I checked [the rules](https://github.com/nicklockwood/SwiftFormat/blob/master/Rules.md) but can't find it, could someone help please?
  
```
-    private struct Store {
+    private enum Store {
```

**Comment by Cyberbeni** [comment]
enumNamespaces
