### ISSUE TITLE
trailingCommas rule adds extra commas to closure capture list

### ISSUE THREAD

**Issue by honghaoz** [nicklockwood/SwiftFormat#1043]
For following code
```swift
class Foo {

  let title: String = ""
  let topView: UIView = UIView()

  func foo() {
    UIView.animate(withDuration: 0.333) { [
      title = title,
      weak topView = topView, // <-- can't have "," 
    ] in
      print(title)
      _ = topView
    }
  }
}
```
Rule `trailingCommas` adds extra comma at the end of the list, which makes the code fail to compile:
The error is `Expected 'weak', 'unowned', or no specifier in capture list`

<img width="742" alt="CleanShot 2021-10-13 at 19 45 05@2x" src="https://user-images.githubusercontent.com/3926785/137241951-7ff51588-83d4-4312-8755-e7cf20ae8184.png">

Tested on Xcode 13.0.

**Comment by nicklockwood** [comment]
@honghaoz ah thanks - I see the problem. It only happens when there is a comment after the second line. I removed the comment along with the comma before when testing and so the comma wasn't added.

**Comment by honghaoz** [comment]
hmm, that's interesting, I event didn't realize the comment affects the formatting.
actually my original code doesn't have the comment, instead it uses string interpolation:
```swift
import UIKit

class Foo {

  let title: String = ""
  let topView = UIView()

  func foo() {
    UIView.animate(withDuration: 0.333) { [
      title = title,
      fooTitle = "title: \(title)",
      weak topView = topView,
    ] in
    print(title)
    _ = topView
    }
  }
}
```
this code also produces incorrect comma,

---
even if I remove comments and string interpolation, I also noticed that if I have a comma on the last line, running `swiftformat .` doesn't remove the comma.
```swift
import UIKit

class Foo {

  let title: String = ""
  let topView = UIView()

  func foo() {
    UIView.animate(withDuration: 0.333) { [
      title = title,
      weak topView = topView,
    ] in
    print(title)
    _ = topView
    }
  }
}
```
