### ISSUE TITLE
Invalid redundantSelf when using @State property wrapper

### ISSUE THREAD

**Issue by c0diq** [nicklockwood/SwiftFormat#1044]
SwiftFormat incorrectly prompts to remove `self` with this simple example:

Test.swift:9:1: warning: (redundantSelf) Insert/remove explicit self where applicable.
Test.swift:10:1: warning: (redundantSelf) Insert/remove explicit self where applicable.

```
import SwiftUI

struct Test: View {
    @State var foo: Int
    @State var bar: Int

    init() {
        let foo = 3
        self._bar = State(initialValue: foo)
        self._foo = State(initialValue: foo)
    }

    var body: some View {
        Text("Hello, World!")
    }
}
```

**Comment by nicklockwood** [comment]
@c0diq I'm not able to reproduce this when using

```swift
swiftformat --self init-only --lint <file>
```

Perhaps I'm missing something?
