### ISSUE TITLE
Add section in README.md under `How?` for rules_swiftformat

### ISSUE THREAD

**Issue by cgrindel** [nicklockwood/SwiftFormat#1053]
I recently released [cgrindel/rules_swiftformat](https://github.com/cgrindel/rules_swiftformat), a set of [Bazel](https://bazel.build/) rules and macros that use SwiftFormat to format Swift source files as part of the build process. Would you be open to a PR that adds a section under `How?` that mentions the repository and provides a link to the quickstart?

**Comment by nicklockwood** [comment]
@cgrindel sure 👍
