### ISSUE TITLE
Redundant self inside of something that is in expect() from Nimble

### ISSUE THREAD

**Issue by lethef-tomorrow** [nicklockwood/SwiftFormat#1058]
I know that this issue is already known and actually redundantSelf is already disabled for this method, but in the cases where I have to write for example:
`expect(AddressValidator().validate(street1: self.thirtyFiveCharacters)).to(equal(.valid))`
(where self is not directly in the expect(), but in something else in that is in expect()) redundant self is still a problem. 

Is this a bug on your side, or am I doing something wrong here.

**Comment by nicklockwood** [comment]
@lethef-tomorrow fixed in 0.48.18
