### ISSUE TITLE
Indention question: should multi-line strings be indented?

### ISSUE THREAD

**Issue by superarts** [nicklockwood/SwiftFormat#1069]
I wonder what you guys think about this format change done by SwiftFormat. It's a bit tricky because I would have this in most of the cases:

```swift
let string = getString("""
   xx1
   xx2
""")
```

But for command lines, this would result additional spaces in between each lines, thus the pre-change code below. I wonder if the formatted code below is more preferable.

```swift
         let gitLogs = try os.shell("""
-            git --no-pager log \
-            --ancestry-path \(base)..\(head) \
-            --pretty=format:'%D\(separator)%h\(separator)%s\(separator)%an\(separator)%ad' \
-            --date=iso8601
-            """)
+        git --no-pager log \
+        --ancestry-path \(base)..\(head) \
+        --pretty=format:'%D\(separator)%h\(separator)%s\(separator)%an\(separator)%ad' \
+        --date=iso8601
+        """)
```

**Comment by nicklockwood** [comment]
@superarts the next version of swiftformat will include an `--indentstrings true` option to handle this case.

**Comment by superarts** [comment]
Thank you @nicklockwood ! Looking forward to it!
