### ISSUE TITLE
`SwiftFormat` does not specify a Swift version (`4.2`) that is satisfied by any of targets (`name`) integrating it.

### ISSUE THREAD

**Issue by lanlinxl** [nicklockwood/SwiftFormat#1075]
This error occurred when I used pod Install, no matter the specified version or the latest version, I am not sure how to solve it, I need help！

**Comment by andecoder** [comment]
This is happening to me as well, everything worked fine with Cocoapods 1.10.2 but after updating to 1.11.2 I started getting this error

**Comment by nicklockwood** [comment]
@lanlinxl @andecoder I believe this should now work for version 0.49.0 - can you check?

**Comment by lanlinxl** [comment]
> 
It's working fine, thanks
