### ISSUE TITLE
RedundantReturn not working?

### ISSUE THREAD

**Issue by drekka** [nicklockwood/SwiftFormat#1076]
Hi, I've noticed that RedundantReturn is not removing `return` statements from code like this:

```swift
public var title: String {
    return offer.headline
}
```

Is this correct?

**Comment by nicklockwood** [comment]
@drekka what is your `--swiftversion` set to? It must be set to 5.1 or higher for return to be removed inside functions and computed properties (prior to 5.1, this was only supported in closures).

**Comment by drekka** [comment]
Cool. Will check
