### ISSUE TITLE
RedundantGet breaks code if getter can throw

### ISSUE THREAD

**Issue by Arthur-Guillaume** [nicklockwood/SwiftFormat#1088]
Rule RedundantGet break code it the getter of a computed property can throw.
example: 
```
enum Endpoint {
  case foo
  var url: URL {
    get throws {
                switch self {
                  case .foo:
                  return try URL(string: "https://my-wonderful-api.com/foo")
                }
  }
}
```
In this example, get is considered redundant whereas the code won't compile without `throws`.

**Comment by nicklockwood** [comment]
@Arthur-Guillaume can you check you're running the latest version of SwiftFormat? AFAIK this was fixed a while ago.

**Comment by Arthur-Guillaume** [comment]
@nicklockwood thanks for your quick answer. 

I was running an old version, update to 0.49 fixed this issue. 
Sorry about it.
