### ISSUE TITLE
Xcode Extension "Error: Unknown rule 'wrapMultilineStatementBraces'"

### ISSUE THREAD

**Issue by carlosefonseca** [nicklockwood/SwiftFormat#1092]
Am I missing something or is there an issue with `wrapMultilineStatementBraces` on the Xcode Extension? 🤔 

![CleanShot 2021-12-07 at 10 42 24](https://user-images.githubusercontent.com/14120/145014585-e812c472-ff8d-4b8c-9817-b7fc4e7ff8b9.png)

**Comment by nicklockwood** [comment]
@carlosefonseca apologies - it looks like I accidentally built the extension from the develop branch, which removes that rule. I'll ship a fixed version as soon as I can.

**Comment by nicklockwood** [comment]
@carlosefonseca fixed in 0.49.1
