### ISSUE TITLE
Could I off space between numbers and operator "..."?

### ISSUE THREAD

**Issue by Laravelk** [nicklockwood/SwiftFormat#1097]
<img width="500" alt="image" src="https://user-images.githubusercontent.com/24323162/145385590-d777c304-4760-486e-9d4e-5136ee811b0a.png">

Hello. Could you help please I want to off the rule in this case. Is it possible?

Which behavior I want to get: 
<img width="495" alt="image" src="https://user-images.githubusercontent.com/24323162/145385864-8a6f1230-73a6-4889-ba5e-992dc8784228.png">

My configuration file:
<img width="646" alt="image" src="https://user-images.githubusercontent.com/24323162/145386344-c651ff22-04bb-4031-8ede-6b08c89f60ff.png">

**Comment by nicklockwood** [comment]
Use `--ranges no-space`

**Comment by Laravelk** [comment]
Thank you
