### ISSUE TITLE
Reformat corrupted code

### ISSUE THREAD

**Issue by jomnius** [nicklockwood/SwiftFormat#11]
We have a debug feature to crash the application and we use this code:
`let crash: String? = nil; let _ = crash!
`

The "String? = nil" was reformatted as "String ?= nil" which does not compile

**Comment by nicklockwood** [comment]
Thanks for the report, I'll fix it for the next update.

**Comment by nicklockwood** [comment]
I can't seem to reproduce this. What version of SwiftFormat are you running?

Can you provide the whole file? (or a minimal file that still produce the error)

**Comment by nicklockwood** [comment]
I can't reproduce this on any version, so I'm going to assume you just got a bad build. If you are still seeing this on version 0.6, please reopen the ticket.

**Comment by jomnius** [comment]
That was 0.5.1, seems to be ok in 0.7.1. Thanx!
