### ISSUE TITLE
0.26.1 :  redundantself flag 

### ISSUE THREAD

**Issue by nasht** [nicklockwood/SwiftFormat#110]
Hey Nick :)

Our convention is to use the exact opposite of this rule. Is it possible to implement something like an `explicitself` flag? 

Great work on this tool!

Thanks,

Nash

**Comment by nicklockwood** [comment]
It's possible, but a bit more work - I'll consider it for a future release.

**Comment by nicklockwood** [comment]
@nasht implemented in 0.28.0. Add `--self insert` to your swiftformat options to always use `self` for member variables and functions.
