### ISSUE TITLE
How do I use decimalgrouping?

### ISSUE THREAD

**Issue by Jasperav** [nicklockwood/SwiftFormat#1103]
When I have this in my .swiftformat file:

```
--enable isEmpty
--enable wrapSwitchCases
--enable wrapEnumCases
--disable wrapMultilineStatementBraces
--maxwidth 80
--wraparguments before-first
--wrapparameters before-first
--wrapcollections before-first
--wrapconditions before-first
--decimalgrouping 3,4
```

it just ignores the `--decimalgrouping 3,4`. It doesn't format `1000` to `1_000`. 

When I run this in my command line:

`swiftformat --rules numberFormatting --decimalgrouping 3,4 .`

it will do the formatting.

To me it is unclear how I should apply the `decimalgrouping` through a .swiftformat file. It looks like it is some sort of sub rule of `numberFormatting`, but the documentation doesn't state how I should apply it in my .swiftformat file.

When I change my .swiftformat file like so, I get an error:

```
--enable isEmpty
--enable wrapSwitchCases
--enable wrapEnumCases
--disable wrapMultilineStatementBraces
--maxwidth 80
--wraparguments before-first
--wrapparameters before-first
--wrapcollections before-first
--wrapconditions before-first
numberFormatting --decimalgrouping 3,4
```

`error: Unknown option 'numberFormatting' in configuration file.`

**Comment by nicklockwood** [comment]
> it just ignores the --decimalgrouping 3,4. It doesn't format 1000 to 1_000.

A value of 3,4 means group every 3rd digit, starting after the 4th digit. I guess you want to use 3,3 instead (or just 3)?

**Comment by nicklockwood** [comment]
> To me it is unclear how I should apply the decimalgrouping through a .swiftformat file. It looks like it is some sort of sub rule of numberFormatting

numberFormatting is the rule, --decimalgrouping is the configuration. Rules are enabled using

--enable numberFormatting

and configuration options appear on a line by themselves:

--decimalgrouping 3

**Comment by Jasperav** [comment]
@nicklockwood `--decimalgrouping 3,3` in my .swiftformat file will still format `1_000` to `1000`. Note that when I invoke this through the command line:

swiftformat --rules numberFormatting --decimalgrouping 3,4 .

it keeps `1_000` as `1_000` (and changes `1000` to `1_000`)

**Comment by nicklockwood** [comment]
@Jasperav ah yes, you're right. It's an inclusive threshold, so 3,4 and 3, <4 are equivalent.

**Comment by Jasperav** [comment]
This config file still doesn't do the trick:

```
--enable isEmpty
--enable wrapSwitchCases
--enable wrapEnumCases
--enable numberFormatting
--disable wrapMultilineStatementBraces
--maxwidth 80
--wraparguments before-first
--wrapparameters before-first
--wrapcollections before-first
--wrapconditions before-first
--decimalgrouping 3,3
```

**Comment by nicklockwood** [comment]
If you're using --inferoptions, that works by analyzing the formatting in the files you pass, it doesn't output your config settings.

I tried your config and it worked for me. What command line options are you using to format the file?

**Comment by Jasperav** [comment]
Hmm that's strange.

This doesn't work, it changes `1_000` to `1000`:

```
--enable numberFormatting
--decimalgrouping 3,4
```

This does work, changing `1000` to `1_000`:

`swiftformat --rules numberFormatting --decimalgrouping 3,4 .`

**Comment by nicklockwood** [comment]
I think there's probably a problem with SwiftFormat not recognizing your .swiftformat file, or it being overridden by another config somehow. What does it print in the terminal when you run it?

**Comment by nicklockwood** [comment]
If you run `swiftformat . --config /absolute/path/to/your/.swiftformat` does it work then?

**Comment by nicklockwood** [comment]
Where is the .swiftformat file in relation to your swift file?

Can you screenshot the folder structure, or draw me an ascii diagram like:

```
project
  .swiftformat
  source
    foo.swift
```

**Comment by Jasperav** [comment]
Hmm I had the .swiftformat file inside my project, not in my project root, it worked after I moved it to my root dir. My bad :(

**Comment by nicklockwood** [comment]
Makes sense. .swiftformat files are applied hierarchically, so they only apply to files in the same directoty or child directories of the one they are in.

**Comment by nicklockwood** [comment]
(If you'd prefer to put it elsewhere, you can specify the path explicitly with the --config argument)
