### ISSUE TITLE
Feature Request - Xcode format all files

### ISSUE THREAD

**Issue by JulesMoorhouse** [nicklockwood/SwiftFormat#1106]
It would be super useful to have an option to format all swift files in Xcode.

I'm picturing, before you commit your files, you run this feature and fix any issues.

I know you can do this at the command line, but it would be much more convenient to have it in Xcode.

I think there would also need to be a confirmation message.

Merry Christmas..

**Comment by nicklockwood** [comment]
@JulesMoorhouse this would of course be ideal, but unfortunately Apple doesn't expose the necessary hooks in the Xcode Extensions API to make this possible.

**Comment by JulesMoorhouse** [comment]
@nicklockwood i assume you mean the all files part not the alert?

**Comment by nicklockwood** [comment]
@JulesMoorhouse both Xcode only exposes the currently open file to the extension, not the project path.

**Comment by JulesMoorhouse** [comment]
@nicklockwood 🙄

**Comment by JulesMoorhouse** [comment]
@nicklockwood if I wanted to run 'swiftformat .' from my top level project folder, rather than cd into the folder where my swift files are and back out before using git etc, what’s the easiest way to do this?

**Comment by nicklockwood** [comment]
The "." in "swiftformat ." is the path. You can replace it with a path like "swiftformat source/swift".

**Comment by JulesMoorhouse** [comment]
Ah ok 👍

**Comment by JulesMoorhouse** [comment]
Can I add the folder to a Config file so I can just run swiftformat ?

**Comment by nicklockwood** [comment]
SwiftFormat will search subfolders automatically, so you only really need to specify a path if there are files you *don't* want to format.

If that's the case, you can exclude the folders you don't want to format by putting

```
--exclude path
```

In your .swiftformat config file.
