### ISSUE TITLE
Use project specific configuration files in Xcode extension is possible

### ISSUE THREAD

**Issue by intitni** [nicklockwood/SwiftFormat#1108]
Hi, 

I believe I have found a workaround to enable the Xcode extension to read a ".swiftformat" configuration file at the root path of a project.

Here is a working version https://github.com/intitni/SwiftFormat/tree/read-project-configuration-experiment

The solution is that we can use a non-sandboxed XPC Service to call some apple script to get a file path of the opening Xcode window. The file path is usually the path of "xcodeproj" or "xcworkspace", or just the root path if it's a swift package.

Then we can search upwards for a .swiftformat file, read it, and pass it back to the extension.

To make the XPC Service work, we will have to set harden runtime - apple events to true for the extension app target. When running the extension's actions for the first time, we will see an alert asking if we allow it to call the apple script on Xcode.

If that's an acceptable feature, I would like to clean it up and submit a pull request this weekend ( • ̀ω•́ )✧

**Comment by nicklockwood** [comment]
That sounds like a great feature, a PR would be amazing! 🙏
