### ISSUE TITLE
blockcomments rules not working

### ISSUE THREAD

**Issue by prakashraman** [nicklockwood/SwiftFormat#1117]
Hi,

When I try to include the "--blockcomments" in my configuration file. It errors with

```
error: Unknown option --blockcomments. Did you mean --comments? in configuration file.
```

I am using 
```
swiftformat --version                                                    
0.49.1
```

Has the rule and/or the values changed?

Thanks!

**Comment by nicklockwood** [comment]
@prakashraman it's a rule rather than a configuration option, so you need to use `--enable blockComments`.

Thanks for mentioning this though - I should make the error message clearer.

**Comment by prakashraman** [comment]
Ah right! Thanks, it works now! Love your program btw, it's brilliant!
