### ISSUE TITLE
wrap/maxwidth in comment blocks

### ISSUE THREAD

**Issue by prakashraman** [nicklockwood/SwiftFormat#1118]
Is it possible to have comments wrap as well? Maybe based on the --maxwidth option?

**Comment by nicklockwood** [comment]
It's possible in theory, but there are a lot of edge cases, e.g if the comment contains code snippets.

**Comment by prakashraman** [comment]
Ah, ok. If it won't be much work could you point me the right direction? I'd like to give it a shot.

**Comment by prakashraman** [comment]
Great, thanks for the pointers @nicklockwood ! I shall give it go. And let you know how it goes!
