### ISSUE TITLE
CocoaPods potentially out of sync: 0.49.1 is still the latest available

### ISSUE THREAD

**Issue by Panajev** [nicklockwood/SwiftFormat#1126]
Hello @nicklockwood ,

Sorry if it is the "it is Monday it takes more than 23 hours for CocoaPods to pick up the new tag", but I am getting the following error if I try to get the 0.49.2 update:

> 
> [!] CocoaPods could not find compatible versions for pod "SwiftFormat/CLI":
>   In Podfile:
>     SwiftFormat/CLI (= 0.49.2)
> 
> None of your spec sources contain a spec satisfying the dependency: `SwiftFormat/CLI (= 0.49.2)`.

Which is consistent with the latest version advertised here: https://cocoapods.org/pods/SwiftFormat not sure if there is anything for you to do or if it is automatic.

Kind Regards,

Goffredo

**Comment by nicklockwood** [comment]
@Panajev it's not you, I forgot to push the update - I'll do it now..

**Comment by nicklockwood** [comment]
@Panajev now fixed.

**Comment by Panajev** [comment]
Thank you @nicklockwood  :).
