### ISSUE TITLE
error: redundantClosure rule timed out.

### ISSUE THREAD

**Issue by shkhaliq** [nicklockwood/SwiftFormat#1153]
I just upgraded to SwiftFormat `0.49.5` and I am running into the above error. I tried running in verbose to find out exactly what file is causing it but verbose didn't help

Verbose output:
```
error: 1 file could not be formatted.
```

I was able to reproduce this issue in 0.49.4 as well but not on 0.49.3. Is there a way to get more verbose logs on exactly the file that caused it? Or do we know why this suddenly started happening

**Comment by nicklockwood** [comment]
@shkhaliq presumably it's an infinite loop in the `redundantClosure` rule. If you run with `--verbose` mode it should log all of the files as it formats them, so the last one that was logged should be the one that failed.

**Comment by nicklockwood** [comment]
@shkhaliq @jgoldhammer fixed in 0.49.7
