### ISSUE TITLE
Can't build because warning "'temporaryDirectory' is only available in macOS 10.12 or newer"

### ISSUE THREAD

**Issue by dazy1030** [nicklockwood/SwiftFormat#1158]
## about
* Can't build because warning `'temporaryDirectory' is only available in macOS 10.12 or newer` at line 556 of CommandLine.swift.
* It may have something to do with 573ae3f445fadabdf3ad6c4fe37e2b88c88a9f81.
* If version `0.49.4` is specified in a similar environment, the build succeeds.

## environment
* SwiftFormat 0.49.6
* macOS 12.3
* Xcode13.3
* iOS App project (target iOS 15.0 or newer)
* use SPM.（I have introduced [this guideline](https://github.com/nicklockwood/SwiftFormat#xcode-build-phase).）
```swift
// swift-tools-version:5.6
import PackageDescription

let package = Package(
    name: "BuildTools",
    platforms: [.macOS(.v10_12)],
    dependencies: [
        .package(url: "https://github.com/nicklockwood/SwiftFormat", from: "0.49.0"),
    ],
    targets: [.target(name: "BuildTools", path: "")]
)
```

**Comment by nicklockwood** [comment]
@dazy1030 fixed in 0.49.7

**Comment by bilalb** [comment]
Hi,

I almost have the same issue on both 0.49.7 & 0.49.18:
> 'temporaryDirectory' is only available in iOS 10.0 or newer

I have tried to clean the project, remove derived data and reset package caches but nothing helped.
Do you have any suggestion to fix that?
Please let me know if I can provide any further information.

Thank you in advance

## Environment
- macOS 12.5.1
- Xcode 13.4.1
- iOS App project (target iOS 14.3 or newer)
- use SPM

**Comment by radekwilczak** [comment]
I have same issue as @bilalb. Checked with 0.49.7 & 0.49.18
On 0.49.4 I have this issue: https://github.com/nicklockwood/SwiftFormat/issues/424
I've added SwiftFormat through Package Dependencies on iOS Project in Xcode 13.4.1.
@nicklockwood  any ideas? ;)

**Comment by nicklockwood** [comment]
I'm not exactly clear how you can correct it, but it seems like the way you've integrated SwiftFormat means it's trying to build it *for iOS*, which isn't right.

Even if you are planning to format an iOS project, the SwiftFormat plugin should be built for macOS, in which case the iOS version you are targeting shouldn't matter?

**Comment by bilalb** [comment]
I've just realised SwiftFormat **should not** be added to the project's package dependencies 😅
So I've removed it and now everything works as expected 🎉 

Thanks your feedback and keep up the great work!

**Comment by radekwilczak** [comment]
@bilalb If not added as project's package dependencie - then how to add it through SPM?

**Comment by bilalb** [comment]
It should not be added via SPM, as described in [Xcode build phase > Using Swift Package Manager](https://github.com/nicklockwood/SwiftFormat#using-swift-package-manager)
