### ISSUE TITLE
Add detailed instructions for installing as pod 

### ISSUE THREAD

**Issue by garricn** [nicklockwood/SwiftFormat#116]
Hello :) Thank you for SwiftFormat.

I am trying to install SwiftFormat as a pod, again. This time with my team. I couldn't figure it out before. Now, with two other relatively experienced developers, we still can't figure it out. I think it would be helpful if there was a more detailed explanation of the requirements and a how-to.

I reached out to @shotat on Twitter and he said if I created the issue he might be able to create the instructions. He does not speak english. Perhaps @shotat could write the instructions in his/her native tongue and then we/I can translate from there.

Thank you!

**Comment by nicklockwood** [comment]
I've now used this feature myself a few times, and it seems fairly straightforward. In your Podfile, add the following to your target:

     pod 'SwiftFormat/CLI'

The CLI will then be installed in your Pods directory, typically at:

    "${SRCROOT}/Pods/SwiftFormat/CommandLineTool/swiftformat"

To run the script, put this in your run script build phase:

    "${SRCROOT}/Pods/SwiftFormat/CommandLineTool/swiftformat" "${SRCROOT}/YourSourceFolder" --someoptions

**Comment by nicklockwood** [comment]
@garricn did those instructions work for you? I've added them to the README for the next release.

**Comment by garricn** [comment]
Yes, I figured it out! I think the important thing was to run pod update first to get the latest version. It was installing 0.24.x. Thank you. I'm glad to hear you will update the README.

**Comment by shotat** [comment]
Thanks!
