### ISSUE TITLE
--lint doesn't fail with error for stdin

### ISSUE THREAD

**Issue by GusevAndrey** [nicklockwood/SwiftFormat#1160]
I try to detect if any changes needed during pre-commit:
```bash
git-format-staged --no-write --formatter "swiftformat --lint --config $SWIFT_FORMAT_CONFIG stdin --stdinpath '{}'" "*.swift" 
```
And getting no error neither other result to distinguish run caused formatting.
SwiftFormat: 0.48.18

**Comment by nicklockwood** [comment]
@GusevAndrey fixed in 0.49.7
