### ISSUE TITLE
Opposite of `elseOnSameLine`?

### ISSUE THREAD

**Issue by akaralar** [nicklockwood/SwiftFormat#117]
Thanks for a great formatting tool! I was wondering if it would be possible to get `else`, `catch`, etc break one line after `}` and start on a new line. Right now when `elseOnSameLine` is disabled, it doesn't enforce `else` to move to a new line. Would it be possible to get that as an option as well?

**Comment by nicklockwood** [comment]
That should be possible, yes.

**Comment by nicklockwood** [comment]
Implemented in 0.30.0 - sorry it took so song!
