### ISSUE TITLE
Question: Removing wrap brace rule?

### ISSUE THREAD

**Issue by JulesMoorhouse** [nicklockwood/SwiftFormat#1170]
![image](https://user-images.githubusercontent.com/361024/165263362-bdf19916-7d63-4645-92d6-0cc29f0eba65.png)

How can I turn off new line on braces ?

I thought `wrapMultiLineStatementBraces` would be the rule, but that doesn't work when I turn on or off in the SwiftFormat app, when using the command from the editor in Xcode, unless I need to restart Xcode after changing rules in the app ?

Thanks.

**Comment by nicklockwood** [comment]
In swiftformat terminology, "braces" are these "{" and these "(" are called "parens".

I think you want `--closingparen same-line`

**Comment by JulesMoorhouse** [comment]
Can I add that in the Swift Format app?
Can’t see it or a way to add custom rules

**Comment by nicklockwood** [comment]
In the SwiftFormat for Xcode extension app, it's listed as an option under the wrapArguments rule:

<img width="497" alt="Screenshot 2022-04-26 at 11 58 28" src="https://user-images.githubusercontent.com/546885/165285657-54bb80c9-e267-4695-8e4e-199eff2fbaf8.png">
