### ISSUE TITLE
Switching `Allman` does not re-format code

### ISSUE THREAD

**Issue by bdolewski** [nicklockwood/SwiftFormat#1172]
Hi!

Looks like it's broken in version `0.49.7`. Somehow cannot force `swiftformat` to move `{` to new lines.
This is my code - just stock project from Xcode:
```swift
import SwiftUI

@main
struct AllmanDemoBugApp: App {
    var body: some Scene {
        WindowGroup {
            ContentView()
        }
    }
}
```

**My config:**
```
--allman true
```

**Expected**:
```swift
struct AllmanDemoBugApp: App
{
    var body: some Scene
    {
        WindowGroup 
        {
            ContentView()
        }
    }
}
```

**Actual:**
No changes

**Comment by cn-bdolewski** [comment]
Okay, false alarm. Apparently I was passing wrong `config` to `SwiftFormat` hence the issue.
