### ISSUE TITLE
Wrong removal of self 

### ISSUE THREAD

**Issue by akaralar** [nicklockwood/SwiftFormat#118]
```
protocol P1 { }
protocol P2: P1 { }
class C1: P2 { }
class C2: P2 {
  let bar: C1? 
  func foo(transform: (P1) -> P1?) -> C2? {
    let bar: C1?
    if let b = self.bar, let b2 = transform(b) as? C1? {
      bar = b2
    } else {
      bar = nil
    }
    ...
  }
}
```

when I run swiftformat with a code block similar to the above, it removes `self.bar` in the `if let` binding, however it is actually necessary since there is a variable `bar` in that scope defined before the `if let` already.

**Comment by nicklockwood** [comment]
Fixed in 0.27.0
