### ISSUE TITLE
'brew install swiftformat' on M1 Mac: can't find the formula for swiftformat

### ISSUE THREAD

**Issue by rudifa** [nicklockwood/SwiftFormat#1185]
Asking for a friend @epajot:

On his M1 Mac, `brew install swiftformat` returns errors

```
Warning: No available formula with the name "swiftformat".
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
==> Searching for a previously deleted formula (in the last month)...
Error: No previously deleted formula found.
==> Searching taps on GitHub...
Error: No formulae found in taps
```

He also tried the rosetta terminal, with similar result.

Please advise.

@rudifa

**Comment by nicklockwood** [comment]
I'm not really a a brew expert, so you might have more luck asking on the homebrew issues page, but some things you could try are:

```
brew update
brew install swiftformat
```

or

```
arch -arm64 brew install swiftformat
```

**Comment by epajot** [comment]
Thx you Nick,

By upgrading Brew, SwiftFormat was updated automatically on my M1, (no need to use the Rosetta Terminal)

Really appreciate your way and congrats for your work and contribution for the swift's users,

Best regards
Eric
