### ISSUE TITLE
Incorrectly considers `$foo` unused when using `foo`

### ISSUE THREAD

**Issue by denizdogan** [nicklockwood/SwiftFormat#1190]
In this example, modified from an article from Swift by Sundell: https://www.swiftbysundell.com/articles/bindable-swiftui-list-elements/

```swift
struct NoteListView: View {
    @ObservedObject var list: NoteList

    var body: some View {
        List {
            ForEach($list.notes) { $note in
                Text(note.foobar)  // notice it says `note` and not `$note` – this is intentional
            }
        }
    }
}
```

Running the above through SwiftFormat generates this:

```swift
struct NoteListView: View {
    @ObservedObject var list: NoteList

    var body: some View {
        List {
            ForEach($list.notes) { _ in
                Text(note.foobar)  // Cannot find 'note' in scope
            }
        }
    }
}
```

Unless I'm mistaken, SwiftFormat _incorrectly_ determines that `$note` is unused since I only use `note` and not `$note`. There are situations where you want to use `$note` as the parameter but still use just `note`, such as this:

```swift
ForEach($vm.items) { $item in
    Button {
        item.enabled.toggle()  // this works, thanks to $item
    } label: {
        Text("\(item.name) is \(item.enabled ? "enabled" : "disabled")")
    }
}
```

It would not work without using `$item`.

Am I correct in thinking this is a bug?

**Comment by nicklockwood** [comment]
@denizdogan fixed in 0.49.10
