### ISSUE TITLE
redundantSelf not working all the time

### ISSUE THREAD

**Issue by tonyarnold** [nicklockwood/SwiftFormat#120]
There are a couple of situations where `redundantSelf` option isn't doing anything (and it probably should):

```swift
override var objectValue: Any? {
     didSet {
          self.bind(field: self.textField, to: self.viewModel)
    }
}
```

and 

```swift
private var viewModel: ConstantViewModel? {
     return self.objectValue as? ConstantViewModel
}
```

In both of these circumstances, I would expect the `self.` to be removed.

**Comment by nicklockwood** [comment]
Yeah, I knew about these. They were hard to get right so I decided to err on the side of not breaking code. I'll try and sort it for next release - thanks for the reminder 👍

**Comment by tonyarnold** [comment]
Yeah, that seems like sound thinking. Thanks, Nick!

**Comment by nicklockwood** [comment]
@tonyarnold fixed in 0.28.0

**Comment by supermarin** [comment]
Is this at least configurable? we're enforcing `self.` everywhere for the sake of consistency

**Comment by supermarin** [comment]
Oh sorry, just seen https://github.com/nicklockwood/SwiftFormat/issues/110#issuecomment-289115222. 👍

**Comment by fbartho** [comment]
Is this maybe regressed? I'm seeing failure to remove self :(

```
$ swiftformat --self remove "MyFile.swift"
```

**Comment by nicklockwood** [comment]
@fbartho can you include a sample file so I can check?

**Comment by fbartho** [comment]
Absolutely! I'll scrub the file of identifying details and prepare it shortly.

**Comment by fbartho** [comment]
Oh! In the process of simplifying the file I deleted something that made the failure occur. (I've retested with the full file. -- Now binary searching to find the line that confuses things.

**Comment by fbartho** [comment]
Include the following snippet in your file, and half or more of the `self` references won't be stripped!
```swift
class DangerField: UITextField {
    override var text: String? {
        get {
            return nil
        }

        set(newValue) {}
    }
}
```

Gist for full source file: https://gist.github.com/fbartho/7125c77d889dbcb6696b468810a4b428
