### ISSUE TITLE
[Question] clear out all space in blank new line when adding by `shift + O` in vim

### ISSUE THREAD

**Issue by ycchen24** [nicklockwood/SwiftFormat#1209]
I am new to Xcode and use `vim` and swift format for my editor and lint under Xcode. When using `shift + O` to add newline in vim under Xcode, it adds multiple space as indent? like following image

![Screen Shot 2022-07-01 at 10 54 35 PM](https://user-images.githubusercontent.com/45693208/177000057-7dc084d8-5fd3-4f28-9106-eb6ceacc4fb0.png)

how can I prevent that, so when I call `git diff`, it looks more like following

![Screen Shot 2022-07-01 at 11 06 24 PM](https://user-images.githubusercontent.com/45693208/177000060-bdf583d2-b077-426e-a970-5556f4b19286.png)
)

**Comment by nicklockwood** [comment]
@ycchen24 I'm not sure I entirely understand the question. To prevent Xcode adding this space you can disable it in the Xcode preferences (see screenshot).

Running swiftformat with the default config will also remove these spaces retroactively.

<img width="586" alt="Screenshot 2022-07-06 at 23 58 47" src="https://user-images.githubusercontent.com/546885/177657333-4b079d9d-5515-4836-83d9-8d00254d84c4.png">

**Comment by ycchen24** [comment]
Ooops thank you it works
