### ISSUE TITLE
Multiple attributes / @MainActor formatted as function

### ISSUE THREAD

**Issue by jshier** [nicklockwood/SwiftFormat#1217]
When formatting statements with one or more `@MainActor` attributes, the `@MainActor` seems to be treated as a function. For example:

```swift 
typealias Operation = @Sendable @MainActor (@MainActor (Action) -> Void) async -> Void
```

is formatted as

```swift
typealias Operation = @Sendable @MainActor(@MainActor(Action) -> Void) async -> Void
```
The original formatting is the correct one.

Unlike #1194, this project is configured for Swift 5.6 in the root config.

**Comment by nicklockwood** [comment]
@jshier fixed in 0.49.13
