### ISSUE TITLE
class with static var replaced by enum

### ISSUE THREAD

**Issue by technicat** [nicklockwood/SwiftFormat#1218]
Running swiftformat 0.49.12 from the shell on a file with just this

```
public enum TTSError: Error {}

public class TTS {
    static var ID: Int = 0
}

```
replaces the class with enum

```
public enum TTSError: Error {}

public enum TTS {
    static var ID: Int = 0
}
```
The key piece seems to be the static var, if that's removed, no problem

**Comment by technicat** [comment]
Hmm, well, OK, not so crazy about that rule, but the whole thing is working alright as an enum (it's got some static functions in there, too). Thanks.

**Comment by nicklockwood** [comment]
@technicat the idea behind it is that if you are using a type purely as a namespace, it makes sense to use an empty enum, which can't be instantiated and takes up no space in memory.

But if you don't like the rule you can disable it with `--disable enumNamespaces`.

**Comment by technicat** [comment]
Just seems hackish to me to use enums not to enum (reminds me of the Java practice of using interface classes to hold constants), but that's OK, if I really want to avoid it looks like I can use class instead of static for the properties.

**Comment by LePips** [comment]
Because Swift doesn't have namespaces, it's actually more appropriate to use an `enum` for the allocation reason over a class. I've done this and have worked with many who have as well.
