### ISSUE TITLE
Parsing fails for extension using angle bracket syntax

### ISSUE THREAD

**Issue by calda** [nicklockwood/SwiftFormat#1221]
As of Swift 5.7 / [SE-0361](https://github.com/apple/swift-evolution/blob/main/proposals/0361-bound-generic-extensions.md), the following syntax is valid:

```swift
extension Array<String> { 
  // ...
}
```

We'll probably want the `typeSugar` rule to update this to:

```swift
extension [String] { 
  // ...
}
```

which is also valid, and probably more idiomatic. I assume this would work properly with the existing implementation of the `typeSugar` rule, but this test case currently fails on `develop`:

```swift
func testExtensionTypeSugar() {
    let input = "extension Array<String> {}"
    let output = "extension [String] {}"

    // 🛑 XCTAssertEqual failed: threw error "Expected identifier on line 1"
    testFormatting(for: input, output, rule: FormatRules.typeSugar)
}
```

I assume this is a parsing issue, since this would not have been valid syntax in Swift 5.6 and earlier.

**Comment by nicklockwood** [comment]
@calda fix landed in 0.49.14
