### ISSUE TITLE
Inconsistent await tuple formatting between Xcode extension and command-line

### ISSUE THREAD

**Issue by simondelphia** [nicklockwood/SwiftFormat#1224]
* Originally commented on #1194, but still happening and think it deserves to be a separate issue

I am getting different behaviour for this between the command line and the Xcode extension.

 have a .swiftformat file in my repo, and I opened it in the "SwiftFormat for Xcode" app, and I made sure the command line and the app have the same version (0.49.13).
 
 EDIT: Still a problem in 0.49.14

When formatting a tuple with an `await` inside Xcode it makes it `await (` and the command line makes it `await(`

My .swiftformat file has --swiftversion 5.6 and I'm on Xcode 13.4.1 (13F100). SwiftFormat for Xcode is also showing Swift 5.6.

**Comment by nicklockwood** [comment]
@simondelphia can you share your .swiftformat file and a source example? I'm not able to reproduce this. If I have a file containing:

```swift
let foo = await (bar, baz)
```

And a `.swiftformat` file with just:

```
--swiftversion 5.6
```

And I run `swiftformat .` inside that directory, I get no changes. If I reduce the version to 5.4 then it removes the space after `await`.

If I try it with the Xcode plugin I get the same behavior. This all seems as expected.

**Comment by simondelphia** [comment]
Hm yea I copied the swiftformat file into a folder with a new blank project and put in a couple lines with `await (…, …)` and you're right it's working there, but not in my project.

**Comment by nicklockwood** [comment]
Do you have a `.swift-version` file in your project directory?

Also, when you run `swiftformat` from the terminal, does list any other `Reading config file at ...` paths?

**Comment by simondelphia** [comment]
Yes and yes.

`.swift-version` has `5.6.1` in it — the patch is probably unnecessary, but that seems like it shouldn't matter?

I also tried it with the `.swift-version` copied over to my test folder and it worked fine

**Comment by simondelphia** [comment]
I also just tried copying my whole project file into a separate folder with my config file and swift version file and it worked there.

**Comment by simondelphia** [comment]
Oh wow there's another .swift-version file in a subfolder that I did not notice. My bad @nicklockwood !

**Comment by simondelphia** [comment]
Might be helpful if the command line logs noted all the `swift-version` files it was referencing ?
