### ISSUE TITLE
`--swiftversion latest` option to automatically format according to the most recent available language version?

### ISSUE THREAD

**Issue by calda** [nicklockwood/SwiftFormat#1226]
We specify a `--swiftversion` flag in our `airbnb.swiftformat` file so that version-dependent format rule implementations use all of the latest language features. We have to [periodically update this](https://github.com/airbnb/swift/pull/169), so it can drift out of date.

Any thoughts on including a `--swiftversion latest` option, to automatically format according to the most recent available language version?

**Comment by nicklockwood** [comment]
Seems reasonable, although I think you could probably just set it to 999 or something and have the same effect?

**Comment by calda** [comment]
Good idea, if `--swiftversion 999` works then we probably don't need a `latest` option

**Comment by calda** [comment]
Cool, I do prefer `--swiftformat latest` from a semantic / self-documenting perspective. I'll make a PR.

**Comment by nicklockwood** [comment]
@calda I think based on the PR discussion we're not doing this, right?

**Comment by calda** [comment]
Yeah, I figured we can just leave it as-is since there isn't a clear / simple direction for inferring this. In our SPM package plugin that wraps SwiftFormat I did start grabbing the `Package.swift` `swift-tools-version` (https://github.com/airbnb/swift/pull/180) which I think works nicely for SPM packages, but there isn't a clean / simple way to do this for other types of projects.
