### ISSUE TITLE
Support for SCRIPT_INPUT_FILE_* variables

### ISSUE THREAD

**Issue by danyf90** [nicklockwood/SwiftFormat#1228]
Hello,
is there any plan to support the SCRIPT_INPUT_FILE_* variables passed by Xcode when input files are configured for a build action, similar to the `--use-script-input-files` [provided by Swiftlint](https://github.com/realm/SwiftLint/blob/86e765c4180d0d9883f5045d7550676c71520da8/Source/swiftlint/Helpers/LintOrAnalyzeArguments.swift#L30-L31)?

I am happy to help implementing this if needed 🚀

**Comment by nicklockwood** [comment]
Yes that makes sense. By all means open a PR - thanks!

**Comment by nicklockwood** [comment]
@danyf90 landed in 0.49.14
