### ISSUE TITLE
Add option for computed properties to `wrapAttributes`

### ISSUE THREAD

**Issue by bennokress** [nicklockwood/SwiftFormat#1232]
When using the rule `wrapAttributes` I would like to make a difference between stored properties and computed properties. The reason for this is especially when writing SwiftUI code I often write something like this:
```swift
struct ExampleScreen: View {

    @State var isExampleActive = false

    @ViewBuilder
    func someExampleViewElement(_ isEnabled: Bool) -> some View {
        isEnabled ? EnabledView() : DisabledView()
    }

    @ViewBuilder
    var anotherExampleViewElement: some View {
        isExampleActive ? EnabledView() : DisabledView()
    }

}
```
When formatting the code with the current set of options I always get either this (`--varattributes prev-line`):
```swift
    @State
    var isExampleActive = false
```
Or this (`--varattributes same-line`):
```swift
    @ViewBuilder var anotherExampleViewElement: some View {
        isExampleActive ? EnabledView() : DisabledView()
    }
```
While I completely dislike the first option and there's nothing wrong with the second option, I'd rather have computed properties behave like functions to get a more consistent code style. That's why I would like to propose adding a differentiation for `storedvarattributes` and `computedvarattributes`. Since that breaks the current implementation it could also be a solution to add `computedvarattributeaffiliation` with the options `func` or `var` (default). And maybe find a better name for that option 😅

**Comment by nicklockwood** [comment]
Implemented in 0.54.0
