### ISSUE TITLE
`unusedArgument` rule incorrectly removing "async" keyword from closure

### ISSUE THREAD

**Issue by bdrelling** [nicklockwood/SwiftFormat#1237]
The [unusedArgument](https://github.com/nicklockwood/SwiftFormat/blob/master/Rules.md#unusedarguments) rule seems to be incompatible with usage of `async` in a closure.

I had the configuration for this rule set to `--stripunusedargs closure-only`, but if it's set to the default (`always`), it still happens (as expected).

### Example

When generating a new [`vapor`](https://github.com/vapor/vapor) project, the default `routes.swift` file looks like this:
```swift
func routes(_ app: Application) throws {
    app.get { req async in
        "It works!"
    }

    app.get("hello") { req async -> String in
        "Hello, world!"
    }

    try app.register(collection: TodoController())
}
```
When SwiftFormat runs, it updates the file, stripping `async` from the method blocks...
```swift
func routes(_ app: Application) throws {
    app.get { req _ in
        "It works!"
    }

    app.get("hello") { req _ -> String in
        "Hello, world!"
    }

    try app.register(collection: TodoController())
}
```
... and promptly breaks compilation.

**Comment by nicklockwood** [comment]
@bdrelling fixed in 0.49.14
