### ISSUE TITLE
Using --typeblanklines option for the rule blankLinesAtStartOfScope will fail the build 

### ISSUE THREAD

**Issue by dimic-milos** [nicklockwood/SwiftFormat#1240]
Build fails with `error: Unknown option --typeblanklines. Did you mean --typemark? in configuration file.` when adding the option `typeblanklines preserve`

xCode Version 13.4.1 (13F100)
SwiftFormat import as SPM .package(url: "https://github.com/nicklockwood/SwiftFormat", from: "0.49.0") and integrated via BuildTools
Apple M1 Pro

Other rules behave as expected.

Config file is:

```
--swiftversion 4.2

--exclude **/BuildTools

--self insert
--wraparguments before-first
--marktypes never
--typeblanklines preserve
--disable trailingCommas
--enable redundantReturn
--enable markTypes
```

**Comment by nicklockwood** [comment]
@dimic-milos try changing `0.49.0` to `0.49.14` in your package import.

**Comment by dimic-milos** [comment]
Thanks, works fine with 0.49.14
