### ISSUE TITLE
Xcode - "for await case let ..." causes "Unexpected token }" error

### ISSUE THREAD

**Issue by gcox** [nicklockwood/SwiftFormat#1243]
When formatting the following code using the Xcode extension (haven't tried the cli yet), formatting fails with an "Unexpected token }" error for the closing "}" on line 13.

```swift
class Something {
  func doWorkA() async {
    await withTaskGroup(of: String?.self) { group in
      (0..<10).forEach { _ in
        _ = group.addTaskUnlessCancelled {
          await self.doWorkB()
        }
      }

      for await case let nextValue? in group where !Task.isCancelled {
        await self.doWorkC(nextValue)
      }
    } // <-- Error points to this brace
  }

  func doWorkB() async -> String? {
    nil
  }

  func doWorkC(_ string: String) async {
  }
}
```

Another example: https://github.com/mecid/swift-unidirectional-flow/blob/4d2c7f8a610b154e983c1c3a95e9e5003770dee7/Sources/UnidirectionalFlow/Store.swift#L42

The code compiles as written. 

I've tested this using the SwiftFormat for Xcode 0.49.14 (1) in Xcode 13 & 14b4.

**Comment by nicklockwood** [comment]
@gcox fix landed in 0.49.15
