### ISSUE TITLE
Ternary operator in string interpolation forces single-line string to become multi-line and breaks build

### ISSUE THREAD

**Issue by orchetect** [nicklockwood/SwiftFormat#1248]
## Issue

1. When a single-line string has interpolation containing a ternary expression, the line will be broken up into multiple lines according to the `wrap` rule.
2. In this example it also seems to put the `?` operator on its own line which is also not ideal.

## Conditions

SwiftFormat 0.49.14
Xcode 14 beta 5

This is an example using default SwiftFormat options, with the following customizations:
`--maxwidth 100`
`--wrapternary before-operators`

## Original
```swift
let str = "\(true ? "A really long string here it's really long again I cannot emphasize enough how long this string is" : "Some other string")"
```

## SwiftFormat formatted

```swift
let str = "\(true
    ?
    "A really long string here it's really long again I cannot emphasize enough how long this string is"
    : "Some other string")"
```

![string-interpolation-ternary-bug](https://user-images.githubusercontent.com/11605557/184059197-dc6817ed-4fcb-4dc2-8089-eb7ed32a47a2.png)

**Comment by nicklockwood** [comment]
@orchetect fixed in 0.49.15
