### ISSUE TITLE
Excluded files

### ISSUE THREAD

**Issue by mergesort** [nicklockwood/SwiftFormat#125]
Hi there,

I was trying to figure out if there is a way to exclude a file (or folder) from being formatted? I have code-generated files using Sourcery, which insert this header.

```
// Generated using Sourcery 0.5.9 — https://github.com/krzysztofzablocki/Sourcery
// DO NOT EDIT
```

The header tells Sourcery to not re-generate the next build through, but combined with `--header strip` turned on in SwiftFormat, it regenerates it each time.

One solution would be to move my generated Sourcery files elsewhere, that doesn't fall under the path, or point SwiftFormat to multiple directories, but I think the cleanest solution would be to allow for excluded files or paths in SwiftFormat.

Let me know what you think, or if there's something I'm missing about how to work around this.

Thanks!

**Comment by nicklockwood** [comment]
Yes, use the `--exclude` option, followed by one or more comma-delimited files or folders.

**Comment by mergesort** [comment]
Oh, awesome, thank you! Just a suggestion, but might wanna include that in the README, I missed it when I went searching.

**Comment by nicklockwood** [comment]
@mergesort yeah, that's fair. It's in the `--help`, which should generally be considered the source of truth for docs, although it's a bit terse in some cases.

**Comment by mergesort** [comment]
Totally fair. I just realized that when I ran `swiftformat --help`, it was using an old version from brew (0.24.6) and not the recent pod version, so I didn't see the option. Sorry for the bother!
