### ISSUE TITLE
When using redundantSelf it inappropriately removes self when using Logger

### ISSUE THREAD

**Issue by Simulacrotron** [nicklockwood/SwiftFormat#1265]
When using redundantSelf it inappropriately removes self when using `Logger`, which is required.  For example:
```
...
import os

private let logger = Logger(subsystem: Bundle.main.bundleIdentifier!, category: "Some Thing I'm Logging")

var someVar: AThing

...

logger.log("do some action that we want to log: \(self.someVar)")
logger.error("ERROR something bad happened that we want to log: \(self.someVar))
```

After running SwiftFormat the following happens

```
logger.log("do some action that we want to log: \(someVar)")
 \\ ! now produces error Reference to property 'someVar' in closure requires explicit use of 'self' to make capture semantics explicit
logger.error("ERROR something bad happened that we want to log: \(someVar)")
 \\ ! now produces error Reference to property 'someVar' in closure requires explicit use of 'self' to make capture semantics explicit
```

I've tried adding `logger` to the "Self Required" field in the UI and it doesn't change how it works.  Even if this did, this would be a bad solution since in another file I might the logger might be name my logger `thisThingIsForLogging` or some other nonsense.

**Comment by nicklockwood** [comment]
@Simulacrotron the argument to --selfrequired is the name of the function(s) you want to exclude, not the object they are members of. So in this case it should be `log,error`, not `logger`
