### ISSUE TITLE
disabling spaceInsideBrackets spaceInsideBraces trailingSpace consecutiveSpaces seems to have no effect with whitespace between colons

### ISSUE THREAD

**Issue by arielelkin** [nicklockwood/SwiftFormat#1267]
I'm trying to disable the trimming of whitespace so that spacing between colons is preserved in a specific place, but disabling `spaceInsideBrackets spaceInsideBraces trailingSpace consecutiveSpaces` seems to have no effect:

     // swiftformat:disable spaceInsideBrackets spaceInsideBraces trailingSpace consecutiveSpaces
    class func load(key: KeychainKey) throws -> Data? {
        let query = [
            kSecClass as String       : kSecClassGenericPassword,
            kSecAttrAccount as String : key.asString,
            kSecAttrService as String : service,
            kSecReturnData as String  : kCFBooleanTrue!,
            kSecMatchLimit as String  : kSecMatchLimitOne ] as [String : Any]

result:

    class func load(key: KeychainKey) throws -> Data? {
        let query = [
            kSecClass as String: kSecClassGenericPassword,
            kSecAttrAccount as String: key.asString,
            kSecAttrService as String: service,
            kSecReturnData as String: kCFBooleanTrue!,
            kSecMatchLimit as String: kSecMatchLimitOne,
        ] as [String: Any]

**Comment by nicklockwood** [comment]
Try disabling spaceAroundOperators
