### ISSUE TITLE
`opaqueGenericParameters` turns `<T>` into `some Any` 

### ISSUE THREAD

**Issue by simondelphia** [nicklockwood/SwiftFormat#1273]
Turning on `opaqueGenericParameters` in 0.50.0 causes unconstrained generics `<T>` to become `<some Any>` in Swift 5.7:

```
func doSomething<T>(foo: Bar<T>)
```

becomes

```
func doSomething(foo: Bar<some Any>)
```

This isn't necessarily an issue per se, but the `some Any` seems weird to my team.

Is there a better way to handle these?

Maybe this?

```
func doSomething(foo: some Bar)
```

**Comment by nicklockwood** [comment]
It seems weird but it's semantically correct. If you'd prefer to exclude this case, you can use the option `--someAny false`

**Comment by simondelphia** [comment]
Ah thanks, didn't realize there was another option
