### ISSUE TITLE
Crash when opaqueGenericParameters is enabled

### ISSUE THREAD

**Issue by noremac** [nicklockwood/SwiftFormat#1278]
Hello! This is follow up from https://github.com/nicklockwood/SwiftFormat/issues/1269 (thanks btw!)

I have found one more crash in 0.50.1 that I have narrowed down to this code:

```swift
public struct Foo<Value> {
    public func withValue<V, R>(
        _ valueDuringOperation: V,
        operation: () throws -> R
    ) rethrows -> R
        where Value == @Sendable () -> V,
        V: Sendable
    {
        fatalError("")
    }

    public func withValue<V, R>(
        _ valueDuringOperation: V,
        operation: () async throws -> R
    ) async rethrows -> R
        where Value == () -> V
    {
        fatalError("")
    }
}
```

- The crash only happens when `opaqueGenericParameters` is enabled.
- If either of the two methods in this type are commented out, the crash does not happen. The crash only happens when both methods exist.

**Comment by calda** [comment]
Thanks for the report, fixed in https://github.com/nicklockwood/SwiftFormat/pull/1280
