### ISSUE TITLE
genericExtensions doesn't support nested generics

### ISSUE THREAD

**Issue by vox-humana** [nicklockwood/SwiftFormat#1281]
Thanks for such quick support of the new Swift 5.7 features.
Playing with it I've found this bug with `genericExtensions` option.

Here is an example of unformatted code:
```
extension Array where Element == Foo<Bar> {}
```

SwiftFormat produces this code with an error:
```
extension Array < Foo<Bar> {}
```

Tested on `0.50.1` and the latest develop 95c3702d0fd8415706099ec2a9acabd8092285fe

**Comment by calda** [comment]
Fixed in https://github.com/nicklockwood/SwiftFormat/pull/1282, thanks for the report
