### ISSUE TITLE
Redundanttype inferred allways

### ISSUE THREAD

**Issue by YanSte** [nicklockwood/SwiftFormat#1298]
Hello 🤚🏻

I would like to know if it is possible to add this new rule. **"Inferred-always"**

To give the possibility to always use the type from variable declarations.

## redundantType

Remove redundant type from variable declarations.

Option | Description
--- | ---
`--redundanttype` | "inferred", "explicit", **"inferred-always"** or "infer-locals-only" (default)

```diff
// Inferred-always
- let view: UIView = .init()
+ let view = UIView()

- let view: UIView = UIView()
+ let view = UIView()

class Foo {
-     let view: UIView = init()
+     let view = UIView()

      func method() {
-         let view: UIView = init()
+         let view = UIView()
      }
}
```

**Comment by nicklockwood** [comment]
I don't think this needs to be a separate option, it should be the standard behaviour for inferred. I'll add a feature request for it.

**Comment by YanSteph** [comment]
Perfect, Thanks 🙏🏻
