### ISSUE TITLE
Request: Remove explicit .init when possible

### ISSUE THREAD

**Issue by mdiep** [nicklockwood/SwiftFormat#130]
I'd love to have a rule for this. SwiftLint has [a rule](https://github.com/realm/SwiftLint/blob/master/Source/SwiftLintFramework/Rules/ExplicitInitRule.swift) for it.

```diff
- let int = Int.init(4)

+ let int = Int(4)
```

I've no idea if that's beyond the scope of SwiftFormat. Feel free to close if it is. ☺️

**Comment by nicklockwood** [comment]
This should be doable, I'll look into it 👍

**Comment by alexito4** [comment]
Hopefully this can be closed now.

**Comment by nicklockwood** [comment]
Added in 0.29.0
