### ISSUE TITLE
How can I change settings in Xcode plugin?

### ISSUE THREAD

**Issue by ahwulf** [nicklockwood/SwiftFormat#131]
Seems pointless to integrate into Xcode if all I can get is the default settings. Is there no way to specific what settings I want?

**Comment by nicklockwood** [comment]
I'm working on it, but note that it's not entirely useless: it doesn't use the default settings, but instead infers the settings to use by looking at the existing file, so for files that have already been mostly formatted to the correct style, it will correct any exeptions to those rules.

**Comment by ahwulf** [comment]
It would be handy to have a config file perhaps in the root of the current workspace/project (I assume you have access to the environment?)

**Comment by nicklockwood** [comment]
@ahwulf 
> I assume you have access to the environment?

I don't. That's the problem. @tonyarnold is looking into an alternative approach though.

**Comment by tonyarnold** [comment]
Yeah, sorry - this hasn't been a priority for me - busy few weeks at home/work. I have verified that it's possible to pass preferences back and forth between the host/shell app and the editor extension. Now I need to find time to build out the UI for editing defaults. 

Hopefully within the next week I'll have time - this is something I really want myself.

**Comment by ahwulf** [comment]
I'd be happy with a simple config file and no UI even. I think a lot of people would like to include it in their project so every gets the same look, or optionally have it in a known place in your ~ directory so you could have a local standard config file.

**Comment by tonyarnold** [comment]
@ahwulf that's not possible with how Apple have designed Xcode Source Editor Extensions right now. I am confident that I can let you set defaults for your user account, but the process is not allowed to access the filesystem, so there won't be per-project settings with the current version of Xcode.

**Comment by ahwulf** [comment]
account would be OK, Apple sure is pathetic sometimes

**Comment by tonyarnold** [comment]
I can see why they've done things this way. Our only course of action is to file radars 📡

**Comment by ahwulf** [comment]
Apple's radar seems unable to see much :-)

**Comment by swiftjsoneditor** [comment]
I am really looking forward to it, it would be insanely helpfull

**Comment by mlfarrell** [comment]
I could use this feature as well.  Great tool otherwise.  Thanks!

**Comment by DarkByte3PG** [comment]
I'd be happy with a per-account config file, as I'm sure most devs would be, since we're mostly using only one code formatting style across our projects.

The problem with auto-inferring settings by looking at how the code was written is not helping me much, since my client brought me someone else's (ton of) code, which is badly and uneven formatted.

So, how about a global configuration file? This way, whenever Apple decides to allow more leeway, it would only be a matter of expanding upon that global config.

Thanks!

**Comment by nicklockwood** [comment]
If you are working with an existing project that is badly formatted, I’d strongly suggest using the command-line tool (which is fully configurable) to do a one-off reformat of the whole project, then the Xcode plugin should be effective for per-file edits from that point onwards.

**Comment by DarkByte3PG** [comment]
Thanks, @nicklockwood , that's a good idea! Don't know how I missed it :)

**Comment by DarkByte3PG** [comment]
Btw, elseOnSameLine can be _enabled_ (forcing the "else" in constructs like "} else {"), but _disabled_ (of course) does nothing, leaving the code as it is. Is there any possibility to move the "else {" to a new line?

Thanks!

**Comment by VinceBurn** [comment]
Hi, do you have a plan for this? Because I would be interested in contributing for this item.

I've seen that https://github.com/Jintin/Swimat is using `UserDefaults(suiteName:)`  to share settings across the application and extension. Where you looking at a solution like that or you have found an other way?

**Comment by nicklockwood** [comment]
@VinceBurn yes, using user defaults is the plan. The sticking point at the moment is building a UI for managing the settings. For now, a simple text box where you can enter the command-line arguments might be the best option.

**Comment by nicklockwood** [comment]
@DarkByte3PG indenting switch cases is now supported using the `--indentcase true` option.

**Comment by DarkByte3PG** [comment]
@nicklockwood : wow, thanks! I'll take a look into this tomorrow.

**Comment by VinceBurn** [comment]
@nicklockwood I would go for a UI in the same "spirit" as the "general" section of the "system preferences", but scrolling.
And it should be coded in a way that should be easy to add new settings as they are developed.
I would leave out detailed descriptions and example for each settings.

**Comment by nicklockwood** [comment]
@VinceBurn that would probably be more user-friendly, but it will take longer to build and be harder to maintain than the textfield option. If you want to take a stab at it though, then be my guest :-)

**Comment by evisoup** [comment]
@nicklockwood  so the rules for existing files are clear

>  it doesn't use the default settings, but instead infers the settings to use by looking at the existing file, so for files that have already been mostly formatted to the correct style, it will correct any exeptions to those rules.

What would be the behavior for a new file?  🤔

I just did a little experiment by creating a poorly formatted code in a new file, but the formatter seems still does the job. 

Just curious what should I expect from it.

**Comment by nicklockwood** [comment]
@evisoup that comment only applies to the Xcode plugin. If you are using the command line tool rather than the Xcode plugin then it *doesn't* attempt to infer the format options from your existing files - it will always use the default settings unless you explicitly override them.

If you are using the Xcode plugin, then it has no knowledge of any files in your project other than the one you are currently formatting (this is a limitation imposed by Apple). For a new file, it will try to derive the format options from the code that's already there, but if it doesn't have enough information to go on, it will use the default settings.

**Comment by evisoup** [comment]
@nicklockwood  Thanks for the clarification. And yes, I was curious about the behavior of the plug in only, which you answered👍

**Comment by VinceBurn** [comment]
@nicklockwood I have something working for rules, which should be easy to maintain. Option on the other hand is more complicated and will need some more thinking.

I would like you to take a look at it, to see if you think it is in the right direction. If you think it is in the right direction I will add some test and then propose a merge request for the rules part.
( https://github.com/VinceBurn/SwiftFormat/tree/feature/user-selected-rules )

**Comment by nicklockwood** [comment]
@vinceburn thanks! It’s late here, but I’ll take a look tomorrow.

**Comment by nicklockwood** [comment]
@VinceBurn looking good! Can you open a work-in-progress PR so it's easier for me to review and give feedback? A couple of comments so far:

* I don't think it's a problem that it only supports rules - the options are inferred from the current state of the file being formatted, but the rules are the part that there is currently no way to configure at all.

* I'd prefer not to require 10.13 as a minimum, so maybe just hard-code the row height to something sensible for 10.12?

Cheers!

**Comment by tonyarnold** [comment]
> I'd prefer not to require 10.13 as a minimum

Given that Xcode 9.3 is 10.13+ only, Apple might be making this decision for you…

Sorry for ducking out on this issue - I'll happily help to review the WIP PR once it is opened.

**Comment by nicklockwood** [comment]
@ahwulf support for enabling/disabling rules in the Xcode plugin has landed in version 0.33.0.
