### ISSUE TITLE
Beheaded assignments

### ISSUE THREAD

**Issue by crenelle** [nicklockwood/SwiftFormat#1312]
SwiftFormat appears to turn
let _ = whatever()
into
_ = whatever()

which appears to upset SwiftUI Views, generating the error: 

Type '()' cannot conform to 'View'

I'm using Xcode 14.1.

**Comment by nicklockwood** [comment]
This is supposed to be handled correctly inside SwiftUI views - can you provide a sample that demonstrates the problem?

In the meantime, you can disable the [redundantLet](https://github.com/nicklockwood/SwiftFormat/blob/master/Rules.md#redundantLet) rule to fix this in your porject.

**Comment by crenelle** [comment]
[Gesundheit.zip](https://github.com/nicklockwood/SwiftFormat/files/10052038/Gesundheit.zip)

Here's a project, I just open the ContentView.swift file in Xcode and run SwiftFormat on the one file.

**Comment by nicklockwood** [comment]
@crenelle fixed in 0.50.4
