### ISSUE TITLE
Command PhaseScriptExecution failed with a nonzero exit code

### ISSUE THREAD

**Issue by JulesMoorhouse** [nicklockwood/SwiftFormat#1315]
Hi,

I'm trying to setup a build phase for SwiftFormat I've already installed via home-brew.

However, I only want to use lint mode.

Here's my build phase..
`
if which swiftformat >/dev/null; then
  swiftformat . --lint --config .swiftformat
else
    echo "error: SwiftFormat not installed, download from https://github.com/nicklockwood/SwiftFormat"
    exit 1
fi
`

I only have `Show environment variables in build log` checked.

I've deliberately create an an issue in my code for SwiftFormat to pick up.

However, I always get `Command PhaseScriptExecution failed with a nonzero exit code` when an issue is found by SwiftFormat.

I've tried the `For install builds only` checkbox which obviously doesn't run SwiftLint on normal builds.

I just don't want an error to produced, just any warnings from SwiftFormat...

I'm not sure if it's relevant but here's my .swiftformat file..

```
# format options
--stripunusedargs closure-only
--patternlet inline
--maxwidth 110

# rules
--disable wrapMultilineStatementBraces,initCoderUnavailable,braces

--exclude fastlane,./MyApp/Localization/Strings.swift
```

I'm not sure what I'm doing wrong ?

Edit: from the build log I can see SwiftFormat is working and finding issues, but I’m just not sure why it’s causing a build error, especially as it only does so when it finds issues.

I’m using Xcode 14.1

I've just ran `brew upgrade` and I can see it upgraded SwiftFormat, I get more issues now.. but the error persists

**Comment by JulesMoorhouse** [comment]
Ohhh adding `exit 0` directly after the SwiftFormat call stops the error...
Not sure why this should be required ?

**Comment by nicklockwood** [comment]
You can add the --lenient option to suppress errors when running in lint mode.
