### ISSUE TITLE
Joined header comments

### ISSUE THREAD

**Issue by honghaoz** [nicklockwood/SwiftFormat#1318]
I just upgraded from 0.50.3 to 0.50.5, but seeing this unexpected reformatting:

Original code:
```swift
//
//  Transition.swift
//
//  Created by Johnny Appleseed on 10/18/20.
//  Copyright © 2022 Ape. All rights reserved.
//

//
//  Something else...
//
```

Formatted code:
```swift
//
//  Transition.swift
//
//  Created by Johnny Appleseed on 10/18/20.
//  Copyright © 2022 Ape. All rights reserved.
//
//
//  Something else...
//
```
I intentionally added the middle empty line to separated two group of header comments. However, the new fileHeader behavior always removes the empty line and it seems like there's no option to opt out.

---
Following code is also reformatted:
```swift
//
//  Transition.swift
//
//  Created by Johnny Appleseed on 10/18/20.
//  Copyright © 2022 Ape. All rights reserved.
//

//
//  Something else...
```

Following code is ok (no reformatting)
```swift
//
//  Transition.swift
//
//  Created by Johnny Appleseed on 10/18/20.
//  Copyright © 2022 Ape. All rights reserved.
//

//  Something else...
```

```swift
//
//  Transition.swift
//
//  Created by Johnny Appleseed on 10/18/20.
//  Copyright © 2022 Ape. All rights reserved.
//

//  Something else...
//
```

I think this commit is related: https://github.com/nicklockwood/SwiftFormat/commit/8db718ec17f448ba40a190308d2bd0bdc96531ab

**Comment by nicklockwood** [comment]
@honghaoz fixed in 0.50.6
