### ISSUE TITLE
`redundantSelf` rule adding backticks to method name if it's same as keyword

### ISSUE THREAD

**Issue by blackm00n** [nicklockwood/SwiftFormat#132]
`self.switch(toSmth: foo)` is converted to
```
`switch`(toSmth: foo)
```

Should `self` be left in this case?

**Comment by nicklockwood** [comment]
Arguably that might be preferable.

**Comment by blackm00n** [comment]
I believe [this code](https://github.com/nicklockwood/SwiftFormat/blob/18e03a138356935c412ad7fb97e34a490cec42ce/Sources/Rules.swift#L2027) is causing it. I personally prefer redundant self instead of backticks. Maybe it should be a parameter for `redundantSelf` rule, but I don't have a strong opinion.

**Comment by nicklockwood** [comment]
@blackm00n this is fixed in 0.43.3.
