### ISSUE TITLE
How to add SwiftFormat as plugin?

### ISSUE THREAD

**Issue by rokon-uddin** [nicklockwood/SwiftFormat#1321]
With the release of version 0.50.4 `SwiftFormat` added plugin capabilities. For the last few days, I have been trying to leverage the plugin feature in my project. Unfortunately, I could not make it. Please share the complete code snippet to add the `SwiftFormat` plugin to the Xcode project as well as to another SPM.

**Comment by DD-P** [comment]
You should be able to add the SwiftFormat package to your project, then right click on the project and choose `SwiftFormatPlugin` from the contextual menu. My .swiftformat file is in the projects top level folder.

![Screen Shot 2022-12-05 at 7 29 56 PM Medium](https://user-images.githubusercontent.com/1289710/205565092-5c97777c-5e1f-4002-9755-5ef318c6271f.jpeg)
![Screen Shot 2022-12-05 at 7 30 34 PM Medium](https://user-images.githubusercontent.com/1289710/205565110-f89d78c4-e704-4e24-8656-52052caa9703.jpeg)

**Comment by nicklockwood** [comment]
@rokon-uddin Swift Package Manager plugin instructions are now included in the README
