### ISSUE TITLE
redundantLet in switch cases rule

### ISSUE THREAD

**Issue by facumenzella** [nicklockwood/SwiftFormat#1322]
In a project I am working I've noticed this warning `'let' pattern has no effect; sub-pattern didn't bind any variables`.

```swift
    var variable: Int {
        switch self {
            case let .a: // warning shown here
                return 0
            case .b:
                return 1
        }
    }
```

I was looking for a rule to strip the `let` out but could not find it. I am happy to work on a rule for that, but wanted to confirm there's nothing in place before working on it.

**Comment by nicklockwood** [comment]
@facumenzella landed in 0.51.0
