### ISSUE TITLE
RedundantImports

### ISSUE THREAD

**Issue by katovBash** [nicklockwood/SwiftFormat#1328]
Hello!)

Error: Unknown rule 'redundantImports'. Did you mean 'redundantInit'?

Terminal can't find redundantImports. 
Swift version - 5.7
SwiftFormatter version - 0.50.6

This feature has been deleted?
How can I find it :)?

**Comment by nicklockwood** [comment]
I don't think there's ever been a `redundantImports` rule. Are you maybe thinking of `duplicateImports`?

**Comment by katovBash** [comment]
oh, ok, thanks)
