### ISSUE TITLE
Adding SwiftFormat to Swift Source Compatibility Test Suite

### ISSUE THREAD

**Issue by aksswami** [nicklockwood/SwiftFormat#133]
It's probably a good idea, to add SwiftFormat to "Swift Source Compatibility Test Suite".
https://swift.org/blog/swift-source-compatibility-test-suite
https://swift.org/source-compatibility/#current-list-of-projects
Alamofire, ObjectMapper are already in the list.

**Comment by aksswami** [comment]
Oh. Got your point. Just thought that, as SwiftFormat is widely used tool for linting/reformatting and other purpose, It's compatibility should be tracked. And It may also help swift developers providing more insight for swift version change on community driven projects.

**Comment by nicklockwood** [comment]
Agreed. I'm not sure the best way to do that though. It might make more sense to have a *SwiftFormat* compatibility test suite (possibly the same one as Swift uses) that I automatically run the formatter on and verify isn't broken. That would be quite an effort to set up though.

**Comment by aksswami** [comment]
Yes. That will be quite an effort and I am not even sure how to go about implementing one. If there is anything I can do, I am open to help and contribute. Anyway you can close the issue now or keep it open to track as `improvement`.

**Comment by nicklockwood** [comment]
Thanks! I'll keep it open for now as a reminder.

**Comment by nicklockwood** [comment]
@aksswami SwiftFormat now has an internal compatibility suite, and I've submitted a request to have it added to Apple's compatibility suite also: https://github.com/apple/swift-source-compat-suite/pull/452
