### ISSUE TITLE
Format files in parallel using command line

### ISSUE THREAD

**Issue by InderKumarRathore** [nicklockwood/SwiftFormat#1330]
Is it possible to format list of files (say 200) concurrently?
Right now I see that files are formatted sequentially. I can run commands from shell script like `swiftformat filename &` to run it in parallel but then for all the files it reads the config file again which is not efficient. Although I got some performance improvement. But it would be nice if libs supports it in built

**Comment by nicklockwood** [comment]
AFAICT it should be formatting files provided via the command line or via a `--filelist` file concurrently. What makes you think that it isn't?

**Comment by InderKumarRathore** [comment]
Because I tried to format 120 files by passing 120 files list to command and it takes around 16 seconds to format. whereas if i run a ruby script and create 120 threads and each thread formats single file then it takes 5 seconds. Thus my assumption that it format's file one by one.

**Comment by nicklockwood** [comment]
If you run with --verbose mode, it is appreciably slower? (verbose mode disables concurrency)

**Comment by InderKumarRathore** [comment]
It doesn't, never mind I used ruby to make it parallelized.
