### ISSUE TITLE
Xcode 14 introduces new run script build phase warning

### ISSUE THREAD

**Issue by CharlotteFallices** [nicklockwood/SwiftFormat#1336]
The warning looks like:
> Run script build phase 'SwiftFormat' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase.

Ref: [Running custom scripts during a build](https://developer.apple.com/documentation/xcode/running-custom-scripts-during-a-build) and [Improving the speed of incremental builds](https://developer.apple.com/documentation/Xcode/improving-the-speed-of-incremental-builds)

**Comment by nicklockwood** [comment]
You should probably just uncheck the "Based on dependency analysis" checkbox. I'll add a note in the README.

**Comment by nicklockwood** [comment]
@CharlotteFallices fixed in 0.50.9
