### ISSUE TITLE
Question: Why is the Xcode Source Editor Extension not in brew

### ISSUE THREAD

**Issue by igorkulman** [nicklockwood/SwiftFormat#134]
I was just wondering, why is the Xcode Source Editor Extension not in brew (cask)?  I can install SwiftFormat quite easily using brew and but when I want to use the Xcode Source Editor Extension I have to download the source code and build it myself. I know I do it just once, but anyway.

**Comment by nicklockwood** [comment]
Is brew appropriate for installing a GUI application? I thought it was only for command-line apps?

I'm considering putting the Xcode Extension in the app store once the formatter reaches a reasonable level of stability.

You shouldn't have to build the extension yourself though - there's a signed binary already included in the repository.

**Comment by igorkulman** [comment]
[Homebrew cask](https://caskroom.github.io/) is for installing GUI apps

**Comment by nicklockwood** [comment]
>Homebrew cask is for installing GUI apps

Ah. TIL ¯\_(ツ)_/¯

**Comment by mmysliwiec** [comment]
Is there any progress on this issue? Can we install SwiftFormat Xcode extension with `brew cask`? It would be extremely useful.

**Comment by aerobounce** [comment]
I've made a personal tap for `SwiftFormat for Xcode.app`.
If you like: [aerobounce/Homebrew-SwiftFormat-for-Xcode](https://github.com/aerobounce/Homebrew-SwiftFormat-for-Xcode)

**Comment by nicklockwood** [comment]
I've now added an official cask based on @aerobounce's tap: https://github.com/nicklockwood/SwiftFormat#xcode-source-editor-extension
