### ISSUE TITLE
SwiftFormat for Xcode application missing from the EditorExtension folder

### ISSUE THREAD

**Issue by arielelkin** [nicklockwood/SwiftFormat#1348]
SwiftFormat for Xcode application is not inside the EditorExtension folder as documented here:

https://github.com/nicklockwood/SwiftFormat/blob/34cd9dd87b78048ce0d623a9153f9bf260ad6590/README.md?plain=1#L217

**Comment by nicklockwood** [comment]
@arielelkin yes, sorry, this is outdated documentation. You'll actually find it on the downloads page on github, here: https://github.com/nicklockwood/SwiftFormat/releases/tag/0.50.7

**Comment by nicklockwood** [comment]
@arielelkin I've updated the docs
