### ISSUE TITLE
Turn off coloring output?

### ISSUE THREAD

**Issue by konrad1977** [nicklockwood/SwiftFormat#1349]
I am writing a package this using Emacs. I wonder if there is an option to turn off the coloring. It messes a bit with my parsing.

**Comment by nicklockwood** [comment]
Swiftformat uses isatty(STDERR_FILENO) to determine if the the stderr output is TTY compatible, and if not it won't color the output.

I don't know much about Emacs packages, but for example you could pipe the stderr output to a file like this, which would strip the formatting:

swiftformat myfile.swift >& output.txt

**Comment by konrad1977** [comment]
<img width="1614" alt="Skärmavbild 2023-01-16 kl  11 54 35" src="https://user-images.githubusercontent.com/4384932/212662306-bcf3f9d2-7465-4cf3-8e86-25b6c1004435.png">

Just changed my regex a bit. Now works like a charm. Thanks!
