### ISSUE TITLE
.swiftformat file uses deprecated rules

### ISSUE THREAD

**Issue by bobergj** [nicklockwood/SwiftFormat#1356]
https://github.com/nicklockwood/SwiftFormat/blob/ae4d0b672cd7094ae513097c617951a5ac714418/.swiftformat#L10-L13

Unless I am missing something `--comments indent` and `--empty void` are deprecated.
This creates some confusion when attempting to use this file as a template for another project.

**Comment by nicklockwood** [comment]
@bobergj thanks - fixed in 0.50.9
