### ISSUE TITLE
Add Github Actions annotation reporter

### ISSUE THREAD

**Issue by bobergj** [nicklockwood/SwiftFormat#1365]
### What 

Get inline lint violation warnings in github PRs: 
![github-action-annotation-check](https://user-images.githubusercontent.com/265631/218380405-0d62d4ee-abe7-4ca2-9f66-32906b4cbb78.png)

### How

There's an existing `--report` argument that writes a json-formatted report to the specified path.
Extend that as follows:
* Add a `--reporter` argument, possible values are  (`github-actions-log`, `json`)
* When the `--report` argument is not specified, default reporter output to stdout

#### Example Usage

```
./swiftformat --lint --reporter github-actions-log .
./swiftformat --lint --reporter json --report report.json .
```

**Comment by nicklockwood** [comment]
@bobergj this feature is included in 0.50.9
