### ISSUE TITLE
Release wrapeffects option

### ISSUE THREAD

**Issue by bobergj** [nicklockwood/SwiftFormat#1368]
Is there reason the `--wrapeffects` options added by https://github.com/nicklockwood/SwiftFormat/pull/1301 isn't released? It's in develop, and there's no open issue. Anything we can do to make it releasable?

**Comment by nicklockwood** [comment]
It will be in the next feature release (0.x.0). I try not to include new features in bug releases as people should be able to update to those with minimal risk of new bugs.

**Comment by nicklockwood** [comment]
@bobergj landed in 0.51.0
