### ISSUE TITLE
hoistAwait results in non-compiling code when a function takes an async autoclosure

### ISSUE THREAD

**Issue by bobergj** [nicklockwood/SwiftFormat#1375]
SwiftFormat 0.51.1
Xcode 14.2 (Swift 5.7.2)

Original code:
```swift
    func functionTakingAutoclosuredExpresson<T>(
        _ expression: @autoclosure () async -> T
    ) async
        -> T
    {
        await expression()
    }

    func asyncFunction() async -> Int {
        0
    }

    func functionThatIsIncorrectlyFormattedByRule() async throws {
        let foo = await functionTakingAutoclosuredExpresson(
            await asyncFunction()
        )
    }
   ```
   
   
SwiftFormat output:
```swift
       func functionThatIsIncorrectlyFormattedByRule() async throws {
        let foo = await functionTakingAutoclosuredExpresson(
            asyncFunction()  // Compiler ERROR: Expression is 'async' but is not marked with 'await'
        )
    }
```

If you wonder why in the world I have an async autoclosure, it's for XCTest custom assert helpers:
```swift
    func assertBlabla<T>(
        _ expression: @autoclosure () async throws -> T,
        filePath: String = #filePath,
        lineNumber: Int = #line
    )  
```

**Comment by bobergj** [comment]
Apart from hoistAwait currently being unsafe, I would argue that both `hostAwait` and `hostTry` are  opinionated rules rather than established best practice. Thus they should be disabled by default.
Because the transformations may result in less readable code, making it unclear which sub-expression has effects.

Eg.
```
self.init(
    foo: try computeFoo()
    bar: computeBar()
    baz: computeBaz()
)
```

Becomes:
```
try self.init(
    foo: computeFoo()
    bar: computeBar
    baz: computeBaz
)
```
Now we have to inspect at all the computeX  functions to see which one can throw.

**Comment by nicklockwood** [comment]
@bobergj you're right that these rules probably aren't for everyone. I wanted to enable them by default for visibility and to ensure that any bugs would be found quickly - I may disable them later.

Thanks for raising this bug. There's probably no easy way for me to solve this except with a user-supplied list of functions (similar to the `--selfrequired` option). I can probably mitigate it a bit by ensuring that async is never hoisted into non-async contexts though.

In the meantime, the workaround is to disable the rule, either globally or locally with a `// swiftformat:disable` directive.

**Comment by facumenzella** [comment]
After reading this, I was thinking that we can add an option to hoist if every internal expression is `async` (same for `hoistTry`)

**Comment by nicklockwood** [comment]
@facumenzella I'm not sure what you mean? How would you know if an expression is async?

**Comment by facumenzella** [comment]
I was referring to [this](https://github.com/nicklockwood/SwiftFormat/issues/1375#issuecomment-1453008210) comment. 

```swift
self.init(
    foo: await computeFoo()
    bar: await computeBar()
    baz: await computeBaz()
)
```

to this:
```swift
await self.init(
    foo: computeFoo()
    bar: computeBar()
    baz: computeBaz()
)
```

If all the expressions inside a scope are marked with `await` hoisting wouldn't introduce ambiguity.

**Comment by nicklockwood** [comment]
@facumenzella ah, I see. Yes, that makes sense. I thought you were suggesting a solution to the autoclosure problem.

**Comment by nicklockwood** [comment]
@bobergj I've added a `--asynccapturing` option in 0.51.2 that you can use like this:

```
--asynccapturing functionTakingAutoclosuredExpresson
```

**Comment by gregcotten** [comment]
came here to report I also experienced this issue!

**Comment by gregcotten** [comment]
@nicklockwood absolutely yes!
