### ISSUE TITLE
runtime error occurs when using pre-compiled binary swiftformat_linux.zip on ubuntu.

### ISSUE THREAD

**Issue by kagemeka** [nicklockwood/SwiftFormat#1380]
error message
```
swiftformat: error while loading shared libraries: libswift_StringProcessing.so: cannot open shared object file: No such file or directory
```

environment 
- docker 
  - swift:latest (linux/amd64)
- swift version: 5.7.3
- swiftformat version: 0.50.3

this binary works well on github actions ubuntu-latest.

**Comment by kagemeka** [comment]
it's resolved!

by installing
```sh
apt install -y libpython3-dev
```

**Comment by nicklockwood** [comment]
It looks like you're using a very old SwiftFormat version. Can you upgrade to the latest and see if the problem still occurs?

**Comment by kagemeka** [comment]
the error still occurs even though upgrading the version to 0.51.2.

I run a script
```sh
find / | grep libswift_StringProcessing
```
the output was
```
/usr/lib/swift_static/linux/libswift_StringProcessing.a
/usr/lib/swift/linux/libswift_StringProcessing.so
```
