### ISSUE TITLE
Is there any way to order // MARK: Internal BEFORE // MARK: Lifecycle?

### ISSUE THREAD

**Issue by thepost** [nicklockwood/SwiftFormat#1381]
Apologies if this is obvious. I can't for the life of me figure this out. Until then I've had to disable the `organizeDeclarations` rule, as I don't want the init function to be the first thing you see in a class or struct.

**Comment by nicklockwood** [comment]
Cc @calda

**Comment by calda** [comment]
This isn't currently possible, but would be reasonably straightforward to add support for. For example, we could add a `--typeordering` option where the default is `lifecycle,open,public,internal,fileprivate,private` and then allow consumers to customize the order. 

I'd be curious to hear where exactly you'd like to order the lifecycle declarations, though. I personally don't really see the appeal of an ordering like `open,public,internal,lifecycle,fileprivate,private`, although I do see the appeal of removing the `lifecycle` category completely in favor of just placing `init`s in the corresponding ACL group.
