### ISSUE TITLE
explicit config vs local .swiftformat

### ISSUE THREAD

**Issue by vhosune** [nicklockwood/SwiftFormat#1387]
So I have my global .swiftformat in ~/.config/.swiftformat and was using the explicit --config
And also have custom .swiftformat per project
I see that it was broken by 
 
```
Ignore .swiftformat files when using explicit config
https://github.com/nicklockwood/SwiftFormat/commit/356a4716a418fba9ac90e50ee2267d49198ff40c

```

is there a workaround to re-enable local config ?
(0.51.2)

**Comment by nicklockwood** [comment]
Can you move your .swiftformat up to root level? It would probably also work to make it an alias or symlink

**Comment by vhosune** [comment]
sure, wanted to keep my config like in
https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html

**Comment by nicklockwood** [comment]
I'll consider adding an option for this
