### ISSUE TITLE
A new rule regarding "try" is creating errors when used in "\(try something())"

### ISSUE THREAD

**Issue by altagir** [nicklockwood/SwiftFormat#1388]
Given this piece of code, where try is used inside a \\()

` if let url = URL(string: "tel://\(number!.replace(regex: try NSRegularExpression(pattern: "[^0-9]"), replacement: ""))"),
`

Applying swiftformat will change this into :
`if let url = URL(string: "tel://\try (number!.replace(regex: NSRegularExpression(pattern: "[^0-9]"), replacement: ""))"),
`

which creates compile error
The "try " has been inserted between \ and (, it should have been inserted after "\\("

Is there a way to disable this new rule, by the way ? thanks

**Comment by facumenzella** [comment]
Thanks for reporting @altagir 
This should be fixable. In the meantime, the workaround is to disable the rule globally or locally with a `// swiftformat:disable` directive.

**Comment by nicklockwood** [comment]
@altagir fixed in 0.50.3
