### ISSUE TITLE
Question about Swiftformat and config file

### ISSUE THREAD

**Issue by ilikerb0407** [nicklockwood/SwiftFormat#1393]
When I saw the version 0.51.0, it said that

> SwiftFormat now ignores .swiftformat files when explicit --config file is provided

but when I saw README.md,

> If you have created a [config file], you can specify its path using --config "/path/to/your/config-file/". Alternatively, if you name the file .swiftformat and place it inside the project you are formatting, it will be picked up automatically

I just wonder if these two points contrast or not ?

Thanks for your time ~

**Comment by nicklockwood** [comment]
The "alternatively" implies that these are either/or options, which was always the intention.
