### ISSUE TITLE
Disable `if let` and `guard let` shortened syntax in Swift 5.7

### ISSUE THREAD

**Issue by bartlomiejswierad-vodeno** [nicklockwood/SwiftFormat#1399]
Hey,

Currently, when I provide swift version 5.7, SwiftFormat enforces new shortened syntax of `if let` and `guard let`, when for some private reasons we can't use it. Is there a possibility to disable this rule?

Rule example:
Before:
```swift
class Foo {
    var bar: String?

    func baz() {
        guard let bar = bar else { return }
        doAnything()
    }
    func doAnything() {}
}
```
After:
```swift
class Foo {
    var bar: String?

    func baz() {
        guard let bar else { return }
        doAnything()
    }
    func doAnything() {}
}
```

SwiftFormat: v0.51.2
Xcode 14.2
Swift 5.7.2
MacOS 13.2.1

**Comment by nicklockwood** [comment]
Yes, you can use `--disable redundantOptionalBinding`.

For future reference you can use `--lint` or `--verbose` to find out which rule was applied to which line so you know which to disable.

**Comment by bartlomiejswierad-vodeno** [comment]
Thanks for the advice!
