### ISSUE TITLE
Provide --self option to ignore capture lists

### ISSUE THREAD

**Issue by keith** [nicklockwood/SwiftFormat#1413]
With capture lists using variables on self, and using `--self insert`, the valid replacement of `[weak a]` is `[weak a = self.a]`. To me this case feels a bit different than when you're passing a variable on self to a function. I think it would make sense to allow ignoring this case for inserting `self.`. Another related case is the new abbreviated `if let` syntax, where an analogy to this capture list behavior would be expanding `if let a` to `if let a = self.a`, which also might feel a little heavy handed. I'm not sure what the right balance is here since it's obviously just a stylistic decision, but I think it would make sense to allow these very brief cases to remain as written, even if you insert `self.` in the common case.

**Comment by nicklockwood** [comment]
The fix to your previously mentioned bugs disables self-insertion in these cases anyway. In principle it should be supported, but I'll leave that as a future exercise for now.
