### ISSUE TITLE
File and/or line level exclusions

### ISSUE THREAD

**Issue by deepumukundan** [nicklockwood/SwiftFormat#142]
I read some issues and PR's talking about a config file for the preferences. Would a file or line level exclusion also make sense in addition to the default config file? Something similar to https://github.com/realm/SwiftLint#disable-rules-in-code? I have seen some places where the removeRedundantSelf rule causing code to not compile. Marked out sections of code will prevent future formatting.

**Comment by nicklockwood** [comment]
Yes, this is something I plan to do. File level should be fairly easy. Line-level may be trickier due to the way the rules are currently implemented.

**Comment by deepumukundan** [comment]
Gotcha. File level would be helpful too. Thanks Nick!

**Comment by nicklockwood** [comment]
@deepumukundan ironically, line-level turned out to be easier, because I didn't have to decide on a file format. Implemented in 0.32.0.
