### ISSUE TITLE
Syntax error for function inside a closure due to self

### ISSUE THREAD

**Issue by Vaberer** [nicklockwood/SwiftFormat#1420]
I found one use case where swiftformat does not work. I'm using Xcode 14.3 and `--swiftversion 5.8`.
```
    var property = 0

    func test() {
        let buttonView = ButtonView()
        buttonView.didTap = { [weak self] in
            guard let self else { return }

            func internalFunc(param: Bool) {
                if param {
                    self.property += 10
                } else {
                    self.property -= 10
                }
            }

            if arc4random() == 0 {
                internalFunc(param: true)
            } else {
                internalFunc(param: false)
            }
        }
    }
```

The swiftformatter wants to remove self. in `self.property` but this causes a syntax error `Reference to property 'property' in closure requires explicit use of 'self' to make capture semantics explicit`

If a closure contains a function, it's not allowed to remove the self.

**Comment by nicklockwood** [comment]
@calda would you be able to take a look at this? You're more familiar with the implicit-self-in-closures logic.

**Comment by Vaberer** [comment]
@nicklockwood you are super fast :D

**Comment by alexito4** [comment]
I've also seen this issue when telling [0.51.5](https://github.com/nicklockwood/SwiftFormat/releases/tag/0.51.5) to use 5.8 syntax. Using 5.7 syntax works fine.

**Comment by calda** [comment]
Here's a fix: 1422

**Comment by calda** [comment]
Also, based on the discussion [here](https://forums.swift.org/t/why-does-se-0269-have-different-rules-for-inner-closures-vs-inner-functions/64334/10) I'm pretty sure this is just a bug in my implementation of [SE-0365](https://github.com/apple/swift-evolution/blob/main/proposals/0365-implicit-self-weak-capture.md). I'll look at making it so this compiles without an error in future versions.

**Comment by martin-muller** [comment]
Interesting case we noticed when updating to 0.51.6: 

When condition precedes strong self declaration in guard statements, compiler deems the explicit usage of self as required while SwiftFormat sees the self as redundant and removes it.

```swift
class A {
    let thing: Any? = nil

    func foo(condition: Bool) {
        let _: () -> Any? = { [weak self] in
            guard condition,
                  let self else {
                return
            }

            return self.thing // SwiftFormat removes `self` here resulting in: Reference to property 'thing' in closure requires explicit use of 'self' to make capture semantics explicit
        }
    }
}
```

---

If we flip the order of statements in guard, compilation succeeds.

```swift
class A {
    let thing: Any? = nil

    func foo(condition: Bool) {
        let _: () -> Any? = { [weak self] in
            guard let self,
                  condition
            else {
                return
            }

            return thing
        }
    }
}
```

---

Interestingly the strong self declaration doesn't need to be first, other declarations can precede and compilation is successful. 

```swift
class A {
    let thing: Any? = nil

    func foo(condition: Bool) {
        let _: () -> Any? = { [weak self] in
            guard let _ = self?.thing,
                let self
            else {
                return
            }

            return thing
        }
    }
}
```

But I suppose this is more of a Swift's issue rather than SwiftFormat's @calda?

**Comment by calda** [comment]
Good find @martin-muller! That's a silly one, I'm surprised I hadn't seen that sooner.

Both of these issues are bugs in Swift 5.8 itself, which I've fixed here:
 - https://github.com/apple/swift/pull/65211
 - https://github.com/apple/swift/pull/65310

I'm working on getting these fixes into Swift 5.9. In the mean time it makes sense to special-case SwiftFormat to handle this edge case in Swift 5.8 mode.

**Comment by everlof** [comment]
@calda Any of these also cover this case? Or should I submit a ticket for it?

```
class A {
    public func f(_: @autoclosure @escaping () -> Int) {
        fatalError()
    }

    func int() -> Int { 1 }
    func doIt() { f(self.int()) }
}
```

Swiftformat removes `self.` which then yields the following swift compilation-error:
`Call to method 'int' in closure requires explicit use of 'self' to make capture semantics explicit`

**Comment by nicklockwood** [comment]
@everlof this is a separate known issue with the redundantSelf rule and autoclosure parameters. The current solution is to use `--selfrequired f` (where f is a comma-delimited list of any functions in your codebase that have autoclosure arguments)

**Comment by everlof** [comment]
> @everlof this is a separate known issue with the redundantSelf rule and autoclosure parameters. The current solution is to use `--selfrequired f` (where f is a comma-delimited list of any functions in your codebase that have autoclosure arguments)

Ah, I see, thanks for the swift reply!
