### ISSUE TITLE
FileHeader strip is not working when there is a url

### ISSUE THREAD

**Issue by ibrahimoktay** [nicklockwood/SwiftFormat#1425]
We have a code generation tool that adds file header automatically and these headers contain urls. Removing these urls manually is quite tedious task and unfortunately, swiftformat does not remove them either.

Here is a sample:
```swift
        //
        //  SomeFile.swift
        //  SomeModule
        //
        //  Created by Someone on dd/MM/yyyy.
        //  Copyright © Some. All rights reserved.
        //  https://some.example.com
        //

        /// func
        func foo() {}
```

**Comment by nicklockwood** [comment]
@ibrahimoktay fix landed in 0.51.7
