### ISSUE TITLE
Insert line break after import with `@_spi`

### ISSUE THREAD

**Issue by ski-u** [nicklockwood/SwiftFormat#1428]
## About this bug
- `SwiftFormat@0.51.6` now insert unnecessary line break when we import with `@_spi` prefix
  - like ↓
  <img width="773" alt="line_break_after_imports" src="https://user-images.githubusercontent.com/37182704/232035163-84192aa1-85de-4bc0-9c5d-700f72625b0a.png">

## About my environment
```
❯ swift --version
swift-driver version: 1.75.2 Apple Swift version 5.8 (swiftlang-5.8.0.124.2 clang-1403.0.22.11.100)
Target: arm64-apple-macosx13.0
```

```
❯ xcodebuild -version
Xcode 14.3
Build version 14E222b
```

**Comment by nicklockwood** [comment]
@ski-u fixed in 0.51.7
