### ISSUE TITLE
redundantSelf removes self for an Optional<Self> in Swift 5.8

### ISSUE THREAD

**Issue by RomanTysiachnik** [nicklockwood/SwiftFormat#1432]
## Configuration

The unexpected result happens with `redundantSelf` rule and Swift 5.8 version specified in the config.

## STR

You can use that simple example:

```swift
protocol ADelegate: AnyObject {
    func aDidSomething(_ a: A)
}

class A {
    weak var delegate: ADelegate?

    func testFunction() {
        DispatchQueue.main.async { [weak self] in
            self.flatMap { $0.delegate?.aDidSomething($0) }
        }
    }
}

```

For us, it was triggered both for Swift monads and for our custom extensions for the `Optional`.

## EXR

No changes in the code above

## ACR

`self` gets removed and causes compilation error

```swift
DispatchQueue.main.async { [weak self] in
    flatMap { $0.delegate?.aDidSomething($0) }
}
```

**Comment by nicklockwood** [comment]
@RomanTysiachnik fixed in 0.51.8

**Comment by calda** [comment]
Thanks for taking care of this one @nicklockwood

**Comment by nicklockwood** [comment]
@calda no problem. Btw, is this another case where `self` actually should be implicit in Swift? Or do you think it's correct that it's required in this case?

**Comment by RomanTysiachnik** [comment]
Thanks for fixing that, @nicklockwood

**Comment by calda** [comment]
I think the current compiler behavior is expected. SE-0365 specifically says that `weak self` captures can be used implicitly "after self has been unwrapped". 

In theory it could be reasonable to support this when self is still an optional, but that would only apply when calling methods directly on `Optional` itself (since there isn't a way to do optional chaining on implicit self). That's probably too narrow of a use case to support in the language.

**Comment by nicklockwood** [comment]
@calda right, but using `map` or `flatMap` to unwrap an optional instead of `if/guard let` (as it this example) is not an unusual technique. This probably isn't the forum to discuss it, but it's probably worth discussing.

**Comment by RomanTysiachnik** [comment]
@nicklockwood  WDYT if that's going to be something like:

```swift
class Signal {
    func map() { ...}
    func flatMap() { ... }
    
    func somethingElse(_ closure: @escaping () -> Void) { ... } 
}

let signal = Signal()
signal. somethingElse { [weak self] in
    flatMap { ... }
}
```

Question: which `flatMap` would be used? It could possibly be resolved by the compiler, but in terms of readability, that doesn't look clear.

**Comment by nicklockwood** [comment]
@RomanTysiachnik there's no actual ambiguity. To call signal.flatMap you'd have to unwrap the optional, which you can only do using explicit self:

```swift
self?.flatMap { ... }
```

or

```swift
guard let self else { return }
flatMap { ... }
```

**Comment by RomanTysiachnik** [comment]
But if you leave the code as it is:

```swift
signal.somethingElse { [weak self] in
    flatMap { ... }
}
```

should the compiler fail with an error asking for unwrapping or optional self?
