### ISSUE TITLE
SwiftFormatPlugin - Build ERROR

### ISSUE THREAD

**Issue by TonnyCS** [nicklockwood/SwiftFormat#1443]
Hello,
I'm trying to add SwiftFormat using the SwiftFormatPlugin to one of my projects, unfortunately I'm stuck when trying to build the project, as when the plugin is being applied, it ends on an internalError stating:
```
internalError("invalid plugin capability command(intent: PackageModel.PluginCommandIntent.custom(verb: \"swiftformat\", description: \"Formats Swift source files using SwiftFormat\"), permissions: [PackageModel.PluginPermission.writeToPackageDirectory(reason: \"This command reformats source files\")])")
```

The plugin is being applied as such:
```
let package = Package(
  name: "TestPackage",
  platforms: [
    .iOS(.v15)
  ],
  ...
  dependencies: [
    .package(url: "https://github.com/nicklockwood/SwiftFormat", .upToNextMajor(from: 
  "0.1.0"))
  ]
  targets: [
    .target(
      name: "TestTarget"
      dependencies: [...],
      plugins: [
        .plugin(name: "SwiftFormatPlugin", package: "SwiftFormat")
      ]
    )
  ],
  swiftLanguageVersions: [
    .version("5.7")
  ]
)
```

Is there something I forgot to add?
Thanks for any contributions.

**Comment by AfanasyKoryakinRMR** [comment]
let package = Package(
    name: "SwiftFormatPluginPackage",
    products: [
        .plugin(name: "ExecuteSwiftFormat", targets: [ "ExecuteSwiftFormat" ]),
        .plugin(name: "SwiftFormatBuildPlugin", targets: [ "SwiftFormatBuildPlugin" ])
    ],
    dependencies: [
        .package(path: "../SwiftFormat"),
    ],
    targets: [
        .plugin(
            name: "ExecuteSwiftFormat",
            capability: .command(
                intent: .custom(verb: "swiftformat", description: ""),
                permissions: [
                    .writeToPackageDirectory(reason: "This command reformats source files"),
                ]
            ),
            dependencies: [
                .product(name: "SwiftFormat", package: "SwiftFormat"),
            ]
        ),
        .plugin(
            name: "SwiftFormatBuildPlugin",
            capability: .buildTool(),
            dependencies: [
                .product(name: "SwiftFormat", package: "SwiftFormat")
            ]
        )
    ]
)

**Comment by AfanasyKoryakinRMR** [comment]
`let package = Package(
    name: "SwiftFormatPluginPackage",
    products: [
        .plugin(name: "ExecuteSwiftFormat", targets: [ "ExecuteSwiftFormat" ]),
        .plugin(name: "SwiftFormatBuildPlugin", targets: [ "SwiftFormatBuildPlugin" ])
    ],
    dependencies: [
        .package(path: "../SwiftFormat"),
    ],
    targets: [
        .plugin(
            name: "ExecuteSwiftFormat",
            capability: .command(
                intent: .custom(verb: "swiftformat", description: ""),
                permissions: [
                    .writeToPackageDirectory(reason: "This command reformats source files"),
                ]
            ),
            dependencies: [
                .product(name: "SwiftFormat", package: "SwiftFormat"),
            ]
        ),
        .plugin(
            name: "SwiftFormatBuildPlugin",
            capability: .buildTool(),
            dependencies: [
                .product(name: "SwiftFormat", package: "SwiftFormat")
            ]
        )
    ]
)`

**Comment by AfanasyKoryakinRMR** [comment]
let package = Package(
    name: "SwiftFormatPluginPackage",
    products: [
        .plugin(name: "ExecuteSwiftFormat", targets: [ "ExecuteSwiftFormat" ]),
        .plugin(name: "SwiftFormatBuildPlugin", targets: [ "SwiftFormatBuildPlugin" ])
    ],
    dependencies: [
        .package(path: "../SwiftFormat"),
    ],
    targets: [
        .plugin(
            name: "ExecuteSwiftFormat",
            capability: .command(
                intent: .custom(verb: "swiftformat", description: ""),
                permissions: [
                    .writeToPackageDirectory(reason: "This command reformats source files"),
                ]
            ),
            dependencies: [
                .product(name: "SwiftFormat", package: "SwiftFormat"),
            ]
        ),
        .plugin(
            name: "SwiftFormatBuildPlugin",
            capability: .buildTool(),
            dependencies: [
                .product(name: "SwiftFormat", package: "SwiftFormat")
            ]
        )
    ]
)


#if swift(>=5.6)
    #if canImport(XcodeProjectPlugin)
    import XcodeProjectPlugin
    #endif

    @main
    struct SwiftFormatPlugin: XcodeCommandPlugin, CommandPlugin {
        func performCommand(context: PackagePlugin.PluginContext, arguments: [String]) async throws {}

        /// This entry point is called when operating on an Xcode project.
        func performCommand(context: XcodePluginContext, arguments: [String]) throws {
            let tool = try context.tool(named: "SwiftFormat")
            let toolURL = URL(fileURLWithPath: tool.path.string)

            let process = Process()
            process.executableURL = toolURL

            let directory = context.xcodeProject.directory
            process.arguments = [
                "--swiftversion", "5.7",
                "--exclude", "\(directory)/Packages/SwiftFormat",
                "--config", "\(directory)/Scripts/SwiftFormat/swiftFormatConfig",
                "\(directory)/ToYou",
                "\(directory)/ToYouPushContentExtension",
                "\(directory)/ToYouPushServiceExtension",
                "\(directory)/ToYouShareExtension",
                "\(directory)/Tests",
                "\(directory)/Packages"
            ]

            try process.run()
            process.waitUntilExit()

            if process.terminationReason == .exit, process.terminationStatus == 0 {
                print("Formatted")
            } else {
                let problem = "\(process.terminationReason):\(process.terminationStatus)"
                Diagnostics.error("swiftformat invocation failed: \(problem)")
            }
        }
    }
#endif

**Comment by nicklockwood** [comment]
@MarcoEidinger any idea about this?

**Comment by MarcoEidinger** [comment]
@TonnyCS you shouldn't need to declare the plugin in your target. It should be sufficient to declare `SwiftFormat` as package dependency.

```
let package = Package(
  name: "TestPackage",
  platforms: [
    .iOS(.v15)
  ],
  ...
  dependencies: [
    .package(url: "https://github.com/nicklockwood/SwiftFormat", .upToNextMajor(from: 
  "0.1.0"))
  ]
  targets: [
    .target(
      name: "TestTarget"
      dependencies: [...],
    )
  ],
  swiftLanguageVersions: [
    .version("5.7")
  ]
)
```
