### ISSUE TITLE
Format on save?

### ISSUE THREAD

**Issue by danielcompton** [nicklockwood/SwiftFormat#145]
SwiftLint formats the code on save by [swizzling methods](https://github.com/ypresto/SwiftLintXcode/blob/06a8dfa70174522a33224db3bb33d8bc800bc6f9/SwiftLintXcode/SaveHook.swift). This is a little bit dicey, but OTOH provides very handy functionality. Would this be considered for SwiftFormat?

**Comment by nicklockwood** [comment]
My understanding is that this isn't supported by Xcode any more due to code-signing. You can only do it if you run a hacked version of Xcode?

**Comment by danielcompton** [comment]
Yes, I think you're right :(.

**Comment by jnordberg** [comment]
Any way to do this in 2022?

**Comment by squarefrog** [comment]
@jnordberg yep, you can do this by using the Xcode extension and overriding the save keyboard shortcut. Here’s a [quick guide](https://luisramos.dev/xcode-format-and-save).
