### ISSUE TITLE
reverse RedundantSelf rule

### ISSUE THREAD

**Issue by TripwireNL** [nicklockwood/SwiftFormat#1456]
Hi,

This is not really an issue more a question, so in our project we want to reverse the RedundantSelf rule. So instead of removing the redundant self we want to throw warnings when there's **no self**. Is there an easy way to do this or does this require to rewrite the redundantSelf rule?

Thx!

**Comment by nicklockwood** [comment]
If you use the `--self insert` option it will insert self instead of removing it. It doesn't work 100% of the time though, as it can't recognize members inherited from classes or extensions in other files or modules.
