### ISSUE TITLE
How to format file on save?

### ISSUE THREAD

**Issue by nikivdev** [nicklockwood/SwiftFormat#1474]
I tried to 'hack' it by using https://watchexec.github.io

So I ran: `watchexec --restart --exts swift "swiftformat ." --project-origin .`

This runs swiftformat . whenever any swift file changes in directory. But if I do it and save in xcode I get this:

<img width="621" alt="image" src="https://github.com/nicklockwood/SwiftFormat/assets/6391776/34e41754-0f5f-4b87-ad5b-c55d04422f89">

Which makes it unusable.

I want to run SwiftFormat automatically on each time I save a file.

Thank you.

**Comment by nicklockwood** [comment]
Unfortunately, this isn't a workflow that Apple supports in Xcode. Extensions have no hook to run when the file is saved, and modifying the file outside of Xcode produces the issue you demonstrate.

Using something like VSCode is an option, though obviously I understand why that's not ideal.

**Comment by mesqueeb** [comment]
@nicklockwood Any other recommended workarounds for this? I'd love to be able to get auto-format on save in Xcode.

**Comment by nicklockwood** [comment]
@mesqueeb I'm not aware of any way to do this. It's relatively easy to set up a file watcher that runs when any file in your project changes, but the problem is that breaks the undo history in Xcode, which makes it really annoying to use in practice.

**Comment by mesqueeb** [comment]
Was able to set it up with [BetterTouchTool](https://folivora.ai)

![image](https://github.com/nicklockwood/SwiftFormat/assets/3253920/51189a99-eefe-46a7-84c3-6e86c9f2f1d5)
