### ISSUE TITLE
redundantSelf rule not caught of files with scoped imports

### ISSUE THREAD

**Issue by marcelo-es** [nicklockwood/SwiftFormat#1475]
Hello..

The `redundantSelf` rule seems not to be caught of files that contain an `import struct`.

## Details

SwiftFormat version: 0.51.12
Swift version: 5.8

## Description

When linting the snipped below (with `swiftformat . --lint --swiftversion 5.8`), SwiftFormat finds the `redundantSelf` broken rule as expected.

```swift
import Foundation

struct ImportScopes {
    let something: String
    init(someSomething: String) {
                                       // warning: (blankLinesAtStartOfScope)
        self.something = someSomething // warning: (redundantSelf)
    }
}
```

However, just by changing the import into a scoped import, the seemingly unrelated `redundantSelf` rule is not caught anymore.

```swift
import struct Foundation.Date // change into a scoped import

struct ImportScopes {
    let something: String
    init(someSomething: String) {
                                       // warning: (blankLinesAtStartOfScope)
        self.something = someSomething // no warning here
    }
}
```

Other rules seem to be fine.

**Comment by nicklockwood** [comment]
@marcelo-es fixed in 0.51.13
