### ISSUE TITLE
preferKeyPath option not recognized. On v0.51.13

### ISSUE THREAD

**Issue by xRayZx** [nicklockwood/SwiftFormat#1485]
Getting `error: Unknown option --preferKeyPath. Did you mean --patternlet? in configuration file.`

I'm trying to disable keypaths so that compactMap doesn't get formatted to use key paths.

**Comment by nicklockwood** [comment]
preferKeyPaths is a rule, not an option, so it's disabled using `--disable preferKeyPaths`.

**Comment by xRayZx** [comment]
Ah, that worked. Thanks!
