### ISSUE TITLE
Rule Suggestion: Remove Blank Lines After {

### ISSUE THREAD

**Issue by JustinJiaDev** [nicklockwood/SwiftFormat#149]
Currently `SwiftFormat` supports trimming blank lines before `}` but not after `{`. 

```
func foo() {

    bar()
}
```

is currently valid.

Maybe it's worth adding another `blankLinesAtBeginOfScope` rule to match `blankLinesAtEndOfScope` rule?

**Comment by nicklockwood** [comment]
Removing blank lines at the start of a function is something I want to support - I just need to think a bit about what the rule should be, as it's not always what you want (e.g. you probably want it in a function, but it may look weird inside a class)

**Comment by JustinJiaDev** [comment]
I think it's okay for classes, because SwiftFormat still has a BlankSpaceBetweenScopes rule. 

Something like:

```swift
class Foo {
    let x: String

    func a() {
        // do something
    }

    func b() {
        // do something
    }
}
```

**Comment by JustinJiaDev** [comment]
It looks like `blankLinesAtStartOfScope` has been added so I'll close this one. Thanks @nicklockwood!
