### ISSUE TITLE
Error formatting code containing new Regex literals

### ISSUE THREAD

**Issue by eaigner** [nicklockwood/SwiftFormat#1492]
Apple introduced `Regex` literals with macOS 13. I have found that `swiftlint` runs into errors with the new literals.

A minimal example would be an escaped closing brace:

     /\)/

This will fail with:

    error: Unexpected token ) at 72:15 in /.../MyFile.swift.

**Comment by nicklockwood** [comment]
@eaigner can you provide some of the surrounding context? Regex literal parsing is context-dependent due to ambiguity with the `/`operator, and I'm not sure how you'd have valid code that started with a regex literal with nothing preceding it.

**Comment by nicklockwood** [comment]
@eaigner I believe this is fixed in 0.51.14. Let me know if not.

**Comment by nicklockwood** [comment]
@eaigner due to a merge screwup on my part, the fix was not actually included in 0.51.14. It's included in 0.51.15 instead.
