### ISSUE TITLE
Error message when rejecting doc comments on local functions is misleading

### ISSUE THREAD

**Issue by lehmacdj** [nicklockwood/SwiftFormat#1493]
When linting this code snippet with `swiftformat --lint --swiftversion 5.8 --rules docComments test.swift`
```swift
func foo() {
  /// A doc comment on a locally scoped function
  func bar() {}
}
```
it produces the error message `/Users/devin/src/test.swift:2:1: warning: (docComments) Use doc comments for comments preceding declarations.` which is misleading because the correct fix in this case is to make the comment not a doc comment. That is linting this snippet (using the same command as before) doesn't produce a lint error.
```swift
func foo() {
  // A normal comment on a locally scoped function
  func bar() {}
}
```

I suggest that the error message be amended on the local function case to say something like `warning: (docComments) Don't use doc comments preceding locally scoped declarations.`

**Comment by nicklockwood** [comment]
@lehmacdj I've improved the message in version 0.52.0. There's still some further room for improvement, but it would require creating a custom message depending on exactly what the correction was.
