### ISSUE TITLE
headerFileName has unclear language and is not a useful warning as-is

### ISSUE THREAD

**Issue by charles-hennge** [nicklockwood/SwiftFormat#1505]
headerFileName
Ensure file name reference in header matches actual file name.

In practice we get the following error:
`warning: (headerFileName) Ensure file name reference in header matches actual file name`

If a developer was unaware that the warning was specifically talking about file names written in the _comment header_ of the file they might easily assume that there is some kind of build chain issue being raised and could waste time changing file names or investigating the libraries they are using for file name matches/mismatches. Please change the language here for clarity or this warning will cause more harm than good.

**Comment by nicklockwood** [comment]
@charles-hennge I've improved the wording in 0.52.1
