### ISSUE TITLE
Generate Docker Image for `0.52.0` version

### ISSUE THREAD

**Issue by rickyhosfelt** [nicklockwood/SwiftFormat#1506]
On the [packages](https://github.com/nicklockwood/SwiftFormat/pkgs/container/swiftformat) page I do not see the Docker Image for `0.52.0` the most up-to-date version there is `0.51.15` can you deploy `0.52.0` so we can update to the latest version? 

Thanks!

**Comment by nicklockwood** [comment]
@rickyhosfelt it looks like the Docker action failed - I'll need to investigate why: https://github.com/nicklockwood/SwiftFormat/actions/runs/5848853466

**Comment by nicklockwood** [comment]
@rickyhosfelt it worked on the second attempt. Just one of those things I guess.
