### ISSUE TITLE
"Max Width" can't be set

### ISSUE THREAD

**Issue by houmie** [nicklockwood/SwiftFormat#1512]
Please see the screenshot below. I'm not able to set values for "Max Width" for the line.
Even if I unclick wrap. Am I missing something? Thanks

<img width="470" alt="Screenshot 2023-08-19 at 11 28 28" src="https://github.com/nicklockwood/SwiftFormat/assets/1832933/d225f397-a717-44db-8cec-0183e4bcadcc">

**Comment by nicklockwood** [comment]
Is the "infer options" checkbox at the top of the screen checked? If so, turn it off.

**Comment by houmie** [comment]
Yes, that worked perfectly.  What does that "infer options" mean? Like a starting template?  It's not very clear.

**Comment by nicklockwood** [comment]
It looks at the existing file and tries to guess what options you are already using.

**Comment by houmie** [comment]
Thanks. Great work.
