### ISSUE TITLE
The `redundantLet` rule can break SwiftUI views that use `let _ = print()` inside an overlay

### ISSUE THREAD

**Issue by mikemahony** [nicklockwood/SwiftFormat#1520]
[This ticket ](https://github.com/nicklockwood/SwiftFormat/issues/1127) seems to have almost fixed the issue.  However, it still arises when used inside an `overlay`:
![image](https://github.com/nicklockwood/SwiftFormat/assets/1740063/407b419f-2026-402e-81af-6619b88ccac1)
![image](https://github.com/nicklockwood/SwiftFormat/assets/1740063/e744be74-b74b-4010-8f2b-2255a1d37bdb)

**Comment by nicklockwood** [comment]
@mikemahony fixed in 0.52.4
