### ISSUE TITLE
0.52.4 did not get marked as latest release

### ISSUE THREAD

**Issue by chenrui333** [nicklockwood/SwiftFormat#1523]
looks like 0.52.4 release did not get marked as latest release, raise this issue for awareness. Thanks!

![image](https://github.com/nicklockwood/SwiftFormat/assets/1580956/82735901-41ca-4e8b-bccf-0d7f19438673)

relates to https://github.com/Homebrew/homebrew-core/pull/143477

**Comment by nicklockwood** [comment]
@chenrui333 thanks - not sure how that happened, but it's fixed now.
