### ISSUE TITLE
Incorrect removal of return in if within a failable init

### ISSUE THREAD

**Issue by yonaskolb** [nicklockwood/SwiftFormat#1525]
Using SwiftFormat 0.52.4 with `swiftversion` set to 5.9, and the `redundantReturn` rule.

SwiftFormat incorrectly removes the return here leading to a compiler error `'nil' requires a contextual type`
```diff
init?(optionalHex: String?) {
    if let optionalHex {
        self.init(hex: optionalHex)
    } else {
-        return nil
+        nil
    }
}
```

Will be removing this code anyway, as it serves no real purpose, but wanted to open an issue to let you know

**Comment by nicklockwood** [comment]
@yonaskolb fixed in 0.52.4. Thanks for the report!
