### ISSUE TITLE
Problems with `sortTypealiases` rule

### ISSUE THREAD

**Issue by DanielCech** [nicklockwood/SwiftFormat#1526]
It looks like the `sortTypealiases` rule is not available. It is mentioned in the list of rules that are available by default but if you call `swiftformat --rules` it is not mentioned there.

When I tried it on the code it looks like it is not working. My typealiases are not sorted.

```
public typealias Cache = ScheduleTimeCreating & ScheduleTimesFetching & ChildMeFetching
```

**Comment by nicklockwood** [comment]
@DanielCech it's working for me - try `swiftformat --version` and make sure that you have the latest (0.52.4).

**Comment by DanielCech** [comment]
@nicklockwood You are right. I used older version of SwiftFormat. Thank you for your help. It works for me as well. Closing.
