### ISSUE TITLE
Xcode 15 recommended settings cause sandbox reports for BuildTools

### ISSUE THREAD

**Issue by kevingriffin** [nicklockwood/SwiftFormat#1529]
Using the BuildTools guide in the README, sandbox reports like

`Sandbox: swift-package(43344) deny(1) file-read-data /Users/kevin/Developer/Eikaiwa/BuildTools`

are emitted when using the setting "Enable User Script Sandboxing".

Is it just best to leave this off?

**Comment by nicklockwood** [comment]
Yes - I should update the README.

**Comment by kevingriffin** [comment]
Thank you for the response! I'll close this and leave it off.
