### ISSUE TITLE
README.md/rules/semicolons/3rd example no change

### ISSUE THREAD

**Issue by brucer42** [nicklockwood/SwiftFormat#153]
No effect here AFAICT

- return;
- goto(fail)
+ return;
+ goto(fail)

**Comment by nicklockwood** [comment]
Yes, that's intentional. Removing the semicolon in that case would change the behavior of the code.

**Comment by brucer42** [comment]
I get it but it looks like a diff.  It's really an explanation. Perhaps a
comment in the "diff"?

About wraparguments: I have inherited some code with long function argument
lists. Like 150 characters. Wraparguments doesn't change them. Any ideas?

Great tool!

**Comment by nicklockwood** [comment]
> Wraparguments doesn't change them

Yeah, I don't currently have a way to specify a wrap width, so wraparguments only makes the wrapping consistent for a given function, it doesn't enforce a particular line length.

**Comment by nicklockwood** [comment]
> Wraparguments doesn't change them

Yeah, I don't currently have a way to specify a wrap width, so wraparguments only makes the wrapping consistent for a given function, it doesn't enforce a particular line length.

**Comment by nicklockwood** [comment]
I've updated the docs. Hopefully they're a bit clearer now.
