### ISSUE TITLE
Incorrectly inserts space into array slice syntax.

### ISSUE THREAD

**Issue by cheeseonhead** [nicklockwood/SwiftFormat#154]
# Code
`let newMoves = Array<BoardPoint>(gameData.moves[game.gameData.moves.count...])`

# Expected
There's no space around `...` as having space there causes compile error.

# Actual
Spaces are inserted around `...`.
`let newMoves = Array<BoardPoint>(gameData.moves[game.gameData.moves.count ... ])`

**Comment by nicklockwood** [comment]
Thanks. Is this syntax new in Swift 4? I've not come across it before.

Should be a simple fix anyway.

**Comment by nicklockwood** [comment]
Fixed in 0.29.2
