### ISSUE TITLE
doesn't recognize both --disable all and // swiftformat:disable all

### ISSUE THREAD

**Issue by hhajime** [nicklockwood/SwiftFormat#1540]
When attempting to disable SwiftFormat for a all of code, neither the -- disable all nor the // swiftformat:disable all directives seem to be working. 

here's my .swiftformat.yml

```
# .swiftFormat

#  disable all rules for optional rule activation.
--disable all
// swiftformat:disable all
```

**Comment by nicklockwood** [comment]
.swiftformat files aren't yaml and shouldn't have a .yml extension - could that be the problem?
