### ISSUE TITLE
Generic Type Name Violation To Swift 5.9 new feature

### ISSUE THREAD

**Issue by MrYu4** [nicklockwood/SwiftFormat#1555]
Swift 5.9 has new feature called:Parameter Packs
[SE-0399](https://github.com/apple/swift-evolution/blob/main/proposals/0399-tuple-of-value-pack-expansion.md)

Now I try to write this code In Swift 5.9:
```
func tuplify<each T>(_ value: repeat each T) -> (repeat each T) {
  return (repeat each value)
}
```
but I was told that this error happened by swiftFormat:
> Generic Type Name Violation: Generic type name should start with an uppercase character: 'each' (generic_type_name)

So how could I do?

**Comment by nicklockwood** [comment]
@MrYu4 are you sure that error is from SwiftFormat? It looks more like SwiftLint output to me.
