### ISSUE TITLE
Indent rule default?

### ISSUE THREAD

**Issue by simon-assistiq** [nicklockwood/SwiftFormat#1557]
Possibly stupid question but I'm just curious. The [Rules.md file](https://github.com/nicklockwood/SwiftFormat/blob/main/Rules.md#indent) doesn't specify a default indent. Is there one? When you run `swiftformat .` without specifying `indent` it does seem to leave the indents in my project unchanged (4 spaces)… is it actually defaulting to 4 or is it figuring out the indent dynamically? Tried a quick search in the code but it wasn't clear to me.

**Comment by nicklockwood** [comment]
It's listed under the options for the rule, see the `--indent` option. If you want 2 spaces use `--indent 2`

**Comment by simon-assistiq** [comment]
This is what I'm seeing 

<img width="743" alt="image" src="https://github.com/nicklockwood/SwiftFormat/assets/148139046/013375db-2050-4a16-b40b-20def6a21769">

Where does it say what the default is? Or am I looking in the wrong file?

**Comment by nicklockwood** [comment]
The default is 4 spaces.

**Comment by nicklockwood** [comment]
You can use the --inferoptions command to generate a set of defaults from your project, but that's slow, so it doesn't run every time automatically.

**Comment by simon-assistiq** [comment]
Thanks
