### ISSUE TITLE
RegEx

### ISSUE THREAD

**Issue by pdshelley** [nicklockwood/SwiftFormat#1558]
the following line of code has the error of `spaceAroundParens`

`let result = inputText.matches(of: /\s(\w+)$/)`

I believe this is an error, as this is valid syntax with RegexBuilder introduced in Swift 5.7.

**Comment by nicklockwood** [comment]
I'm not seeing any errors with this line of code. Can you share your .swiftformat config. Does the error definitely present for a file with just that line of code in it? Maybe it depends on some surrounding context?
