### ISSUE TITLE
 Xcode source editor extension, prioritize read project folder's .swiftformat

### ISSUE THREAD

**Issue by winddpan** [nicklockwood/SwiftFormat#1559]
Is there any way to accomplish this?
I'm unsure whether the Xcode Plugin is aware of the Project's environment or path. 
If it is, perhaps the Xcode source editor extension should prioritize the Swiftformat rule of the project folder and then fallback to the rule of the host application.

**Comment by nicklockwood** [comment]
@winddpan unfortunately this is not possible due to extension sandboxing - it can only see the contents of the currently-open file, and not the location on disk.

**Comment by sdykae** [comment]
@nicklockwood  maybe could we could add configuration options by copying .swiftformat file contents to a configuration textarea option in the extension, could be more easier than check boxes
```
--indent 2
```

**Comment by nicklockwood** [comment]
@sdykae you can import your .swiftformat file into the SwiftFormat for Xcode app using the File>Open menu.

**Comment by sdykae** [comment]
> @sdykae you can import your .swiftformat file into the SwiftFormat for Xcode app using the File>Open menu.

was looking for that option, thank you so much
