### ISSUE TITLE
Comment before closure at beginning of line removed

### ISSUE THREAD

**Issue by PlayfulGeek** [nicklockwood/SwiftFormat#157]
In the following example, comment 2 is lost, probably due to one of the "braces" rules.

Before:
![image](https://user-images.githubusercontent.com/1126933/28131957-529761f6-66f0-11e7-9a90-f508e89e108c.png)

After: 
![image](https://user-images.githubusercontent.com/1126933/28131972-5f66a1e4-66f0-11e7-9079-1d361426fa2b.png)

(test code)

    let responses = [

        // comment 1
        "response1",

        // comment 2 (for optional response)
        {
            let calculatedCondition = true
            return calculatedCondition ? "response2" : nil
        }(),

        // comment 3
        "response3"

        ].flatMap { $0 }

**Comment by nicklockwood** [comment]
Thanks, I'll add a fix.

**Comment by nicklockwood** [comment]
Fixed in 0.29.3. Thanks!
