### ISSUE TITLE
Linux binary is non executable

### ISSUE THREAD

**Issue by cerisier** [nicklockwood/SwiftFormat#1570]
In 0.52.8 Release, the linux binary executable is not "executable"
```
$ ls -l
-rw-r--r--@ 1 user  staff  9740576 Oct 17 11:19 /home/user/swiftformat_linux
$
```

**Comment by nicklockwood** [comment]
This seems to be a limitation of then github workflow. I've fixed the download manually for now, but I'm not sure what the long term solution is.

**Comment by cerisier** [comment]
Closing since this has since been fixed :) Thanks
