### ISSUE TITLE
0.52.9 is not available via Homebrew

### ISSUE THREAD

**Issue by honkmaster** [nicklockwood/SwiftFormat#1579]
```
~ %   brew install swiftformat

Warning: swiftformat 0.52.8 is already installed and up-to-date.
To reinstall 0.52.8, run:
```

`brew update` was run in advance.

https://formulae.brew.sh/formula/swiftformat list 0.52.8 as the most recent version

**Comment by nicklockwood** [comment]
It has to be manually updated and approved by the Homebrew team, so it usually takes a little while to appear.

**Comment by honkmaster** [comment]
Oh wow. Didn’t know that this is a manual process. Thanks @nicklockwood.

**Comment by jshier** [comment]
Rather than opening a new issue (which I can if you want), it seems like 0.52.9 isn't available on CocoaPods yet, despite the podspec being updated in the repo.

**Comment by nicklockwood** [comment]
@jshier yes, that also needs to be pushed manually (but that one's on me 🤦‍♂️)

**Comment by honkmaster** [comment]
BTW: Was brew always that slow? 0.52.10 also takes some time.
