### ISSUE TITLE
wraparguments after-first?

### ISSUE THREAD

**Issue by MiaShopgal** [nicklockwood/SwiftFormat#1580]
SwiftFormat for Xcode Version 0.52.8 (1)

given these two functions in the same file, after formatted, why the 2nd method isn't formatted just like the 1st one?

before formatting

    func foo(
      bar: Int,
      baz: String
    ) {

    }
    
    func foo(a: Int, b: Int) {
        
    }

after formatting

    func foo(bar: Int,
             baz: String) {
    }

    func foo(a: Int, b: Int) {
    }

**Comment by nicklockwood** [comment]
The rule is only applied to functions that are already wrapped, or which exceed the specified line length.

There have been requests to support wrapping all functions, but that's not implemented yet.

**Comment by MiaShopgal** [comment]
Roger that. 
Looking forward to this feature be implemented :)
