### ISSUE TITLE
Cannot disable rules

### ISSUE THREAD

**Issue by wladyslaws** [nicklockwood/SwiftFormat#159]
Hello, thank you for this awesome tool:) I want to give it a try, but apparently rules disabling is not working for me. Here is the output of two following commands for disabling and then checking rules.

    /Users/home>swiftformat --rules --disable unusedArguments,redundantLet,redundantPattern,wrapArguments

    blankLinesAtEndOfScope
    blankLinesBetweenScopes
    braces
    consecutiveBlankLines
    consecutiveSpaces
    elseOnSameLine
    fileHeader
    hoistPatternLet
    indent
    linebreakAtEndOfFile
    linebreaks
    numberFormatting
    ranges
    redundantBackticks
    redundantGet
    redundantInit
    redundantLet (disabled)
    redundantNilInit
    redundantParens
    redundantPattern (disabled)
    redundantRawValues
    redundantReturn
    redundantSelf
    redundantVoidReturnType
    semicolons
    spaceAroundBraces
    spaceAroundBrackets
    spaceAroundComments
    spaceAroundGenerics
    spaceAroundOperators
    spaceAroundParens
    spaceInsideBraces
    spaceInsideBrackets
    spaceInsideComments
    spaceInsideGenerics
    spaceInsideParens
    specifiers
    todos
    trailingClosures (disabled)
    trailingCommas
    trailingSpace
    unusedArguments (disabled)
    void
    wrapArguments (disabled)

    /Users/home>swiftformat --rules

    blankLinesAtEndOfScope
    blankLinesBetweenScopes
    braces
    consecutiveBlankLines
    consecutiveSpaces
    elseOnSameLine
    fileHeader
    hoistPatternLet
    indent
    linebreakAtEndOfFile
    linebreaks
    numberFormatting
    ranges
    redundantBackticks
    redundantGet
    redundantInit
    redundantLet
    redundantNilInit
    redundantParens
    redundantPattern
    redundantRawValues
    redundantReturn
    redundantSelf
    redundantVoidReturnType
    semicolons
    spaceAroundBraces
    spaceAroundBrackets
    spaceAroundComments
    spaceAroundGenerics
    spaceAroundOperators
    spaceAroundParens
    spaceInsideBraces
    spaceInsideBrackets
    spaceInsideComments
    spaceInsideGenerics
    spaceInsideParens
    specifiers
    todos
    trailingClosures (disabled)
    trailingCommas
    trailingSpace
    unusedArguments
    void
    wrapArguments

Specified rules are not applied to files that are subject to formatting, nor they appear in --rules output.
I'm running Xcode 8.3.3 (8E3004b) on Sierra 10.12.6 (16G29). Do you have any idea what maybe the cause and fix? Maybe some linking problems?
I'm willing to make a patch and pull request, but need some hints/guidance first. Apart from that this is awesome work:)

**Comment by nicklockwood** [comment]
SwiftFormat has no memory of previous commands that you have given it. If you want to disable the rules, you have to pass the list of disabled rules each time you use it.

**Comment by wladyslaws** [comment]
thank you:)
