### ISSUE TITLE
..< and .. should no space

### ISSUE THREAD

**Issue by nypisces** [nicklockwood/SwiftFormat#16]
0...i
0..<i

**Comment by nicklockwood** [comment]
This was actually deliberate, as I think it looks nicer. It's different from what Apple does in their docs though, so maybe it should be configurable.

**Comment by nicklockwood** [comment]
I've added the `--ranges nospace` option to remove these in v0.8. I couldn't quite bring myself to remove them by default, sorry.

**Comment by nypisces** [comment]
Thanks, I love this option.
