### ISSUE TITLE
Changing text in multiline strings

### ISSUE THREAD

**Issue by alastaircoote** [nicklockwood/SwiftFormat#160]
I have some hard-coded JSON in my code:

    """
        {
            "Content-Type":["application/json"],
            "Cache-Control":["public","max-age=1"]
        }
    """

After running swiftformat it looks like this:

    """
        {
            "Content - Type":["application / json"],
            "Cache - Control":["public","max - age = 1"]
        }
    """

I'm assuming this is because it is applying Swift formatting rules to the text, which I obviously don't want it to do!

**Comment by nicklockwood** [comment]
Seems like a reasonable assumption. And yes, clearly a bug!

**Comment by alastaircoote** [comment]
(for anyone running into this issue as well, using `--disable spaceAroundOperators` solves this specific issue in the immediate term, though obviously it also affects your Swift code as well)

**Comment by nicklockwood** [comment]
FYI, it turns out the issues is that SwiftFormat currently doesn't understand the """ multiline string delimiter, introduced in Swift 4. I haven't spent a lot of time on Swift 4 support yet, but I'll see if I can make this work.

**Comment by alastaircoote** [comment]
Didn't realise it was Swift 4 only. Relative newbie here. Apologies for jumping the gun!

**Comment by nicklockwood** [comment]
No problem - I'll have to fix it eventually :-)

**Comment by nicklockwood** [comment]
Fixed in 0.29.3. Thanks!
