### ISSUE TITLE
Inheriting rules in a subdirectory

### ISSUE THREAD

**Issue by meherkasam** [nicklockwood/SwiftFormat#1600]
Apologies if this has already been answered somewhere in the documentation. I read through the README and searched through issues but couldn't quite find what I was looking for.

I have the following directory structure:

```
example
├── .swiftformat
└── inner
    ├── .swiftformat
    └── test.swift
```

Contents of `example/.swiftformat`:
```
--rules semicolons
```

Contents of `example/inner/.swiftformat`:
```
--rules spaceAroundParens
```

Contents of `example/inner/test.swift`:
```
func hello(){
    print("Hello");
}
```

Command run from `example/`:
```
swiftformat .
```

Expected contents of `example/inner/test.swift`:
```
func hello() {
    print("Hello")
}
```

Actual contents of `example/inner/test.swift`:
```
func hello() {
    print("Hello");
}
```

It appears that the rules set in the parent directory level are not being applied to a sub-directory if it contains its own `.swiftformat` file. The goal here is to achieve a structure where the root level would contain a few baseline rules and some subfolders deep down the hierarchy might want to conform to all of the baseline rules, but have their own stricter rules on top of the baseline rules. Is this achievable without having to maintain manual copies of the same rules in multiple places?

Thank you for your help and appreciate any insight you can provide here.

**Comment by nicklockwood** [comment]
The `--rules` option is exclusive, meaning only those rules that are listed in the file will be enabled.

What you probably want to do is use `--enable` in the child directory `.swiftformat` files instead, so that rules specified higher up are inherited.

**Comment by meherkasam** [comment]
That's exactly what I needed. Thank you so much!
