### ISSUE TITLE
cocoapods integration instructions not correct.

### ISSUE THREAD

**Issue by RishabhTayal** [nicklockwood/SwiftFormat#161]
In the tutorial, the path is incorrect. The path should be `${PODS_ROOT}/SwiftFormat/CommandLineTool/swiftformat .` instead of `"${SRCROOT}/Pods/SwiftFormat/CommandLineTool/swiftformat"`. I will create a PR to fix this.

**Comment by nicklockwood** [comment]
Thanks!

**Comment by RishabhTayal** [comment]
Please note that I also added a `.` in the end.
