### ISSUE TITLE
--anonymousforeach ignore is not working

### ISSUE THREAD

**Issue by Mehdi-Sohrabi0** [nicklockwood/SwiftFormat#1612]
Hi,

I want to ignore the new rule for converting `forEach` loop to `for loop`, so I added `--anonymousforeach ignore` to my `.swiftformat` file (also tried with `--anonymousforeach preserve`), but still when I'm running `swiftformat .` it will convert my `forEach` loop to `for` loop.

Any help or suggestion would be appreciated.

Best

**Comment by nicklockwood** [comment]
Add --disable preferForLoop to your config

**Comment by Mehdi-Sohrabi0** [comment]
> Add --disable preferForLoop to your config

Thanks a lot, solved the problem.
