### ISSUE TITLE
Internal keyword is dropped on access-level imports (AccessLevelOnImport feature)

### ISSUE THREAD

**Issue by mr-swifter** [nicklockwood/SwiftFormat#1618]
Access-level modifiers on import declarations feature has been added to Swift 5.9. See [reference](https://github.com/apple/swift-evolution/blob/main/proposals/0409-access-level-on-imports.md). It's under experimental flag now, but can be used. 

This feature allows, in particular, do internal imports:
```swift
internal import MyPackage
```

It seems this `internal` keyword falls under `redundantInternal` rule and removed when I apply `swiftformat`, but in reality it now has absolutely different meaning and can't be consider just as redundant internal.

**Comment by nicklockwood** [comment]
@mr-swifter fixed in 0.53.1
