### ISSUE TITLE
`hoistAwait` rule puts `await` before `try`, that makes code **Invalid**

### ISSUE THREAD

**Issue by smartpie** [nicklockwood/SwiftFormat#1619]
Rule `hoistAwait` takes `await` out of the arguments to the beginning and puts in before `try`

For example, code:
```
try foo(await bar())
```
Transforms into:
```
await try foo(bar())
```

Which is uncopilatable code. The problem is that `try` must be before `await`. The `hoistAwait` rule is responsible for this.

**Comment by nicklockwood** [comment]
@smartpie fixed in 0.53.2
