### ISSUE TITLE
False positive with `spaceAroundBrackets` for consuming or borrowing array parameter

### ISSUE THREAD

**Issue by Jnosh** [nicklockwood/SwiftFormat#1656]
The following reports a violation of the `spaceAroundBrackets` rule:

```swift
func foo(arg: consuming [String]) {
  // ...
}
```

Same with `borrowing` or when using the non-shorthand `Array<...>` syntax.

swiftformat expects the following instead:
```swift
func foo(arg: consuming[String]) {
  // ...
}
```

swiftformat: 0.53.5

**Comment by Jnosh** [comment]
I just noticed another similar issue when using the `isolated` keyword:

```swift
// warning: (spaceAroundParens) Add or remove space around parentheses.
func foo(isolation: isolated (any Actor)) {
    // ...
}
```

Here `spaceAroundParens` is triggered where SwiftFormat wants to remove the space between `isolated` and the following parentheses.
I'm just adding it here since it's a very similar issue but feel free to let me know if I should open a separate issue.

As written above, the parentheses are redundant anyway and can just be removed but this will become relevant with [SE-420](https://github.com/apple/swift-evolution/blob/main/proposals/0420-inheritance-of-actor-isolation.md#user-content-fnref-2-fa73ead4cff2dc3249d4579a8d64a87d) which allows isolated to take an optional argument, e.g. `(any Actor)?` where the parentheses become necessary.

**Comment by Jnosh** [comment]
Thank you, I tried the new release and it's working perfectly.

**Comment by Vyazovoy** [comment]
@nicklockwood @calda, the `isolated` fix forks for `func` but if I define a property like:
```swift
public var someName: @Sendable (_ isolation: isolated (any Actor)?) async throws -> Int
```
SwiftFormat still removes the space after `isolated`
