### ISSUE TITLE
Format rule --allman false

### ISSUE THREAD

**Issue by CaramelHeaven** [nicklockwood/SwiftFormat#1660]
What is the rule which format my brace at new line?

I have --allman false but this is not work, when I want to format my guard\if statement with 2+ conditions I will get `{` at new line, example

```
guard boolCondition,
      anotherCondition else
{
    return nil
}
```

If i have 1 condition everything is fine

```
guard boolCondition else {
    return nil
}
```

Also, I have `--guardelse same-line`

**Comment by nicklockwood** [comment]
This is the [wrapMultilineStatementBraces](https://github.com/nicklockwood/SwiftFormat/blob/main/Rules.md#wrapmultilinestatementbraces) rule. Use

```
--disable wrapMultilineStatementBraces
```

to turn it off.

**Comment by CaramelHeaven** [comment]
Thanks you very much, sir. Have a good day
