### ISSUE TITLE
`wrapEnumCases` breaks for associated values when `case` is on  different line

### ISSUE THREAD

**Issue by MartinP7r** [nicklockwood/SwiftFormat#1662]
The base code is not pretty but valid Swift, but the formatted code is broken in this case:

`--enable wrapEnumCases`

input

```swift
enum SortOrder { case
    asc(String), desc(String)
}
```

output

```swift
enum SortOrder { case
    asc(String)
    desccase String
}
```

**Comment by nicklockwood** [comment]
@MartinP7r fixed in 0.53.7 (the formatting is still a bit whack but it should no longer make the code uncompilable)
