### ISSUE TITLE
Really strange permission problem

### ISSUE THREAD

**Issue by everlof** [nicklockwood/SwiftFormat#1663]
I get this with the installation below:

`The file “.swiftformat” couldn’t be opened because you don’t have permission to view it.`

I have no reason what the issue might be - perhaps not even related to swiftformat? Because swiftformat runs fine in other projects. But this project is pretty new and really simple setup..

Xcode: Version 15.3 (15E204a)
macOS: 14.4 (23E214)

Installation in Xcode project: 

```
unset SDKROOT

if [[ "$(uname -m)" == arm64 ]]; then
    export PATH="/opt/homebrew/bin:$PATH"
else
    export PATH="/usr/local/bin:$PATH"
fi

if ! which mint > /dev/null; then
    echo "error: \`mint\` is not installed - install it using \`brew install mint\`"
    exit 1
fi

mint run nicklockwood/SwiftFormat@0.53.5 . || exit 1

```

My `.swiftformat`:

```
--exclude DerivedData
```

I've tried changing permissions of the `.swiftformat` file as well, but no success:

```
$ ll -la .swiftformat 
-rw-r--r--  1 david  staff  22 Apr  1 09:32 .swiftformat

$ chmod 777 .swiftformat 

$ ll -la .swiftformat 
-rwxrwxrwx  1 david  staff  22 Apr  1 09:32 .swiftformat
```

If I remove the `.swiftformat` file and just do:

```
mint run nicklockwood/SwiftFormat@0.53.5 URLDrop || exit 1
```

I get:

![Screenshot 2024-04-01 at 09 48 55](https://github.com/nicklockwood/SwiftFormat/assets/1321434/92447819-d042-4e54-90de-a69418f12ddb)

Is it something related to Xcode sandboxing the run-phase?

**Comment by everlof** [comment]
Solved by chaning: `ENABLE_USER_SCRIPT_SANDBOXING = NO` to `YES`

**Comment by RapidOwl** [comment]
For anyone else finding this, doing the opposite solved my problem.

`ENABLE_USER_SCRIPT_SANDBOXING` was set to "Yes". I changed it to "No" and SwiftFormat started working.
