### ISSUE TITLE
Build phase - swiftformat not able to view .swiftformat on test target

### ISSUE THREAD

**Issue by evliu** [nicklockwood/SwiftFormat#1669]
Hi, does anyone have any insight into why the build phase script works on the main build target for my iOS app project but not in the test and uitest targets? I can add it to `Input Files`, but then I would also need to add every single swift file also. I'm sure it's just a setting but I can't figure it out after hours on google and copilot. Thanks in advance!

<img width="519" alt="Screenshot 2024-04-10 at 9 15 23 PM" src="https://github.com/nicklockwood/SwiftFormat/assets/151991228/a5d3d34c-be72-4b33-b728-28518765cffd">

**Comment by nicklockwood** [comment]
Could it be that you need to set `ENABLE_USER_SCRIPT_SANDBOXING=NO`?

**Comment by evliu** [comment]
> Could it be that you need to set `ENABLE_USER_SCRIPT_SANDBOXING=NO`?

Thank you so much 😭 I had it set on the main target but totally forgot about it after the fact!!!!! ripping out my hair! sorry for the trouble!
