### ISSUE TITLE
Report as XML conforming to the Checkstyle specification to support in Jenkins pipeline

### ISSUE THREAD

**Issue by saeed-rz** [nicklockwood/SwiftFormat#1673]
I would like to have a new reporter to report as XML.
Reports warnings as XML conforming to the Checkstyle specification, as defined here:
https://www.jetbrains.com/help/teamcity/xml-report-processing.html

I can try to write it if it's ok. what do you think? (I probably need help).

**Comment by nicklockwood** [comment]
@saeed-rz seems like a good idea - I'd be happy to accept a PR that does this. I'd suggest you start by taking a look at the JSONReporter and GithubActionsLogReporter for reference.

**Comment by nicklockwood** [comment]
@saeed-rz the general release process is that I make 0.0.x releases until there are no new reported bugs, then I'll make a 0.x.0 release with new features. I'll sometimes make an exception and include new features alongside the bug fixes, but I try to avoid it because it can break things

**Comment by saeed-rz** [comment]
@nicklockwood Thanks for the explanation.

**Comment by nicklockwood** [comment]
@saeed-rz landed in 0.54.0
