### ISSUE TITLE
Want to add antonym rules for `redundantNilInit`

### ISSUE THREAD

**Issue by rakuyoMo** [nicklockwood/SwiftFormat#1677]
Our team's norm is that all variables need to be explicitly assigned an initial value, including the special case of `Optional`. I noticed the [redundantNilInit](https://github.com/nicklockwood/SwiftFormat/blob/main/Rules.md#redundantnilinit) rule and hoped there would be an opposite rule that would automatically add a `nil` initial value to `Optional` type values.

**Comment by nicklockwood** [comment]
Seems reasonable. If you'd be interested in trying to contribute such a rule I'd be happy to accept it, otherwise I'll add it to the backlog

**Comment by rakuyoMo** [comment]
> Seems reasonable. If you'd be interested in trying to contribute such a rule I'd be happy to accept it, otherwise I'll add it to the backlog

I'll try it. Do you recommend adding a new rule, or adding a new parameter to `redundantNilInit`?

**Comment by nicklockwood** [comment]
> I'll try it. Do you recommend adding a new rule, or adding a new parameter to `redundantNilInit`?

It should be a new parameter. Probably something like `--nilinit insert/remove/properties-only`

**Comment by rakuyoMo** [comment]
Close with https://github.com/nicklockwood/SwiftFormat/pull/1679
