### ISSUE TITLE
False negative when inserting `self.`

### ISSUE THREAD

**Issue by keith** [nicklockwood/SwiftFormat#168]
In this case:

```swift
struct Foo {
    var bar: String
}

extension Foo {
    init() {
        bar = "hi"
    }
}
```

If you attempt to insert missing `self.`, `bar =` is not given a `self.`

**Comment by nicklockwood** [comment]
This is a known limitation of the way SwiftFormat is implemented. It has no concept of overall program structure (no AST), so inherited or extension members can't be identified as belonging to self.

I may eventually be able to make this work for extensions in the same file, as in this case, but it will never cover 100% of cases.
