### ISSUE TITLE
`opaqueGenericParameters` rule fails when `@_specialize(where S == ...)` attribute is added

### ISSUE THREAD

**Issue by inamiy** [nicklockwood/SwiftFormat#1684]
When `@_specialize(where S == ...)` attribute is added before `func` declaration,
this func's generic parameter `<S: Sequence<Element>>` cannot be replaced with opaque `some Sequence<Element>`.
But swiftformat (as of ver 0.53.7) + `opaqueGenericParameters` rule formats this wrongly.

**Comment by nicklockwood** [comment]
@inamiy fixed in 0.53.8

**Comment by inamiy** [comment]
@nicklockwood Thank you for quick update!
