### ISSUE TITLE
Applying trailing closures in Modifiers.

### ISSUE THREAD

**Issue by kwokpia** [nicklockwood/SwiftFormat#1686]
Help, how can this be achieved?

```diff
-         List(...){...}.toolbar(content: { ... })
+         List(...){...}.toolbar {...}

**Comment by nicklockwood** [comment]
@kwokpia if you add the argument `--trailingclosures toolbar` it will convert this case. Normally only anonymous closure arguments are converted to trailing.

**Comment by kwokpia** [comment]
> @kwokpia if you add the argument `--trailingclosures toolbar` it will convert this case. Normally only anonymous closure arguments are converted to trailing.

It worked as expected. Thanks!
