### ISSUE TITLE
Add Privacy manifest

### ISSUE THREAD

**Issue by robo-hitesh** [nicklockwood/SwiftFormat#1692]
At WWDC23 Apple is requiring all api calls that fall under this ruleset https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api#4278394
be added to a privacy manifest file.
Does SwiftFormat need to include this manifest?
Please let me know about your upcoming plans to apply the privacy manifest.

**Comment by nicklockwood** [comment]
If you are using SwiftFormat locally to format your code then I don't believe you need to include a manifest. If you plan to ship the SwiftFormat framework in your app then you might - if so please let me know how you plan to use it and I'll see if I can help.
