### ISSUE TITLE
spaceAroundOperators false positive with @MainActor and @Sendable

### ISSUE THREAD

**Issue by brzzdev** [nicklockwood/SwiftFormat#1698]
Given
`let example = Example<(@MainActor () -> Void)?>(nil)`
or
`let example = Example<(@Sendable () -> Void)?>(nil)`
then
`spaceAroundOperators`
will change these to
`let example = Example < (@MainActor () -> Void)?> nil`
`let example = Example < (@Sendable () -> Void)?> nil`
which is then an error in Xcode.

`let example = Example<(() -> Void)?>`
doesn't have this issue.

**Comment by nicklockwood** [comment]
@brzzdev fixed in 0.53.10
