### ISSUE TITLE
Swift 4 build errors

### ISSUE THREAD

**Issue by rajbarik** [nicklockwood/SwiftFormat#170]
Any fix for Swift 4 support? I get this error: "error: package has unsupported layout; found loose source files:"

**Comment by nicklockwood** [comment]
Not yet. There's a branch for 3.2 support here: https://github.com/nicklockwood/SwiftFormat/tree/xcode-9b5 but it has some performance regressions.

**Comment by nicklockwood** [comment]
Fixed in 0.29.5
