### ISSUE TITLE
Realize `_modify` as an accessor?

### ISSUE THREAD

**Issue by MahdiBM** [nicklockwood/SwiftFormat#1717]
I noticed the [`_modify`](https://forums.swift.org/t/modify-accessors/31872) accessor is not in the [accessors list](https://github.com/nicklockwood/SwiftFormat/blob/6c9975902989b4cf89fdf438fd511b9d7720fee8/Sources/FormattingHelpers.swift#L2873).
Not sure if it makes any special differences, but optimally SwiftFormat should also take care of this accessor to prevent possible bugs?

**Comment by nicklockwood** [comment]
@MahdiBM fixed in 0.54.0
