### ISSUE TITLE
Whitespace and extra line at end of file

### ISSUE THREAD

**Issue by VinceMikhailKearney** [nicklockwood/SwiftFormat#173]
When there is only one blank line at the end of the file it seems to add an extra one, I had seen in the CHANGELOG that you commented in August 2016 it was sorted so I was wondering if it's a rule I need to change as I can't seem to figure it out looking through it all? :)

Another question:
I have a pre-commit hook that gives me a patch file to see what the differences are, which I can then apply and commit (and have it passed as I applied the patch file previously) but I notice that it seems to delete whitespace and then add it again immediately after... Meaning the patch file isn't actually changing anything which can be frustrating with every commit.
(P.s. I know the one just above is a long shot and not overly well explained but more just wondering if this sounds familiar to you at all.)

Just to demonstrate, the screenshot below shows a line being deleted to immediately be added again. At the end it adds an extra new line at the end of the file, although there already is one.
<img width="811" alt="screenshot 2017-09-06 22 45 07" src="https://user-images.githubusercontent.com/22050106/30136025-0d18fe5a-9355-11e7-95a5-2803cc97b2d3.png">
Thanks

**Comment by nicklockwood** [comment]
It's not possible for a line to be deleted and added again, as that would not result in a change in the patch file. I suspect what is happening is that the line originally contained trailing spaces or tabs, and SwiftFormat has removed those.

The blank line added at the end of the file is also not a bug, it's a deliberate feature. If you don't want that, you can disable it with `--disable linebreakAtEndOfFile`
