### ISSUE TITLE
Unable to disable/modify rules 

### ISSUE THREAD

**Issue by foramcd** [nicklockwood/SwiftFormat#1752]
I have installed SwiftFormat with SPM 0.54.0.
I am trying to disable few rules in swiftformat file but this is not working

<img width="1728" alt="Screenshot 2024-07-08 at 9 29 29 PM" src="https://github.com/nicklockwood/SwiftFormat/assets/144029393/783e4c5c-51ff-4909-bf0e-cb619a8070c5">
<img width="1728" alt="Screenshot 2024-07-08 at 9 29 39 PM" src="https://github.com/nicklockwood/SwiftFormat/assets/144029393/4625917f-042e-4679-978b-ef2a822bc8ac">

**Comment by nicklockwood** [comment]
It's not supported to put `--disable ifdef indent` like that without a comma delimiter between the rule names. Could that be the issue?

**Comment by foramcd** [comment]
I updated the rules with SwiftFormat software. 
It's working now.

![Uploading Screenshot 2024-07-09 at 12.05.53 AM.png…]()
