### ISSUE TITLE
Improper remove `let` in SwiftUI body

### ISSUE THREAD

**Issue by mingchen** [nicklockwood/SwiftFormat#1762]
```sh
% swiftformat -version
0.54.1
```

Default rule.

```swift
import SwiftUI

class Foo: View {
    var body: some View {
        let _ = Self._printChanges()

        Text("Foo")
}
```

Should not remove `let` in this context. However after run swiftformat, got following code

```swift
import SwiftUI

class Foo: View {
    var body: some View {
        _ = Self._printChanges()

        Text("Foo")
}

```

This caused a compile error:

> Type '()' cannot conform to 'View'

<img width="613" alt="image" src="https://github.com/user-attachments/assets/24c7e465-5684-488c-ae05-8db52cdabb43">

All the `let` in SwiftUI `body` should not be removed.

**Comment by nicklockwood** [comment]
@mingchen I'm not able to reproduce this bug in 0.54.1 with the code sample you've provided - can you double check? Maybe the sample you provided has been oversimplified?

**Comment by nicklockwood** [comment]
@mingchen any update?
