### ISSUE TITLE
0.54.2 not yet available in CocoaPods 

### ISSUE THREAD

**Issue by pixyzehn** [nicklockwood/SwiftFormat#1772]
Hi,

I'm trying to update SwiftFormat to v0.54.2 via CocoaPods, but it's still not available.
ref: https://github.com/CocoaPods/Specs/tree/master/Specs/5/e/d/SwiftFormat

Could you push the version for CocoaPods? Since I see the same problem for v0.54.0 (https://github.com/nicklockwood/SwiftFormat/issues/1725), would it be possible to prevent this for future versions?

Thanks in advance!

**Comment by nicklockwood** [comment]
Sorry about that - it should be fixed npow
