### ISSUE TITLE
Using swiftformat in Xcode Cloud

### ISSUE THREAD

**Issue by KptnTanyel** [nicklockwood/SwiftFormat#1774]
Hi, I'm trying to set up SwiftFormat to be run automatically after a specific branch has changed via Xcode Cloud.

```
#!/bin/sh

brew install swift-format
swiftformat .
```

The installation of SwiftFormat completes successfully, but `swiftformat .` throws:
`ci_post_clone.sh: line 4: swiftformat: command not found`

How do I run SwiftFormat via Xcode Cloud?

**Comment by nicklockwood** [comment]
@KptnTanyel swift-format and swiftformat are different tools

**Comment by KptnTanyel** [comment]
I just realized this myself and was going to close this topic, but you were quicker 😄
Thanks for your attention and quick reply.

Hopefully my mistake will help someone else figure this out quicker.
