### ISSUE TITLE
Build with Swift Package Manager

### ISSUE THREAD

**Issue by yonaskolb** [nicklockwood/SwiftFormat#178]
While trying to run SwiftFormat with [Mint](https://github.com/yonaskolb/Mint), I found that SwiftFormat doesn't build with `swift build` in Xcode 9.

```
package has unsupported layout; found loose source files
```

This can be fixed by updating the Package to Swift 4

**Comment by nicklockwood** [comment]
I don’t use SwiftPM myself, so this is tricky for me to test. Would you mind creating a PR with the necessary changes?

**Comment by nicklockwood** [comment]
@yonaskolb I had a go at updating the package format, but when I run `mint install https://github.com/nicklockwood/SwiftFormat` I get:

```
Using latest tag "0.29.8"
🌱  Checking out https://github.com/nicklockwood/SwiftFormat "0.29.8"...
🌱  Building swiftformat. This may take a few minutes...
error: package has unsupported layout; found loose source files: /usr/local/lib/mint/packages/github.com_nicklockwood_SwiftFormat/checkout/Tests/CommandLineTests.swift, /usr/local/lib/mint/packages/github.com_nicklockwood_SwiftFormat/checkout/Tests/FormatterTests.swift, /usr/local/lib/mint/packages/github.com_nicklockwood_SwiftFormat/checkout/Tests/OptionsTests.swift, /usr/local/lib/mint/packages/github.com_nicklockwood_SwiftFormat/checkout/Tests/PerformanceTests.swift, /usr/local/lib/mint/packages/github.com_nicklockwood_SwiftFormat/checkout/Tests/RulesTests.swift, /usr/local/lib/mint/packages/github.com_nicklockwood_SwiftFormat/checkout/Tests/SwiftFormatTests.swift, /usr/local/lib/mint/packages/github.com_nicklockwood_SwiftFormat/checkout/Tests/TokenizerTests.swift
```

The latest tag is actually **0.29.9**. Mint seems to have cached the 0.29.8 version, and I can't find any way to make it pull the latest.

**Comment by yonaskolb** [comment]
Ah yes I just noticed this, the repo isn't fetching new tags properly. I have to fix that.

As a workaround you can delete the mint cach
```
rm -rf /usr/local/lib/mint
```

**Comment by yonaskolb** [comment]
Another workaround is to specify the specific version
```
mint install nicklockwood/SwiftFormat@0.29.9
```
