### ISSUE TITLE
Can't figure out lintonly  format

### ISSUE THREAD

**Issue by AndriiPetrovDev** [nicklockwood/SwiftFormat#1820]
I want to add something like `--lintonly maxwidth 120` but this format is incorrect. How to use it with rule with parameter?

**Comment by nicklockwood** [comment]
--lintonly is applied to rules rather than options, so you'd use --lintonly wrap as that is the rule that wraps lines to fit the max width

**Comment by AndriiPetrovDev** [comment]
Sorry I didn't get it :)  So how it should looks like in my config file?

**Comment by AndriiPetrovDev** [comment]
If I use it like
`--lintonly wrap
--maxwidth 120`
It just formats code but I need lint instead

**Comment by nicklockwood** [comment]
Do you only want to lint your code, with no formatting applied at all? If so, use --lint instead (without any arguments). --lintonly is for when you want certain rules to be applied only in --lint mode.

**Comment by nicklockwood** [comment]
So you'd use it like this:

swiftformat --lint --rules wrap --maxwidth 120

**Comment by AndriiPetrovDev** [comment]
No I want to format  my project with a lot of rules (using config) and get only 1 warning for too long lines (because automatic wrap works but decrease readability)

**Comment by nicklockwood** [comment]
@AndriiPetrovDev ah, apologies I misunderstood your requirement. Currently the only way to do this is to run the tool twice, once default format mode with just the rules you wish to format and a second time in --lint mode with just the rules you wish to lint.

The purpose of the --lintonly argument is so you can use the same config for both modes and the --lintonly rules will only apply when in --lint mode.

**Comment by AndriiPetrovDev** [comment]
> only way to do this is to run the tool twice

Thank you Nick
