### ISSUE TITLE
[QUESTION] Which file format has the config file?

### ISSUE THREAD

**Issue by stherold** [nicklockwood/SwiftFormat#1825]
Maybe just a dumb question but I want to enable syntax highlighting and auto-formatting for this file in Neovim. Therefore I need to know which file format that is.

**Comment by nicklockwood** [comment]
The config file is not really any standard format, it's just a set of command-line arguments on separate lines. 

The use of # for comments is consistent with a few different formats like .ini or .yml so maybe try one of those and see if the formatting looks good?

**Comment by stherold** [comment]
Thanks, I'll try that 👍

**Comment by stherold** [comment]
Actually [bash style](https://github.com/Blackjacx/Scripts/blob/504f21cb2c27475ec85371efb031f029ad21d156/bootstrap/config_dirs/nvim/lua/user/core/filetypes.lua#L10) works fine for me 🙃

![image](https://github.com/user-attachments/assets/433346a8-2150-479c-8e19-8fd8d445e118)
