### ISSUE TITLE
`Swift Testing` `@Test` wrapper - `spaceAroundBrackets` produces incorrect results

### ISSUE THREAD

**Issue by denisgaskov** [nicklockwood/SwiftFormat#1846]
## Sample code
This
```swift
@Test(arguments: [kSecReturnRef, kSecReturnAttributes] as [String])
func foo(type: String) {
  print(type) // just suppress 'unused parameter'
}
```
is transformed to this (which perhaps is not correct; the rule should just ignore it)
```swift
@Test(arguments: [kSecReturnRef, kSecReturnAttributes] as[String])
func foo(type: String) {
  print(type) // just suppress 'unused parameter'
}
```

<img width="849" alt="Снимок экрана 2024-09-05 в 08 02 40" src="https://github.com/user-attachments/assets/ac044eaa-9a13-463a-b27a-5a909b54fa03">

## Environment
- SwiftFormat: `0.54.3`
- Xcode: `Version 16.0 beta 6 (16A5230g)`
- Swift: `swiftlang-6.0.0.9.10 clang-1600.0.26.2`

**Comment by nicklockwood** [comment]
@denisgaskov fixed in 0.54.4
