### ISSUE TITLE
Bug: unusedArguments false positive with multiline string

### ISSUE THREAD

**Issue by nikitabobko** [nicklockwood/SwiftFormat#1847]
```swift
// main.swift
public func foo(message: String = "hi") {
    let message =
        """
        Message: \(message)
        """
    print(message)
}

foo()
```

1.  Run `swiftformat --verbose main.swift`
2.  ```
    Running SwiftFormat...
    Formatting /Users/bobko/main.swift
    -- rules applied: unusedArguments
    Writing /Users/bobko/main.swift
    warning: No Swift version was specified, so some formatting features were disabled. Specify the version of Swift you are using with the --swiftversion option, or by adding a .swift-version file to your project.
    SwiftFormat completed in 0.01s.
    1/1 files formatted.
    ```

**Actual result:**
```
public func foo(message _: String = "hi") {
    let message =
        """
        Message: \(message)
        """
    print(message)
}

foo()
```

The file is no longer possible to compile:
```
main.swift:4:20: error: use of local variable 'message' before its declaration
        Message: \(message)
                   ^
main.swift:2:9: note: 'message' declared here
    let message =
        ^
```

**Expected result:** the file stays untouched

---

If you use plain string instead of multiline string or use another name for variable inside the function, the bug is not reproducible

```
$ swiftformat --version
0.54.3
```

**Comment by nicklockwood** [comment]
@nikitabobko fixed in 0.54.4
