### ISSUE TITLE
Make the format of Windows files on newer releases more practical

### ISSUE THREAD

**Issue by tristanlabelle** [nicklockwood/SwiftFormat#1854]
The [newest release](https://github.com/nicklockwood/SwiftFormat/releases/tag/0.54.4) has the following files:
```
swiftformat.amd64.exe.zip
SwiftFormat.amd64.msi.zip
swiftformat.arm64.exe.zip
SwiftFormat.arm64.msi.zip
```

There's a few tweaks we could make to make those more practical:
- msi is already a compressed format. Zipping only saves 2% and adds an extra step to the installation. I suggest having unzipped msi's as in the [previous release](https://github.com/nicklockwood/SwiftFormat/releases/tag/0.54.3).
- The zipped exe's are also impractical because they don't include the requisite swift runtime and depend on the user knowing which runtime they were built with and installing it. To be self-contained, we should include the Swift runtime msi's in the zip.

My suggestions would result in:
```
SwiftFormat.amd64.zip
SwiftFormat.amd64.msi
SwiftFormat.arm64.zip
SwiftFormat.arm64.msi
```

**Comment by nicklockwood** [comment]
Yeah, I decided to just remove the exe files for now.

**Comment by tristanlabelle** [comment]
Thanks! Resolving this. We could track having "portable" zips with exe + swift runtime dlls separately. For our needs at The Browser Company, the msi's do the job 👍🏻
