### ISSUE TITLE
Incorrect error message when indentation has an extra space.

### ISSUE THREAD

**Issue by Cyberbeni** [nicklockwood/SwiftFormat#1893]
Had this extra space in my Package.swift: https://github.com/Cyberbeni/MultiArchSwiftDockerfileExample/commit/eb6ee78cc6e74badb6e7bbc5e9af7f0a7566a6b9
Which resulted in the following error message:
> Package.swift:18:1: error: (wrap) Wrap lines that exceed the specified maximum width.

(Using SwiftFormat as a SPM plugin will skip the Package.swift file, I assume we can't change that. My CI workflow uses a standalone version of SwiftFormat.)

**Comment by nicklockwood** [comment]
@Cyberbeni fixed in 0.55.2
