### ISSUE TITLE
"self" incorrectly stripped from expression inside autoclosure

### ISSUE THREAD

**Issue by fellipecaetano** [nicklockwood/SwiftFormat#190]
My codebase uses [Nimble](https://github.com/Quick/Nimble) to expand its test assertion vocabulary. Nimble wraps most expectation expressions inside autoclosures, and inside them `self` is required to make capture semantics explicit. After formatting our test sources some of our test cases stopped compiling.

I understand this is an obscure edge case and that it's unlikely something can be done about it right now, but I'm opening this issue for documentation.

As an example, the following code snippet stops working after being formatted:

```swift
func testNonZeroMinutes() {
    let date = Date(timeIntervalSince1970: 1_491_233_400)
    expect(self.formatter.string(from: date)) == "12:30"
}
```

I'll be glad to provide more context about the issue if needed.

**Comment by nicklockwood** [comment]
Hi @fellipecaetano, yes this is a known issue. Unfortunately there's no context available for SwiftFormat to identify autoclosures since they look the same as ordinary arguments. At the moment the only option is to disable the redundantSelf rule.

**Comment by nicklockwood** [comment]
This is fixed in 0.30.2. I've just added a special case for `expect()`, since the Nimble framework is the only place where this issue has arisen so far.

**Comment by LeonidKokhnovich** [comment]
We have a custom built framework that uses "@autoclosure". Is there any way to extend this fix for all other use cases?

**Comment by nicklockwood** [comment]
@LeonidKokhnovich I'm considering adding a customizable whitelist of function names, but this isn't currently implemented.
