### ISSUE TITLE
Custom 'forEach' method is converted into a 'for' loop

### ISSUE THREAD

**Issue by RussBaz** [nicklockwood/SwiftFormat#1900]
Hi. I have a code like this:

```swift
var timesPinged = 0

allocator.forEach {
    timesPinged += $0.counter
}
```

Which is converted into:
```swift
var timesPinged = 0

for item in allocator {
    timesPinged += item.counter
}
```

Unfortunately, `allocator` is an instance of my own class that does not conform to 'Sequence' protocol.

```
swiftformat --version
0.54.5
```

**Comment by nicklockwood** [comment]
There's no way for SwiftFormat to detect this automatically. Your best options are to disable the rule, either globally using `--disable preferForLoop` or locally with the comment `// SwiftFormat:disable:next preferForLoop`

**Comment by RussBaz** [comment]
I understand, thanks. Is it a sane default, though? I mean having `preferForLoop` on by default.

**Comment by nicklockwood** [comment]
I mean, it's been enabled for years and you are the first to encounter this issue ¯\_(ツ)_/¯

**Comment by RussBaz** [comment]
It is unfortunate. I am surprised to be the first one, though.

I have applied a local fix you suggested, but I think I should rename this method.

**Comment by nicklockwood** [comment]
I've added a known issue to the readme. If your type behaves like a method I'd suggest maybe making it conform to Sequence so that it can be used with a for in loop (but without context I understand that might not be possible or worthwhile)
