### ISSUE TITLE
`unusedArguments` does not work with functions calling functions with the same labels

### ISSUE THREAD

**Issue by reika727** [nicklockwood/SwiftFormat#1902]
I have a code like this:

```swift
func f(foo _: Int) {}

func g(foo: Int) {
    f(foo: 42)
}
```

This code does not change after being formatted. However, the argument `foo` is not used inside the function `g`, so it should be `func g(foo _: Int)` (since the `unusedArguments` option is enabled by default.)

If you comment out the call of `f` inside `g`, the code will be formatted properly.

```swift
// BEFORE FORMATTED
func f(foo _: Int) {}

func g(foo: Int) {
    // f(foo: 42)
}
```

```swift
// AFTER FORMATTED
func f(foo _: Int) {}

func g(foo _: Int) {
    // f(foo: 42)
}
```

So maybe this strange behavior comes from `f` and `g` having the same argument label `foo`?

**Environment**

```console
$ swiftformat --version
0.54.5
```

**Comment by nicklockwood** [comment]
@reika727 fixed in 0.55.2
