### ISSUE TITLE
SHA256 checksum mismatch in Homebrew formula for 0.55.0

### ISSUE THREAD

**Issue by rgoldberg** [nicklockwood/SwiftFormat#1924]
The Homebrew formula for 0.55.0 has an SHA256 checksum that doesn't match that for the file at:

https://github.com/nicklockwood/SwiftFormat/archive/refs/tags/0.55.0.tar.gz

I've opened an issue in `homebrew-core`:

https://github.com/Homebrew/homebrew-core/issues/198214

Was that file intentionally published more than once?

Is either checksum from the `homebrew-core` issue correct?

**Comment by nicklockwood** [comment]
@rgoldberg yes, I screwed up and had to re-tag the release - I guess somebody posted a Homebrew update in between. Should be fixed in 0.55.1

**Comment by rgoldberg** [comment]
@nicklockwood thanks.

Once the formula is auto bumped in `homebrew-core`, I'll verify that the new formula works, then I'll close all the related issues.

**Comment by chenrui333** [comment]
gonna ship via https://github.com/Homebrew/homebrew-core/pull/198429
