### ISSUE TITLE
Release is not available in cocoapods

### ISSUE THREAD

**Issue by NikKovIos** [nicklockwood/SwiftFormat#1925]
https://github.com/nicklockwood/SwiftFormat/releases/tag/0.55.1 

```
CocoaPods could not find compatible versions for pod "SwiftFormat/CLI":
  In Podfile:
    SwiftFormat/CLI (~> 0.55.1)
```

**Comment by nicklockwood** [comment]
0.55.1 is listed as the latest version on the CocoaPods site: https://cocoapods.org/pods/SwiftFormat

Maybe it was a caching/latency issue?

**Comment by NikKovIos** [comment]
Maybe...
