### ISSUE TITLE
Version 0.55.3 not available on GitHub actions

### ISSUE THREAD

**Issue by bastianfischer-neotaste** [nicklockwood/SwiftFormat#1935]
Hi all! 

First of all, thanks for working on this amazing tool - it really enhances our workflow in a lot of different ways.
We are using SwiftFormat with GitHub actions and it seems that version 0.55.3 was not deployed yet - when can we expect it to be available? Also for my understanding, what is the process behind deploying to GitHub actions?

Best regards,
Bastian 🙂

**Comment by nicklockwood** [comment]
@bastianfischer-neotaste should be fixed now: https://github.com/nicklockwood/SwiftFormat/pkgs/container/swiftformat/314894709?tag=0.55.3

**Comment by bastianfischer-neotaste** [comment]
Unfortunately uses 0.55.2 still (on GitHub):

> Run `swiftformat --version`
0.55.2

**Comment by nicklockwood** [comment]
@bastianfischer-neotaste is it sorted now? The version listed on github is 0.55.3

https://github.com/actions/runner-images/blob/main/images/macos/macos-13-Readme.md

**Comment by bastianfischer-neotaste** [comment]
Yes, works! Thanks a lot 🙌
