### ISSUE TITLE
Split wrapArguments to separate function declaration and implementation

### ISSUE THREAD

**Issue by AMatecki** [nicklockwood/SwiftFormat#198]
Hi,
I would like to have more control over wrapArguments. Currently I have to choose the same behaviour
for function declaration and implementation.  I can't have beforeFirst implementation:
```
        let storyboard = UIStoryboard(
            name: "More",
            bundle: nil
        )
```

and afterFirst declaration:
```
    init(foo: Foo,
         bar: Bar) {
}
```

The main reason why I want them separately is that I don't like hanging ") {"in the new line in case of declarations with beforeFirst option:
```
    init(
      foo: Foo,
      bar: bar
    ) {
```

This version would be OK:
```
 init(
    foo: Foo,
    bar: Bar) {

```
Is there a chance you could add to the project?

**Comment by AMatecki** [comment]
Hey @nicklockwood, any chance you could make this change?

**Comment by yonaskolb** [comment]
I would love to be to control the new line brace (hanging as you say @AMatecki ) separately from the before or after first. Would this also solve your problem @AMatecki? Or do you also want different first param wrapping for func declarations and call sites?

**Comment by AMatecki** [comment]
My main pain point is hanging new line brace, everything else would be a nice bonus

**Comment by yonaskolb** [comment]
Yeah I'm not a huge fan of it either. I'd basically like to be able to have `beforeFirst` without the hanging brace

**Comment by AMatecki** [comment]
Hey @nicklockwood, just checked the latest version with --closingparen option, looks like I got what I asked for. Big thanks, now I have to integrate Swiftformat with our CI :)
