### ISSUE TITLE
Grouping for fraction digits

### ISSUE THREAD

**Issue by tinder-garricnahapetian** [nicklockwood/SwiftFormat#199]
We use the SwiftLint `number_separator` rule in our project. If we continue to use this rule it will conflict with the SwiftFormat `numberFormatting` rule because SwiftFormat will remove underscores from fraction digit groups while SwiftLint will require them.

**Comment by tinder-garricnahapetian** [comment]
Hi Nick, I just wanted to check in with you regarding this. Any plans to tackle this issue? How easy would it be for someone like me to handle? I hope all is well. Happy new year! :)

**Comment by nicklockwood** [comment]
@tinder-garricnahapetian sorry I haven't gotten around to this yet. The rule itself is pretty straightforward (really just a minor change to the existing rule), but the complexity is in figuring out how to name it and fit it in with the existing set of options. That probably makes it unsuitable as something for an external contributor, but I'll try to get it added for the next release.

**Comment by nicklockwood** [comment]
@tinder-garricnahapetian I've implemented this feature now on the develop branch. It should be included with the next major release.

**Comment by nicklockwood** [comment]
@tinder-garricnahapetian this is now implemented in version 0.34.0
