### ISSUE TITLE
Wrong spacing when specifying a type for a generic parameter

### ISSUE THREAD

**Issue by gragera** [nicklockwood/SwiftFormat#2]
<img width="568" alt="screen shot 2016-08-22 at 23 35 29" src="https://cloud.githubusercontent.com/assets/287089/17872633/3d5b6e6e-68c1-11e6-9c04-f86f27eddae9.png">

The original spacing was correct :)

**Comment by nicklockwood** [comment]
Ha, nice! I bet the -> confused it. I'll add a new test. Thanks!

**Comment by nicklockwood** [comment]
Fixed in 0.2

**Comment by gragera** [comment]
<img width="572" alt="screen shot 2016-08-23 at 08 13 38" src="https://cloud.githubusercontent.com/assets/287089/17882043/510e25b6-690a-11e6-9945-d4431d771e4e.png">

<img width="491" alt="screen shot 2016-08-23 at 08 19 51" src="https://cloud.githubusercontent.com/assets/287089/17882068/7136eb16-690a-11e6-93ec-ca962bd0c0f6.png">

It does not look fixed :( . If you need some failing code to reproduce this just let me know!

**Comment by nicklockwood** [comment]
The case I fixed was:

    Foo<Bar> ->

These are

    Foo<Bar> in

And

    (Foo<Bar>) ->

Respectively, which I didn't fix.

I'll add tests for these as well, but if you have any other variants, please include them in the ticket :-)

**Comment by nicklockwood** [comment]
Fixed in v0.3
