### ISSUE TITLE
[FEATURE REQUEST] blankLinesAtBeginningOfScope

### ISSUE THREAD

**Issue by Starscream27** [nicklockwood/SwiftFormat#210]
There's already a *blankLinesAtEndOfScope* allowing one to remove blank lines at end of scope. I would suggest we add the equivalent for the beginning of scope: *blankLinesAtBeginningOfScope*

E.g.

```swift
    func gestureRecognizerShouldBegin(_: UIGestureRecognizer) -> Bool {

        return true
    }
```

would be formatted into

```swift
    func gestureRecognizerShouldBegin(_: UIGestureRecognizer) -> Bool {
        return true
    }
```

**Comment by nicklockwood** [comment]
Added in version 0.33.0
