### ISSUE TITLE
Xcode Source Editor Extension installation issue

### ISSUE THREAD

**Issue by daniavram** [nicklockwood/SwiftFormat#213]
After attempting to install as described in the readme, I get the following error: `"SwiftFormat for Xcode" is damaged and can't be opened. You should move it to the Trash.` Am I doing something wrong?

**Comment by nicklockwood** [comment]
@daniavram sorry about that - I'd just merged a WIP PR onto the main branch and that overwrote the binary. Try again now.

**Comment by daniavram** [comment]
@nicklockwood Awesome. It works now. Thanks 😉 Will close. But, just an idea, if you could add an icon to the `SwiftFormat for Xcode` file (the one from `EditorExtension` folder) it would be great. Great work with the extension, anyways! 😁
