### ISSUE TITLE
Add support for directories with spaces in names

### ISSUE THREAD

**Issue by danielgalasko** [nicklockwood/SwiftFormat#22]
We just got SwiftFormat running for our team and noticed that it failed with the following error for any projects that were included in a folder with a space in the name. One example is: `Documents/Xcode Projects/ProjectToRunSwiftLintOn/`

The error we saw in Xcode's build log:

```
/Users/danielgalasko/Library/Developer/Xcode/DerivedData/OurApp-dznbqhvktztcjrfezxvdxareyphq/Build/Intermediates/OurApp.build/Debug-iphonesimulator/OurAppKit.build/Script-E634E70E1D79C26D005A6B25.sh: line 2: /Users/danielgalasko/Documents/Xcode: No such file or directory
```

Changing the directory name to `XcodeProjects` fixed the issue

Thanks for the awesome tool! 👍

**Comment by nicklockwood** [comment]
Did you try escaping the space with a \, or putting the path in quotes?

**Comment by danielgalasko** [comment]
run script actually looks as follows:

```
${SRCROOT}/swiftformat ${SRCROOT}/OurAppKitKit/
```

So its not really possible unless we add a script to modify `$(SRCROOT)`

**Comment by nicklockwood** [comment]
You can probably omit the `$(SRCROOT)/` altogether since the script runs relative to srcroot anyway, but this should work too:

```
"${SRCROOT}/swiftformat" "${SRCROOT}/OurAppKit/"
```

**Comment by danielgalasko** [comment]
Nice to know 😄 getting the feeling that this is actually an Xcode bug and not a SwiftFormat one? Feel free to close and thanks for the help 🙌

**Comment by nicklockwood** [comment]
I think this is just how command line arguments work - they're space-delimited so spaces in arguments have to be escaped somehow. I'll add a note to the docs though because it's not obvious, especially if the space is hidden inside a macro.

**Comment by nicklockwood** [comment]
I've updated the docs to make this clearer.

**Comment by danielgalasko** [comment]
Great stuff sir 🙌
