### ISSUE TITLE
Some header rule exception variations don't work

### ISSUE THREAD

**Issue by rudedogg** [nicklockwood/SwiftFormat#220]
I'm attempting to keep a copyright header on a file. It seems that some variations of the comment to disable the rule are missed by SwiftFormat.

Swift Version: 4
SwiftFormat Version: `swiftformat, version 0.33.1`
Options/Command: `swiftformat --header strip --stripunusedargs closure-only --indent 2 *.swift`

## Working
```swift
// swiftformat:disable --header strip
//
//  Created by Sedat Ciftci on 18/03/16.
//  Copyright © 2016 Sedat Gokbek Ciftci. All rights reserved.
//
// swiftformat:enable --header strip
```

## Not Working (stripped/deleted)
```swift
// swiftformat:disable --header strip
//  Created by Sedat Ciftci on 23/02/15.
//  Copyright (c) 2015 Sedat Ciftci. All rights reserved.
// swiftformat:enable --header strip
```

**Comment by nicklockwood** [comment]
@rudedogg fixed in 0.33.2, but you'll need to use `// swiftformat:disable fileHeader` as it's the name of the rule, rather than the option
