### ISSUE TITLE
Use libSyntax?

### ISSUE THREAD

**Issue by AndrewSB** [nicklockwood/SwiftFormat#231]
Hey @nicklockwood! This is awesome and I'm so happy you've spent the time to build it 🙃

Have you thought about using [libSyntax](https://github.com/apple/swift/tree/master/lib/Syntax) to do the tokenizing and whatnot? I see that alot of that is implemented in this library, but (to me) it makes sense for the Swift community to colocate all of the syntax parsing expertise into one tool, instead of building multiple tools in isolation.

I couldn't find any discussion on this, if this has already been answered, please just link me to that and close this!

**Comment by nicklockwood** [comment]
@AndrewSB I have considered it, but it would require a major rewrite (libSyntax wasn't available when I started).

**Comment by AndrewSB** [comment]
That makes sense, thanks for responding!
