### ISSUE TITLE
spaceAroundOperators and wildcard

### ISSUE THREAD

**Issue by VinceBurn** [nicklockwood/SwiftFormat#232]
In a `if #available` statement the `*` should not be treated as an operator.

Currently when applying the `spaceAroundOperators` rules the following change will be apply:

-    if #available(iOS 10.0, *) {
+    if #available(iOS 10.0, * ) {

(a space was added after the `*`)

**Comment by VinceBurn** [comment]
If combined with the `spaceInsideParens` rule, this is not an issue.

**Comment by nicklockwood** [comment]
I'll leave it open, as rules are supposed to be independent and one rule shouldn't introduce a bug that another rule is required to fix

**Comment by nicklockwood** [comment]
@VinceBurn fixed in version 0.33.8
