### ISSUE TITLE
Failed to format some mathmatic function

### ISSUE THREAD

**Issue by chenyunguiMilook** [nicklockwood/SwiftFormat#233]
failed to format this type of code

```swift
fileprivate func bezierCoeffs(_ P0: CGFloat, _ P1: CGFloat, _ P2: CGFloat, _ P3: CGFloat) -> [CGFloat] {
    var Z = [CGFloat].init(repeating: 0, count: 4)
    Z[0] = -P0 + 3*P1 + -3*P2 + P3
    Z[1] = 3*P0 - 6*P1 + 3*P2
    Z[2] = -3*P0 + 3*P1
    Z[3] = P0
    return Z
}
```

**Comment by nicklockwood** [comment]
@chenyunguiMilook I just tried this sample with SwiftFormat 0.33.4 and it seemed to work. Can you confirm?

**Comment by chenyunguiMilook** [comment]
@nicklockwood I'm using 0.33.4, and I have tried again, it works!!, yesterday I tried it just after installation, Xcode popup failed, may be caused by some other reason.
