### ISSUE TITLE
Whitespace between try!/try? and .init() Removed

### ISSUE THREAD

**Issue by tinder-garricnahapetian** [nicklockwood/SwiftFormat#241]
Test Case 1:

`let foo: Int = try! .init()`

Result:

`let foo: Int = try!.init()`

Test Case 2:

`let foo: Int = try? .init()`

Result:

`let foo: Int = try?.init()`

Test Case 3:

`let foo: Int = try .init()`

Result:

`let foo: Int = try .init()`

swiftformat, version 0.33.5

**Comment by nicklockwood** [comment]
@tinder-garricnahapetian this is now fixed in 0.33.6. Thanks for reporting it!

**Comment by tinder-garricnahapetian** [comment]
my pleasure :)
