### ISSUE TITLE
One liner

### ISSUE THREAD

**Issue by mihaicristiantanase** [nicklockwood/SwiftFormat#244]
Hi!

Is there a rule that can take the following function:
```
func emptyMethod() {
}
```
and format it like this:
```
func emptyMethod() {}
```
due to the empty content?

**Comment by nicklockwood** [comment]
@mihaicristiantanase added in 0.35.0

**Comment by mihaicristiantanase** [comment]
I've checked and it works perfectly.
Thanks!
