### ISSUE TITLE
Partial formatting

### ISSUE THREAD

**Issue by mihaicristiantanase** [nicklockwood/SwiftFormat#245]
Hi!

Is there a way to format only a portion of a file?
Something like:
```
swiftformat --range 24,42 FileToFormat.swift
```
where "range" takes two lines as parameters

**Comment by mihaicristiantanase** [comment]
@nicklockwood, do you think it's a trivial task to allow the command line tool to do partial formatting?
I'm asking because I'd like to use swiftformat with git hooks.

**Comment by nicklockwood** [comment]
@mihaicristiantanase it's doable, but formatting can be fairly unreliable when applied to a range - for example it may mess up the indenting if the selection overlaps the start or end of a scope. It's probably safer to format the entire file.

**Comment by ferranpujolcamins** [comment]
How this compares to the partial formatting that xcode offers?

**Comment by nicklockwood** [comment]
@ferranpujolcamins this has now been added in 0.45.3. Use `--linerange start,end`.
