### ISSUE TITLE
Is it possbile to add an option for trailingCommas

### ISSUE THREAD

**Issue by nypisces** [nicklockwood/SwiftFormat#25]
Or must build the rules by myself?

**Comment by nicklockwood** [comment]
You mean an option to disable them?

**Comment by nypisces** [comment]
yes

**Comment by nicklockwood** [comment]
Not currently.

To disable the rule, remove that line from the array in Rules.swift and rebuild the tool.

To make it actively remove them, you'd need to write a new rule.

**Comment by nicklockwood** [comment]
FYI, this is now supported via the `--commas` option.
