### ISSUE TITLE
How to Disable [Key : Second Line Value] Alignment?

### ISSUE THREAD

**Issue by tinder-whitneyfoster** [nicklockwood/SwiftFormat#251]
Hi! We'd just like to know the rule name that handles this functionality so I can disable it:
```
let dictionary = [
    key: value,
    key2: 
        secondLineValue
]
```
changes to:
```
let dictionary = [
    key: value,
    key2: 
    secondLineValue
]
```
We're trying to avoid second line values but we'd like to avoid using this SwiftFormat rule for the few that slip through the cracks. 

Thanks!

**Comment by nicklockwood** [comment]
@tinder-whitneyfoster sorry for the delayed response. This is handled by a combination of the `wrapArguments` and `indent` rules, however I've fixed the indenting of wrapped dictionary values in SwiftFormat 0.35.3, so if you update to the latest release the problem should be solved.
