### ISSUE TITLE
@testable is being removed from imports in test files

### ISSUE THREAD

**Issue by alimoeeny** [nicklockwood/SwiftFormat#253]
I must be missing something, but couldn't figure out why swiftformat removes the `@testable` from 
```swift
@testable import Marmalade
```
in my test files. Marmalade here being the library that is being tested and Test files need the `@testable` so that we don't need to expose internals of the library just to get them tested.

**Comment by nicklockwood** [comment]
@alimoeeny that definitely shouldn’t happen. Can you verify that you’re using the latest version?

If you are, can you provide a sample file that I can use to reproduce the issue?

**Comment by alimoeeny** [comment]
Thanks @nicklockwood 
- I am using `0.33.6` with Pods (as a pod + a build step that calls it).
- yes I can provide a sample. I think I need to provide a project because this only happens on the test side and just a file will not do. Should I create a repo with this sample project in it?

**Comment by nicklockwood** [comment]
@alimoeeny the code doesn’t have to compile to be formattable. A single file should be sufficient.

**Comment by alimoeeny** [comment]
Of course.
if you run swiftformat on the following file, the `@testable` will be removed:
```
import Fundation
@testable AlisLibrary
import Quick
import Nimble

class AlisLibrarySpecs {
    var x String
    var i Int

}
```

**Comment by nicklockwood** [comment]
@alimoeeny there seems to be a syntax error in your code - it should be

`@testable import AlisLibrary`

But you are missing the `import` statement.

**Comment by nicklockwood** [comment]
@alimoeeny if I add the `import` statement then SwiftFormat doesn't remove the `@testable` line.

Do you think that could have been the whole issue, or do you have another test case?

**Comment by alimoeeny** [comment]
@nicklockwood I could have sworn that it happened with the `import` 
Since last we talked I have `--excludeded` my test project. I just went and removed the exclude and all worked fine.
I must have been very confused. :face_palm: :bumps_head_to_wall: 
Thank you very much. And I apologize for taking your time.
