### ISSUE TITLE
Cannot activate the Xcode extension

### ISSUE THREAD

**Issue by igorkulman** [nicklockwood/SwiftFormat#262]
I updated the Xcode extension to 0.33.7 but I noticed it disappeared from Xcode 9.2. When I go to System Preferences | Extensions there is no Xcode section as in the past:

<img width="780" alt="screen shot 2018-05-22 at 09 57 12" src="https://user-images.githubusercontent.com/4746070/40349357-ae832bfa-5da6-11e8-8d83-629488a4e0d0.png">

I tried 0.33.6 but same result, not showing in Extensions. I am running macOS 10.13.4 (17E202).

Any ideas?

**Comment by giln** [comment]
I have the same issue.
I think it disappeared when I changed Xcode version.
I have 4 versions of Xcode installed: 7.3.1, 8.3.3, 9.4.1, 10-beta 2.
 It worked with Xcode 10 beta 1 but disappeared when I installed beta 2 I think (or maybe it was after upgrading to Xcode 9.4.1)?

**Comment by giln** [comment]
OK I found a workaround.
My Xcode versioned was named: Xcode-9.4.1.app
I renamed it to Xcode and the menu appeared again.

**Comment by OliverPearmain-Pusher** [comment]
I have a requirement for multiple versions of Xcode and therefore always name my Xcode applications `Xcode-X.Y.Z.app`. 

I was able to resolve this issue (of the Extension not appearing) _without having to rename Xcode_ by running the following two commands: 

- `/System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister -f /Applications/Xcode-X.Y.Z.app`

- `/System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister -f /Applications/SwiftFormat\ for\ Xcode.app`

Hope this might help.  I got the inspiration from issue #422
