### ISSUE TITLE
Passing != to a function

### ISSUE THREAD

**Issue by jandamm** [nicklockwood/SwiftFormat#266]
I need a predicate like this `{ $0 != referenceValue }`.
To reduce some overhead I used a curry function `func curry<A, B, C>(_ function: @escaping (A, B) -> C) -> (A) -> (B) -> C` on `!=`.

So my final code looks like this:
`curry(!=)(referenceValue)`

Unluckily SwiftFormat is unhappy with `(!=)` and "corrects" it to `(! =)`.
`( != )` doesn't help either. It first get's corrected to `(!=)` and then again to `(! =)`. This compiles the first but not the second time.
I got it to work for now with \n but it looks kind of weird:
```
curry(
    !=
)(referenceValue)
```

I use the newest homebrew version: 0.33.8
like this `swiftformat . --indent tabs` as a build script.

Code can be found [here](https://github.com/jandamm/trackr/blob/8c27e4b4a360490513f52d38b2441bc7a6f70713/Trackr/Location/Tracking.swift#L45)

**Comment by nicklockwood** [comment]
@jandamm Thanks for reporting the issue. This is now fixed in version 0.33.9
