### ISSUE TITLE
--dryrun option has no return value

### ISSUE THREAD

**Issue by michaelmcguire** [nicklockwood/SwiftFormat#267]
PR #177 added support for `--dryrun` and returning a non-zero exit code if anything would be modified.  PR #202 looked to use that by giving instructions on configuring [Danger](https://github.com/danger/danger) using the assumption that you'll get a non-zero exit code if anything is formatted.  While I don't use Danger, I'm guessing these instructions are broken (with or without `--dryrun`) since it doesn't appear non-zero exit codes are returned anymore.  Was this an intentional change?

I'd like to incorporate a check in our CI environment to make sure everything is properly formatted but don't want to rely on parsing output from `swiftformat`.  If I added back a non-zero exit code when formatting is performed (or would be performed), would that PR be accepted?  

Thanks for your work on this!

**Comment by michaelmcguire** [comment]
I found the [commit](https://github.com/nicklockwood/SwiftFormat/commit/016b20028594c6b1973a06a505cfd52a16f86955) where this was removed.

**Comment by nicklockwood** [comment]
@michaelmcguire it doesn't make sense to me that a mode called "dryrun" would return an error in the event that the command completes successfully.

I think a better option might be to add a new mode called something like "--lint" which behaves the same as "--dryrun" but returns an error if any changes would have been applied.

Does that seem reasonable?

**Comment by heyitswither** [comment]
Hey, I was just about to ask about this. What's the progress on it? @michaelmcguire

**Comment by michaelmcguire** [comment]
@heyitswither hope to open a PR tomorrow

**Comment by nicklockwood** [comment]
@michaelmcguire the `--lint` option has landed in version 0.33.13. Thanks!

**Comment by michaelmcguire** [comment]
@nicklockwood Awesome! Happy to help!

**Comment by haemi** [comment]
I'm on 0.44.17 but the return value is always 0 for `swiftformat --lint .` even if there are errors found - am I missing something?
