### ISSUE TITLE
Error: Parentheses removed from closure call via positional index (tuple)

### ISSUE THREAD

**Issue by lla01** [nicklockwood/SwiftFormat#268]
In case there's a tuple that contains a closure as one of its members and the closure needs to be called with parameters, then the code from the following snippet, which dereferences the closure via tuple indexes and immediately calls it, is not properly formatted.

Instead, SwiftFormat removes the parentheses around the closure parameters, resulting in malformed swift syntax.

```Swift
// Tuple; second member is a closure that takes a Bool as parameter
let namedBlock: (String, (Bool) -> Void) = ("Hello", { exclamation in print("Hello World" + (exclamation ? "!" : ".")) })

// Dereference the tuple members via index
print(namedBlock.0)

// In the following lines, SwiftFormat removes the parentheses, resulting in uncompilable code.
namedBlock.1(true) 
namedBlock.1(false)
```

**Comment by nicklockwood** [comment]
@lla01 Fixed in 0.33.11
