### ISSUE TITLE
Newline bellow struct and class declaration

### ISSUE THREAD

**Issue by 3lvis** [nicklockwood/SwiftFormat#27]
Hi Nick! 

First of all great work on this tool, the code wasn't that hard to read and it was well documented, the installation steps were top notch, getting this running was easy peasy.

Ok, now to the question, I've read on Twitter that you were sticking to Apple's style/guidelines when it comes to formatting, but I've noticed that you're adding a newline bellow struct and class implementations meanwhile in the Apple's Swift book doesn't do this. What was your reasoning behind this change?

# [Apple's sample code in the Swift book](https://developer.apple.com/library/ios/documentation/Swift/Conceptual/Swift_Programming_Language/ClassesAndStructures.html#//apple_ref/doc/uid/TP40014097-CH13-ID82)
<img width="266" alt="screen shot 2016-09-13 at 10 05 51" src="https://cloud.githubusercontent.com/assets/1088217/18466499/3a205714-799c-11e6-868f-8a1b6b3c685d.png">

# My code formatted using SwiftFormat
<img width="344" alt="screen shot 2016-09-13 at 10 00 26" src="https://cloud.githubusercontent.com/assets/1088217/18466503/41f33d12-799c-11e6-8cb1-76a6f7a5f09a.png">

**Comment by nicklockwood** [comment]
It's based on an interpretation of Apple's guidelines, which aren't always entirely self-consistent.

I don't currently add a space before a var inside a class or struct, but I do add it before a function or nested class, or between classes and functions at the same scope.  So my rules would not add spaces inside Apple's Resolution and VideoMode classes like they have in your UIColor extension.

FWIW, I'm not 100% happy with that rule either though, so I'm happy to take feedback about alternative ways that it could work.

**Comment by 3lvis** [comment]
Oh, I see now, it's related to extensions, seems like this doesn't apply to class and struct. Thanks for your feedback!
