### ISSUE TITLE
Non-zero exit code on error

### ISSUE THREAD

**Issue by lassik** [nicklockwood/SwiftFormat#271]
Currently the exit code is zero (indicating success) even when there is an error.

```
$ echo "(" | swiftformat; echo "exit code is $?"
error: unexpected end of file at 2:0
exit code is 0
```

I believe it would be better to make it non-zero so that editor plugins and batch jobs don't try to use the output from stdout.

I have latest version from Homebrew:

```
$ swiftformat --version
swiftformat, version 0.33.11
```

**Comment by nicklockwood** [comment]
@lassik fixed in version 0.33.13
