### ISSUE TITLE
Parenthesis around 'if condition' getting removed upon formatting 

### ISSUE THREAD

**Issue by zuberalimir** [nicklockwood/SwiftFormat#275]
Here is the issue.

I would like to have the 'if condition' parenthesis intact upon formatting.

Before formatting:

        if(1==1 &&2==2){
        }

After Formatting:

       if 1 == 1 &&2 == 2 {
        }

Thanks

**Comment by nicklockwood** [comment]
You can use `—disable redundantParens` in the command line arguments to disable the rule that removes them.

**Comment by zuberalimir** [comment]
Thanks for the heads up !

**Comment by pmanna** [comment]
I've experienced a similar issue, and yes, using `—disable redundantParens` resolves it, but still…

The following code
`
if conditionA && (conditionB || conditionC) {
`

Gets formatted to
`
if conditionA, conditionB || conditionC {
`

That's NOT the same, obviously…

**Comment by nicklockwood** [comment]
@pmanna you can prevent this change by disabling the `andOperator` rule, which is responsible for changing the `&&` to a `,`. With that disabled, the `redundantParens` rule won't remove the parens.

But unless I'm missing something, the rule is behaving correctly. The comma operator takes precedence over `||`, so removing the parens in the second example should not affect the behavior.

**Comment by pmanna** [comment]
OK, probably my idea was that `,` had same precedence as `||` (that would have changed behaviour), but it looks like you're right that indeed doesn't change, even though my wording would have been different (i.e. that OR had precedence)…
Sorry about the false alarm!

**Comment by nicklockwood** [comment]
@pmanna > even though my wording would have been different (i.e. that OR had precedence)

Ah, yes quite. In fact it's more that `,` isn't actually an operator at all, but a delimiter between expressions, so it always has the lowest precedence.
