### ISSUE TITLE
Custom operators parsing

### ISSUE THREAD

**Issue by mpsnp** [nicklockwood/SwiftFormat#277]
It would be great to have a possibility to list  custom operators which are used in project, because now, swiftformat recognizes binary operator as postfix unary operator and makes code incorrect:

Before formatting:
```
            button |> roundedButtonStyle <> {
                $0.layer.cornerRadius = 15
                $0.bounds.size.height = 30
            }
```

After formatting:

```
            button |> roundedButtonStyle<> {
                $0.layer.cornerRadius = 15
                $0.bounds.size.height = 30
            }
```

**Comment by nicklockwood** [comment]
It shouldn’t be necessary to list custom operators because the pre/in/postfixness is unambiguous from the white space around the operator.

I suspect the bug here is that SwiftFormat’s parser is confusing your <> operator with a generic argument. I’ll investigate.

**Comment by mpsnp** [comment]
@nicklockwood , i could fix this issue, if you tell me from where to start searching the bug.
The problem is that swift compiler after formatting returns error: `'<>' is not a postfix unary operator` and fails to compile.

**Comment by mpsnp** [comment]
I guess also this could be related to this issue, it adds blank line in place of comment in this example:

```swift
    static var reducer: Reducer<AccountState, Action> = .init { state, action in
        // Some code here
    }
    // Swift format adds blank line here
    <>
    reduce(state: \.signInOperation, action: Action.prism.signIn)
```

As well as it breaks indentation here:

Before:
```swift
    static var reducer: Reducer<AppState, Action> =
        reduce(state: \.accountState, action: Action.prism.accountAction)
        <>
        reduce(state: \.flightState, action: Action.prism.flightAction)
        <>
        reduce(state: \.logbookState, action: Action.prism.logbookAction)
        <>
        reduce(state: \.teamState, action: Action.prism.teamAction)
```

After:
```swift
    static var reducer: Reducer<AppState, Action> =
        reduce(state: \.accountState, action: Action.prism.accountAction)
    <>
    reduce(state: \.flightState, action: Action.prism.flightAction)
    <>
    reduce(state: \.logbookState, action: Action.prism.logbookAction)
    <>
    reduce(state: \.teamState, action: Action.prism.teamAction)
```
