### ISSUE TITLE
FormatCommandError error 0 in Playgrounds #56

### ISSUE THREAD

**Issue by kevnm67** [nicklockwood/SwiftFormat#278]
Same/similar issue resolved in #56 but seems limited to multi-page playgrounds. 
<img width="748" alt="screen shot 2018-07-21 at 1 08 45 pm" src="https://user-images.githubusercontent.com/2734154/43038473-3e798e7e-8ce7-11e8-9ed7-ae04f3fe73b6.png">

```
swiftformat, version 0.33.11
```

**Comment by nicklockwood** [comment]
@kevnm67  I don't think this is the same issue. Can you provide the contents of the Playground that causes this error so I can reproduce it locally?

**Comment by kevnm67** [comment]
@nicklockwood Sure.  It only happens after adding at least 1 page to a playground. 

Here's an example playground:
[SwiftFormatBug.playground.zip](https://github.com/nicklockwood/SwiftFormat/files/2223374/SwiftFormatBug.playground.zip)

**Comment by nicklockwood** [comment]
@kevnm67 fixed in 0.34.0
