### ISSUE TITLE
redundantParens broke optional completion closure 

### ISSUE THREAD

**Issue by arnaudWasappli** [nicklockwood/SwiftFormat#280]
RedundantParens enable cause the code to be broke for my completion closure:

<img width="1160" alt="redundantparens" src="https://user-images.githubusercontent.com/7737273/43163336-d2916d86-8f5b-11e8-9b46-8f19ee84873d.png">

**Comment by nicklockwood** [comment]
@arnaudWasappli thanks, I'll put up a fix asap

**Comment by nicklockwood** [comment]
@arnaudWasappli fixed in version 0.33.13
