### ISSUE TITLE
Unable to install specific SwiftFormat version via brew

### ISSUE THREAD

**Issue by bhanubirani** [nicklockwood/SwiftFormat#285]
Hi Team - I'm wondering how to install specific version of SwiftFormat via homebrew. Technically, I expect swift format to expose all/selected versions on home brew. This way we can pick and install any version. At the moment there's only one version available which can be seen via ```brew search swiftformat``` command.

Currently, it's throwing the following response:
```
$ brew search swiftformat
==> Formulae
swiftformat
```
Is there a way to get the specific version of swift-format on machine via brew?

PS: We ran under this problem as our team is running on Xcode 9.2 which doesn't support latest ```swfitformat```.

**Comment by nicklockwood** [comment]
You should be able to run

`brew switch swiftformat 0.x.x`

to select the earlier version on your local machine. I’m not sure what happens if you’ve never installed that version though.

**Comment by nicklockwood** [comment]
@bhanubirani the latest swiftformat supports installation on Sierra again, so that should solve your issue.

**Comment by klauslanza** [comment]
It's an old thread, but this is still an issue. Would love having the possibility to select a previous version, even if not installed in a particular machine (like, for example, `brew install postgresql@8.4.4`).
Looks like this should be configured on Brew repo to manage several formulae.
