### ISSUE TITLE
If "default" appears at the end of a line, the following one is indented.

### ISSUE THREAD

**Issue by RabugenTom** [nicklockwood/SwiftFormat#29]
Hi again Nick
This is related to #28: when a line ends with `default`, the next non empty line is indented, and if this line is a comment, the line after the comment is indented too (v0.9.4).
For example
````swift
let f = FileManager.default
// Comment
let x = 0
````
is formatted as
````swift
let f = FileManager.default
    // Comment
    let x = 0
````
Appending a semicolon after `default` prevents this.

**Comment by nicklockwood** [comment]
OK, this (and hopefully all similar cases) is now fixed in v0.9.5. Thanks again.
