### ISSUE TITLE
Errors have ANSI color even when stderr is not a terminal

### ISSUE THREAD

**Issue by lassik** [nicklockwood/SwiftFormat#290]
`swiftformat` writes ANSI-colored error messages to stderr, which is nice when stderr goes to a terminal. However, it seems to write the terminal color codes even when stderr goes into a file or pipe:

```
$ { echo "(" | swiftformat 2>&1; } > tempfile; hexdump -C tempfile
00000000  1b 5b 33 31 6d 65 72 72  6f 72 3a 20 75 6e 65 78  |.[31merror: unex|
00000010  70 65 63 74 65 64 20 65  6e 64 20 6f 66 20 66 69  |pected end of fi|
00000020  6c 65 20 61 74 20 32 3a  30 1b 5b 30 6d 0a        |le at 2:0.[0m.|
0000002e
```

Standard Unix practice is to call [`isatty()`](http://pubs.opengroup.org/onlinepubs/9699919799/functions/isatty.html) to check whether or not the stream is outputting to a terminal, and adapt accordingly (ANSI colors to terminal, plain text otherwise).

I'm using the latest version from Homebrew:

```
$ swiftformat --version
swiftformat, version 0.35.2
```

**Comment by lassik** [comment]
Related PR from December that was closed by its author: https://github.com/nicklockwood/SwiftFormat/pull/203

I would recommend automatic `isatty()`-adaptive behavior instead of a manual `--no-ansi` option.

**Comment by nicklockwood** [comment]
Thanks, I didn’t know about isatty(). Sounds like a much better solution than a manual flag.

**Comment by nicklockwood** [comment]
@lassik I’ve implemented `isatty()` in version 0.35.3.

**Comment by lassik** [comment]
Thanks for being so responsive, that's awesome :)

Unfortunately I think there's a subtle bug in [the current code](https://github.com/nicklockwood/SwiftFormat/blob/a8535a56f2c75d5f529f6633b366413e4eb3f473/CommandLineTool/main.swift#L53). `CLI.print` can print to either stdout or stderr depending on circumstances, but it checks `isatty(STDOUT_FILENO)` even in the cases where the output will actually go to `stderr` I think there should be a separate check `isatty(STDERR_FILENO)` for these cases.

**Comment by nicklockwood** [comment]
@lassik yeah, I realized that after publishing it. I‘ll fix it for the next release, but tbh I think it’s  probably fine for most use cases.

Typically you’d remap stdout (to a file or whatever) and leave stderr pointing to the Terminal, in which case this will still work fine. I was mainly concerned about people using it as a script phase in Xcode, which this also solves.

**Comment by lassik** [comment]
Agreed. Seems reasonable.
