### ISSUE TITLE
Linebreaks before ending parenthesis in function calls should be a rule

### ISSUE THREAD

**Issue by sebastianfrelle** [nicklockwood/SwiftFormat#292]
Let's take the call to the UIView initializer `init(frame:)` as an example.

```swift
UIView(frame: CGRect(origin: CGPoint(x: 0, y: 0), size: CGSize(width: 0, height: 0)))
```

I have a strong preference for applying linebreaks to this call like so:

```swift
UIView(
  frame: CGRect(
    origin: CGPoint(
      x: 0,
      y: 0),
    size: CGSize(
      width: 0,
      height: 0)))
```

I think this is the more readable option, as it is visually reminiscent of a list of bullet points:

* UIView
  * frame
    * origin
      * x
      * y
    * size
      * width
      * height

However, SwiftFormat currently dictates the following structure:

```swift
UIView(
  frame: CGRect(
    origin: CGPoint(
      x: 0,
      y: 0
    ),
    size: CGSize(
      width: 0,
      height: 0
    )
  )
)
```

Every line taken up by a single `)` adds no extra visual information to the code and is therefore, in my opinion, a waste of space.

I propose exposing this behavior as a rule to allow for customization.

**Comment by nicklockwood** [comment]
@sebastianfrelle seems reasonable.

**Comment by nicklockwood** [comment]
@sebastianfrelle (note: while there is currently no way to make SwiftFormat enforce your preferred style, if you wish to allow this style to pass through unmodified, use `--disable wrapArguments`)

**Comment by nicklockwood** [comment]
@sebastianfrelle I’ve added a new `—closingparen` option in 0.35.3 to control this.

**Comment by sebastianfrelle** [comment]
@nicklockwood Never got around to saying thank you. I appreciate the work that went into this addition.
