### ISSUE TITLE
Wraparguments for wrong formatted function not working

### ISSUE THREAD

**Issue by michalcickan** [nicklockwood/SwiftFormat#294]
I have a wrong formated code `func foo(a: Int, b: Int, c: Int) { ... }`

And when I use `--wraparguments`, it doesn't work. Wraparguments works only when it's is partially formatted:

1. func foo(a: Int,
                  2. b: Int) {

then `beforefirst` `afterfirst` works. 

Is it possible to force format of top function, to `afterfirst`, when arguments are in one line?

**Comment by nicklockwood** [comment]
@michalcickan it’s not possible currently. `wraparguments` will only rewrap functions that have already been wrapped onto multiple lines. I’ll consider adding an option for this.

**Comment by pmanna** [comment]
May or may not be the same, but I've had to disable _wrapArguments_ because formatting was going from this
```swift
	MultivaluedSection(multivaluedOptions: [.Insert, .Delete]
//						,
//						header: "Multivalued TextField",
//						footer: ".Insert adds a 'Add Item' (Add New Tag) button row as last cell."
					){

						$0.addButtonProvider = { section in
```
to this
```swift
	MultivaluedSection(multivaluedOptions: [.Insert, .Delete]
//									,
		//) {								   header: "Multivalued TextField",
			$0.addButtonProvider = { section in
```
both with _after-first_ & _preserve_, i.e. a comment line was misplaced, a second was gone, and closing parenthesis / opening bracket was commented out, that of course triggered a syntax error.

Easy fix on our side, still wanted to point this out…

**Comment by nicklockwood** [comment]
@pmanna thanka for reporting. This isn't really the same issue, but it looks like a serious bug and I'll get it fixed asap.

**Comment by nicklockwood** [comment]
@pmanna the bug you reported is fixed in version 0.40.0.

**Comment by pmanna** [comment]
@nicklockwood Thanks, great support!

**Comment by nicklockwood** [comment]
@michalcickan swiftformat 0.41.0 now allows you to specify a `--maxwidth` and will wrap arguments that exceed it automatically.

**Comment by Dayreks** [comment]
@nicklockwood I have a question still regarding this thread. With the parameter of `--maxWidth` we definitely can avoid this issue, but it is also affecting all the other places where I wouldn't want to trigger the argument wrapping. Am I not correctly using this parameter or maybe there is another way to work around it ?
