### ISSUE TITLE
Suggestion: Allow private(set) formatting as Apple suggest it in the docs ?

### ISSUE THREAD

**Issue by gragera** [nicklockwood/SwiftFormat#3]
<img width="337" alt="screen shot 2016-08-22 at 23 38 23" src="https://cloud.githubusercontent.com/assets/287089/17872699/887bdff0-68c1-11e6-9e79-9e51d39800e7.png">

vs

<img width="336" alt="screen shot 2016-08-22 at 23 38 36" src="https://cloud.githubusercontent.com/assets/287089/17872702/90e0bfee-68c1-11e6-83e5-4b2603883326.png">

What do you think?

**Comment by nicklockwood** [comment]
Seems a bit petty to make this an option. I think I'll change it to Apple standard and see if anyone objects.

**Comment by nicklockwood** [comment]
Fixed in 0.2
