### ISSUE TITLE
The following configuration fails to be parsed.

### ISSUE THREAD

**Issue by RabugenTom** [nicklockwood/SwiftFormat#30]
Hi Nick,
SwiftFormat (v0.9.5) fails to parse the file when it contains something like:
````swift
struct A {
    func f(x: Bool) -> Bool {
    switch x {
        case true: return false
        default: return true
        }
    }
}

enum B {
    case foo
}
````
It seems confused with the `case`'s in `f` and those of `B`.

**Comment by nicklockwood** [comment]
Thanks - fixed in 0.9.6

**Comment by RabugenTom** [comment]
Hi Nick,
It seems there is an issue with the binary bundled with 0.9.6. It seems
that some reference to a swift file on your desktop is hardcoded. No issues
when the binary is built from code.
Best regards.
Le ven. 16 sept. 2016 à 14:11, Nick Lockwood <notifications@github.com> a
écrit :

**Comment by nicklockwood** [comment]
Yes, I forgot to rebuild after fixing the bug. Should be fixed if you redownload.
