### ISSUE TITLE
Add glob support in list of excluded files

### ISSUE THREAD

**Issue by mgrebenets** [nicklockwood/SwiftFormat#301]
Hello

This feature request is for adding glob support in the list of excluded files.
In our setup we have quite a few files generated and we want to exclude them from formatting with SwiftFormat.

While we can use `--exclude` option, we have to list each and every file or directory in the project, and we have a lot of those.

With introduction of config files we can as well put custom `.swiftformat` file in each directory that needs to be excluded, but that's still a workaround not the proper solution (imho).

The ideal solution would be to support glob patters in list of files to exclude, e.g. wildcards, so we can do this:

```
--exclude .*Generated.*,*PaintCode*,IgnoreThisAll/**/*
```

and it will exclude all file paths that match listed patterns.

**Comment by nicklockwood** [comment]
@mgrebenets glob support has been added in version 0.35.4
