### ISSUE TITLE
Required parentheses stripped away from function types

### ISSUE THREAD

**Issue by PabloSichert** [nicklockwood/SwiftFormat#302]
Formatting

```swift
let foo: ((a: Int, b: Int)) -> Void
```

results in

```swift
let foo: (a: Int, b: Int) -> Void // 🛑 Function types cannot have argument labels; use '_' before 'index'
```

where the second set of parentheses distinguishes a single tuple parameter from the "tuple contents" as parameter list.

#268 and #269 might be related

**Comment by nicklockwood** [comment]
@PabloSichert you're right - I fixed it for 
https://github.com/nicklockwood/SwiftFormat/issues/268 and then broke it again with the fix for 
https://github.com/nicklockwood/SwiftFormat/issues/269 🤦‍♂️

I've pushed another fix to the develop branch if you'd like to test it.

**Comment by PabloSichert** [comment]
Tried it out on the `develop` branch – works as expected. Thanks!

**Comment by nicklockwood** [comment]
@PabloSichert fixed in 0.35.5

**Comment by dmiluski** [comment]
Hi, I'm using:
swiftformat, version 0.35.9

And just ran into this issue, I believe?
```
        let selected: (Audience) -> Void = { [weak self] (_ audience) in
              ...content
        }
```
was formatted to
```
        let selected: (Audience) -> Void = { [weak self] _ audience in
              ...content
        }
```

Where config is set to:
```
--allman false
--binarygrouping none
--closingparen same-line
--commas inline
--comments ignore
--decimalgrouping none
--elseposition same-line
--empty void
--exponentcase lowercase
--exponentgrouping disabled
--fractiongrouping disabled
--header ignore
--hexgrouping none
--hexliteralcase uppercase
--ifdef noindent
--importgrouping alphabetized
--indent 4
--indentcase false
--linebreaks lf
--octalgrouping none
--operatorfunc spaced
--patternlet hoist
--ranges nospace
--self remove
--semicolons inline
--stripunusedargs unnamed-only
--trimwhitespace always
--wraparguments afterfirst
--wrapcollections beforefirst
```

Did I perhaps misinterpret a config setting which is making this update? This appears to be the only file which is negatively affected by this rule application.

**Comment by dmiluski** [comment]
Ignore, I had a syntactical error. "_ + audience". I'm actually surprised that ever compiled.

**Comment by nicklockwood** [comment]
@dmiluski I’ve never seen an inline closure parameter written that way, but I can see why it would work since it’s similar to

let handler = (_ arg: Type) -> Void

In any case SwiftFormat should not change valid syntax into invalid syntax, however unusual it is, so I’ll try to fix it.
