### ISSUE TITLE
empty blocks are formatted as {}

### ISSUE THREAD

**Issue by wizofaus** [nicklockwood/SwiftFormat#305]
A recent change to swift format has caused empty functions etc. to be reformatted as {}.
I can't see any way to turn off this behaviour.
The fact that some devs in our team have one version and some another is causing issues, but we don't want this behaviour.

**Comment by nicklockwood** [comment]
@wizofaus you can use `—disable emptyBraces` to turn off the behavior.

For future reference, all rule changes for each swiftformat release can be found in the CHANGELOG.md file in this repository, which should help when investigating such mysteries in future.

You can also use the `—verbose` option for a breakdown of which rules were applied to each file when running swiftformat.

**Comment by wizofaus** [comment]
Ok thanks that works, but I don't suppose there's an option to stop older versions of swift format failing when `-disable emptyBraces` is specified?

**Comment by nicklockwood** [comment]
@wizofaus, I’m afraid not. But is there any reason not to ask everyone to upgrade?

**Comment by wizofaus** [comment]
The '-disable emptyBraces' is in a script that's in source control, so it depends what branch people are working on...
Also that option doesn't seem to reverse the change it made in the first place.

**Comment by nicklockwood** [comment]
@wizofaus SwiftFormat does now support using a .swiftformat file in your project directory to specify the rule, but support for that feature was added just recently so it won’t work for users on older swiftformat versions.

Disabling the rule won’t re-insert the linebreak between {…}, however you could do a global find/replace of {} with {\n} and then run swiftformat to restore the correct indentation.

**Comment by nicklockwood** [comment]
@wizofaus I'll close this for now as I don't think there's anything else I can suggest, but feel free to reopen the issue if you have further questions.
