### ISSUE TITLE
Is there a way to change the closing parenthesis/curly bracket indentation?

### ISSUE THREAD

**Issue by NeverwinterMoon** [nicklockwood/SwiftFormat#306]
I am trying to make SwiftFormat working similarly to AppCode's formatting

In AppCode (I think with default formatting), it looks like this
``` snippet #1
waitUntil { done in
  self.controller.webView(
    webView,
    decidePolicyFor: fakeAction,
    decisionHandler: { policy in
      expect(webView.loadCalls) == [(TAConstants.myJourneyPageURL + "?native=true").asURLRequest]
      expect(policy) == .cancel

      done()
    }) // <-- this here is placed on same vertical line as decisionHandler, because the opening curly bracket was there
}
```

SwiftFormat would do this:
``` snippet #2
waitUntil { done in
  self.controller.webView(
    webView,
    decidePolicyFor: fakeAction,
    decisionHandler: { policy in
      expect(webView.loadCalls) == [(TAConstants.myJourneyPageURL + "?native=true").asURLRequest]
      expect(policy) == .cancel

      done()
  }) // <- this here is placed on same vertical line as self.controller.webView, I guess because the opening parenthesis is there... So the logic is completely different to AppCode's one
}
```

More than that, in AppCode I can do something like this:
``` snippet #3
waitUntil { done in
  self.controller.webView(
    webView,
    decidePolicyFor: fakeAction,
    decisionHandler: { policy in
      expect(webView.loadCalls) == [(TAConstants.myJourneyPageURL + "?native=true").asURLRequest]
      expect(policy) == .cancel

      done()
    } // <- this is placed on vertical line with decisionHandler, makes sense
  ) // <- this is placed on vertical line with self.controller.webView, makes sense
}
```

If I run SwiftFormat on snippet #3, it will move the brackets together and produce the result as seen in the snippet #2. AppCode would preserve it as it is.

**Comment by nicklockwood** [comment]
@NeverwinterMoon the indenting of closing paren/brace pairs is deliberate, although you are not the first to suggest that it might not be ideal so I'll consider revising it or offering some configuration.

The example shown in snippet #3 should be preserved though, and when I run SwiftFormat on your isolated example it is. Are you using the Xcode extension? If so it may be inferring some style rules from the rest of your code that is causing it to modify the wrapping, and you might wish to set the rules explicitly using the configuration app.

To preserve the example in snippet #3 you need to have `--wraparguments preserve` or `--wraparguments beforefirst`. If you are using `--wraparguments afterfirst` then it would convert snippet #3 to

```swift
waitUntil { done in
    self.controller.webView(webView,
                            decidePolicyFor: fakeAction,
                            decisionHandler: { policy in
                                expect(webView.loadCalls) == [(TAConstants.myJourneyPageURL + "?native=true").asURLRequest]
                                expect(policy) == .cancel

                                done()
    })
}
```

which is perhaps what you are seeing?

**Comment by nicklockwood** [comment]
This now works as proposed in snippet 3.
