### ISSUE TITLE
Suggestion - Rules Configuration

### ISSUE THREAD

**Issue by jerrydillon** [nicklockwood/SwiftFormat#31]
Great start on what could be a very useful tool.
What would be great is if you could work on a configurable set of flags to turn on/off.

Examples 

- Extra Line breaks after declarations on/off
- Terminating value containers with commas yes/no
- Brace positions same line / next line

Great start!!

**Comment by nicklockwood** [comment]
Thanks for the suggestions. I would like to add more configuration options at some point, but my priority for the time being is to fix all the bugs and get the standard set of rules as refined as possible.

Features like Allman-style braces (where the bracket appears on next line) would be fun to add, but AFAIK almost nobody uses this style for Swift code, and I don't want to add style options just for the sake of it.

Similarly, having a trailing comma in a value container is less of a style issue and more about good practice (prevents redundant line changes in commit history), so I'm not sure I'd want to make it optional.

**Comment by nicklockwood** [comment]
FYI, trailing commas can now be disabled.

**Comment by nicklockwood** [comment]
These configuration options are all implemented version 0.15.
