### ISSUE TITLE
a case report: for combining String and #macro with '+' literal while using as a parameter.

### ISSUE THREAD

**Issue by metasmile** [nicklockwood/SwiftFormat#312]
``` 
DispatchQueue(label: "com.stells.internal."+[SPACE]#file, qos: .utility)
```

then 2 errors are printing.
```
Error:(694, 57) expected ',' separator
Error:(694, 55) '+' is not a postfix unary operator
```

Right cases are
```
DispatchQueue(label: "com.stells.internal."+#file, qos: .utility)
```
or 

```
DispatchQueue(label: "com.stells.internal."[SPACE]+[SPACE]#file, qos: .utility)
```

**Comment by nicklockwood** [comment]
@metasmile thanks for reporting, I'll get that fixed asap.

In the meantime, manually putting spaces around the + will prevent swiftformat from breaking the code. Alternatively, you can use:

```swift
// swiftformat:disable:next spaceAroundOperators
DispatchQueue(label: "com.stells.internal."+#file, qos: .utility)
```

**Comment by metasmile** [comment]
Got it. Thanks for fast respond.

**Comment by nicklockwood** [comment]
@metasmile fixed in 0.35.7

**Comment by metasmile** [comment]
No. it was not resolved case. Clearly a bug. If this cli tool to you made can call "formatter"
format -> compile -> error is not allowed.

**Comment by metasmile** [comment]
// swiftformat ?? 
It already tells it is not complete formatter as itself.

**Comment by nicklockwood** [comment]
@metasmile I don't understand what you mean. I closed the ticket because I fixed the bug in the latest version. The bug you reported occurred in version 0.35.6. In version 0.35.7 it no longer happens.

**Comment by metasmile** [comment]
I see, very sorry for the offensive comment a little. Since 0.35.7, finally, complete our build without any exception comment flag use with flowing stat
```
swiftformat . --disable redundantInit  
running swiftformat...
swiftformat completed. 288/528 files updated in 2.67s
swiftformat . --disable redundantInit
running swiftformat...
swiftformat completed. 35/528 files updated in 1.92s
swiftformat . --disable redundantInit
running swiftformat...
swiftformat completed. 0/528 files updated in 1.94s
swiftformat . --disable redundantInit
running swiftformat...
swiftformat completed. 0/528 files updated in 1.81s
```
In overall it was blazingly fast. Yeah, and I did execute it 3 times. It seems optimize again for some files. it was just my curious.

Our project info is purely written in swift code, plus some swift files related with CoreML and auto-generated by R.swift(this is not little as you may know), and all codes recently changed with swift 4.2, also excluded Pods or external libraries.
```
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Swift                          511          12360          12758          49115
JSON                            14              0              0            382
Markdown                         1              0              0              2
-------------------------------------------------------------------------------
SUM:                           284           8646           5617          34810
-------------------------------------------------------------------------------
```

If swift format come to 1.0 or complete level, it can be official formatting engine for Xcode or AppCode I think. Or you may think real-time syntax correction together with IDE. feature. Someday I also would like to contribute. Thanks for making great syntax optimizer.
