### ISSUE TITLE
Rule request: Order class properties and methods by access control value

### ISSUE THREAD

**Issue by jsonfellin** [nicklockwood/SwiftFormat#317]
This might not be achievable, but I'd love it to enforce a particular order for our projects.

**Comment by nicklockwood** [comment]
@jsonfellin it's probably possible, with caveats. For example, if the properties are not already grouped together, then it's probably not an idea to move them around in the file.

Would you put the public properties first, or private? (or should it be configurable?)

**Comment by jsonfellin** [comment]
Thanks for the reply. This might be overkill, but I like most of the rules and options in this comment from SwiftLint: 
https://github.com/realm/SwiftLint/issues/2294

Though I imagine it would be a tall order to deal with moving code around in a reliable way.

**Comment by nicklockwood** [comment]
This is now possible using the `organizeDeclarations` rule
