### ISSUE TITLE
ifdef gets indented incorrectly if you have comments after #endif

### ISSUE THREAD

**Issue by thii** [nicklockwood/SwiftFormat#319]
When you have ifdef between enum cases or switch cases **and** a comment after `#endif`, the indentation of `#endif` is being formatted incorrectly.

### Input
```swift
enum State {
    case one
#if THIS
    case two
#endif //
}
```

### Configuration
```
--ifdef outdent
```

### Expected output
The code remains unchanged.

### Actual output
```swift
enum State {
    case one
#if THIS
    case two
    #endif //
}
```

**Comment by nicklockwood** [comment]
@thii fixed in version 0.35.8. Thanks for reporting it!
