### ISSUE TITLE
Incorrectly transforming documentation comments to code block documentation

### ISSUE THREAD

**Issue by danielgalasko** [nicklockwood/SwiftFormat#32]
Given a trivial documentation comment for a method, its documentation is rendered as follows

![screen shot 2016-09-22 at 10 22 51 am](https://cloud.githubusercontent.com/assets/4479146/18741300/b5382f30-80ae-11e6-8d6b-b622f956bae8.png)

When swiftformat is run, the following is produced

![screen shot 2016-09-22 at 10 23 08 am](https://cloud.githubusercontent.com/assets/4479146/18741316/cd5b1b18-80ae-11e6-9546-82935dc750e9.png)

I believe this to be a result of adding trailing white space to the first `/** ` and then the closing `    */` is preceded by whitespace. This turns it into a code block.

**Comment by nicklockwood** [comment]
Thanks, looking into it now.

**Comment by danielgalasko** [comment]
Side note, it also flattens out any indentation for code blocks AKA

```swift
/**
I am a comment, code block to follow
    let codeBlock = current
    print("this will get flattened and the indentation stripped")
*/
func foo() {}
```

This will end up as

```swift
/**
I am a comment, code block to follow
let codeBlock = current
print("this will get flattened and the indentation stripped")
*/
func foo() {}
```

**Comment by 3lvis** [comment]
@danielgalasko 

The second comment might be related to some of the listed Known Issues: 

https://github.com/nicklockwood/SwiftFormat#known-issues

:)

**Comment by nicklockwood** [comment]
@danielgalasko yeah, the second is a known issue. There are some workarounds suggested in the README.

**Comment by nicklockwood** [comment]
This should now be fixed in 0.11 (the first issue, not the second).

**Comment by danielgalasko** [comment]
Wow brilliant stuff @nicklockwood 🙌

**Comment by nicklockwood** [comment]
@danielgalasko it took a little while, but the second issue is now also fixed :-)
