### ISSUE TITLE
What is the exact syntax of globs in --exclude option?

### ISSUE THREAD

**Issue by mgrebenets** [nicklockwood/SwiftFormat#330]
While globs are implemented, it's not clear what's the exact syntax for them.
Could the README be updated with a couple of examples please?
Most of the globs I tried didn't quite for me so far.

For example, for this line

<pre> --exclude *AutoGenerated*</pre>

I get this error:

> error: --exclude option expects a value

I tried 
<pre> --exclude Pods,.*AutoGenerated.*</pre>

and other combinations with no luck

The only way I was able to make it work is like so:

<pre> --exclude **/*AutoGenerated*,**/*SwiftGen*</pre>

Though then the execution is slow, see https://github.com/nicklockwood/SwiftFormat/issues/329

**Comment by nicklockwood** [comment]
That error message is clearly not helpful, but I can’t tell if the behavior is actually wrong. Can you describe your project folder structure? Can the AutoGenerated folder appear at any level of nesting?

**Comment by mgrebenets** [comment]
Yep. We have quite a few patterns for auto generated Swift code. 
For example
- directory called `Generated`  This directory can appear pretty much on any level in our project. The project is broken into modules (components) and each component can have auto generated content. 
- another example are files with `.AutoGenerated.` in the name. These can appear on any level as well. 
- same for files with `+SwiftGen` or `+Generated` in the name. 

Quite a few patterns and we’d want a simple glob to ignore them on any level. 

We have similar setup for Ruby and Rubocop and end up having a bunch of globs in ruby configs.

**Comment by nicklockwood** [comment]
@mgrebenets I wasn't able to reproduce the error:

> error: --exclude option expects a value

With `--exclude *AutoGenerated*`. Is it possible you actually wrote `--exclude *` (or possibly had a space after the * before the rest of the string?)

**Comment by mgrebenets** [comment]
Spoke too soon :D

The error only happens when glob (regex) match fails to find any single match.

For example

`--exclude **/*nofilesmatching*` - fails
`--exclude **/*.swift,**/*nofilesmatching*` - works now since there's at least one match available.

**Comment by nicklockwood** [comment]
@mgrebenets thanks, I was able to replicate this now. The explicit "--config" argument was the key part I was missing.

**Comment by nicklockwood** [comment]
@mgrebenets this is now fixed in version 0.36.0. I've replaced the unhelpful error with a more meaningful warning instead.
