### ISSUE TITLE
SwiftFormat crashes on launch due to invalid signature

### ISSUE THREAD

**Issue by swisspol** [nicklockwood/SwiftFormat#337]
Podfile contains `pod 'SwiftFormat/CLI'`

We run a CI job every Sunday to auto-format our code with SwiftFormat. It passed on Dec 23, 2018 12:32 AM but failed on next run at Dec 30, 2018 12:32 AM. The executable just crashes instantly on launch. I can repro locally on my MBP with 10.14.2 (18C54).

_Version 0.35.6 and 0.37.1 are affected (I just tried running `pod update` as we were using an old version of SwiftFormat)._

```
$ ./Pods/SwiftFormat/CommandLineTool/swiftformat
Killed: 9
```
```
$ lldb ./Pods/SwiftFormat/CommandLineTool/swiftformat
(lldb) target create "./Pods/SwiftFormat/CommandLineTool/swiftformat"
Current executable set to './Pods/SwiftFormat/CommandLineTool/swiftformat' (x86_64).
(lldb) r
error: process exited with status -1 (unable to attach)
```

Crash logs are created in `~/Library/Logs/DiagnosticReports`:
```
Process:               swiftformat [25065]
Path:                  /Users/USER/*/swiftformat
Identifier:            swiftformat
Version:               ???
Code Type:             X86-64 (Native)
Parent Process:        bash [9970]
Responsible:           swiftformat [25065]
User ID:               501

Date/Time:             2018-12-30 14:28:21.830 -0800
OS Version:            Mac OS X 10.14.2 (18C54)
Report Version:        12
Bridge OS Version:     3.0 (14Y674)
Anonymous UUID:        8618749C-55BE-49B0-D91A-6F09D9DE37EE

Sleep/Wake UUID:       98FD6B43-A7EA-4AF3-AFC3-F7BE3FEA5A2B

Time Awake Since Boot: 23000 seconds
Time Since Wake:       1900 seconds

System Integrity Protection: enabled

Crashed Thread:        Unknown

Exception Type:        EXC_CRASH (Code Signature Invalid)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    Namespace CODESIGNING, Code 0x1

kernel messages:

Backtrace not available

Unknown thread crashed with X86 Thread State (64-bit):
  rax: 0x0000000000000000  rbx: 0x0000000000000000  rcx: 0x0000000000000000  rdx: 0x0000000000000000
  rdi: 0x0000000000000000  rsi: 0x0000000000000000  rbp: 0x0000000000000000  rsp: 0x00007ffee37faa30
   r8: 0x0000000000000000   r9: 0x0000000000000000  r10: 0x0000000000000000  r11: 0x0000000000000000
  r12: 0x0000000000000000  r13: 0x0000000000000000  r14: 0x0000000000000000  r15: 0x0000000000000000
  rip: 0x0000000112eb7000  rfl: 0x0000000000000200  cr2: 0x0000000000000000
  
Logical CPU:     0
Error Code:      0x00000000
Trap Number:     0


Binary images description not available


External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 17217
    thread_create: 0
    thread_set_state: 0
```

Here's the code-signing info:
```
$ codesign -dvvv ./Pods/SwiftFormat/CommandLineTool/swiftformat 
Executable=/Users/pol/Source/ios_client/Pods/SwiftFormat/CommandLineTool/swiftformat
Identifier=swiftformat
Format=Mach-O thin (x86_64)
CodeDirectory v=20200 size=87691 flags=0x0(none) hashes=2733+5 location=embedded
Hash type=sha256 size=32
CandidateCDHash sha1=253b388fb4856a62c5e8cbfa17f148b5d5bb481b
CandidateCDHash sha256=0f90651f795ac74b5f3a0baf853b092ea8b2c71a
Hash choices=sha1,sha256
CDHash=0f90651f795ac74b5f3a0baf853b092ea8b2c71a
Signature size=4778
Authority=(unavailable)
Info.plist=not bound
TeamIdentifier=8VQKF583ED
Sealed Resources=none
Internal requirements count=1 size=172
```

**Comment by nicklockwood** [comment]
@swisspol this is a little confusing. You're saying the *same version* of SwiftFormat worked on the 23rd and then crashed on launch on the 30th?

Is your CI machine installing the pod fresh each time? In which case could it somehow be that it got a corrupt copy of the binary on one run and not on another?

Also in your testing, is it just 0.35.6 and 0.37.1 that are affected, or all versions?

I've seen issues when building where the deployed binary crashes, and I have to build again, but I've never seen a problem where a deployed binary works once and then not subsequently.

**Comment by nicklockwood** [comment]
Can you try deleting your pods folder and then running `pod cache clean` before reinstalling, to see if that fixes it?

**Comment by swisspol** [comment]
The binary is checked into the repo as we check in the entire /Pods/
directory to ensure reproducibility of builds and guaranteed lock down of
dependencies.

These two versions don’t work, I didn’t try others. The older version is
the one we have been using for months on the exact same macs. It repros on
my Mac as well as at least 2 of the CI Macs the job failed on. The CI Macs
do not auto-install sw updates btw but my Mac does.

It actually makes sense that it suddenly stops working: if the code signing
cert was recently invalidated or it’s past its expiration date.

Note that there’s no other code signing issues that I’m aware of on my Mac
nor the CI macs.

The simplest thing to try would be for me to download the binary from a
link: do you have one?

**Comment by anilabsinc-ajay** [comment]
Facing this issue suddenly for xcode extension

**Comment by anilabsinc-ajay** [comment]
![screenshot 2018-12-31 at 1 01 19 pm](https://user-images.githubusercontent.com/33340773/50556227-3a3ed900-0cfc-11e9-8bac-8c1d14dd659f.png)

**Comment by dominicfreeston** [comment]
We're seeing the same issue. We store our pods in the repo so nothing's changed locally. Expired certificate or something?

**Comment by swisspol** [comment]
Can we simply strip the signature from the binary? Why does this even need to be signed? It’s a low level developer tool.

**Comment by nicklockwood** [comment]
@swisspol certainly you can. You can also just build it locally from source if you’re checking in the binary.

I’m not sure if it needs to be signed or not tbh. I assumed it would cause issues with Gatekeeper if it wasn’t, but maybe it’s not necessary for a CLI app?

**Comment by swisspol** [comment]
You should have to codesign your tool. The ones provided as part of the OS are signed but third party ones are not to my knowledge. It's more hassle than it's worth at this time.
```
$ codesign -dvvv ./Pods/SwiftLint/swiftlint 
./Pods/SwiftLint/swiftlint: code object is not signed at all
```
```
$ codesign -dvvv /usr/local/bin/clang-format 
/usr/local/bin/clang-format: code object is not signed at all
```
```
$ codesign -dvvv /usr/local/bin/cmake
/usr/local/bin/cmake: code object is not signed at all
```

Anyway, removing the signature from the tool makes it work again:
```
$ codesign --remove-signature ./Pods/SwiftFormat/CommandLineTool/swiftformat
```

**Comment by nicklockwood** [comment]
@swisspol “you should have to codesign your tool” - did you mean “shouldn’t”?

I guess on that basis I’ll ship it unsigned in the next release. I don’t think there’s anything I can do about the current releases, but stripping the code signature or rebuilding from source seems like a reasonable workaround.

**Comment by nicklockwood** [comment]
@swisspol can you verify the new version (0.37.2) I've pushed to master is working correctly for you? (it's not on CocoaPods yet).

**Comment by anilabsinc-ajay** [comment]
@nicklockwood The latest version also have the same Problem, Fixed by downloading the project and re compile with own developer certificate

**Comment by nicklockwood** [comment]
@anilabsinc-ajay I don't understand how that can be the case. The swiftformat binary for 0.37.2 is now not signed at all. Can you run `codesign -dvvv [path_to_your_copy_of_the_swiftformat_binary]` and verify what it says?

**Comment by swisspol** [comment]
Works for me:
```
$ cd /Users/pol/Downloads/SwiftFormat-0.37.2/CommandLineTool 
Pol-MacBook-Pro:CommandLineTool pol$ codesign -dvvv swiftformat 
swiftformat: code object is not signed at all

$ ./swiftformat 

swiftformat, version 0.37.2
copyright (c) 2016 Nick Lockwood
(...)
```

**Comment by nicklockwood** [comment]
@anilabsinc-ajay oh wait, were you referring to the extension, not the command-line tool?

I’ve resigned that, but I don’t think it can be distributed unsigned without causing gatekeeper issues.

**Comment by anilabsinc-ajay** [comment]
@nicklockwood , Please check that once as the extension is crashing due to certificate issue, For me it is now working with my certificate, For the time I will continue with that. Once you sure about that I will update it will Original.
