### ISSUE TITLE
My installation is corrupted

### ISSUE THREAD

**Issue by robreuss** [nicklockwood/SwiftFormat#338]
The extension was working great for me for months but I had a couple of Xcode crashes and it no longer shows on the "Editor" menu list.  I re-downloaded a copy and when I double click the "SwiftFormat for Xcode" file in the Applications folder as instructed, I get an error message "The file can't be found".  Any ideas?  Is there some way I can clean out any remnants in Xcode before reinstalling?  

Thanks for a great extension - I use it all the time.

**Comment by nicklockwood** [comment]
@robreuss I've never heard of that error before. I suspect this might be related to https://github.com/nicklockwood/SwiftFormat/issues/337, in which case I'll push a new update shortly that will hopefully correct the problem. I don't think there's any need to "clean out" anything from Xcode, but it's possible that something else has gone wrong.

**Comment by robreuss** [comment]
@nicklockwood Yeah, I saw that issue when I searched but got the impression it was probably more pod-specific (I'm doing the extension install, obviously).  Thanks for looking into it!

**Comment by nicklockwood** [comment]
@robreuss it affects any precompiled binary in the project. If you rebuild the extension from source it should work, but that's a bit fiddly as you have to build the extension and then the app and sign them both correctly.

**Comment by nicklockwood** [comment]
@robreuss can you try the latest version I've just pushed to master and see if that fixes the problem?

**Comment by robreuss** [comment]
@nicklockwood Fixed.  Thank you sir.
