### ISSUE TITLE
Enforce space between [* self] and parameters in closures

### ISSUE THREAD

**Issue by tonyarnold** [nicklockwood/SwiftFormat#34]
Given the following closure:

```swift
observeNext { [unowned self] (result, textField) in
    // Do the thing with the thing
}
```

I would expect the space to remain between `[unowned self]` and the parameters `(result, textField)`, however SwiftFormat 0.11.2 is removing the space.

**Comment by nicklockwood** [comment]
Fixed in 0.11.3
