### ISSUE TITLE
Xcode Extension stop working after latest Upgrade

### ISSUE THREAD

**Issue by techmehra** [nicklockwood/SwiftFormat#340]
Thanks for Nice Extension. I was using this extension since last year, But now it stop appearing on xcode and system menu

**Comment by nicklockwood** [comment]
@techmehra there was an issue with code signing that broke the previous version. Have you tried downloading the latest build from master?

**Comment by techmehra** [comment]
Yes I have latest version and it is working, When i open it. But the problem is that the xcode extension is no more visible on System Pref.

<img width="546" alt="screenshot 2019-01-08 at 10 38 53 am" src="https://user-images.githubusercontent.com/18284379/50810825-a095ae00-1331-11e9-8d11-f0b324303903.png">

<img width="706" alt="screenshot 2019-01-08 at 10 39 35 am" src="https://user-images.githubusercontent.com/18284379/50810839-b7d49b80-1331-11e9-84b6-b04b1379eaee.png">

**Comment by nicklockwood** [comment]
@techmehra is this still happening with the latest release?
