### ISSUE TITLE
New closure behavior?

### ISSUE THREAD

**Issue by michaelmcguire** [nicklockwood/SwiftFormat#342]
We have recently upgraded from `0.33.10` to `0.37.2` and are noticing new behavior related to formatting closures. These are the options we use:

```
--decimalgrouping 3
--indent 2
--semicolons never
--disable redundantReturn,blankLinesAtStartOfScope,andOperator
--wraparguments beforefirst
--wrapcollections beforefirst
```

Code that previously was:

```
    var arrayOfTuples = zip(evenItems, oddItems)
      .map({ pair -> (TitledContent.IconLabel, TitledContent.IconLabel?) in
        return (pair.0, pair.1)
      })
```

is now getting formatted as:

```
    var arrayOfTuples = zip(evenItems, oddItems)
      .map(
        { pair -> (TitledContent.IconLabel, TitledContent.IconLabel?) in
          return (pair.0, pair.1)
        }
      )
```

This, unfortunately, collides with our `swiftlint` rules regarding opening braces so the two tools are battling each other. Was this change in behavior intended? Is there a way to turn off this formatting of closures? It appears to be affected by the `wrapArguments` rule where it was not before.

**Comment by michaelmcguire** [comment]
Blasted! My searching skills failed me! It is absolutely a duplicate. Is there anything I can do to help with the issue? We can move the discussion there.

**Comment by nicklockwood** [comment]
It’s no problem. Thanks for reminding me about this issue. I’m going to try and get a fix in for the next release.

**Comment by nicklockwood** [comment]
Closed as dupe. See 
https://github.com/nicklockwood/SwiftFormat/issues/320 for further updates.
