### ISSUE TITLE
Non-optional backticks removed from KeyPath

### ISSUE THREAD

**Issue by PabloSichert** [nicklockwood/SwiftFormat#343]
Formatting

```swift
struct Foo {
    let `defer`: Bool
}

let foo: KeyPath<Foo, Bool> = \.`defer`
```

results in

```swift
struct Foo {
    let `defer`: Bool
}

let foo: KeyPath<Foo, Bool> = \.defer // 🛑 error: consecutive statements on a line must be separated by ';'
```

My guess - Keywords are not checked in KeyPaths in the `redundantBackticks` rule?

Apparently only checks on the shorthand notation are needed. The following compiles fine:

```swift
struct Foo {
    let `defer`: Bool
}

let foo: KeyPath<Foo, Bool> = \Foo.defer
```

This has really low priority to me, and I'd be fine inserting a comment for the linter there.

Thought it still might be worth the report

**Comment by nicklockwood** [comment]
@PabloSichert fixed in 0.37.3

**Comment by PabloSichert** [comment]
Just built `swiftformat` from source and can confirm it's fixed (doesn't seem to be released on `brew` yet).

Thank you!

**Comment by PabloSichert** [comment]
Small update:

```swift
let foo: KeyPath<Foo, Bool> = \.defer
```

seems to be valid syntax as of Swift 5.0.

**Comment by nicklockwood** [comment]
@pablosichert thanks for the update - I'll add a version-specific check.

**Comment by nicklockwood** [comment]
This check has been added in 0.41.0
