### ISSUE TITLE
Formatting issue with documentation

### ISSUE THREAD

**Issue by xuaninbox** [nicklockwood/SwiftFormat#344]
/**
     xxxxxxxx.
     - Parameters:
        - a: xxx.
        - b: xxx.
     */

will be formatted to 

     /**
     xxxxxxxx.
     - Parameters:
     - a: xxx.
     - b: xxx.
     */

which breaks the Parameters when generating the doc

**Comment by nicklockwood** [comment]
@xuaninbox this is a known issue. There are some workarounds listed in the README.

**Comment by xuaninbox** [comment]
I see thank you!
