### ISSUE TITLE
redundantSelf does not work in XCode Extension

### ISSUE THREAD

**Issue by hoffsilva** [nicklockwood/SwiftFormat#348]
Hello!

When I run swiftformat command on terminal it removes unnecessary "self", but when I use the xcode extension with redundantSelf rule checked, it does not work. 

```swift
class Test {

       var bar: String
       var foo: String

       init(bar: String) {
            self.bar = bar
            self.foo = "foo" //This changed to foo = "foo" when I use the command swiftformat Test.swift on terminal.
       }
}

**Comment by nicklockwood** [comment]
@hoffsilva do you have this checkbox enabled? If so it will try to infer the options to use from the current contents of the file. Disable the checkbox to specify the options manually.

<img width="327" alt="screen shot 2019-01-24 at 18 58 34" src="https://user-images.githubusercontent.com/546885/51701848-3e63cb00-200a-11e9-85f8-48393402aa07.png">

**Comment by hoffsilva** [comment]
Ok @nicklockwood it worked. Thank you. This extension is awesome.
