### ISSUE TITLE
Tests are failing on `master`

### ISSUE THREAD

**Issue by bachand** [nicklockwood/SwiftFormat#350]
I just [cloned the repo](https://github.com/bachand/SwiftFormat).

I selected the `SwiftFormat (Framework)` scheme.
![image](https://user-images.githubusercontent.com/1791049/52161035-08f75700-2674-11e9-873f-f239f5bd12c6.png)

I typed <kbd>CMD</kbd>+ <kbd>U</kbd> to run the tests.

`testDoubleWildcardMatchesDirectorySlash()` is failing.

![image](https://user-images.githubusercontent.com/1791049/52161062-40660380-2674-11e9-8fcf-95f54b2a23d0.png)

**Comment by nicklockwood** [comment]
@bachand I see the problem. There are one too many `deletingLastPathComponent()` calls, so it’s scanning the directory *above* the project, which may be your entire home directory.

I expect you have another copy of SwiftFormat checked out somewhere, and it’s finding that.

I’ll fix this for the next release, but it the meantime you can work around it by nesting the SwiftFormat project folder inside another directory.

**Comment by bachand** [comment]
Thanks for the quick reply @nicklockwood . I do have another version checked out.

**Comment by nicklockwood** [comment]
@bachand I've pushed a fix to master. I'll include it in the next release.
