### ISSUE TITLE
Group options with their associated rules in SwiftFormat for Xcode app

### ISSUE THREAD

**Issue by nicklockwood** [nicklockwood/SwiftFormat#353]
This is a placeholder issue to discuss a redesign of the UI for the SwiftFormat for Xcode app, as [originally proposed here](https://github.com/nicklockwood/SwiftFormat/pull/228#discussion_r172923810).

When the app was originally developed, it wasn't practical to group options by rule as the requisite metadata didn't exist in the SwiftFormat API. Thanks to [recent changes](https://github.com/nicklockwood/SwiftFormat/commit/33eeb3b9c9382b6d70341566ccbd79d227192bec) this should now be possible.

**Comment by VinceBurn** [comment]
Hi @nicklockwood,

The easy part is to identify which options only affect 1 rule and groups those option with the appropriate rule.  
For the visual I was thinking having the rule in the list, and below the related option(s) indented by 10 to 20 pt. I think a collapse / expand would be overkill.

The hard part is to decide what to do with options that affect more than 1 rule.  
Those options should have their own section (or tab).  
To indicate that an option will affect a rule we could:  
1. list all the rule impacted by the option in the option cell.  
2. list all the option impacting a rule in the rule cell. 
3. Do 1 & 2.   
4. Other solution

Do you have a preference or a different idea?

**Comment by nicklockwood** [comment]
@VinceBurn I would be inclined to just replicate options that affect mutliple rules inside each rule. Perhap there could be some kind of icon or dropdown arrow next to the shared options to show a list of other rules they affect, but I don't know if that's really neccesary.

**Comment by VinceBurn** [comment]
@nicklockwood, that was my first idea, and I thought of the following draw back about the replicate option on every rule they impact.
1. the list become longer due to option duplication
2. visually the first impression is that the option is only impacting that rules (it is easy for a user to think that an option associated with a rule is not the same as an option associated with an other rule, even if they share the same name)

That is why I prefer to separate options in 2 categories, options that have a to one relationship with a rule and options that have a to many relationship to rule. I think implementation would also be more straightforward, so we could have it working sooner and iterate on the result if don't like it.

**Comment by nicklockwood** [comment]
@VinceBurn OK, I'm happy to take your lead on it.

**Comment by nicklockwood** [comment]
cc @tonyarnold, in case he has any thoughts.

**Comment by tonyarnold** [comment]
Sorry gents, I'm super snowed under right now - any chance wireframes or screenshots of the idea could be added to this thread? I'm more than happy to help put the UI together, but I'm not sure what changes we're discussing.

**Comment by VinceBurn** [comment]
Hi @tonyarnold,

here is what I have in mind for option that have a "to one relationship" with rule.

![options](https://user-images.githubusercontent.com/5777036/52720181-2500cf80-2f75-11e9-92fe-ac51505b1256.png)

**Comment by tonyarnold** [comment]
What exactly is an "Option", though? Can you give me a couple of examples? 

I feel like the UI here could use some love, structurally, and I'm happy to propose a layout/design, but I'm really unclear on what data is going to be presented.

**Comment by nicklockwood** [comment]
@tonyarnold "Options" are the settings that currently appear in the Options tab. Basically any configuration for rules that extends beyond turning them on/off.

(FYI, the discussion has now moved to https://github.com/nicklockwood/SwiftFormat/pull/372, so I think I'll close this issue)
