### ISSUE TITLE
testFileHeaderCreationYearReplacement() failing

### ISSUE THREAD

**Issue by bachand** [nicklockwood/SwiftFormat#354]
I cloned the repo clean, opened the project in Xcode 10.1, and ran the tests for `SwiftFormat (Framework)`.

<img width="1512" alt="screen shot 2019-02-08 at 10 42 09 pm" src="https://user-images.githubusercontent.com/1791049/52517630-c9d88100-2bf2-11e9-9f92-271fb1701270.png">

<img width="1512" alt="screen shot 2019-02-08 at 10 42 41 pm" src="https://user-images.githubusercontent.com/1791049/52517635-dc52ba80-2bf2-11e9-8e6d-008aaed573b8.png">

### Failure 1
```
UI Test Activity: 
Assertion Failure: RulesTests.swift:7059: XCTAssertEqual failed: ("// Copyright © 1969

let foo = bar") is not equal to ("// Copyright © 1970

let foo = bar") - 
```

### Failure 2
```
UI Test Activity: 
Assertion Failure: RulesTests.swift:7060: XCTAssertEqual failed: ("// Copyright © 1969

let foo = bar
") is not equal to ("// Copyright © 1970

let foo = bar
") - 
```

**Comment by nicklockwood** [comment]
@bachand ugh, timezones 🙄thanks, I’ll push a fix. In the meantime this will probably work as long as you try it at the right time of day.

**Comment by nicklockwood** [comment]
@bachand OK, this is fixed on master.

**Comment by bachand** [comment]
Thanks @nicklockwood
