### ISSUE TITLE
Explicitly enable rules

### ISSUE THREAD

**Issue by fortmarek** [nicklockwood/SwiftFormat#356]
I think it'd be great if you could do something like whitelist feature that Swiftlint has - ie something like
```bash
--explicit-enable andOperator, anyObjectProtocol, blankLinesAtEndOfScope
```

This would be great for trying out specific commands and giving a more explicit overview of what rules are enabled or if there are teams that want to use this feature, but want to start off with only a handful of rules they think are the most useful (and maybe adding more in the future).

Let me know what you think!

**Comment by nicklockwood** [comment]
@fortmarek if I understand you correctly, the `—rules` argument already does this. E.g.

```bash
$ swiftformat . —rules andOperator,indent
```

Will run *just* the andOperator and indent rules on the current directory.

**Comment by fortmarek** [comment]
Oh, my bad! Thanks 🎉
