### ISSUE TITLE
XAlign 

### ISSUE THREAD

**Issue by o-zaporozhchenko** [nicklockwood/SwiftFormat#359]
is there a way to prevent change lining equalities made by Xalign?
to have:
```
        label.isHidden        = isSomething
        searchButton.isHidden = isSomething
        serchBar.isHidden     = !isSomething

```
instead of:
 ```
        label.isHidden = isSomething
        searchButton.isHidden = isSomething
        serchBar.isHidden = !isSomething

```

https://github.com/qfish/XAlign link if u didnt know it

**Comment by nicklockwood** [comment]
I think `--disable consecutiveSpaces` should do what you want.

https://github.com/nicklockwood/SwiftFormat/blob/master/Rules.md#consecutiveSpaces

**Comment by o-zaporozhchenko** [comment]
Thx, i will try

**Comment by nicklockwood** [comment]
@o-zaporozhchenko did that work? Can I close this issue?

**Comment by o-zaporozhchenko** [comment]
@nicklockwood Yes, it worked.
