### ISSUE TITLE
disable isEmpty rule as default

### ISSUE THREAD

**Issue by o-zaporozhchenko** [nicklockwood/SwiftFormat#361]
Don't you think `isEmpty` rule should be disabled as default?
I got my project broken in multiple places just coz updated pods. Then I found that u implemented this rule, disabled it in `.swiftformat` file, then fixed a few places it broke. 
Same could happen to anyone. I think thats a nice rule, but shouldn't be on default, as soon it can break something.

**Comment by nicklockwood** [comment]
@o-zaporozhchenko this is tricky. Ideally I don't want SwiftFormat's default rules to break any projects, but there is a lot of power in defaults, and if I disable a rule by default there's a good chance many people will never realize that it exists.

If you run SwiftFormat and it breaks your app, it's relatively easy to figure out which rule was to blame and disable it, but if you run it and a rule that you might have wanted was disabled, you'll probably never realize.

Does that make sense?

In any case, could you share some examples of files that it broke? Were they all using NSArray/etc, or was it something else?

**Comment by o-zaporozhchenko** [comment]
@nicklockwood this is old project, so there is just copied some pods manually, so it broken by NSArray, and some of thats' old objc collections with no bridge. 

Well, I can only say that I agree that people may not find needed rules if they disabled. So, i propose to have link to quick cheet-sheet with examples just in first sentences in github. Coz now u need actually read a lot until get to the rules. It will show exactly what Swiftformat can, and make easier to start with using it. 

And I think things like this, that could break something may even make people to stop swiftformat version in podfile and never update it :(

**Comment by huy-le** [comment]
I think the approach "opt-in" is better than "opt-out". The rule you define may not widely use by all teams. Instead of implicitly inject new rule which lead developers to figure out what's changes, would be great to have release notes to show What's new between the old version and new version.

**Comment by nicklockwood** [comment]
I've disabled the isEmpty rule again by default in 0.39.4.
