### ISSUE TITLE
isEmpty is broken

### ISSUE THREAD

**Issue by ochristensen** [nicklockwood/SwiftFormat#366]
`if a - b.count > 0 {...}` -> `if a - !b.isEmpty { ... }`
`if customTypeWithoutIsEmpty.count > 0 { ... }` -> `if !customTypeWithoutIsEmpty.isEmpty { ... }`

**Comment by nicklockwood** [comment]
@ochristensen this is a known issue. Recommended workaround is to disable the rule, either globally or on a per-case basis using `// swiftformat:disable isEmpty` directives.

**Comment by ochristensen** [comment]
that's disappointing as I really like the fix otherwise!
