### ISSUE TITLE
Functions sorting in object

### ISSUE THREAD

**Issue by raptorxcz** [nicklockwood/SwiftFormat#371]
Hi,

It would be great if SwiftFormat sorted functions in objects. My idea is that first would be public / internal function and then all necessary private functions. Then other public / internal functions.

What do you think about it?

**Comment by nicklockwood** [comment]
@raptorxcz I think this is a duplicate of https://github.com/nicklockwood/SwiftFormat/issues/317

**Comment by raptorxcz** [comment]
You are right. 

Thanks
