### ISSUE TITLE
Settings from configuration app no longer reflect in Xcode Source Editor Extension

### ISSUE THREAD

**Issue by tonyarnold** [nicklockwood/SwiftFormat#373]
I've setup a `.swiftformat` file for my various projects, but I've also tried just editing settings using the app (for instance the `required self` setting). 

Changes to settings no longer seem to flow through to the Xcode Source Editor Extension.

**Comment by nicklockwood** [comment]
I think there may have been a signing issue with the last build. If you rebuild locally from source it ahould work.

**Comment by tonyarnold** [comment]
That seems to have worked. Thanks, Nick!

**Comment by VinceBurn** [comment]
Hi @nicklockwood,  One of my colleague have notice the same thing, for more than the last version. I currently have a locally build version and its ok.

Have you investigated it more for the released version ?

**Comment by nicklockwood** [comment]
@VinceBurn I've pushed a fixed (I believe) version to master. I'll try to check this more carefully in future - normally I just build the extension and verify that it runs, but I wasn't checking that the options actually synced correctly.
