### ISSUE TITLE
Add number of lines before auto formatting using wrapArguments

### ISSUE THREAD

**Issue by kuyazee** [nicklockwood/SwiftFormat#377]
Possibility for the rules under wrapArguments to have a line_length checking before automatically wrapping the code if possible.

**Comment by nicklockwood** [comment]
I think this would be a wider feature, as you'd want it to apply to other code not just declarations, but I am planning to add this at some point.

**Comment by kuyazee** [comment]
That's great news.

Have you considered using yml for the configuration file by the way?

**Comment by nicklockwood** [comment]
@kuyazee sorry, I forgot to update the ticket, but 0.41.0 added a `--maxwidth` option to enforce automatic wrapping of arguments.
