### ISSUE TITLE
redundantParens removes required parentheses for Selectors

### ISSUE THREAD

**Issue by ochristensen** [nicklockwood/SwiftFormat#398]
`if menuItem.action == Selector(("aSelectorThatIsNotFound:")) { ... }`
The second set of parens is the way the SwiftCompiler suggests to ignore the warning, but redundantParens removes them.

**Comment by nicklockwood** [comment]
@ochristensen TIL! Thanks for reporting, I'll get that fixed.

**Comment by nicklockwood** [comment]
@ochristensen fixed in 0.40.4.
