### ISSUE TITLE
Formatting of code fragments

### ISSUE THREAD

**Issue by tonyarnold** [nicklockwood/SwiftFormat#40]
I'd love to see a `FormatOption` property to treat the passed input as a fragment of a larger section of code. This would aid with formatting user selections in Xcode, rather than the entire file.

I believe the "simplest" way to implement this would be to take the existing indent of the first line of code passed to `SwiftFormat.format()` and retain it (and indent subsequent lines relative to the first line).

**Comment by nicklockwood** [comment]
I was going to say this seems like a good idea, but I see you've already implemented it!

**Comment by tonyarnold** [comment]
Oh, no, I haven't! I started to, but I couldn't quite get my head around where to retain the necessary indent. I'm happy to have another crack with some guidance.

**Comment by tonyarnold** [comment]
I just implemented formatting of selections. They lose their indent entirely, and drop back to start from column 0.

**Comment by nicklockwood** [comment]
Ah OK. I'll take a look at doing it then.

**Comment by nicklockwood** [comment]
@tonyarnold here you go: https://github.com/nicklockwood/SwiftFormat/pull/41

**Comment by tonyarnold** [comment]
You're a good person. Thanks for being so fast!
