### ISSUE TITLE
Support Swift 5

### ISSUE THREAD

**Issue by neonio** [nicklockwood/SwiftFormat#401]
Now swift 5 has been released.
we found @unknown default will be indent

![image](https://user-images.githubusercontent.com/14893869/55064992-f6b6f980-50b5-11e9-9c41-4f5a852e28dd.png)

**Comment by nicklockwood** [comment]
@neonio this is working correctly for me. Are you using the latest version of SwiftFormat? (0.40.4)

**Comment by neonio** [comment]
Sorry I found I am not using the newest version, the latest version is work as expected.

**Comment by neonio** [comment]
@nicklockwood Thank you again for investing such a great tool for us.
