### ISSUE TITLE
Feature request: Allow space around operators to be disabled independently of delimiters

### ISSUE THREAD

**Issue by nallick** [nicklockwood/SwiftFormat#409]
Version: 0.40.4

Colon placement before a type name when defining variables, properties, and parameters frequently varies between authors. The same happens with key/value pairs in dictionaries. It would be nice to standardize this. For example these variations are typical:

var i:Int = 0
var i: Int = 0
var i : Int = 0

**Comment by nicklockwood** [comment]
@nallick SwiftFormat currently enforces the second of these three.

Are you saying you would like to be able to configure it to use a different variant?

**Comment by nallick** [comment]
The second seems to be the generally accepted case and I can live with that. However in code I was testing it wasn't applying that rule. I'll have to dig deeper and find a reproducible case.

**Comment by nicklockwood** [comment]
@nallick please do. Even if you can't narrow it down, feel free to send me the whole file and I'll trace the cause.

**Comment by nallick** [comment]
I found the cause of my problem. Apparently the colon here is treated as an operator. I was using the option: --disable spaceAroundOperators and that prevents changes around the colon in type specifications and dictionaries. I sometimes emphasize precedence by writing things like a = b*2 + 1, which is why I had that option disabled. IMO the colon in this context isn't an operator.

**Comment by nicklockwood** [comment]
@nallick ah thanks, that makes sense. It's not a bug - SwiftFormat doesn't actually think the colon is an operator, but I should possibly split up that rule, or at least allow separate configuration for operators and other delimiters.

**Comment by nallick** [comment]
That would make sense to me. Thanks for your time.

**Comment by nicklockwood** [comment]
@nallick in 0.43.2 I've added a `--nospaceoperators` option which should solve your issue.
