### ISSUE TITLE
Bug: Problems with --operatorfunc spaced

### ISSUE THREAD

**Issue by DavinAhn** [nicklockwood/SwiftFormat#410]
**Steps to reproduce:**
In an empty directory add Test.swift with:
```
protocol TestProtocol {}
class TestArray<Element> {}
let value = (TestArray<Int> & TestProtocol).self
```

From the same directory run:
`swiftformat --operatorfunc spaced ./Test.swift`

**Expected results:**
```
protocol TestProtocol {}
class TestArray<Element> {}
let value = (TestArray<Int> & TestProtocol).self
```

**Actual results:**
```
protocol TestProtocol {}
class TestArray<Element> {}
let value = (TestArray < Int> & TestProtocol).self
```

**Notes:**
There was no problem with 0.40.1, but occur this problem after updating to 0.40.5.

**Comment by nicklockwood** [comment]
@DavinAhn thanks for reporting, I'll get this fixed asap.

**Comment by nicklockwood** [comment]
@DavinAhn fixed in 0.40.6

**Comment by DavinAhn** [comment]
Dear @nicklockwood.
Thank you very much for your quick fix.
But, 0.40.6 was not updated on [brew](https://formulae.brew.sh/formula/swiftformat#default) 😭

**Comment by nicklockwood** [comment]
@DavinAhn it should be soon. Homebrew updates have to be manually approved by their team - here's the PR: https://github.com/Homebrew/homebrew-core/pull/38819
