### ISSUE TITLE
Split wrapArguments to separate function declaration and implementation 

### ISSUE THREAD

**Issue by ismetanin** [nicklockwood/SwiftFormat#421]
Hi! 
There was #198 about the same problem but, for the author, it fixed with `--closingparen` option.

I'd like to use `after-first` for function declaration
```swift
func foo(bar: String,
         baz: String) -> Bool {
    return true
}
```

But at the same time, I'd like to use `before-first` for function implementation
```swift
let result = foo(
    bar: "bar",
    baz: "baz"
)
```

**Comment by AnthonyMDev** [comment]
Yes, I agree! Though #198 was resolved for the use case of the author, it didn't actually resolve this feature request, and I'd really love to have this also. @nicklockwood, is there any chance we could get this implemented with separate configurations for function declarations and calling functions?

**Comment by AnthonyMDev** [comment]
To be clear, what I want in my config file is something like this:
```
--closingparen balanced
--wrapparameters before-first // This wraps parameters in the declaration of a function.
--wraparguments preserve // This preserves wrapping on passing arguments in when calling a function.
--wrapcollections before-first
```

**Comment by AnthonyMDev** [comment]
@nicklockwood  I'm working on a PR for this today. This is going to be a breaking change. 
I'm considering the API of this now. Would like your thoughts. 

I'm thinking of creating a new option `--wrapparameters` which would define the behavior currently used for `--wraparguments` on function declarations, and then `--wraparguments` would be used for all other argument lists. Does that make sense to you?

**Comment by nicklockwood** [comment]
@AnthonyMDev that does make sense, and it's the approach I would take. It should be possible to have `--wrapparameters` take the same value as `--wraparguments` if not specified, in which case it won't be much of a breaking change.

**Comment by AnthonyMDev** [comment]
I was thinking about doing that. I wasn't sure if you wanted it to take the default of `--wraparguments` or not, since while it doesn't break things that way, its not completely clear. 
I'll do that though then! :)

I'm almost done with the PR, so I'll get that part fixed and have it up for you in a bit.
