### ISSUE TITLE
Invalid self. added to enums associated values

### ISSUE THREAD

**Issue by diegolopezbugna** [nicklockwood/SwiftFormat#423]
Hi, great work with swiftformat! 

I was using 0.40.4 and it was ok, I upgraded to 0.40.8 and swiftformat adds some self. where it shouldn't: 

with siwftformat 0.40.4:
```
    func setup(for rowType: MPPChargeFeedbackRowType) {
        if case let MPPChargeFeedbackRowType.continueButton(isEnabled, handler) = rowType {
            self.button?.isEnabled = isEnabled
            self.handler = handler
```

with swiftformat 0.40.8:
```
    func setup(for rowType: MPPChargeFeedbackRowType) {
        if case let MPPChargeFeedbackRowType.continueButton(isEnabled, self.handler) = rowType {
            self.button?.isEnabled = isEnabled
            self.handler = handler
```
...

**Comment by nicklockwood** [comment]
@diegolopezbugna thanks for reporting this, I'll get it fixed asap!

**Comment by nicklockwood** [comment]
@diegolopezbugna I wasn't able to reproduce the bug with the code sample you provided. Can you supply a code sample that reproduces the bug in isolation?

**Comment by diegolopezbugna** [comment]
Ok, I tried to make a test that fails but couln't. In the test it works as expected. 
My format flags are:
--allman false
--commas inline
--comments ignore
--empty void
--exponentcase lowercase
--header ignore
--ifdef indent
--indent 4
--indentcase false
--insertlines true
--patternlet hoist
--ranges nospace
--removelines enabled
--semicolons never
--self insert
--stripunusedargs always
--trimwhitespace always
--wrapelements beforefirst
Do you see something odd?

**Comment by nicklockwood** [comment]
@diegolopezbugna if you have a source file the reproduces the problem with those settings, I can narrow it down from there.

**Comment by nicklockwood** [comment]
Closing since I can't reproduce it. If you can provide a file or code snippet that demonstrates the problem, feel free to reopen.
