### ISSUE TITLE
removes "self" within closures

### ISSUE THREAD

**Issue by nayooti** [nicklockwood/SwiftFormat#427]

**Comment by nicklockwood** [comment]
Please include an example that demonstrates the problem.

**Comment by nayooti** [comment]
It just happens at line 7 (it happens always) :

self.passwordCell.textField.becomeFirstResponder()

For all my other files it works fine.

`extension AccountSetupController: UITextFieldDelegate {
  func textFieldShouldReturn(_ textField: UITextField) -> Bool {
    let currentTag = textField.tag

    if textField.accessibilityIdentifier == "emailTextField", showOAuthAlertIfNeeded(emailAddress: textField.text ?? "", handleCancel: {
      self.passwordCell.textField.becomeFirstResponder()
    }) {
      // all the action is defined in if condition
    } else {
      if let nextField = tableView.viewWithTag(currentTag + 1) as? UITextField {
        if nextField.tag > 1, !advancedSectionShowing {
          // gets here when trying to activate a collapsed cell
          return false
        }
        nextField.becomeFirstResponder()
      }
    }

    return false
  }
}`

**Comment by nicklockwood** [comment]
Fixed in version 0.40.9. Thanks for reporting!
