### ISSUE TITLE
This question is about Xcode build phase

### ISSUE THREAD

**Issue by xiebeijia** [nicklockwood/SwiftFormat#437]
**1.Installed in CocoaPods mode, the podfile file information is as follows**
```
platform :ios,’8.0’
target 'SwiftDemo05' do
pod 'SwiftFormat/CLI'
end
```
**2.The script information is as follows**
```
"${PODS_ROOT}/SwiftFormat/CommandLineTool/SwiftFormat"
"${SRCROOT}/SwiftDemo05/ViewController.swift"
```
**3.The first compilation error is reported as follows**
`/Users/tci/Library/Developer/Xcode/DerivedData/SwiftFormat_Demo-axgqyiomhscrdbclxpyoeztysxnm/Build/Intermediates.noindex/SwiftFormat_Demo.build/Debug-iphonesimulator/SwiftFormat_Demo.build/Script-73828924228A6D1500005BD3.sh: line 3: /Users/tci/Desktop/西贝/xibei_workspace/SwiftFormat_Demo/SwiftFormat_Demo/ViewController.swift: Permission denied`
**4.The solutions are as follows**
`sudo chmod -R 777 /Users/tci/Desktop/西贝/xibei_workspace/SwiftFormat_Demo`
**5.Second compilation error**
```
/Users/tci/Desktop/西贝/xibei_workspace/SwiftFormat_Demo/SwiftFormat_Demo/ViewController.swift: line 1: //: is a directory
/Users/tci/Desktop/西贝/xibei_workspace/SwiftFormat_Demo/SwiftFormat_Demo/ViewController.swift: line 2: //: is a directory
/Users/tci/Desktop/西贝/xibei_workspace/SwiftFormat_Demo/SwiftFormat_Demo/ViewController.swift: line 3: //: is a directory
/Users/tci/Desktop/西贝/xibei_workspace/SwiftFormat_Demo/SwiftFormat_Demo/ViewController.swift: line 4: //: is a directory
/Users/tci/Desktop/西贝/xibei_workspace/SwiftFormat_Demo/SwiftFormat_Demo/ViewController.swift: line 5: //: is a directory
/Users/tci/Desktop/西贝/xibei_workspace/SwiftFormat_Demo/SwiftFormat_Demo/ViewController.swift: line 6: //: is a directory
/Users/tci/Desktop/西贝/xibei_workspace/SwiftFormat_Demo/SwiftFormat_Demo/ViewController.swift: line 7: //: is a directory
/Users/tci/Desktop/西贝/xibei_workspace/SwiftFormat_Demo/SwiftFormat_Demo/ViewController.swift: line 9: import: command not found
/Users/tci/Desktop/西贝/xibei_workspace/SwiftFormat_Demo/SwiftFormat_Demo/ViewController.swift: line 11: class: command not found
/Users/tci/Desktop/西贝/xibei_workspace/SwiftFormat_Demo/SwiftFormat_Demo/ViewController.swift: line 13: syntax error near unexpected token `('
/Users/tci/Desktop/西贝/xibei_workspace/SwiftFormat_Demo/SwiftFormat_Demo/ViewController.swift: line 13: `    override func viewDidLoad() {'
Command /bin/sh failed with exit code 2
```
**How to solve this **problem?**
Remarks：swift 4.0    Xcode 9.2    Mac 10.13.1

**Comment by xiebeijia** [comment]
![question](https://user-images.githubusercontent.com/35449079/57672942-ccf96800-764c-11e9-8181-6b1112845e74.png)

**Comment by nicklockwood** [comment]
I'm not sure what the cause is, but I don't have the means to test on a setup this old anymore. I suggest you use a prebuilt SwiftFormat binary and just copy it into your project manually instead of using CocoaPods integration.
