### ISSUE TITLE
Space after @escaping

### ISSUE THREAD

**Issue by karolus** [nicklockwood/SwiftFormat#44]
Currently `SwiftFormat` is removing space between `@escaping` and closure type, so instead of `@escaping (String) -> Void` it end up as `@escaping(String) -> Void`. Is it intentional behaviour? For me it looks strange - like `@escaping` only applies to arguments of the closure, instead of whole closure type. Of course it doesn't make sense for someone who knows Swift, but still - formatting, at the first sight, might be confusing.

**Comment by nicklockwood** [comment]
Fixed in 0.12.1
