### ISSUE TITLE
'Swiftformat for Xcode' doesn't install into Xcode via Mac OS 10.15Beta

### ISSUE THREAD

**Issue by UncleRic** [nicklockwood/SwiftFormat#447]
I'm trying to install Swiftformat into my Xcode (v 10.2.1+) as I've done with OS v 10.14.

Mac OS 10.15 <apparently> doesn't allow Swiftformat to enter the Extensions after launching the 'Swiftformat for Xcode' application.

And hence, can't get Swiftformat installed into my Xcode.

**Comment by nicklockwood** [comment]
@UncleRic I'm not running the beta yet so I can't verify. Do other extensions work? Have you tried rebuilding the extension locally from source?
