### ISSUE TITLE
Broken result

### ISSUE THREAD

**Issue by smic** [nicklockwood/SwiftFormat#451]
SwiftFormat creates a wrong result which cannot be compiled

From
`precondition(0.0 <= (u + accuracy) && (u - accuracy) <= 1.0)`
to
`precondition((>= 0.0u + accuracy) && (u - accuracy) <= 1.0)`

[SwiftFormatProblem.swift.zip](https://github.com/nicklockwood/SwiftFormat/files/3314979/SwiftFormatProblem.swift.zip)

**Comment by nicklockwood** [comment]
@smic thanks for reporting. It looks like a bug in the `yodaConditions` rule - you can fix it for now by adding this comment to the line above:

```swift
// swiftformat:disable:next yodaConditions
```

**Comment by nicklockwood** [comment]
@smic fixed in 0.40.10.
