### ISSUE TITLE
Rule timed out when running large parallel builds.

### ISSUE THREAD

**Issue by szweier** [nicklockwood/SwiftFormat#454]
When building a scheme with a large number of targets and `Parallelize Build` enabled, rules will sporadically time out. https://github.com/nicklockwood/SwiftFormat/blob/master/Sources/SwiftFormat.swift#L418 

The issue seemed to resolve itself when adding the `--verbose` flag. I believe the reason for this is that turning verbose on turns concurrency off https://github.com/nicklockwood/SwiftFormat/blob/master/Sources/CommandLine.swift#L703. 

I'm not sure if you have thoughts as to what can be done to help determine a better time out for situations such as these or if you can provide a flag to either opt in/out of the rule timeout or adjust the timeout.

**Comment by nicklockwood** [comment]
@szweier are you still experiencing this issue on the latest version?

**Comment by oonoo** [comment]
I have the same issue and it seems the same solution to turn off concurrency by using --verbose solves it for me. I use version 0.44.10.
