### ISSUE TITLE
Swift 5.1: Generic Function Builders trigger rule spaceAroundOperators

### ISSUE THREAD

**Issue by bscothern-Cricut** [nicklockwood/SwiftFormat#457]
If you create a Function Builder in Swift 5.1 that is generic then the `spaceAroundOperators` rule causes the builder to be formatted as:

`@SomeFunctionBuilder <AnotherType>` 

rather than staying the expected:

`@SomeFunctionBuilder<AnotherType>`

 when working with a generic type and having the rule: `spaceAroundGenerics` enabled.

**Comment by nicklockwood** [comment]
I'm having trouble reproducing this bug. Do you have a code sample I can use to reproduce the issue?

**Comment by ageevvalentin** [comment]
I have the same issue.

before format:
```
@Wrapper<(@escaping () -> Bool) -> Void>
var value
```
after format:
```
@Wrapper <(@escaping () -> Bool) -> Void>
var value
```
Wrapper code:
```
@propertyWrapper
struct Wrapper<T> {
    var wrappedValue: T!
}
```
