### ISSUE TITLE
redundantParens rule broke generics which has parentheses as a generic param

### ISSUE THREAD

**Issue by fantast1k** [nicklockwood/SwiftFormat#459]
Hi there!

Just started using that tool, and found it very useful. But applying that rule to the following line of string (which is fully valid):
`private let _chargeableSection: TableViewSection<P2PChargeableView.ContentData, P2PChargeableView.ContentData, (), (), (), ()>!`
produces an invalid result like that
`private let _chargeableSection: TableViewSection<P2PChargeableView.ContentData, P2PChargeableView.ContentData,,,, ()>!`

**Comment by nicklockwood** [comment]
Fixed in 0.40.11. Thanks for reporting!
