### ISSUE TITLE
Is preprocessing CLI arguments really necessary?

### ISSUE THREAD

**Issue by ole** [nicklockwood/SwiftFormat#46]
I just read your blog posts about SwiftFormat. Great writeup!

[In part 3](http://bytes.schibsted.com/swiftformat-part-3/), I was surprised to read about the hoops you had to jump through to preprocess command-line arguments to deal with filenames with spaces or escaped quotes. The shell should handle this for you, shouldn't it?

Consider this tiny test program that simply prints the arguments it received:

```swift
// cli.swift
print("argc: \(CommandLine.argc)")
print("arguments: \(CommandLine.arguments)")
```

This handles everything I threw at it in a short test correctly because the shell already passes the correct array to the process:

```bash
$ swiftc cli.swift
$ ./cli someFile.txt
argc: 2
arguments: ["./cli", "someFile.txt"]

$ ./cli file\ with\ spaces.txt
argc: 2
arguments: ["./cli", "file with spaces.txt"]

$ ./cli "file with spaces.txt"
argc: 2
arguments: ["./cli", "file with spaces.txt"]

$ ./cli "file \"with\" quotes.txt"
argc: 2
arguments: ["./cli", "file \"with\" quotes.txt"]

# If you omit the quotes, you get separate strings (as expected)
$ ./cli file with spaces.txt
argc: 4
arguments: ["./cli", "file", "with", "spaces.txt"]
```

I think it's possible the behavior is different if you start the process differently (i.e. not from a shell), but I'm not sure. I'd be interested in hearing how you tested this, i.e. in what situation did you encounter the behavior you describe in the blog post?

Thanks!

**Comment by nicklockwood** [comment]
Heh, I did think it was strange that this was necessary. It's entirely possible that I simply messed up in early testing and jumped to the wrong conclusion.

**Comment by nicklockwood** [comment]
Yeah, this wasn't necessary. Thanks for the heads up!
