### ISSUE TITLE
header option should not remove swift version statement in Package.swift files

### ISSUE THREAD

**Issue by trispo** [nicklockwood/SwiftFormat#463]
The header option replaces the header completely which does not work in Package.swift file as  the compiler needs the swift version statement on the first line.

It would be ideal if the header option would remain the first line of Package.swift and append the header string.

**Comment by nicklockwood** [comment]
It probably makes sense to just exclude Package.swift from formatting doesn't it? Or maybe just exclude it for the file header rule specifically.

**Comment by trispo** [comment]
Well, I could imagine cases where the file header is necessary but for me it would be sufficient to exclude the file from the header rule.

**Comment by nicklockwood** [comment]
@trispo fixed in 0.40.14.
