### ISSUE TITLE
Options for blanklinesaroundmark

### ISSUE THREAD

**Issue by dmiluski** [nicklockwood/SwiftFormat#464]
Given Rule `blanklinesaroundmark`
https://github.com/nicklockwood/SwiftFormat/blob/master/Rules.md#blanklinesaroundmark

I have a preference for 2 lines above // MARK: and 1 line below to help boost readability of each section.

Request:
Provide options for rule blanklinesaroundmark

Options {
   -default: 1 line above, 1 line below
   -spacious: 2 lines above, 1 line below
}

I'm going to start reading through rule/options for a better understanding, but seeing if this would be useful to other parties of created? If here are any hints on where to start if I am to file a PR shortly if there is a prior model to use as precedence that could be useful here?

Questions:
1. Option names?
2. Implementation details

**Comment by lordzsolt** [comment]
I would also like to have this option.

I went ahead and implemented it as well. After a few hours of that, I realised it interferes with the `consecutiveBlankLines` rule.
And there seems to be no precedence of setting up logic _between_ rules.

Technically you could make one of them run before the other one, but that is fragile.

**Comment by ullstrm** [comment]
This is a rule we would very much like to have in place!
