### ISSUE TITLE
Feature Request: redundantType

### ISSUE THREAD

**Issue by wangchou** [nicklockwood/SwiftFormat#469]
Remove redundant types
from
```Swift
let rect: CGRect = CGRect(...)
```
to
```Swift
let rect = CGRect(...)
```

If the name of `Type` and `Initializer` is the same, remove the type declaration.

**Comment by facumenzella** [comment]
Is anyone working on this? I have some time to work on it ...

**Comment by nicklockwood** [comment]
@facumenzella nobody's working on it - go for it!

**Comment by nicklockwood** [comment]
@wangchou implemented in 0.46.0.
