### ISSUE TITLE
Change indent rule: Keep indentation level of empty lines as the context around

### ISSUE THREAD

**Issue by EmilioPelaez** [nicklockwood/SwiftFormat#47]
Right now, if you have:
```
class MyClass {
  func myFunc(){ }
EMPTY LINE
  func other() {}
}
```
EMPTY LINE won't be indented, keeping them indented is Xcode's default and practical, in my opinion, since you don't have to indent when you want to use that line.

I don't suggest that the default behavior is changed, but I'd like to make it an option. I tried to modify the `indent` rule to allow that but was not successful, I would appreciate some guidance.

**Comment by nicklockwood** [comment]
Use `--trimwhitespace nonblank-lines` to disable this in the 0.15 command-line app. If you use the Xcode Extension, it will infer the setting from your file.
