### ISSUE TITLE
Unknown option --xcodeindentation 

### ISSUE THREAD

**Issue by Morniak** [nicklockwood/SwiftFormat#474]
Hi,

Adding `--xcodeindentation enabled` to the `.swiftformat` file get me the following error: 

```
Running SwiftFormat...
warning: No swift version was specified, so some formatting features were disabled. Specify the version of swift you are using with the --swiftversion command line option, or by adding a .swift-version file to your project.
warning: Unknown option --xcodeindentation in configuration file.
error: Failed to format any files.
```

(I have a .swiftversion file and if y remove the `--xcodeindentation enabled` line, everything is working fine again).

Here is my full `.swiftformat`:

```
--exclude Pods
--disable andOperator, redundantRawValues
--enable isEmpty
--xcodeindentation enabled
```

**Comment by nicklockwood** [comment]
@Morniak this works correctly for me. Perhaps you're running an older version? Try

```
swiftformat  --version
```

and check that it prints 0.40.11.

**Comment by Morniak** [comment]
Hi @nicklockwood, I retried today and everything is working as it should. I don't know what was the issue but it doesn't really matter now. Thank for your help.
