### ISSUE TITLE
Customizable SwiftFormat rules

### ISSUE THREAD

**Issue by mergesort** [nicklockwood/SwiftFormat#48]
I was hoping for a mechanism to customize or disable the rules, outside of building a custom binary.

Currently I remove the `blankLinesAtEndOfScope` rule, because I like to end structs/classes/enums with a blank line, and make sure manually to not do the same for functions. If that was customizable, that would be great, otherwise I'd like to be able to just disable the rule.

This tool is great though, thanks a lot!

**Comment by nicklockwood** [comment]
If you use `--removelines false` in version 0.15 that should solve your problem. If you use the Xcode Extension, it's now off by default.

**Comment by mergesort** [comment]
Thank you. ❤️
