### ISSUE TITLE
Feature Request: print filenames in lint mode

### ISSUE THREAD

**Issue by dlindenkreuz** [nicklockwood/SwiftFormat#481]
This is the current output of running SwiftFormat with `--lint`:

> Running SwiftFormat...
(lint mode - no files will be changed.)
SwiftFormat completed in 0.22s.
Source input did not pass lint check.
6/172 files require formatting.

It would be handy to get the filenames printed as well.

**Comment by nicklockwood** [comment]
Try adding the `--verbose` argument as well.

**Comment by dlindenkreuz** [comment]
True dat. This works, but not as well as it could — verbose mode lists all files that are eligible for formatting and in large projects, finding a culprit that makes the lint fail means scrolling (or grepping) the entire output.

Having only misformatted files printed would be a great time saver here.

**Comment by nicklockwood** [comment]
@dlindenkreuz as of version 0.43.0, lint mode now prints every line that requires changes by default. This isn't exactly what you asked for, but it's consistent with how SwiftLint behaves, and is the most useful form of feedback when running inside Xcode.

I'll consider this closed, but feel free to reopen it if you feel that a separate files-only mode is still warranted.
