### ISSUE TITLE
Swift 5.1 compiler crash

### ISSUE THREAD

**Issue by yonaskolb** [nicklockwood/SwiftFormat#482]
SwiftFormat seems to be crashing the Swift compiler in Xcode 11 GM seed 2

**Comment by satishbabariya** [comment]
same here on Linux with swift 5.1 snapshots.

**Comment by nicklockwood** [comment]
Thanks for reporting. Fixed in 0.40.12.

**Comment by yonaskolb** [comment]
Thanks for fixing! :)
