### ISSUE TITLE
Problem with andOperator in ViewBuilder in SwiftUI

### ISSUE THREAD

**Issue by kimbauters** [nicklockwood/SwiftFormat#484]
This is a problem related to formatting of SwiftUI code, and was tested against version 0.40.12. The problem has to do with rule `andOperator`. The minimal example I have that causes the problem is as follows:

````swift
struct CustomView<Content>: View where Content: View {
    private let content: Content
    
    @inlinable init(@ViewBuilder content: () -> Content) {
        self.content = content()
    }
    
    var body: some View {
        Group {
            content
        }
    }
}

struct Problem: View {
    @State private var value = 5
    @State private var passed = true
    
    var body: some View {
        CustomView {
            if value == 5 && passed {
                Text("Great")
            } else {
                Text("Try Again")
            }
        }
    }
}
````
This is a simple struct that uses a custom view with a ViewBuilder. The problem occurs when the `andOperator` rule changes the line `if value == 5 && passed {` to `if value == 5, passed {` which causes the error
`Closure containing control flow statement cannot be used with function builder 'ViewBuilder'`

I'm not quite sure why it happens but I personally only use the comma notation in expressions such as `if let unwrapped = value, someRequirement`, i.e. I use it when I assign a value to a variable — something that is not allowed in SwiftUI. The restriction imposed in SwiftUI would appear to be too strong, but that entirely depends on how the comma notation is implemented in Swift. 

That being said, as it stands, using the `andOperator` rule can and does cause code to become corrupt.

**Comment by nicklockwood** [comment]
@kimbauters fixed in 0.40.14, thanks for reporting it 👍

**Comment by paxos** [comment]
I see the same in `0.43.1`:

`if(self.showFull && self.showBackground){`
gets transformed into
`if self.showFull, self.showBackground {`

causing an error in Xcode:
`
/file.swift:37:13: Closure containing control flow statement cannot be used with function builder 'ViewBuilder'
`

**Comment by paxos** [comment]
https://github.com/nicklockwood/SwiftFormat/issues/517

**Comment by nicklockwood** [comment]
@paxos can you share the surrounding code context is as well? The workaround I added depends on detecting that the if statement is inside a function builder, so your code must look a bit different from the cases I've seen so far.

**Comment by paxos** [comment]
https://github.com/AppPear/ChartView/blob/master/Sources/SwiftUICharts/LineChart/Line.swift#L34
