### ISSUE TITLE
Prevent users from doing stupid things

### ISSUE THREAD

**Issue by ronyeh** [nicklockwood/SwiftFormat#485]
I just saw this in your README.

**WARNING: `swiftformat .` will overwrite any Swift files it finds in the current directory, and any subfolders therein. If you run it in your home directory, it will probably reformat every Swift file on your hard drive.**

It seems like this is a very important warning, and should be highlighted up top, in **bold red colors**. 

Is there a good way to warn a new user of this when typing `swiftformat` for the first time on the command line?

**Comment by AlexisQapa** [comment]
just my two cents, maybe requiring a flag to run if the directory isn't in a git repo.

**Comment by ronyeh** [comment]
Or like other formatting tools, look for a ini file (e.g.  .swiftformatrc)
or .git/ or .hg/. If none exist, throw some big warnings and ask for a
--force flag before proceeding.

**Comment by nicklockwood** [comment]
Just typing `swiftformat` on its own won't format anything, you have to include a valid path (`.` being the path to the current directory). I think it's unlikely a user would type that by accident.

**Comment by ronyeh** [comment]
Let me just say that stupid developers like myself who are working late at
night at around 4am.... sometimes quickly open terminals and run programs
to see if they were installed correctly via homebrew.

I was a single *dot* away from reformatting all the *.swift files under my
macOS home dir. I have learned my lesson. But I want to save other dumb
developers from doing something not easily recoverable.

Thanks for considering additional safeguards to your otherwise useful tool!

Ron

**Comment by ronyeh** [comment]
One last comment:

Since `swiftformat` is a command line tool, I would expect it to behave similarly to other unix-y and macOS-y command line tools.

When I type `rm *.txt` I expect it to delete all the txt files in the current directory, but not subdirectories. I need to add an extra flag for that.

A similar tool in your space is `gofmt` which is actually recursive! However, since it is a unix-y tool, by default it operates on stdin and outputs to stdout. So even if you accidentally run it on your home directory, it will only output formatted golang files.

You need to add a `-w` flag to `gofmt` to have it overwrite the source files. So like the `rm` command, `gofmt` hides the most dangerous maneuver behind an extra flag.

**Comment by nicklockwood** [comment]
I don't see any way I can change this without breaking a lot of existing workflows, and I'm not convinced that the problem is all that serious in practice. I you have further ideas or arguments, feel free to reopen.
