### ISSUE TITLE
Xcode source editor extension not visible in System Preferences - Extensions

### ISSUE THREAD

**Issue by rudifa** [nicklockwood/SwiftFormat#494]
I have used swiftformat successfully since mid-2018, mainly via Editor Extension in Xcode.

However, after installing **macOS 10.15** and **Xcode 11.1** the Extension menu items (Format Entire File, Format Selected Source) disappeared from the Xcode Editor menu.

I pulled the project from `https://github.com/nicklockwood/SwiftFormat.git` and ran `SwiftFormat for Xcode.app`, then looked into `System Preferences - Extensions`, but I found no trace of Xcode extensions or swiftformat therein.

Next, I built and run the scheme `SwiftFormat for Xcode`. The app dialog popped up, but again there was no new entry in `System Preferences - Extensions`.

Am I missing something?
Any advice on how to proceed? 
Is there a log file that would indicate the problem?

**Comment by rudifa** [comment]
**OK, I found a solution to my problem.**

 The article [Xcode​Kit and Xcode Source Editor Extensions](https://nshipster.com/xcode-source-extensions/) by Zoë Smith, March 25th, 2019, says:

_Finally, when multiple copies of Xcode are on the same machine, extensions can stop working completely. In this case, Apple Developer Relations suggests re-registering your main copy of Xcode with Launch Services (it’s easiest to temporarily add lsregister’s location to PATH first):_

```
$ PATH=/System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support:"$PATH"
$ lsregister -f /Applications/Xcode.app
```
Indeed, before installing Xcode 11.0, I kept the previous app, renamed to Xcode1030.app.

I ran above commands, and lo, the the swiftformat extension is now in seen in Extensions, enabled.
And in Xcode, the `Editor - SwiftFormat` menu items are at their usual place, together with my shortcut `^s` for `Format Entire File`.

<img width="780" alt="Screenshot 2019-10-28 at 19 58 31" src="https://user-images.githubusercontent.com/172404/67709216-caea5200-f9bd-11e9-8fd7-66f891da0a7f.png">

**Comment by nicklockwood** [comment]
Makes sense, thanks for following up 👍

**Comment by limuyang2** [comment]
nice

> **OK, I found a solution to my problem.**
> 
> The article [Xcode​Kit and Xcode Source Editor Extensions](https://nshipster.com/xcode-source-extensions/) by Zoë Smith, March 25th, 2019, says:
> 
> _Finally, when multiple copies of Xcode are on the same machine, extensions can stop working completely. In this case, Apple Developer Relations suggests re-registering your main copy of Xcode with Launch Services (it’s easiest to temporarily add lsregister’s location to PATH first):_
> 
> ```
> $ PATH=/System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support:"$PATH"
> $ lsregister -f /Applications/Xcode.app
> ```
> 
> Indeed, before installing Xcode 11.0, I kept the previous app, renamed to Xcode1030.app.
> 
> I ran above commands, and lo, the swiftformat extension is now in seen in Extensions, enabled.
> And in Xcode, the `Editor - SwiftFormat` menu items are at their usual place, together with my shortcut `^s` for `Format Entire File`.
> 
> <img alt="Screenshot 2019-10-28 at 19 58 31" width="780" src="https://user-images.githubusercontent.com/172404/67709216-caea5200-f9bd-11e9-8fd7-66f891da0a7f.png">

nice，thanks

**Comment by klaas** [comment]
Great tipp! This should be included in the FAQ / Known Issues section!

Every once in a while the "SwiftFormat" menu gets missing in my Xcode installation and this helps!

**Comment by drewolbrich** [comment]
> **OK, I found a solution to my problem.**
> 
> The article [Xcode​Kit and Xcode Source Editor Extensions](https://nshipster.com/xcode-source-extensions/) by Zoë Smith, March 25th, 2019, says:

Thank you for posting this.

**Comment by erdemildiz** [comment]
Its worked @limuyang2 🎉

```
$ PATH=/System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support:"$PATH"
$ lsregister -f /Applications/Xcode.app
```

**Comment by MagnoUrbano** [comment]
not working for me, unfortunately.

**Comment by dagronf** [comment]
I noticed with Xcode 14 that once I upgraded using the brew cask method I could not get it to re-appear in Xcode 14. However, if I downloaded and installed the application from the releases tab it reappeared.

May be of use (at least to myself when I come looking for this again in a year or so's time :-) )

**Comment by pupubird** [comment]
In my case is that, once you done with brew install, go to "Applications > SwiftFormat for Xcode" and simply double click to open it

**Comment by bdube** [comment]
> I noticed with Xcode 14 that once I upgraded using the brew cask method I could not get it to re-appear in Xcode 14. However, if I downloaded and installed the application from the releases tab it reappeared.
> 
> May be of use (at least to myself when I come looking for this again in a year or so's time :-) )

Thank you. This worked for me too.

Xcode 15.2
Sonoma 14.3
SwiftFormat 0.53.1 from GitHub releases

Opened `/Applications/SwiftFormat for Xcode.app` and then enabled extension in `System Settings -> Privacy & Security -> Others, Extensions -> Xcode Source Editor -> ☑️ SwiftFormat`

**Comment by houmie** [comment]
Installing it via Brew cask no longer works.  Download the zip from release and install it directly.

**Comment by Scvairy** [comment]
> Installing it via Brew cask no longer works. Download the zip from release and install it directly.

Yep, it didn't show up in Xcode Extensions until I installed it directly from release.

In Sequoia it is now in System Settings → General → Login Items & Extensions → Xcode Source Editor

**Comment by rcoundon** [comment]
I found I needed to add the Swiftformat for Xcode.app to the Open at Login. Then scroll all the way to the bottom of the Login Items and Extensions dialog and click the (i) button here: 

<img width="473" alt="Image" src="https://github.com/user-attachments/assets/9645c8c3-06e2-4bb0-ac5d-665ce8706ce0" />

Then switch it on

<img width="488" alt="Image" src="https://github.com/user-attachments/assets/8bae022e-0ed8-4bfd-8962-3388fb41aba7" />

Then, after restarting XCode, Swiftformat appears in the Editor menu at the bottom
