### ISSUE TITLE
Comment closer is deleted if multiline comments is between a class name and its body

### ISSUE THREAD

**Issue by taku0** [nicklockwood/SwiftFormat#496]
Given the following code,

```swift
class Foo /*
aaa
*/ {
}
```

`swiftformat --swiftversion 5.1 test.swift` results in the following output:

```swift
class Foo { /*
 }
```

Expected output:

```swift
class Foo {
  /*
   aaa
   */
}
```

or something reasonable.

**Comment by nicklockwood** [comment]
@taku0 fixed in 0.41.0. Thanks for reporting!
