### ISSUE TITLE
Problem with andOperator in SwiftUI

### ISSUE THREAD

**Issue by paxos** [nicklockwood/SwiftFormat#517]
I see this in `0.43.1` and Swift 5:

`if(self.showFull && self.showBackground){`
gets transformed into
`if self.showFull, self.showBackground {`

causing an error in Xcode:
`
/file.swift:37:13: Closure containing control flow statement cannot be used with function builder 'ViewBuilder'
`

**Comment by paxos** [comment]
Example code:
https://github.com/AppPear/ChartView/blob/master/Sources/SwiftUICharts/LineChart/Line.swift#L34

**Comment by nicklockwood** [comment]
@paxos thanks, I'll try to get this fixed asap. In the meantime, adding the following line just above the `if` should solve the problem:

```swift
// swiftformat:disable:next andOperator
```

**Comment by nicklockwood** [comment]
@paxos fixed in 0.43.2.

**Comment by paxos** [comment]
This is awesome, thank you so much!
