### ISSUE TITLE
“SwiftFormat for Xcode.app” can’t be opened because Apple cannot check it for malicious software.

### ISSUE THREAD

**Issue by rudifa** [nicklockwood/SwiftFormat#518]
On 1 Jan 2020 around noon UTC, @nicklockwood tweeted:
Can someone verify that the latest SwiftFormat for Xcode build works correctly on their machine?

I just downloaded the `SwiftFormat-master.zip` from github and tried to launch `SwiftFormat for Xcode.app ` 0.43.3.  **It failed to start.**

![image](https://user-images.githubusercontent.com/172404/71643402-8c249100-2cb9-11ea-846d-8ede4e1c8b0f.png)

**Comment by nicklockwood** [comment]
@rudifa Was this on Catalina? And was this after right-click open or just just double-click?

**Comment by nicklockwood** [comment]
@rudifa I've tried resigning and pushing the release again. See if it works better now.

**Comment by rudifa** [comment]
After a fresh download of SwiftFormat-master.zip, I tried to
launch SwiftFormat for Xcode.app, comes up with the same problem:

[image: image.png]
Just in case, also downloaded with safari - same problem

[image: image.png]

**Comment by rudifa** [comment]
UPDATE:
The workaround using *ctrl-click-on-app* lets me to open the app from the
dialog.
However, this is less than ideal.

rudifa
P.S. Happy New Year!

**Comment by nicklockwood** [comment]
@rudifa would you mind trying again with version 0.43.4? I've notarized the app, so it should hopefully work without issue this time.

**Comment by rudifa** [comment]
OK, *SwiftFormat for Xcode.app* 0.43.4 opens successfully (Catalina 10.15.2)
[image: image.png]
[image: image.png]

**Comment by nicklockwood** [comment]
👍
