### ISSUE TITLE
--nospaceoperators does not accept open range

### ISSUE THREAD

**Issue by proxi** [nicklockwood/SwiftFormat#519]
In 0.43.3, it is not possible to specify `..<` in `--nospaceoperators`:

`error: Unsupported --nospaceoperators value '..<'.`

**Comment by nicklockwood** [comment]
@proxi thanks, I'll fix that asap. In the meantime, `--ranges no-space` should still work even though it's deprecated.

**Comment by nicklockwood** [comment]
@proxi fixed in 0.43.4.
