### ISSUE TITLE
Inconsistent whitespace in multi-line, error: Failed to format any files on 2nd run.

### ISSUE THREAD

**Issue by Deco354** [nicklockwood/SwiftFormat#520]
I get a warning about inconsistent whitespace in multi-line string literals which will cause an error if I run swiftformat a 2nd time.

Version 0.43.3

![image](https://user-images.githubusercontent.com/18557720/71664301-639ba600-2d50-11ea-8ca3-7894fa99c7e5.png)

File with warnings
```swift
public enum JavaScriptProperty {
    // Injection for web page to identify if itself is running in an App. It is in the App if there is "kindredApp" property, otherwise not in the App.
    case applePay(isSupported: Bool, isConfigured: Bool)
    
    var script: WKUserScript {
        switch self {
            case .applePay(let isSupported, let isConfigured):
                let scriptString =  """
                window.kindredApp = {
                    applePay: {
                        isSupportedByDevice: \(isSupported),
                        isConfiguredOnDevice: \(isConfigured)
                    }
                }; // line 19
                """
                return WKUserScript(source: scriptString, injectionTime: .atDocumentStart, forMainFrameOnly: false)
        }
    }
}
```

Config file:

```
# Format Options
--swiftversion 5.1

# Excluded Directories
--exclude Carthage,Configs,tools

# Rules
--rules redundantBackticks,redundantBreak,redundantExtensionACL,redundantFileprivate,redundantGet,redundantInit,redundantLet,redundantLetError,redundantNilInit,redundantObjc,redundantParens,redundantPattern,redundantRawValues,redundantReturn,redundantSelf,redundantVoidReturnType
```

I've excluded the file for now which resolves this problem but figured I'd report it.
Oddly enough if I run without my config file I get more of these warnings but no error.
![image](https://user-images.githubusercontent.com/18557720/71664542-3ac7e080-2d51-11ea-9a21-3e7526b3e772.png)

**Comment by nicklockwood** [comment]
@Deco354 thanks, I'll take a look.

**Comment by nicklockwood** [comment]
@Deco354 fixed in 0.43.4.

**Comment by omaralbeik** [comment]
@nicklockwood Is this bug back in `v0.43.5` 🤔

**Comment by nicklockwood** [comment]
@omaralbeik as far as I can tell there are no warnings or errors when formatting the example file with the specified settings. If you are seeing something similar it may be a different bug with similar symptoms. Please post a sample file demonstrating the problem (preferably in a new issue).

**Comment by omaralbeik** [comment]
> @omaralbeik as far as I can tell there are no warnings or errors when formatting the example file with the specified settings. If you are seeing something similar it may be a different bug with similar symptoms. Please post a sample file demonstrating the problem (preferably in a new issue).

Sorry, it was a problem from our side, thanks!
