### ISSUE TITLE
Wrap maxWidth should respect wrapArguments

### ISSUE THREAD

**Issue by AnthonyMDev** [nicklockwood/SwiftFormat#524]
First off, thanks for the amazing library!

I have `--wraparguments before-first --maxwidth 100` in my config file. This line:

```swift
public func parse(result: GraphQLResult<GlobalKeywordSearchQuery.Data>) throws -> GlobalKeywordSearchQuery.Data.Organization.GlobalKeywordSearch {
```
gets formatted as:

```swift
public func parse(result: GraphQLResult<GlobalKeywordSearchQuery.Data>) throws -> GlobalKeywordSearchQuery
    .Data.Organization.GlobalKeywordSearch {
```
This is awkward to me. What I'd like is for this to respect the way that I've configured `--wraparguments`, so since I have that set to `before-first`, I'd think when the `func` declaration is longer than the max width, it would format it with my argument wrapping. 

### My proposal:
Even though there is only one argument, which would not normally wrap, if it is longer than `--maxwidth`, we still apply the `wrapArguments` rule to the single argument. So my formatted code would end up like this:

```swift
public func parse(
    result: GraphQLResult<GlobalKeywordSearchQuery.Data>
) throws -> GlobalKeywordSearchQuery.Data.Organization.GlobalKeywordSearch {
```

**Comment by AnthonyMDev** [comment]
I further noticed that if you haven't manually wrapped arguments at all, even with multiple arguments, this isn't respecting `wrapArguments`.

**Comment by nicklockwood** [comment]
@AnthonyMDev 

> I further noticed that if you haven't manually wrapped arguments at all, even with multiple arguments, this isn't respecting wrapArguments.

Can you clarify what you mean here - are you saying it doesn't wrap the arguments even if they exceed the specified line length? Do you have a sample file that demonstrates this?

**Comment by AnthonyMDev** [comment]
@nicklockwood 
I tested this by adding another parameter.

```swift
public func parse(result: GraphQLResult<GlobalKeywordSearchQuery.Data>, test: Bool = false) throws -> GlobalKeywordSearchQuery.Data.Organization.GlobalKeywordSearch {
```
gets formatted as:

```swift
public func parse(result: GraphQLResult<GlobalKeywordSearchQuery.Data>, test: Bool = false) throws -> GlobalKeywordSearchQuery
    .Data.Organization.GlobalKeywordSearch {
```

Rather than what I think it should be:

```swift
public func parse(result: GraphQLResult<GlobalKeywordSearchQuery.Data>,
    test: Bool = false
) throws -> GlobalKeywordSearchQuery.Data.Organization.GlobalKeywordSearch {
```

**Comment by nicklockwood** [comment]
@AnthonyMDev wrapArguments will only kick in if the arguments themselves extend beyond the maximum line length. As it is, this part:

```swift
public func parse(result: GraphQLResult<GlobalKeywordSearchQuery.Data>, test: Bool = false)
```

is only 91 characters wide. I can see an argument for why this *shouldn't* be the case, but it seems like it is working as intended at the moment.

**Comment by AnthonyMDev** [comment]
I see. Thanks for explaining!
I feel like that's not the correct behavior. If we have a max line length set, then it should be paying attention to the length of the entire line. 

Since the return statement brings it over the line length, we should then wrap the _arguments_ before the `wrap` kicks in and wraps the line (in the middle of the return type in this case).

**Comment by nicklockwood** [comment]
@AnthonyMDev I agree. It gets complicated if whatever else is at the end of the line has higher wrap-priority than the arguments though, since `wrapArguments` logic is processed first before general `wrap`.

E.g. in this case, the `{ ... }` should be wrapped in preference to arguments:

```swift
func foo(long: Int, arguments: String, list: Bool) -> Bool { but.the.inlineFunction.bodyShould.beWrappedFirst() }
```

I guess it would work if the heuristic only counted up as far as the `{` and if that was within the limit it would leave it to `wrap` to handle.

**Comment by AnthonyMDev** [comment]
Ahh that makes a lot of sense. Yes, the priority issue and `warpArguments` running before `wrap` has been a struggle with a few of the other things I've been working on also. 

I'm working on this, and I think that your proposed heuristic is pretty close, but perhaps it should be up until the next start of scope? Whether that scope is a `{` or a `(`. That should deal with return type that are tuples or a closure type.

**Comment by nicklockwood** [comment]
@AnthonyMDev I considered that, but I think it's usually preferable to wrap the function arguments than the return-type. I guess I can imagine cases where that wouldn't be true, though, e.g.

```swift
func foo(bar: Int) -> (a: Int, stupidly: Bool, long: String, tuple: Double) { ... }
```

It's possible I'll eventually need to make the heuristics more advanced, e.g. taking the relative lengths of argument lists into account when prioritising.

**Comment by AnthonyMDev** [comment]
After dealing with some more bugs and trying to improve the heuristic, I realized that this should only actually take the return type into account when the `wrap` rule is enabled. My next PR will address this.

**Comment by nicklockwood** [comment]
@AnthonyMDev ok. Note that I've also made some fixes which may overlap/conflict with yours. Be sure to pull the latest commit off the develop branch.

**Comment by AnthonyMDev** [comment]
thanks for the heads up. I'll rebase on your changes as well.

**Comment by AnthonyMDev** [comment]
@nicklockwood Ooof. I've made some pretty big refactors to the wrapping logic as well. I may have some really big issues merging here. 

After I finish my fixes off of MY last branch, I'm going to just pull your changes one at a time on top of mine, make sure that all of both of our behaviors still make sense and manually merge.

Might have a confusing code review...

**Comment by nicklockwood** [comment]
@AnthonyMDev I'm happy to help out with the rebase if you just want to push a PR with whatever you've got on master.

**Comment by AnthonyMDev** [comment]
Thanks! 
I mad a lot of progress tonight. Going to bed now, but I’ve got a few kinks to work out in my code and then I’ll hopefully have something for you. 

It should add a lot of flexibility to the heuristic, add some new functionality, and likely be more performant as well!
