### ISSUE TITLE
Indent incorrect with chaining function call

### ISSUE THREAD

**Issue by AnthonyMDev** [nicklockwood/SwiftFormat#525]
I'm not sure why, but the `indent` rule is changing the indentation on this chained function call. I don't think that should be happening.

I do have `--xcodeindentation enabled`.

```swift
  private lazy var mockPlistPath =
         Bundle(for: PlistDeploymentConfigManagerTests.self)
-            .path(forResource: "MockDeploymentConfigurations", ofType: "plist")!
```

```swift
   private lazy var mockPlistPath =
         Bundle(for: PlistDeploymentConfigManagerTests.self)
 +       .path(forResource: "MockDeploymentConfigurations", ofType: "plist")!
```
--- 
This is also occurring with chained use of `&&`. I've got `--disable andOperator` and `--disable redundantReturn`.

My code looks like this:

```swift
    public func == (lhs: DeploymentConfiguration, rhs: DeploymentConfiguration) -> Bool {
        return
            lhs.environmentName == rhs.environmentName &&
-                lhs.CLOUDINARY_NAMESPACE == rhs.CLOUDINARY_NAMESPACE &&
-                lhs.CLOUDINARY_NAME == rhs.CLOUDINARY_NAME &&
```
It's changed to this: 

```swift
    public func == (lhs: Foo, rhs: Foo) -> Bool {
        return
            lhs.environmentName == rhs.environmentName &&
+           lhs.CLOUDINARY_NAMESPACE == rhs.CLOUDINARY_NAMESPACE &&
+           lhs.CLOUDINARY_NAME == rhs.CLOUDINARY_NAME &&
```

With `--xcodeindentation enabled`, I think this shouldn't be happening, since that first version is the way xcode automatically indents this.

**Comment by nicklockwood** [comment]
@AnthonyMDev yes, this looks like a bug. Thanks for reporting it.

**Comment by AnthonyMDev** [comment]
Awesome. Looking forward to a fix. I have to `--disable indent` until then. :P

**Comment by AnthonyMDev** [comment]
I'm working on a fix for a few bugs I've found with wrapping/indent. I'll have a PR up for you tomorrow hopefully.
