### ISSUE TITLE
redundantSelf removes required self in capture when contained in if/guard let

### ISSUE THREAD

**Issue by ChristopherRogers** [nicklockwood/SwiftFormat#533]
The self in `self.myVar` below gets removed, but is required by the compiler. It gets removed in an if/guard let statement, but not if it's just a plain "if" statement.

Tested with 0.43.5.

```swift
if let cachedVar = fetchVar(completion: { [weak self] in
    guard let self = self else { return }
    _ = self.myVar
}) {
    print(cachedVar)
}
```

**Comment by nicklockwood** [comment]
@ChristopherRogers fixed in 0.44.0. Thanks!
