### ISSUE TITLE
Wrap should ignore color & image literals

### ISSUE THREAD

**Issue by AnthonyMDev** [nicklockwood/SwiftFormat#535]
`#colorLiteral` and `#imageLiteral` should not be wrapped. They don't display in Xcode as over the maxWidth and when they are wrapped they display buggy in Xcode.

**Comment by nicklockwood** [comment]
@AnthonyMDev do you have an example of code where this happens? AFAIK #imageLiteral and #colorLiteral only have one argument, so they should be wrapped anyway according to the current logic.

**Comment by AnthonyMDev** [comment]
```swift
public static let matchedGreen = #colorLiteral(red: 0.2392156863, green: 0.6470588235, blue: 0.3647058824, alpha: 1)
```

This gets wrapped to 
```swift
public static let matchedGreen = #colorLiteral(
    red: 0.2392156863,
    green: 0.6470588235,
    blue: 0.3647058824, 
    alpha: 1
)
```

And then it shows up all funky in Xcode.

**Comment by AnthonyMDev** [comment]
My colleague @javierrivarolaq said he would be interested in working on a PR to fix this for us.

**Comment by nicklockwood** [comment]
@AnthonyMDev ah I see, I didn't understand how it could happen with image literals as they only have one parameter AFAIK. For colors it makes more sense.

**Comment by AnthonyMDev** [comment]
I think it was still happening previously with `imageLiteral` when they were on a long line sometimes and the line would wrap. If I remember correctly, I think we might have fixed that by ensuring that functions with one parameter don't wrap? Not quite sure. I haven't tested it in a while. I can check again at some point soon, but I know it's happening with colors.

**Comment by javierrivarolaq** [comment]
I have a fix for the bug, will make a PR today.

**Comment by javierrivarolaq** [comment]
Here it is https://github.com/nicklockwood/SwiftFormat/pull/550
