### ISSUE TITLE
xcodeindentation should not indent second line of type declaration

### ISSUE THREAD

**Issue by AnthonyMDev** [nicklockwood/SwiftFormat#536]
To mirror the behavior of Xcode auto indentation, type declarations should not have an indent on their second line. Currently, if exceeding the maxWidth, the indent rule indents this:

```swift
class Foo<Bar, Baz>: Quux, Quuz where Bar == Corge {
    ...
}
```

to:

```swift
class Foo<Bar, Baz>: Quux, Quuz
    where Bar == Corge {
    ...
}
```

It should not indent the second line when `xcodeindentation == enabled`. It should look like this:
```swift
class Foo<Bar, Baz>: Quux, Quuz
where Bar == Corge {
    ...
}
```

**Comment by nicklockwood** [comment]
@AnthonyMDev fixed in 0.45.6. Sorry for the delay!
