### ISSUE TITLE
Corner case for spaceInsideComments

### ISSUE THREAD

**Issue by ChristopherRogers** [nicklockwood/SwiftFormat#537]
I think spaceInsideComments shouldn't be adding a trailing space to single-line documentation comments when the character directly after the third slash is another slash. Usually this happens when commenting out code. Any comments contained within it will usually get four consecutive slashes; this shouldn't be formatted to be documentation comments. (`////` would get formatted to `/// /`). Also I've seen some ASCII-art style comments like `/////////ATTENTION////////`. Likewise, a space gets added after the third slash.

**Comment by nicklockwood** [comment]
@ChristopherRogers agreed, this is a bug.

**Comment by nicklockwood** [comment]
@ChristopherRogers this was fixed in 0.44.1, but I forgot to mention it. Sorry!
