### ISSUE TITLE
Is this expected behavior of --nospaceoperators?

### ISSUE THREAD

**Issue by r-plus** [nicklockwood/SwiftFormat#539]
### tested file

```swift
0..<100
```

### executed command

```
$ swiftformat --version
0.44.0
$ swiftformat . --rules spaceAroundOperators --nospaceoperators --swiftversion 5
Running SwiftFormat...
SwiftFormat completed in 0.13s.
1/1 files formatted.
```

### result
```swift
0 ..< 100
```

I expected `--nospaceoperators` option will not add space around `..<` range operator.
Is this correct behavior of SwiftFormat?

**Comment by nicklockwood** [comment]
@r-plus try `--nospaceoperators "...,..<"`

**Comment by r-plus** [comment]
@nicklockwood oh! thanks a lot. I understood what i should specify to `--nospaceoperators` option.
