### ISSUE TITLE
Inline disable all still applies wrap and wrapArugements with --maxwidth

### ISSUE THREAD

**Issue by sfaxon** [nicklockwood/SwiftFormat#541]
I have some Paintcode generated files that I would rather swifformat leave alone, but using the inline option

    // swiftformat:disable all

does not seem to be honored with the `--maxwidth` parameter. 

    // swiftformat:disable all
    // consider everything in this code block to be `SwiftFormatDisableBug.swift`, very meta. 
    // running `swiftformat --verbose --swiftversion 5.1.3 --maxwidth 120 SwiftFormatDisableBug.swift`
    // will output:
    // Running SwiftFormat...
    // Formatting ./SwiftFormatDisableBug.swift
    // -- rules applied: wrap, wrapArguments
    // Writing ./SwiftFormatDisableBug.swift

    // SwiftFormat completed in 0.03s.
    // 1/1 files formatted.

    private func draw(frame: CGRect) {
        // General Declarations
        let context = UIGraphicsGetCurrentContext()!
        
        backgroundColor = UIColor.clear
        backgroundColor?.setFill()
        context.fill(frame)

        // Bezier Drawing
        let bezierPath = UIBezierPath()
        bezierPath.move(to: CGPoint(x: frame.minX + 0.49500 * frame.width, y: frame.minY + 0.03000 * frame.height))
        bezierPath.addCurve(to: CGPoint(x: frame.minX + 0.52169 * frame.width, y: frame.minY + 0.05639 * frame.height), controlPoint1: CGPoint(x: frame.minX + 0.50994 * frame.width, y: frame.minY + 0.03000 * frame.height), controlPoint2: CGPoint(x: frame.minX + 0.52169 * frame.width, y: frame.minY + 0.04161 * frame.height))
        bezierPath.addCurve(to: CGPoint(x: frame.minX + 0.49500 * frame.width, y: frame.minY + 0.08278 * frame.height), controlPoint1: CGPoint(x: frame.minX + 0.52169 * frame.width, y: frame.minY + 0.07117 * frame.height), controlPoint2: CGPoint(x: frame.minX + 0.50994 * frame.width, y: frame.minY + 0.08278 * frame.height))
        bezierPath.addCurve(to: CGPoint(x: frame.minX + 0.46831 * frame.width, y: frame.minY + 0.05639 * frame.height), controlPoint1: CGPoint(x: frame.minX + 0.48006 * frame.width, y: frame.minY + 0.08278 * frame.height), controlPoint2: CGPoint(x: frame.minX + 0.46831 * frame.width, y: frame.minY + 0.07117 * frame.height))
        bezierPath.addCurve(to: CGPoint(x: frame.minX + 0.49500 * frame.width, y: frame.minY + 0.03000 * frame.height), controlPoint1: CGPoint(x: frame.minX + 0.46831 * frame.width, y: frame.minY + 0.04161 * frame.height), controlPoint2: CGPoint(x: frame.minX + 0.48006 * frame.width, y: frame.minY + 0.03000 * frame.height))
        bezierPath.close()
        iconColor.setFill()
        bezierPath.fill()

        // Oval Drawing
        context.saveGState()
        context.translateBy(x: frame.minX + 0.50000 * frame.width, y: frame.minY + 0.50000 * frame.height)
        context.scaleBy(x: inset, y: inset)

        let ovalPath = UIBezierPath(ovalIn: CGRect(x: -(frame.width*0.5), y: -(frame.height*0.5), width: frame.width, height: frame.height))
        iconColor.setFill()
        ovalPath.fill()

        context.restoreGState()
    }

[SwiftFormatDisableBug.swift.txt](https://github.com/nicklockwood/SwiftFormat/files/4104870/SwiftFormatDisableBug.swift.txt)

This is using release 0.44.0. 

Changing the disable line to 

    // swiftformat:disable all maxwidth wrap wrapArguments

had no impact.

**Comment by nicklockwood** [comment]
@sfaxon thanks, I'll take a look. It probably makes more sense to exclude these files using the --exclude command-line option though, or by using a .swiftformat config file.

**Comment by sfaxon** [comment]
We're actually using some CI tasks to force the same swiftformat version and config down to our main applications as well as about 15 in house dependencies. `--exclude` would work, but unfortunately our "global" config would override it without changes to our tooling that might end up being pretty fragile.

`Swiftformat` is still a huge win without the `maxwidth` option, thanks to everyone involved in the project!

**Comment by nicklockwood** [comment]
@sfaxon this should now be fixed in 0.44.1.
