### ISSUE TITLE
Error:    #if(iOS) formatted into #ifiOS

### ISSUE THREAD

**Issue by timbms** [nicklockwood/SwiftFormat#545]
Hi, 
I am using swiftformat 0.44.0
It corrupts one file where I make use of `#if(iOS)`.
All instance are turned into         
`#ifiOS`
Can you please have a look

**Comment by nicklockwood** [comment]
@timbms thanks for reporting. It looks like this is caused by the `redundantParens` rule, so disabling that rule should be a workaround for now.

**Comment by timbms** [comment]
Confirmed: This workaround is effective. I was so far excluding the relevant file

**Comment by nicklockwood** [comment]
@timbms if that's the only place it happens, you can also fix it by just manually inserting a space after the #if - SwiftFormat won't remove it again.

**Comment by nicklockwood** [comment]
@timbms fixed in 0.44.1.
