### ISSUE TITLE
Fixes enum case spacing but not comment spacing

### ISSUE THREAD

**Issue by keith** [nicklockwood/SwiftFormat#548]
With version 0.44.1 if you have this code:

```swift
enum Foo {
   /// Bad spacing
   case wrongSpacing
}
```

Where there are 3 spaces before the case and comment, running `swiftformat foo.swift` produces:

```swift
enum Foo {
   /// Bad spacing
    case wrongSpacing
}
```

In this case I would expect it to fix the comment leading space as well?

**Comment by nicklockwood** [comment]
@keith fixed in 0.44.5 - thanks for reporting
