### ISSUE TITLE
Pre Commit script fails if the file has a folder with a spaces in it.

### ISSUE THREAD

**Issue by mike011** [nicklockwood/SwiftFormat#551]
With 0.44.1 after following the steps from [here](https://github.com/nicklockwood/SwiftFormat#git-pre-commit-hook), when I make a commit the following script is ran:

```
#!/bin/bash
git diff --diff-filter=d --staged --name-only | grep -e '\(.*\).swift$' | while read line; do
  ./SwiftFormat/format.sh "${line}";
  git add "$line";
done

exit $?
```
The formatting on a file with spaces fails with the following:

```
Running SwiftFormat...
error: File not found at /Users/michael.charland/git/App/Supporting.
```
The file that changed is  /Users/michael.charland/git/App/Supporting Files/Reachability.swift

If I run SwiftFormat on the parent directory Reachability.swift is formatted as expected.

**Comment by nicklockwood** [comment]
@mike011 I've updated the pre-commit hook instructions, and I think it should now work correctly with spaces - can you verify?
