### ISSUE TITLE
redundantReturn doesn't support functions and getters

### ISSUE THREAD

**Issue by subdan** [nicklockwood/SwiftFormat#557]
Hello @nicklockwood.

Could you add support for functions and getters for `redundantReturn` rule? It would be cool to get 3 options for this rule: closures, functions, getters.

Input:
```
var name: String {
    return "Nick"
}
func test() -> String {
    return "test"
}
```
Output:
```
var name: String {
    "Nick"
}
func test() -> String {
    "test"
}
```

**Comment by nicklockwood** [comment]
@subdan it's already supported, but you need to set SwiftFormat's `--swiftversion` to 5.1 or higher because that feature wasn't available on earlier versions of Swift.

**Comment by subdan** [comment]
Oops. Thanks!
