### ISSUE TITLE
Redundant self rule can break String extensions using methods from NSString extensions

### ISSUE THREAD

**Issue by marciniwanicki** [nicklockwood/SwiftFormat#558]
If user defines two custom extensions:

```swift
extension String {
    func first() -> Bool {
        self.second()
    }
}

extension String {
    func second() -> Bool {
        true
    }
}
```

`self` in `self.second()` call is redundant and SwiftFormat correctly removes it. However, when one of the extensions is targeting `String` type and uses a method defined in `NSString` extension:

```swift
extension String {
    func first() -> Bool {
        self.second()
    }
}

extension NSString {
    func second() -> Bool {
        true
    }
}
```
`self` **is required** (I do not know why.. but would love to understand this requirement better).

Same will happen if `String` extension is using one of Apple `NSString` extension methods like 

```swift
/// from UIKIt

extension NSString {

    @available(iOS 7.0, *)
    open func draw(with rect: CGRect, options: NSStringDrawingOptions = [], attributes: [NSAttributedString.Key : Any]? = nil, context: NSStringDrawingContext?)

    @available(iOS 7.0, *)
    open func boundingRect(with size: CGSize, options: NSStringDrawingOptions = [], attributes: [NSAttributedString.Key : Any]? = nil, context: NSStringDrawingContext?) -> CGRect
}
```

**Current behavior:**
The current version 0.44.2 removes `self` and can break the client code.

**Expected behavior:**
`self` is not removed from the call.

**Additional context:**
I struggle to find a consistent pattern when self [should/should not] be used.

```swift
extension Int {
    func first() -> Bool {
        second() // seems to be fine even without `self`
    }
}

extension NSInteger {
    func second() -> Bool {
        true
    }
}
```

Foundation:

```swift
extension IndexPath {
    func first() -> Bool {
        self.second() // does not compile even with `self`
    }
}

extension NSIndexPath {
    func second() -> Bool {
        true
    }
}
```

**Comment by nicklockwood** [comment]
@marciniwanicki I suspect the fact that the String/NSString case works even with `self` is a bug. Swift removed automatic conversion from NSString to String in version 3 IIRC. You should have to explicitly cast with `as`.

**Comment by nicklockwood** [comment]
@marciniwanicki as for the pattern, other than the `String`/`NSString` anomaly, the rule is that is types are the same (Int is the exact same type as NSInteger) then it should work with or without `self`, and if the types are not the same (IndexPath is a struct, NSIndexPath is a class - they are not automatically bridged) then it won't work even with `self`, but should work with `(self as IndexPath)`.

**Comment by marciniwanicki** [comment]
Thanks a lot @nicklockwood for the clarification. I submitted a feedback (FB7565234) and will post an update when I hear back.
