### ISSUE TITLE
Option to prefer a single space in emptyBraces

### ISSUE THREAD

**Issue by andrewjmeier** [nicklockwood/SwiftFormat#560]
I prefer to use `{ }` instead of `{}` but would like to use the emptyBraces rule to prevent empty braces containing new lines or more than one space. Can we add an option to this rule for that? 

I'm happy to make a PR for it.

**Comment by nicklockwood** [comment]
@andrewjmeier a PR would be great, thanks!

I'd propose adding an option called `--emptybraces` with values of `spaced` and `no-space` (default).

**Comment by nicklockwood** [comment]
@andrewjmeier added in 0.48.0
