### ISSUE TITLE
Add option for enforcing a specific style of multiline array/dictionary

### ISSUE THREAD

**Issue by bawjensen** [nicklockwood/SwiftFormat#566]
From what I can tell there are two main patterns for indenting multiline arrays and dictionaries:

```swift
// First - indent like any other block

let myArray = [
    element,
    element,
    element,
]
let myDictionary = [
    "key1": "value1",
    "key2": "value2",
    "key3": "value3",
]

// Second - align with opening bracket

let myArray = [element,
               element,
               element]
let myDictionary = ["key1": "value1",
                    "key2": "value2",
                    "key3": "value3"]
```

Would it be a reasonable feature request to add an option to enforce one or the other? For example in our project we'd prefer to enforce the first case in order to play more nicely with `trailingCommas` given we don't want something like `"key3": "value3",]`.

**Comment by nicklockwood** [comment]
@bawjensen using `--wrapcollections` before-first` should enforce the first style, and `--wrapcollections after-first` should enforce the second.

**Comment by bawjensen** [comment]
Damn, I thought I read the rules thoroughly before creating this but maybe not. I'll take a look at those two options

**Comment by bawjensen** [comment]
yep, that's what I was looking for. Thank you so much for the quick response!
