### ISSUE TITLE
addOperator not valid in config file

### ISSUE THREAD

**Issue by PaulD2012** [nicklockwood/SwiftFormat#571]
if I add --andOperator true to a config file I get the error

error: Unknown option --andOperator in configuration file.

**Comment by nicklockwood** [comment]
Try it in all lowercase: --andoperator

**Comment by PaulD2012** [comment]
Hi

The code is being read by C++ devs now and again. They find

if (x > 3) && (x < 7)

easier to read than

if x > 3, x < 7

So I’m trying to preserve the &&

I added  --andOperator true but may have misread the docs then

Cheers
Paul


On 27 Feb 2020, at 15:36, Nick Lockwood <notifications@github.com<mailto:notifications@github.com>> wrote:


Try it in all lowercase: --andoperator

Sorry, ignore that. andOperator is a rule, not an option. It's enabled by default though - what are you trying to do exactly?

**Comment by nicklockwood** [comment]
@PaulD2012 right, what you want to add in that case is:

```
--disable andOperator
```

**Comment by PaulD2012** [comment]
Thank you for the quick response


On 27 Feb 2020, at 18:25, Nick Lockwood <notifications@github.com<mailto:notifications@github.com>> wrote:


@PaulD2012<https://nam03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FPaulD2012&data=02%7C01%7Cpaul.delivett%40ivanti.com%7C218bc45b0fe9400c1c1908d7bbb2797b%7Ce5208e76dd1247f09541c9b45afaffe6%7C1%7C0%7C637184247531994726&sdata=mDJWtHk3PGOIew8eH6xAy352sakwQhVgBGdy%2FK6PbY8%3D&reserved=0> right, what you want to add in that case is:

--disable andOperator
