### ISSUE TITLE
Xcode generated availability check gets unnecessary whitespace

### ISSUE THREAD

**Issue by garnett** [nicklockwood/SwiftFormat#58]
was `if #available(iOS 9.0, *) {` // autosuggested and generated by Xcode when using unavailable APIs
 swiftformat 0.16.4: `if #available (iOS 9.0, *) {`

**Comment by mergesort** [comment]
This is also happening for `#imageLiteral` and `#colorLiteral` syntax which Apple introduced in Xcode 8.

`#imageLiteral(resourceName: "icon")` is turning into `#imageLiteral (resourceName: "icon")`

**Comment by nicklockwood** [comment]
Looks like I'm explicitly checking for #selector and #keyPath, which is a clunky way to do it. I'll find a better solution. Thanks!

**Comment by nicklockwood** [comment]
Fixed in 0.17
