### ISSUE TITLE
Rules time out when running swiftformat with swift run

### ISSUE THREAD

**Issue by mltbnz** [nicklockwood/SwiftFormat#581]
I am getting warnings that some some rules timed out when running `swiftformat` with `swift run swiftformat .` I have also installed swiftformat system via brew and if I run `swiftformat .` on the branch it works just fine 🤷‍♂️

**Comment by nicklockwood** [comment]
Does swift run use release or debug mode? If it's a debug build it might be running substantially slower, resulting in timeout.

**Comment by mltbnz** [comment]
Thanks for the quick response. That was a hint in the right direction. I did not specify the release mode (like you actually specified in the docs https://github.com/nicklockwood/SwiftFormat#using-swift-package-manager). Works great now. Thanks
