### ISSUE TITLE
Inconsistent formatting of closures after switch

### ISSUE THREAD

**Issue by karlpuusepp** [nicklockwood/SwiftFormat#582]
Given an input like this
```swift
switch Int.random() {
default:
    break
}

foo()
    .map { value in
        value * 2
    }
```

SwiftFormat will reindent the closure expression
```swift
foo()
    .map { value in
    value * 2
}
```

However if the previous `switch` statement is removed  or commented the closure expression is not reindented.

**Comment by nicklockwood** [comment]
@karlpuusepp fixed in 0.44.7
