### ISSUE TITLE
Request: Replace { $0.property } with (\.property) in Swift 5.2

### ISSUE THREAD

**Issue by jshier** [nicklockwood/SwiftFormat#584]
Swift 5.2 add function / `KayPath` equivalence for properties, meaning `map { $0 }` can now be written `map(\.self)` and `map { $0.some.property.path }` can now be written `map(\.some.property.path)`. It would be great if SwiftFormat had an optional rule in Swift 5.2 mode which could make this replacement automatically.

**Comment by gregcotten** [comment]
yes!

**Comment by nicklockwood** [comment]
Good idea!

**Comment by PompeiaPaetenari** [comment]
Just a note that our team is "excitedly" waiting for this after I pointed this out to them :D.

**Comment by nicklockwood** [comment]
@jshier @PompeiaPaetenari sadly it seems that this doesn't actually work in the `\.self` case: https://bugs.swift.org/browse/SR-12897

I'll add it for the other cases though.

**Comment by nicklockwood** [comment]
@jshier @PompeiaPaetenari this is implemented in 0.45.0 (with the aforementioned limitation).

**Comment by jshier** [comment]
Awesome, thanks!
