### ISSUE TITLE
format.sh warnings at building project

### ISSUE THREAD

**Issue by alex-vasiliu** [nicklockwood/SwiftFormat#588]
Hello guys. I just joined a project which is using SwiftFormat. 

My feedback? Pretty annoying that after a build you can no longer command+z (undo), but apart from this, a very good tool to indent code and make it easy to read.

However, I am encountering this issue. Every time I build, I am getting this warning. Can you help me with info to fix it?

[image with warnings](https://imgur.com/LCPckey.png)

In **format.sh** I am running this command

    swiftformat \
    --config .swiftformat \
    AppTest/

**Comment by nicklockwood** [comment]
Those two options are being used in the .swiftformat file. They need to be removed and replaced with the new options instead.

**Comment by avasiliu-ro** [comment]
How can I replace them with the new options but keep the same settings, and make the warning dissapear?

I tried this configuration, it removed the warning but it no longer formats the code.

    swiftformat \
    --nospaceoperators
    --config .swiftformat \
    AppTest/

**Comment by nicklockwood** [comment]
The options are inside a file called ".swiftformat" in the project directory (the leading . means it's an invisible file, so you may not be able to see it).

Open that file and remove the --comments and --ranges options from in that file.

If the --ranges option has a value of "no-space", you'll need to add:

--nospaceoperators "..<,..."

**Comment by avasiliu-ro** [comment]
You are a life saver. It worked, many thanks.
