### ISSUE TITLE
Distribution Through Homebrew

### ISSUE THREAD

**Issue by mergesort** [nicklockwood/SwiftFormat#59]
I was wondering if you had considered adding SwiftFormat to the package manager [Homebrew](https://github.com/Homebrew). That way it would be possible to maintain and update it more easily, by directing users to install via `brew install swiftformat`, and update to the latest versions with `brew update swiftformat`.

Thanks a lot!

**Comment by JustinJiaDev** [comment]
+1!

PS: Xcode Extension now can also be put on the App Store.

**Comment by nicklockwood** [comment]
SwiftFormat 0.18 is now on Homebrew.
