### ISSUE TITLE
separate rules for function braces vs control flow braces

### ISSUE THREAD

**Issue by rex-remind101** [nicklockwood/SwiftFormat#591]
I generally like braces flush like
```swift
if x {
     ...
}
```
which is the default, however, for wrapped argument lists for functions I like the brace to get it's own space like so
```swift
func assignValue<Json, Value>(
    from dict: [AnyHashable: Any],
    using keyPath: String,
    map: (Json) throws -> Value)
    throws -> Value?
{
     ...
}
```
this doesn't seem like a supported configuration though

**Comment by nicklockwood** [comment]
Yes, this isn't supported currently.

**Comment by nicklockwood** [comment]
@rex-remind101 this is now handled by the `wrapMultilineStatementBraces` rule.

It's not exactly what you asked for, as it doesn't distinguish between  function and conditional braces, but is based purely on whether the expression is wrapped. But I think it achieves the same goal. Feel free to reopen if it doesn't meet your needs.
