### ISSUE TITLE
Feature Request: Smart Tabs

### ISSUE THREAD

**Issue by jandamm** [nicklockwood/SwiftFormat#595]
I'm using this config: `--indent tabs --tabwidth 2`.

When formatting this code:
```swift
func f() {
switch value {
case .a,
.b:
print("a or b")
case .c:
print("c")
}
}
```
it produces this output:
```swift
func f() {
	switch value {
	case .a,
			 .b:
		print("a or b")
	case .c:
		print("c")
	}
}
```

While this looks good in my editor with a tabwidth of 2, it does not look good on github (tabwidth 8) or for my colleagues not using my tabwidth.
We decided to use tabs over spaces to have everyone to display the code as one likes.

I would love to be able to do this: `--indent smarttabs`
```swift
func f() {
	switch value {
	case .a,
	     .b:
		print("a or b")
	case .c:
		print("c")
	}
}
```
Here the line after case will only be indented the same as the `case` line with tabs. Then spaces will be inserted to align the both `.`.

In case you haven't heard of SmartTabs before, here is a nice gif displaying it:
![](https://cloud.githubusercontent.com/assets/1058243/18036844/49a9426c-6d3b-11e6-98ae-2c9c3db623ae.gif)
https://github.com/editorconfig/editorconfig/issues/323#issuecomment-327815131

Would be really awesome if you could add this 😍

**Comment by nicklockwood** [comment]
Hmm, I think this is actually how it *used* to work prior to 0.41.0, when I changed tabs to behave more like Xcode. Perhaps the original behavior was actually better.

**Comment by jandamm** [comment]
With the current behavior you have to define the tabwidth for alignment to work. 
At least in my eyes the advantage of using (smart)tabs is that you don't need to know the tabwidth.

I'd really appreciate if you'd add a configuration for this 👍

**Comment by PompeiaPaetenari** [comment]
> We decided to use tabs over spaces to have everyone to display the code as one likes.

Bless you <3
I wish more folks understood this.

**Comment by nicklockwood** [comment]
@jandamm @PompeiaPaetenari I've added a `--smarttabs` option in 0.45.0 (enabled by default).

**Comment by jandamm** [comment]
Works perfectly. Thanks! 👍
