### ISSUE TITLE
property wrappers require an initialization (cannot strip nils) (version 0.44.6)

### ISSUE THREAD

**Issue by Dlemex** [nicklockwood/SwiftFormat#596]
Property wrappers require an initialization. This may just be a problem with complex property wrappers since this was previously resolved.

This 
    @ThreadSafe(queue: statusSyncQueue) fileprivate(set) var deviceIdentifier: String? = nil
cannot become
    @ThreadSafe(queue: statusSyncQueue) fileprivate(set) var deviceIdentifier: String?

Currently in 5.1.3 their removal will cause swift to seg fault.

**Comment by nicklockwood** [comment]
Thanks for reporting this, I'll get it fixed.

**Comment by nicklockwood** [comment]
@Dlemex fixed in 0.44.7
