### ISSUE TITLE
Missed case by the unusedArguments rule when linting

### ISSUE THREAD

**Issue by revolter** [nicklockwood/SwiftFormat#602]
```swift
func openCategory(with categoryId: CategoryId, andSourceTracking _: Tracking) -> Bool {
	return false
}
```

doesn't get flagged when linting with the `unusedArguments` rule enabled, and the default `--stripunusedargs` option value.

And nor does this code:

```swift
func openCategory(with _: CategoryId, andSourceTracking: Tracking) -> Bool {
	return false
}
```

---

The formatter changes this:

```swift
func openCategory(with categoryId: CategoryId, andSourceTracking sourceTracking: Tracking) -> Bool {
	return false
}
```

to:

```swift
func openCategory(with _: CategoryId, andSourceTracking _: Tracking) -> Bool {
	return false
}
```

but does nothing to the two examples.

IOW, it replaces the 2 unused arguments with `_`, but doesn't replace one unused argument with `_` while the other is already `_` or unnamed.

---

It also changes this:

```swift
func openCategory(with categoryId: CategoryId, andSourceTracking: Tracking) -> Bool {
	return false
}
```

to:

```swift
func openCategory(with _: CategoryId, andSourceTracking _: Tracking) -> Bool {
	return false
}
```

but does nothing to:

```swift
func openCategory(with _: CategoryId, andSourceTracking: Tracking) -> Bool {
	return false
}
```

IOW, it adds a `_` to the unnamed argument, but only if it needs to add a `_` to another argument.

**Comment by nicklockwood** [comment]
Fixed in 0.44.8
