### ISSUE TITLE
A couple files in project are indented and outdented over and over again

### ISSUE THREAD

**Issue by brandtdaniels** [nicklockwood/SwiftFormat#606]
We have a contractor on our project from a different country. Whenever he runs `swiftformat .` on our project two specific files are outdented to 4 spaces. Whenever we checkout his branch and run the same command those two same file are re-indented to two spaces. 

He did have his indentation settings in Xcode set to 4 spaces, where we all had ours set to 2 spaces, however I don't think Xcode settings would affect swiftformat. Also, we had him correct his indentation settings and still no change when running swiftformat.

What else could be going on here?

**Comment by nicklockwood** [comment]
@brandtdaniels ask the contractor to check if he has any .swiftformat files sitting in directories above the project. SwiftFormat looks for these files anywhere in the path, so it's possible that the project settings are somehow being overridden.

**Comment by brandtdaniels** [comment]
There was only the one for our project.

**Comment by nicklockwood** [comment]
What version of SwiftFormat is he using? Is it older or newer than yours? (Run `swiftformat --version` to find out).

**Comment by brandtdaniels** [comment]
He is on 0.44.0, I am on 0.43.5

**Comment by nicklockwood** [comment]
Try upgrading to 0.44.0 locally and see if you experience the same issue he's seeing. If so, try upgrading to 0.44.7 (the latest release) and see if that fixes it again.

**Comment by brandtdaniels** [comment]
ok so he updated to 0.44.7, ran swiftformat, committed the changes. I also updated to 0.44.7, pulled his changes, ran swiftformat, and saw no files changed!

I think maybe what we want to do here is lock down a version in our Brewfile, but then it makes it harder to keep things up to date.

**Comment by nicklockwood** [comment]
One option is to include swiftformat in your project, e.g. using Cocoapods.
