### ISSUE TITLE
Bug: wrap with "maxwidth" prefers wrapping before dot-accessors rather than wrapping arguments/parameters & after assignment operator

### ISSUE THREAD

**Issue by 1oo7** [nicklockwood/SwiftFormat#620]
Duplicate of: https://github.com/nicklockwood/SwiftFormat/issues/615

You said 615 was fixed in 0.44.8 but it's not fixed. 

Maybe I did not provide enough information to fully fix this issue. 

### Example 1

Given the Swift version file and SwiftFormat file (see bottom of issue description), the following line:

```
        fooBarBazBase = try unkeyedContainer.decode(FoobyBarBazResults.Set <FoobyBarBazResults.FooBarBazBase>.self)
```

Gets wrapped like this:

```
        fooBarBazBase = try unkeyedContainer
            .decode(FoobyBarBazResults.Set<FoobyBarBazResults.FooBarBazBase>
                .self)
```

Why is it wrapping at the period? It should wrap the argument instead like this:

```
        fooBarBazBase = try unkeyedContainer.decode(
            FoobyBarBazResults.Set<FoobyBarBazResults.FooBarBazBase>.self
        )
```

### Example 2

```
        decoder.dateDecodingStrategy = .formatted(DateFormatter.iso8601DateTimeFormatter)
```

Becomes:

```
        decoder
            .dateDecodingStrategy = .formatted(DateFormatter
                .iso8601DateTimeFormatter)
```

Should be: 

```
        decoder.dateDecodingStrategy = .formatted(
            DateFormatter.iso8601DateTimeFormatter
        )
```

Although this would also not be bad since there's nothing before the `.` in `.formatted`:

```
        decoder.dateDecodingStrategy = 
            .formatted(DateFormatter.iso8601DateTimeFormatter)
```

### Comments

I feel like the only time it should wrap on the dot is when we're using a builder pattern with multiple things like .filter and .map on subsequent lines. But that should be the exception, not the rule. Or maybe there needs to be a way to customize this behavior, like, list the names of all the functions that you prefer to wrap at the dot instead.

### Setup files used to reproduce the issue:

`.swift-verison` file: `5.1`

`.swiftformat` file:

```
# Disabled Rules
--disable andOperator,redundantLetError,redundantReturn,trailingClosures,hoistPatternLet,ranges,trailingCommas,redundantSelf,redundantObjc,fileHeader

# wrapArguments Options
--wraparguments before-first
--wrapcollections before-first
--wrapparameters before-first
--closingparen balanced
--maxwidth 80

# sortedImports Options
--importgrouping testable-bottom

# semicolons Options
--semicolons never

# linebreak Options
--linebreaks lf

# indent Options
--indent 4
--indentcase false
--ifdef indent
--trimwhitespace always

# numberFormatting Options
--decimalgrouping 3
```

**Comment by nicklockwood** [comment]
@1oo7 thanks for the additional examples. The common factor appears to be that functions with a single parameter are not wrapped. I'll try tweaking the heuristic again.

**Comment by nicklockwood** [comment]
@1oo7 I've added a `--nowrapoperators` argument in 0.44.9 that will let you opt out of wrapping at . operators, e.g.

```
--nowrapoperators .
```

To get the result you want for the example you've given you'll probably need to use:

```
--nowrapoperators .,=
```

I'll try to improve the default heuristics further in future.
