### ISSUE TITLE
Request: redundantNilInit should preserve nil initialization for struct properties

### ISSUE THREAD

**Issue by nicholaslythall** [nicklockwood/SwiftFormat#621]
Swift 5.1 added [synthesizing default values for the memberwise initializer](https://github.com/apple/swift-evolution/blob/master/proposals/0242-default-values-memberwise.md) so that the initial values of a struct's mutable properties are used as default parameter values for the generated initializer. E.g:
```swift
struct Dog {
  var age: Int = 0
  var name: String

  // The generated memberwise init:
  init(age: Int = 0, name: String)
}

// 'age' can be ommited
let lassie = Dog(name: "Lassie") 
```

In this situation, `nil` initializers are not redundant as the presence (or lack thereof) results in a different generated init:
```swift
struct Dog {
  var age: Int = 0
  var name: String?

  // The generated memberwise init:
  init(age: Int = 0, name: String?)
}

// 'name' still required
let stray = Dog(name: nil) 
``` 
vs 
```swift
struct Dog {
  var age: Int = 0
  var name: String? = nil

  // The generated memberwise init:
  init(age: Int = 0, name: String? = nil)
}

// 'name' can now be omitted
let stray = Dog()
``` 

Because of this, `redundantNilInit` should not remove any nil initializers from properties in a struct as doing so may result in a breaking change.

**Comment by nicklockwood** [comment]
@nicholaslythall fixed in 0.44.9
