### ISSUE TITLE
Indent code in trailing closure

### ISSUE THREAD

**Issue by thomasMinshull** [nicklockwood/SwiftFormat#622]
I don't seem to be able to find away to get the desired indentation in a trailing closure. 

I have 
```
someInstance.foo(username: username,
                               withPassword: password,
                               mettaData: mettaData) { result in 
                               switch result {
                                  case .success: 
                                     // stuff...
                                  case .failure:
                                    // other stuff... 
                                }
                         }
                      }
```

It would be preferable if the switch statement was indented, so the code in the trailing closure is not inline with the list of arguments. 
```
someInstance.foo(username: username,
                               withPassword: password,
                               mettaData: mettaData) { result in 
                                 switch result {
                                    case .success: 
                                       // stuff...
                                    case .failure:
                                      // other stuff... 
                                  }
                            }
                      }
```

**Comment by thomasMinshull** [comment]
my current swift format file is as follows 

# file options 
--exclude Pods,**/GeneratedMocks.swift,**/Constants/Strings.swift,**/Constants/Images.swift,**/Constants/Storyboards.swift,**/Constants/Fonts.swift,**/Constants/Colors.swift

# rules
--binarygrouping none 
--closingparen same-line 
--commas inline 
--decimalgrouping none 
--hexgrouping none 
--hexliteralcase lowercase 
--ifdef no-indent 
--octalgrouping none 
--patternlet inline 
--nospaceoperators
--stripunusedargs closure-only 
--wraparguments before-first 
--wrapcollections before-first
--maxwidth 140
--indentcase true

# disabled rules 
--disable trailingClosures

**Comment by nicklockwood** [comment]
@thomasMinshull this isn't currently supported. Using `--closingparen balanced` solves the indenting mismatch, but I guess that's not your preference.

```swift
someInstance.foo(
    username: username,
    withPassword: password,
    mettaData: mettaData
) { result in
    switch result {
        case .success:
        // stuff...
        case .failure:
            // other stuff...
    }
}
```

**Comment by nicklockwood** [comment]
@thomasMinshull indenting of trailing closures on wrapped expressions is now indented an extra level in 0.45.0 - take a look and see if this solves your problem.
