### ISSUE TITLE
Closure Indenting

### ISSUE THREAD

**Issue by yonaskolb** [nicklockwood/SwiftFormat#63]
Old versions use to format to this:
```
        register(registrationRequest)
            .onFailure { error in
                app.alert(title: localized.registrationFailed(), message: error.error.friendlyDescription)
            }
            .onComplete { _ in
                self.activity.stopAnimating()
                self.actionButton.isHidden = false
            }
```
but newer releases format to:
```
        register(registrationRequest)
            .onFailure { error in
            app.alert(title: localized.registrationFailed(), message: error.error.friendlyDescription)
        }
        .onComplete { _ in
            self.activity.stopAnimating()
            self.actionButton.isHidden = false
        }
```

I'm not sure which version introduced the change or how. Maybe how it's formatting now is to solve another use case?

**Comment by nicklockwood** [comment]
Ah, I know what caused this. It was indeed a fix for another use case - I'll see if I can find a solution that works for both. Thanks!

**Comment by nicklockwood** [comment]
Hmm, although I think I know what caused the issue, I can't reproduce the bug with this code sample. I think there must have been something before or after this code in the same file that triggered it.

Can you check again and provide a code sample that fails when tested in isolation? Thanks!

**Comment by nicklockwood** [comment]
OK, I figured it out. Can you retest with 0.17.2? Thanks.
