### ISSUE TITLE
SwiftFormat does semantically not equal translations

### ISSUE THREAD

**Issue by weissi** [nicklockwood/SwiftFormat#636]
SwiftFormat suggests this change

```diff
diff --git a/Sources/AsyncHTTPClient/HTTPClient.swift b/Sources/AsyncHTTPClient/HTTPClient.swift
index 62a234c..41feb3c 100644
--- a/Sources/AsyncHTTPClient/HTTPClient.swift
+++ b/Sources/AsyncHTTPClient/HTTPClient.swift
@@ -586,7 +586,7 @@ public class HTTPClient {
     /// `HTTPClient` configuration.
     public struct Configuration {
         /// TLS configuration, defaults to `TLSConfiguration.forClient()`.
-        public var tlsConfiguration: Optional<TLSConfiguration>
+        public var tlsConfiguration: TLSConfiguration?
         /// Enables following 3xx redirects automatically, defaults to `false`.
         ///
         /// Following redirects are supported:
```

which is not semantically equivalent. In fact, the suggested version is worse.

See [this comment](https://github.com/swift-server/async-http-client/pull/227#discussion_r432634892) and [that bug](https://bugs.swift.org/browse/SR-11777) on how `Optional<Thing>` and `Thing?` are _not_ the same when they're properties in classes/structs.

Is there a way for me to turn this off?

**Comment by weissi** [comment]
See here for a proof:

```
$ cat test.swift 
struct A {
    var x: Optional<String>
}

let a = A()
johannes:/tmp
$ swiftc test.swift
test.swift:5:11: error: missing argument for parameter 'x' in call
let a = A()
          ^
          x: <#String?#>
test.swift:1:8: note: 'init(x:)' declared here
struct A {
       ^
-1- johannes:/tmp
$ vi test.swift 
johannes:/tmp
$ cat test.swift 
struct A {
    var x: String?
}

let a = A()
johannes:/tmp
$ swiftc test.swift
# compiles just fine
```

**Comment by nicklockwood** [comment]
@weissi yes, you can disable this by adding the following comment immediately before that line:

```swift
// swiftformat:disable:next typeSugar
```

Alternatively you can disable it globally by adding `--disable typeSugar` to your swiftformat command-line arguments or configuration file.

**Comment by weissi** [comment]
Thanks so much @nicklockwood ! I'll add that. For the future it may be worth adding an option that does the opposite because `Optional<T>` has clear advantages over `T?`. We did it manually in [SwiftNIO](https://github.com/apple/swift-nio/pull/1252).

**Comment by nicklockwood** [comment]
I'll consider adding an option to disable the rule for just this case. It might also make sense just to try to detect this particular case and not apply the transform, since the aim is not to make semantically non-equivalent changes if possible.

**Comment by nicklockwood** [comment]
@weissi I've added an option for this to version 0.44.13. If you put the following in your .swiftformat file:

```
--shortoptionals except-properties
```

then you can remove

```
--disable typeSugar
```

**Comment by nicklockwood** [comment]
@weissi Note: I don't currently replace `T?` with `Optional<T>` when that option is set, because that would be a breaking change in some cases. It *should* be possible to detect those cases, but that's a significantly more complex feature to implement. Feel free to open a feature request if that's something you'd find useful.

**Comment by weissi** [comment]
Amazing! Thanks so much for the super quick turnaround
