### ISSUE TITLE
--allman true does not move brace

### ISSUE THREAD

**Issue by gbrandt** [nicklockwood/SwiftFormat#642]
A file such as

    HStack {
       Text( "test" )
    }

does not become

    HStack
    {
       Text( "test" )
    }

as expected, the opening brace stays behind `HStack`

**Comment by nicklockwood** [comment]
@gbrandt there's currently an exception in the allman rule for closures, but this probably doesn't make sense, especially for cases like this. I'll revisit the logic.

**Comment by nicklockwood** [comment]
@gbrandt fixed in 0.45.0.
