### ISSUE TITLE
SwiftLint's number_separator rule conflict

### ISSUE THREAD

**Issue by shawnkoh** [nicklockwood/SwiftFormat#643]
Hello,

I'm unsure if this is a bug, but I can't seem to get swift format to adhere to SwiftLint's number_seperator rule.

SwiftFormat constantly removes the underscore e.g. 1_234 --> 1234

I'm on version 0.44.13

I tried configuring the numberFormatting settings to no avail.

These are my SwiftFormat settings
```
# format options

--allman false
--binarygrouping 4,8
--commas always
--comments indent
--decimalgrouping 3,6
--elseposition same-line
--empty void
--exponentcase lowercase
--exponentgrouping disabled
--fractiongrouping disabled
--header ignore
--hexgrouping 4,8
--hexliteralcase uppercase
--ifdef indent
--indent 4
--indentcase false
--importgrouping testable-bottom
--linebreaks lf
--maxwidth none
--octalgrouping 4,8
--operatorfunc spaced
--patternlet hoist
--ranges spaced
--self remove
--semicolons inline
--stripunusedargs always
--swiftversion 5.2
--trimwhitespace always
--wraparguments preserve
--wrapcollections preserve
--specifierorder override,public

# rules

--enable isEmpty
```

**Comment by nicklockwood** [comment]
@shawnkoh the decimal grouping values are the grouping size (3) and the minimum length a number needs to be before adding grouping (6), so if you want it to apply to a number with only 4 digits you'll need to change it to

```
--decimalgrouping 3,4
```

**Comment by shawnkoh** [comment]
> @shawnkoh the decimal grouping values are the grouping size (3) and the minimum length a number needs to be before adding grouping (6), so if you want it to apply to a number with only 4 digits you'll need to change it to
> 
> ```
> --decimalgrouping 3,4
> ```

THANK YOU! This was driving us insane! It would be awesome if Rules.md mentioned what the parameters represented

**Comment by nicklockwood** [comment]
@shawnkoh I've improved the documentation - hopefully it's a little clearer now.
