### ISSUE TITLE
Ignore .swiftformat files above file when using explicit --config

### ISSUE THREAD

**Issue by nicklockwood** [nicklockwood/SwiftFormat#644]
When using an explicit --config file and targeting a specific swift file, the user probably isn't expecting their explicit config to be overridden by .swiftformat files at a higher directory level than the specified file.

**Comment by guillaumealgis** [comment]
Indeed, I just ran into this and it is very surprising.

Can I ask why is SwiftFormat looking into parent directories? It seems very unusual that a formatting tool may need to do this, I imagine there's a logical explanation? (I could not find any word on this in the README, only the thing about subdirectories, which is reasonable)

**Comment by nicklockwood** [comment]
@guillaumealgis it's because people were using SwiftFormat to format individual files within a repository (e.g. as part of a git hook) and were surprised that it then ignored the .swiftformat config file, but perhaps there's a better solution?

**Comment by nicklockwood** [comment]
@guillaumealgis as of version 0.51.0, .swiftformat files are ignored is a specific --config parameter is provided
