### ISSUE TITLE
Unexpected indent with comment and `wrap`

### ISSUE THREAD

**Issue by keith** [nicklockwood/SwiftFormat#649]
With this code:

```swift
var description: String {
    [
            foo,
            // we want user-facing lines to be 1-indexed
            bar,
    ]
}
```

If you format with `swiftformat --rules wrap --maxwidth 110 foo.swift --swiftversion 5.2 --cache clear` you end up with:

```swift
var description: String {
    [
        foo,
        // we want user-facing lines to be 1-indexed
            bar,
    ]
}
```

Where `bar` is not de-dented.

0.44.13

**Comment by nicklockwood** [comment]
@keith this seems to be fixed in the latest version (I suspect it was a side-effect of another bug fix)
