### ISSUE TITLE
Unexpected `wrap` with long string

### ISSUE THREAD

**Issue by keith** [nicklockwood/SwiftFormat#651]
With this code:

```swift
func bar() {
    foo.baz(
        "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa")
    _ = a(b: c,
          d: e)
}
```

If you format with `swiftformat --rules wrap --maxwidth 110 foo.swift --swiftversion 5.2 --cache clear` you get:

```swift
func bar() {
    foo
        .baz("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa")
    _ = a(b: c,
          d: e)
}
```

Which no longer wraps at 110.

If you remove the assignment below the call to `baz` it does not reformat.

0.44.13

**Comment by nicklockwood** [comment]
@keith fixed in 0.44.15. Thanks for reporting!
