### ISSUE TITLE
redundantBackticks breaks `get` inside subscript

### ISSUE THREAD

**Issue by jshier** [nicklockwood/SwiftFormat#655]
I created a `subscript` extension for the Vapor `Parameters` type to give myself a slightly more ergonomic way of extracting typed values from `Parameters`.

```swift
extension Parameters {
    subscript<T>(_ name: String, as _: T.Type = T.self) -> T? where T: LosslessStringConvertible {
        `get`(name)
    }
}
```

However, SwiftFormat strips the tick marks around "get", breaking the code.

```swift
extension Parameters {
    subscript<T>(_ name: String, as _: T.Type = T.self) -> T? where T: LosslessStringConvertible {
        get(name)
    }
}
```

Disabling `redundantBackticks` for that line fixes the problem.

**Comment by nicklockwood** [comment]
@jshier fixed in 0.44.14.
