### ISSUE TITLE
How to fix block parameter indentation?

### ISSUE THREAD

**Issue by DanielEdrisian** [nicklockwood/SwiftFormat#657]
Hello,

So I see that SwiftFormat is automatically indenting each parameter and closing bracket, so it's kinda skewed forward:

<img width="424" alt="Screen Shot 2020-06-20 at 5 26 32 PM" src="https://user-images.githubusercontent.com/11810973/85214077-651b5380-b31b-11ea-960a-791ffbbca3a6.png">

Where I would rather have something like:

<img width="424" alt="Screen Shot 2020-06-20 at 5 26 24 PM" src="https://user-images.githubusercontent.com/11810973/85214079-6cdaf800-b31b-11ea-9576-c7c32c33baff.png">

Is there any way to achieve this through the configs? Thanks:)

**Comment by nicklockwood** [comment]
@DanielEdrisian there's something I'm not understanding from your code example: Why are there two closing ) ) at the end? I see one opening ( after register, but the code is cut off so I can't see exactly what's going on. Can you paste the full code in?

**Comment by DanielEdrisian** [comment]
Sure thing! It's a block.
<img width="898" alt="Screen Shot 2020-06-28 at 9 17 30 PM" src="https://user-images.githubusercontent.com/11810973/85972407-c7f89480-b984-11ea-9b82-381b95bcd303.png">

**Comment by DanielEdrisian** [comment]
awesome, thanks for doing this.

**Comment by nicklockwood** [comment]
@DanielEdrisian fixed in 0.44.15. Thanks for reporting!
