### ISSUE TITLE
How to run on a CI?

### ISSUE THREAD

**Issue by kirakik** [nicklockwood/SwiftFormat#66]
Great project! It would be fine to have some info on how to run it on a CI :)

**Comment by nicklockwood** [comment]
I've no idea how, but perhaps someone else can contribute some docs to the readme?

**Comment by alphatroya** [comment]
Maybe there is a lack of option like `--dry-run` to check code formatting by CI tools like [Danger](http://danger.systems)

**Comment by alphatroya** [comment]
I see that 0.32.1 is added a `--dryrun` option, I think it a big step to resolve this issue 👍

**Comment by garriguv** [comment]
Having `--dryrun` is indeed a game-changer 😃 

https://github.com/garriguv/danger-ruby-swiftformat

**Comment by nicklockwood** [comment]
@garriguv nice! Perhaps you could add a README PR that explains how to set up SwiftFormat as a CI step? You are welcome to include a link to your Danger plugin.

**Comment by garriguv** [comment]
@nicklockwood I'll get something ready.

**Comment by nicklockwood** [comment]
I'm going to consider this closed by https://github.com/nicklockwood/SwiftFormat/pull/202 - thanks @garriguv!
