### ISSUE TITLE
swiftformat --rules gives a list that doesn't match what SwiftFormat app puts into a config file; confusing.

### ISSUE THREAD

**Issue by haikusw** [nicklockwood/SwiftFormat#660]
I find it somewhat confusing that `swiftformat --rules` generates a list that doesn't match what the SwiftFormat for Xcode application puts into a format file when you setup settings and save them.

Lots of examples, but `trimwhitespace` is the one I ran into that motivated me to write this.  Here's a view of a sample swiftformat file generated by SwiftFormat for Xcode (Version 0.44.14 (1)) and the `swiftformat --rules` output showing the issue (`swiftformat --version` -> "0.44.14"):

![confusing](https://user-images.githubusercontent.com/222271/85807598-35978d00-b707-11ea-970c-2e57cda23d22.png)

**Comment by nicklockwood** [comment]
Sorry for the confusion. SwiftFormat has a number of _rules_ which can be configured by _options_. These are represented by separate tabs in SwiftFormat for Xcode.

When you call

```
$ swiftformat --rules
```

its prints the list of _rules_, and when you using `--ruleinfo` you must pass one of those rules, which will tell you what it does and which options it can be configured with.

When you export config from SwiftFormat for Xcode, what you are seeing is mainly the _options_ values. You can find out about these using

```
$ swiftformat --options
```

On the last line of the SwiftFormat for Xcode fil you'll see:

```
--disable consecutiveSpaces,redundantFileprivate,unusedArguments
```

This is the rules configuration, so you can find out about these using:

```
$ swiftformat --ruleinfo consecutiveSpaces,redundantFileprivate,unusedArguments
```

**Comment by haikusw** [comment]
Ah ha!  Probably I just didn't read the documentation closely enough.
I'll try to re-read the documentation and maybe suggest clarifications if it still doesn't seem clear.

Thanks for clearing up my confusion.

**Comment by nicklockwood** [comment]
@haikusw I've identified a few things that could be clarified based on your feedback, so I'll try to improve those, but any suggestions are welcome (and thanks for the donation!)

**Comment by haikusw** [comment]
You are welcome. I thought about it and realized that I use SwiftFormat many many times every day while I'm writing code in Xcode.  SwiftFormat is especially helpful when doing large refactors where you're moving large pieces of code around and the indentation gets all weird as a result.  Sure, I could use Xcode's provided formatter, but since we have standardized on SwiftFormat with a set of format settings for this project, I might as well use SwiftFormat as I write code as well as just before I commit my code.   The integrated SwiftFormat Xcode extension and a cmd-key assigned via Xcode's preferences make this super easy; it's now almost as compulsive to format as I write code as Cmd+S for saving is (old pre OS X habits die hard!) :)

Cheers
