### ISSUE TITLE
redundantReturn doesn't seem to work in Xcode extension

### ISSUE THREAD

**Issue by gcox** [nicklockwood/SwiftFormat#661]
I can't get this rule to work in the Xcode extension. I've tried versions 0.44.15 & 0.44.16 in both Xcode 11.5 & Xcode 12 beta 1.
It works as expected from the command line.

I saw this issue: https://github.com/nicklockwood/SwiftFormat/issues/557. I opened the companion app, exported the config, added `--swiftversion 5.2` to it, opened the modified config file with the companion app, restarted Xcode, but it still won't remove redundant returns.

**Comment by nicklockwood** [comment]
@gcox I believe the problem is that there's currently no way to specify Swift version in the Xcode extension. I'll fix this - thanks.

**Comment by nicklockwood** [comment]
@gcox SwiftFormat for Xcode 0.45.0 now includes a Swift version dropdown.

**Comment by gcox** [comment]
@nicklockwood Awesome, thanks. Confirmed that `redundantReturn` works as expected with the extension now.
