### ISSUE TITLE
Indentation of trailing closure not in line with start of closure.

### ISSUE THREAD

**Issue by PompeiaPaetenari** [nicklockwood/SwiftFormat#662]
Just updated to latest SwiftFormat (0.44.16) this morning and tried running it to check for any changes to our code and if I can update us but facing an issue with a closure in a `.map` statement.

```swift
  case .webPage:
    return .web(data(id: id, index: index)
        .map { _ in
         .display(title: title, id: id, name: name, index: index)
      })
```

Error from SwiftLint:
`Closure End Indentation Violation: Closure end should have the same indentation as the line that started it. Expected 8, got 6.`

Before the change, we have (version 0.44.13):
```swift
  case .webPage:
    return .web(data(id: id, index: index)
        .map { _ in
         .display(title: title, id: id, name: name, index: index)
        })
```

In fact, now running version 0.44.13 on the code after having run 0.44.16 on it shows no changes.  This is with the same config file in both instances.

**Comment by nicklockwood** [comment]
@PompeiaPaetenari fixed in 0.44.17
