### ISSUE TITLE
redundantSelf incorrectly removes self when the property is shadowed

### ISSUE THREAD

**Issue by pm-dev** [nicklockwood/SwiftFormat#663]
When --self is set to "remove" (default) or "init-only" it is possible that formatting will change code semantics. This would happen when, in the same scope, you were shadowing an instance variable with a `var`
Example:
Before formatting
```
var model = self.model
// do something with model
self.model = Model(from: xyz)
```
After formatting
```
var model = self.model
// do something with model
model = Model(from: xyz)
```

Expected:
Formatting should not remove the `self.` in this case, as it's not redundant. This will require knowing whether the instance variable is shadowed in the same scope.

**Comment by nicklockwood** [comment]
@pm-dev this sounds like a bug, but I wasn't able to reproduce it with just the few lines you provided in the example. Can you supply a short code sample that demonstrates this bug when formatted in isolation?

**Comment by pm-dev** [comment]
I just retried on the exact same code I was seeing this yesterday and couldn't repro. No idea what could have changed. I'll re-open the issue if I have a file you can run this on to repro, but until then, let's close this out. Apologies for burning a few of your cycles.

**Comment by nicklockwood** [comment]
@pm-dev no problem, feel free to reopen the issue if it happens again.
