### ISSUE TITLE
Replaces symlinks with contents of the linked file

### ISSUE THREAD

**Issue by wokalski** [nicklockwood/SwiftFormat#67]
When `swiftformat` encounters a symlink it replaces it with contents of the symlinked file.

**Comment by nicklockwood** [comment]
Thanks. Can you give a precise example, so I can check that I'm fixing the right thing? Is this when the path you specify in the command line is a symlink, or when the specified folder contains a symlink, etc?

**Comment by wokalski** [comment]
Sure. I'll create a reproducible case today. I had the problem when I ran `swiftformat` in a directory whose subdirectory contained a symlink

**Comment by nicklockwood** [comment]
Thanks, I think that's enough for me to go on.

**Comment by wokalski** [comment]
@nicklockwood I can't reproduce. I hope you haven't started digging through it. I suppose it was Xcode that replaced the content and I didn't notice. Sorry for that.

**Comment by nicklockwood** [comment]
@wokalski I was able to reproduce it for individually symlinked swift files, but not for directories. Probably not likely to be a common problem, but worth a fix anyway 👍

**Comment by nicklockwood** [comment]
This is now configurable in 0.19.
