### ISSUE TITLE
redundantSelf removing non-redundant selfs

### ISSUE THREAD

**Issue by jshier** [nicklockwood/SwiftFormat#678]
I have a type that takes a closure as part of its `init`. SwiftFormat is removing the `self` references from those closures.

```swift
final class Value<T> {
    private let provider: () -> T

    init(provider: @escaping () -> T) {
        self.provider = provider
    }
}
```

When formatting,

```swift
Value {
    self.returnSomeValue()
}
```

is transformed into:

```swift
Value {
    returnSomeValue()
}
```

which is obviously incorrect.

**Comment by nicklockwood** [comment]
It seems like it's failing to identify the braces as a closure. I'll take a look.

**Comment by nicklockwood** [comment]
@jshier I'm not able to reproduce this problem in isolation. Can you provide a standalone code snippet that demonstrates the problem when formatted?

**Comment by jshier** [comment]
I'll try to extract one when I get a chance.

**Comment by nicklockwood** [comment]
@jshier any luck with this?

**Comment by jshier** [comment]
Yes, this example will trigger the issue:

```swift
final class Value<T> {
    private let provider: () -> T

    init(provider: @escaping () -> T) {
        self.provider = provider
    }
}

final class Consumer {
    private(set) lazy var value = Value<String> { [unowned self] in
        self.someProvider()
    }

    private func someProvider() -> String {
        "string"
    }
}
```

It appears the key is the explicit generic on `Value`. `Value {` doesn't trigger the issue while `Value<String> {` does.

**Comment by nicklockwood** [comment]
@jshier fixed in 0.52.3.

**Comment by jshier** [comment]
Yep, thanks! Confirmed fixed in 0.45.3.

**Comment by jsimonlane** [comment]
I found another error where this broke...

```swift
class C {
    let i: Int = 0
    
    func f() {
        print("\(self.i)") // Removes 'self' when it shouldn't!
    }
}
```

**Comment by nicklockwood** [comment]
@jsimonlane why isn't self redundant in that case?
