### ISSUE TITLE
preferKeyPath breaks compound closures

### ISSUE THREAD

**Issue by jshier** [nicklockwood/SwiftFormat#679]
With `preferKeyPath` enabled, closures which reference multiple variables are broken.

```swift
.map { $0.isLoading || $1.isLoading }
```

is reformatted into:

```swift
.map(\.isLoading || $1.isLoading)
```

**Comment by jshier** [comment]
This also breaks methods:

```swift
let results = validations.map { $0.validate(userInput) }
```

is reformatted into:

```swift
let results = validations.map(\.validate(userInput))
```

**Comment by jshier** [comment]
It also breaks optional properties, where this:

```swift
.map { $0?.success }
```

is reformatted into:

```swift
.map(\?.success)
```

**Comment by nicklockwood** [comment]
Thanks - I thought I'd handled those cases, but I should've added more tests 🤦‍♂️ I'll fix it in the next release.

**Comment by nicklockwood** [comment]
@jshier Fixed in 0.45.1.

**Comment by schjonhaug** [comment]
More breaking code related to compactMap (using version 0.45.3):

From: `let emoteIds = reactionSet?.reactions?.compactMap { $0.id }`
To: `let emoteIds = reactionSet?.reactions?.compactMap(\.id)`

From: `let items = combinedItems.compactMap { $0.text }`
To: `let items = combinedItems.compactMap(\.text)`

**Comment by nicklockwood** [comment]
@schjonhaug why does this break? Is it because it can no longer infer the type?

**Comment by schjonhaug** [comment]
Yes exactly. I get the following errors:
```
Generic parameter 'ElementOfResult' could not be inferred
Key path value type 'String' cannot be converted to contextual type 'ElementOfResult?'
```

**Comment by nicklockwood** [comment]
@schjonhaug is the text property of type `String` or of type `String?` in this case? If it's the former, what happens if you change to `map()` instead of `compactMap()`?

**Comment by nicklockwood** [comment]
@schjonhaug from my own testing, it seems like this can open happen in cases where you've used a `compactMap()` with a non-optional value, and could have used `map()` instead, which fixes the problem.

Although it's not ideal that SwiftFormat breaks compilation here, I'm not sure if I'd want to disable it since it's actually telling you something useful.

Let me know if replacing `compactMap()` with `map()` doesn't solve this, otherwise I think I'll just add this as a known issue.

**Comment by nicklockwood** [comment]
FYI, I've filed a Swift bug to report this discrepancy: https://bugs.swift.org/browse/SR-13347

**Comment by schjonhaug** [comment]
Sorry for the late reply, and thanks for investigating this.

Yes, it looks like you're right. The collections in question do indeed consist of of non-optional values and we should've used `map` instead. So I agree with you that it's good to leave SwiftFormat as is.

Thanks for reporting the radar.
