### ISSUE TITLE
Can't install as an extension

### ISSUE THREAD

**Issue by hailie-rei** [nicklockwood/SwiftFormat#68]
Hello!
Please help me to figure out what I'm doing wrong.
I'm using macOS 10.11 (El Capitan). I drag the app to the Applications, but when I run it, "Xcode Source Editor" doesn't appear in the System Preferences -> Extensions.
I ran console command before it and after it and restarted my Mac, but it didn't help.
Thank you!

**Comment by nicklockwood** [comment]
I couldn't get it to work on 10.11 either I'm afraid. Works fine on 10.12.

**Comment by hailie-rei** [comment]
Thank you! It seems I really should upgrade my OS :)

**Comment by nicklockwood** [comment]
I don't think there's anything I can do about this, so I'm closing for now. Feel free to re-open if you find a solution, or something else comes up.

**Comment by jeffersonsetiawan** [comment]
I'm using 10.13 and the extension is not showing. Tried 9.3 and 9.3.1, doesn't work.

Please help.
