### ISSUE TITLE
Running swift format 0.45 in the build phase lint's the .build folder in the BuildTools folder and ignores the rules set by .swiftformat

### ISSUE THREAD

**Issue by yungdai** [nicklockwood/SwiftFormat#689]
I have setup the BuildPhase setup for swiftformat and it seems that even when I don't run the actual command it still lints my code.

I have purged the swiftformat cache folder, cleaned the build folder. I have added the .gitignore folders as recommended as well as added the exclusion of the .build folder to the .swiftformat file.

Nothing seems to work.

I am using SwiftFormat 0.45.3

Even when I disable all everything in the build phase it still happens.

```
SDKROOT=macosx
# swift package update #Uncomment this line temporarily to update the version used to the latest matching your BuildTools/Package.swift file

# uncomment to lint
# swift run -c release --package-path BuildTools swiftformat "$SRCROOT" --lint --lenient
```

The .swiftformat file has the following to make sure that I had everything disabled so I can try one rule at a time, but get's ignored.

```
--swiftversion 5.2.4

# Disabled rules
--disable anyObjectProtocol,blankLinesAroundMark,blankLinesAtEndOfScope,blankLinesAtStartOfScope,blankLinesBetweenScopes,braces,consecutiveBlankLines,consecutiveSpaces,duplicateImports,elseOnSameLine,emptyBraces,fileHeader,hoistPatternLet,indent,leadingDelimiters,linebreakAtEndOfFile,linebreaks,modifierOrder,numberFormatting,preferKeyPath,redundantBackticks,redundantBreak,redundantExtensionACL,redundantFileprivate,redundantGet,redundantInit,redundantLet,redundantLetError,redundantNilInit,redundantObjc,redundantParens,redundantPattern,redundantRawValues,redundantReturn,redundantSelf,redundantVoidReturnType,semicolons,sortedImports,spaceAroundBraces,spaceAroundBrackets,spaceAroundComments,spaceAroundGenerics,spaceAroundOperators,spaceAroundParens,spaceInsideBraces,spaceInsideBrackets,spaceInsideComments,spaceInsideGenerics,spaceInsideParens,strongOutlets,strongifiedSelf,todos,trailingClosures,trailingCommas,trailingSpace,typeSugar,unusedArguments,void,wrap,wrapArguments,wrapAttributes,wrapMultilineStatementBraces,yodaConditions


# Files and Folder Exclusions
--exclude **/Products,**/Frameworks,**/BuildTools/.build
```

**Comment by nicklockwood** [comment]
@yungdai I'm having a bit of trouble visualizing your project structure. Can you maybe zip up the project without the actual source code just the scripts, folders, etc?

**Comment by yungdai** [comment]
My project structure is 

```
Project\
             .swiftformat
             BuildTools\
                               .build\
                               Empty.swift
                               Package.resolved
                               Package.swift
             DFCoreShowcase\
             DFCoreShowcase.xcodeproj
             iOSCore\
             Package.swift
```

**Comment by nicklockwood** [comment]
@yungdai where in that hierarchy is the script that runs swiftformat?

**Comment by yungdai** [comment]
If I do an echo on the $SRCROOT it's pointing to here 
Showing Recent Messages
/Users/p125342/Developer/DFCore/iOSCoreShowcase/DFCoreShowcase

So it would look like this:
DFCoreShowCase\
    .swiftformat
     BuildTools\
         .build\
         Empty.swift
         Package.resolved
         Package.swift
    DFCoreShowcase\
    DFCoreShowcase.xcodeproj
    iOSCore\
    Package.swift

**Comment by nicklockwood** [comment]
@yungdai I've not been able to reproduce this, but I did make some changes to .swiftformat file resolution in 0.46.0. Can you try with this version and see if it solves your issue?
