### ISSUE TITLE
Configure extension options without rebuilding

### ISSUE THREAD

**Issue by kdubb** [nicklockwood/SwiftFormat#69]
The ability to configure the editor extension without requiring a rebuild would be a great next feature. 

I'm not sure how well UI is handled in an editor extension (which may be the reason for the extensions current limitation) but other methods like a `.swiftformat.yml` file in a directory would seem fairly easy; this is the method [SwiftLint](https://github.com/realm/SwiftLint) has adopted and it's quite nice.

**Comment by nicklockwood** [comment]
There's no way to provide UI for editor extension except via the host app. But it infers the config from the file you are formatting, so once you've formatted once with the command line, it should apply correct styles via the extension.

**Comment by tonyarnold** [comment]
Can the editor extension read user defaults written by the host app? I think a shared suite _might_ work. It'd be nice to be able to at least configure overrides for personal defaults, even with the inferred config.

**Comment by nicklockwood** [comment]
@tonyarnold it can. I might be able to do something like use the host app to read a config file in the project repo, and then pass that data to the extension.

I haven't spent a lot of time investigating it so far though.

**Comment by tonyarnold** [comment]
As much as I'd like per-project configurations, I think we should wait to see what Apple does with Source Editor Extensions in Xcode 9 in a couple of months.

That being said, I think I have a good, supported path forward for sharing preferences - did you have any ideas around the UI for this, how things should be exposed, etc? I'm more than happy to have a first pass at this.

For now, the configuration would need to be done in the host app, and I was thinking about exposing all of the options via UI controls that would affect just the Xcode Source Editor Extension. By default, the every option would continue to be inferred from the current file.

**Comment by nicklockwood** [comment]
>For now, the configuration would need to be done in the host app, and I was thinking about exposing all of the options via UI controls that would affect just the Xcode Source Editor Extension. By default, the every option would continue to be inferred from the current file.

That would be great! It's definitely the right approach - I just lack the confidence with AppKit to try it myself.

As I've (hopefully) clarified in (this answer)[https://github.com/nicklockwood/SwiftFormat/issues/122], there are two types of configuration for SwiftFormat - rules and options. The UI should probably expose these as two separate lists - rules each shown with a checkbox to enable and disable, and then options with whatever input is applicable - typically either a dropbox, dropdown or textfield.

Ideally, to make it maintainable, the rules would be presented in a tableView or equivalent, and derived automatically from the FormatRules list already exposed by the SwiftFormat API. Doing the same for options might be more difficult, but I don't mind maintaining it as long as there's a fairly straightforward process to follow for adding new rules.

**Comment by tonyarnold** [comment]
Righto, that all sounds the same as what I was thinking. I'll allocate some time to this, and see where we get. 👍

**Comment by nicklockwood** [comment]
@kdubb added in 0.34.0
