### ISSUE TITLE
Please keep old versions published on brew

### ISSUE THREAD

**Issue by paulb777** [nicklockwood/SwiftFormat#695]
I need to install 0.45.2 for compatibility with GitHub Actions.

`brew upgrade swiftformat` installs 0.45.3

`brew search swiftformat` doesn't show any other version available.

**Comment by nicklockwood** [comment]
@paulb777 you can download the 0.45.2 release here: https://github.com/nicklockwood/SwiftFormat/releases/tag/0.45.2 - you'll find the binary inside the CommandLineTool directory.

Any particular reason you can't just use 0.45.3?

**Comment by paulb777** [comment]
We have presubmit checks that run on GitHub Actions and GitHub Actions is still at 0.45.2.

Is there a better option to keep several developers and GHA in sync than checking in a binary or updating every time checks are run?

**Comment by nicklockwood** [comment]
@paulb777 I have no idea why homebrew makes it so difficult to install old versions. Could you try using [Mint](https://github.com/yonaskolb/Mint) or CocoaPods, or just SPM directly?

**Comment by paulb777** [comment]
Thanks, transition to mint in progress at https://github.com/firebase/firebase-ios-sdk/pull/6229
