### ISSUE TITLE
Transforming trailing braces

### ISSUE THREAD

**Issue by paulb777** [nicklockwood/SwiftFormat#696]
Upgrading from 0.44.17 to 0.45.3 moves several trailing braces to the next line. Details in https://github.com/firebase/firebase-ios-sdk/pull/6229.

I don't see any obvious options that control this or anything at https://github.com/nicklockwood/SwiftFormat/blob/master/CHANGELOG.md about changes to brace organization.

Is there an option to keep the trailing braces?

**Comment by nicklockwood** [comment]
@paulb777 you can disable the `wrapMultilineStatementBraces` rule, introduced in 0.45.0

**Comment by nicklockwood** [comment]
FYI, if you run swiftformat with `--verbose` mode, it will tell you which rules were applied to each file. Alternatively you can use `--lint`, which will tell you which rules it would *like* to apply, but without actually modifying the code.

**Comment by paulb777** [comment]
Thanks!
