### ISSUE TITLE
Generics type explicitly declared for a variable does not seems formatted correctly

### ISSUE THREAD

**Issue by macoto-liu** [nicklockwood/SwiftFormat#7]
I have below code 
let users: MultipleModels<User> = ....

After run swfitformat command the code comes to be 
let users: MultipleModels < User> = ...
it looks like there is whitespace was added after 'MultipleModels' and before 'User' type.
i.e. seems generics symbol '<' was treated as 'Less Than'. 

This might be a problem, can we fix it?

btw: SwiftFormat is awesome for me to use in our project. Compared with other swift format tools, this one is pretty good, and the formatted result is acceptable.  Thanks for your contribution.

**Comment by macoto-liu** [comment]
Here is the swift format version I used 

➜  ~ swiftformat -version
swiftformat, version 0.3

**Comment by nicklockwood** [comment]
Thanks, I'll add a test case and get that fixed for the next release.

**Comment by nicklockwood** [comment]
Fixed in v0.4

**Comment by macoto-liu** [comment]
It looks good for me in v0.4. Thanks for your quick fix :)
