### ISSUE TITLE
SwiftFormat is disabled in Xcode 12 Beta 5

### ISSUE THREAD

**Issue by weenzeel** [nicklockwood/SwiftFormat#705]
Installed SwiftFormat today, but can't get it to work.
I can see the option SwiftFormat in Xcode Editor menu, but it's disabled.

I've just installed Xcode 12 Beta 5. I'm on macOS 11.0-beta (20A5343i).

I read in the release-notes that extension should work in Xcode 12.

I've activated the extension etc.

**Comment by hovaks** [comment]
Deprecations
For compatibility with new security features in macOS 11, Xcode extensions must be built using Xcode 12 and must embed XcodeKit.framework. An Xcode extension rebuilt with these tools remains compatible with older versions of Xcode and macOS. (51822755)

**Comment by nicklockwood** [comment]
@weenzeel @hovaks ah, apologies for then - I've linked XcodeKit but not built with Xcode 12. You'll need to build it yourself from source.

**Comment by haikusw** [comment]
It works fine with Xcode 12 Beta 5 on 10.15.6 fwiw.

**Comment by weenzeel** [comment]
Thank you @kadir-ince for the excellent work-around write up!

**Comment by hyperphonic0** [comment]
Wasn't this fixed in PR https://github.com/nicklockwood/SwiftFormat/pull/669?

Should be just a case doing your own build.

**Comment by nicklockwood** [comment]
@weenzeel as of version 0.46.3 the bundled Extension should work in Xcode 12.
