### ISSUE TITLE
Allman style braces from command line

### ISSUE THREAD

**Issue by 3lvis** [nicklockwood/SwiftFormat#71]
Hi Nick,

First of all thanks again for such an awesome tool. :)

I'm trying to run the `swiftformat` command (from brew) but want to use Allman style braces (since the project owner uses that). I've been digging through the docs but haven't found a way to do this. Could you help me out, please?

**Comment by nicklockwood** [comment]
I'm pretty sure this is covered in the help shown in the command-line tool, but the option you need is `--allman true`

However, a better approach if you're trying to match the existing project style is to run

    swiftformat --inferoptions path/to/project/folder

Then run the tool using the options suggested by the previous command

**Comment by 3lvis** [comment]
Thanks Nick! I'll give it a try today.
