### ISSUE TITLE
Switch @unknown case not formatted properly

### ISSUE THREAD

**Issue by nmcc24** [nicklockwood/SwiftFormat#713]
I'm finding that the switch indentation flag is not working correctly for the new swift 5 `@unknown` case.

`--indentcase true`
![Screenshot 2020-08-26 at 15 57 31](https://user-images.githubusercontent.com/4029254/91388979-55931c00-e830-11ea-82c7-74a4ea6a76d5.png)

`--indentcase false`
![Screenshot 2020-08-26 at 15 57 12](https://user-images.githubusercontent.com/4029254/91388977-5461ef00-e830-11ea-9549-e2595e77248b.png)

Am I right on assuming there is a bug or am I missing something?

**Comment by nicklockwood** [comment]
@nmcc24 this looks like a bug. But it seems that if you move the `@unknown` to the correct place manually then it doesn't move it to the wrong place (which is probably why this wasn't picked up before).

**Comment by nmcc24** [comment]
I can definitely confirm that moving @unkown to the right position works as you suggested 👍 
Thanks for responding this quickly mate!

**Comment by nicklockwood** [comment]
@nmcc24 fixed in 0.46.0.

**Comment by nmcc24** [comment]
> @nmcc24 fixed in 0.46.0.

Thanks a lot mate!
