### ISSUE TITLE
Incorrect `isStartOfClosure(at:)` result for property observer block after executed closure

### ISSUE THREAD

**Issue by calda** [nicklockwood/SwiftFormat#722]
In the example below, `formatter.isStartOfClosure(at: 19)` returns `true`, but should return `false`.

```swift
func testParameterBodyAfterExecutedClosureIsNotClosure() {
    let formatter = Formatter(tokenize("""
    var withBody6: String = { "bar" }() {
        didSet { print("didSet") }
    }
    """))
    XCTAssertFalse(formatter.isStartOfClosure(at: 19))
}
```

This causes the `organizeDeclarations` rule to think this declaration is an `instanceProperty`, rather than an `instancePropertyWithBody`.

(This was discussed in https://github.com/nicklockwood/SwiftFormat/pull/716#discussion_r478797017 — migrating it to an Issue so it can be tracked more easily.)

**Comment by nicklockwood** [comment]
@calda fixed - thanks!
