### ISSUE TITLE
Extend organizeDeclarations to mark protocol conformance extensions

### ISSUE THREAD

**Issue by alphatroya** [nicklockwood/SwiftFormat#727]
Hi! Big thanks for an `organizeDeclarations` rule. It's structuring my code on the fly!

I want to suggest one feature request. Can this rule place MARK: block above each extension block, like this (taken from [here](https://github.com/raywenderlich/swift-style-guide#protocol-conformance))?

```swift
class MyViewController: UIViewController {}

// MARK: - UITableViewDataSource
extension MyViewController: UITableViewDataSource {}

// MARK: - UIScrollViewDelegate
extension MyViewController: UIScrollViewDelegate {}
```

I think it will be useful to discover extensions blocks in the Xcode minimap.

![Снимок экрана 2020-08-31 в 10 21 33](https://user-images.githubusercontent.com/4927633/91693490-c3627f00-eb73-11ea-9172-cf637457d5d7.png)

**Comment by nicklockwood** [comment]
I think this should probably be a separate rule (e.g. `markExtensions`) since it doesn't require any actual code reordering and can be implemented independently.

**Comment by alphatroya** [comment]
Maybe you are right but this action also could move all extensions at the bottom of the file (below the object content) and maybe perform extensions blocks sorting.

**Comment by calda** [comment]
#743 adds support for using `organizeDeclarations` with extensions

**Comment by calda** [comment]
> Can this rule place MARK: block above each extension block

#747 adds a new `markTypes` rule that adds customizable MARK: comments before types and extensions:

```diff
+ // MARK: - FooViewController
+
 final class FooViewController: UIViewController { }

+ // MARK: UITableViewDelegate
+
 extension FooViewController: UITableViewDelegate { }
```
