### ISSUE TITLE
Not removing type definition

### ISSUE THREAD

**Issue by altagir** [nicklockwood/SwiftFormat#738]
Hello, I noticed this new behavior from SwiftFormat

```
-	public let someVar: SomeType= someFunction()
+	public let someVar= someFunction
```

For our coding standards, we prefer to keep the type definition SomeType in our variable declaration.
Makes it more readable without knowing the return of someFunction

is there a new parameter that will let us NOT enforce this new rule ? (i.e. not clean the types)

thanks, regards

**Comment by altagir** [comment]
`--disable redundantType`

**Comment by nicklockwood** [comment]
@altagir the rule is only invoked for the pattern:

```swift
public let someVar: SomeType= SomeType.someFunction()
```

or

```swift
public let someVar: SomeType= SomeType()
```

So another workaround is to rename these to:

```swift
public let someVar: SomeType = .someFunction()
public let someVar: SomeType = .init()
```
