### ISSUE TITLE
Add --verbose option

### ISSUE THREAD

**Issue by garricn** [nicklockwood/SwiftFormat#74]
As a developer, I want to be able to see a verbose output of SwiftFormat so I can know which files are-being or were changed and which are-not-being or were-not changed.

**Comment by ldiqual** [comment]
On the same vibe, knowing which rule applied to which line would be super valuable. Right now I have to "guess" which rule applied by CTRL+F what I think changed in the readme.

**Comment by nicklockwood** [comment]
Implemented in version 0.26.0
