### ISSUE TITLE
IBOutlet variables get 'weak' removed from declaration

### ISSUE THREAD

**Issue by RobertoMachorro** [nicklockwood/SwiftFormat#740]
One of the actions that _SwiftFormat_ took was removing **weak** from my IBOutlet variable declaration:

```swift
-       @IBOutlet weak var someField: NSTextField!
+       @IBOutlet var someField: NSTextField!
```

According to the [Apple documentation](https://developer.apple.com/documentation/uikit/view_controllers/displaying_and_managing_views_with_a_view_controller) (scroll down to _Store References to Important Views_), these should be defined as weak:

> In Swift, include the weak keyword to prevent your view controller from holding a second strong reference to the view—the first originates from the view hierarchy itself.

This to me is a bug and hopefully gets addressed. In the meantime, is there a switch to turn this off? Thanks!

**Comment by nicklockwood** [comment]
This is deliberate, as per Apple's recommendation in the WWDC video (https://developer.apple.com/videos/play/wwdc2015/407/ @ 32:30).

This transform should be safe in virtually all cases, and slightly improves performance. Prior to iOS 6 (when the behavior of viewDidUnload changed), using `weak` was recommended to save memory, but that no longer applies. I suspect that the Apple documentation you linked to just hasn't been updated.

If you prefer to turn this off, you can do so by disabling the `strongOutlets` rule. I suggest taking a look at the [Rules documentation](https://github.com/nicklockwood/SwiftFormat/blob/master/Rules.md) to get a better understanding of the rules that SwiftFormat applies by default and how to disable them.

You can also SwiftFormat run with the `--lint` or `--verbose` option to find out which rules are being applied to which files if you aren't sure how to disable a particular change.

**Comment by RobertoMachorro** [comment]
Thanks! Closing issue.
