### ISSUE TITLE
Update `redundantSelf` rule for Swift 5.3

### ISSUE THREAD

**Issue by nicklockwood** [nicklockwood/SwiftFormat#745]
In Swift 5.3 the requirements for explicit `self` in closures have been relaxed in some case (see https://github.com/apple/swift-evolution/blob/master/proposals/0269-implicit-self-explicit-capture.md) so SwiftFormat should remove `self` in these cases.

**Comment by calda** [comment]
@nicklockwood this was implemented in https://github.com/nicklockwood/SwiftFormat/pull/1303
