### ISSUE TITLE
Multi-line closure parameters cause closure contents to be indented incorrectly

### ISSUE THREAD

**Issue by zacwest** [nicklockwood/SwiftFormat#748]
Given a source file like:

```swift
someFunction { (
    arg1: param,
    arg2: param
) in
    test(arg1, arg2)
}
```

I do not expect the following change:

```diff
@@ -4,5 +4,5 @@
     arg1: param,
     arg2: param
 ) in
-    test(arg1, arg2)
+test(arg1, arg2)
 }
```

I would expect the indent of the code to be where it started here. This happens with the default ruleset (e.g. just `pbpaste | swiftformat`) in version 0.46.3.

**Comment by nicklockwood** [comment]
@zacwest fixed in 0.47.3
