### ISSUE TITLE
Config File

### ISSUE THREAD

**Issue by olbrichj** [nicklockwood/SwiftFormat#75]
I might have missed it, but is there an option to run SwiftFormat with a config file similar to swiftlint?

**Comment by nicklockwood** [comment]
No, currently you have to enter the options via the command line.

**Comment by olbrichj** [comment]
Thanks for the reply. Would be great to add this to the roadmap :)

**Comment by gmosx** [comment]
That would be a great (and obvious?) addition to the tool.

**Comment by alper** [comment]
It would be great if this worked similar to clang-format where it searches either in your project directory or in your $HOME.

**Comment by nicklockwood** [comment]
@olbrichj added in 0.35.0

**Comment by olbrichj** [comment]
great! thank you
