### ISSUE TITLE
Color literals

### ISSUE THREAD

**Issue by AniHovhannisyanAni** [nicklockwood/SwiftFormat#751]
There are some issues related to color literals. Here is the example. Do we miss any rule which will fix it and make one line ?

<img width="348" alt="Screen Shot 2020-09-25 at 12 06 11" src="https://user-images.githubusercontent.com/58420228/94252231-b2b7e580-ff34-11ea-8684-55a39f0e0493.png">

**Comment by nicklockwood** [comment]
This is arguably a bug. I should probably have an option to treat color literals as 1 or 2 characters for the purposes pf wrapping.

**Comment by nicklockwood** [comment]
I'll add a fix for this in the next update. I think the only way to prevent this from wrapping at the moment is to disable the `wrap` rule, or set `--maxwidth` to `none`.

**Comment by nicklockwood** [comment]
@AniHovhannisyanAni I've added a new `--assetliterals` option to control how color/image literals are handled. By default they'll now be treated as having a width of 2 characters.
