### ISSUE TITLE
removes whitespace around inequality operator with repeated if statements

### ISSUE THREAD

**Issue by blackp** [nicklockwood/SwiftFormat#76]
Only used this for the first time today. Seems like a great tool, thanks for making it!

Unfortunately came across a strange bug that introduces a compiler error for one of my files. Please excuse if I'm missing something obvious as a newbie, but I've done a little trial and error and it seems to boil down to multiple if statements in a row.

In my case it's removing whitespace around the less than symbol `if a >= b {` is formatted as `if a>= b`. Which results in a compiler error: ` '>=' is not a postfix unary operator`.

I've attached two files, one is some valid swift that exhibits the bug, and the other is the resulting output of `swiftformat` (v 0.21) with default args.

[test.swift.input.txt](https://github.com/nicklockwood/SwiftFormat/files/681741/test.swift.input.txt)
[test.swift.output.txt](https://github.com/nicklockwood/SwiftFormat/files/681742/test.swift.output.txt)

**Comment by nicklockwood** [comment]
Thanks for reporting it. That definitely shouldn't happen! I'll take a look ASAP.

**Comment by nicklockwood** [comment]
Fixed in version 0.22

**Comment by blackp** [comment]
Thanks @nicklockwood! You beat me to it. I was fascinated to poke around a bit and was just about to post a failing unit test that exhibited the bug in the tokenizer.

I like that your test suite is so comprehensive. Now that I've looked under the hood a bit I'm even more impressed with what you've got here.

**Comment by nicklockwood** [comment]
@blackp thanks!

I haven't managed to fix it properly yet - I just substituted that bug for a less serious one.

So, if you feel like a challenge then by all means keep poking!
