### ISSUE TITLE
`weak` keyword is added automatically during variable declaration

### ISSUE THREAD

**Issue by rafattouqir** [nicklockwood/SwiftFormat#760]
Version: SwiftFormat/CLI (0.46.3)

Issue: 
Global variable name declared with anyName**Delegate** is adding **weak** automatically.

Expected Syntax:

`private var someVarNameDelegate: SomeViewNamedDelegate!`

Current Formatted Syntax:

`private weak var someVarNameDelegate: SomeViewNamedDelegate!`

**Comment by nicklockwood** [comment]
@rafattouqir I'm not aware of any SwiftFormat rule that adds `weak` to delegate properties.

Are you perhaps using SwiftLint with autocorrect in your project as well?

**Comment by rafattouqir** [comment]
> @rafattouqir I'm not aware of any SwiftFormat rule that adds `weak` to delegate properties.
> 
> Are you perhaps using SwiftLint with autocorrect in your project as well?

Yes, I'm.

**Comment by nicklockwood** [comment]
OK, then I guess you should open an issue in https://github.com/realm/SwiftLint/issues :-)

**Comment by rafattouqir** [comment]
Ok, thanks.
