### ISSUE TITLE
space inserted on type cast <>

### ISSUE THREAD

**Issue by altagir** [nicklockwood/SwiftFormat#761]
Hi Nick

Given the following code: 

`        if (error is ApiError < OwnershipErrorCode> &&
                error as! ApiError<OwnershipErrorCode>)
        { }
`

swiftformat inserted 2 "space" around the first "<"
thinking I guess it was a comparison operator

it is not applied after.

**Comment by nicklockwood** [comment]
@altagir fixed in 0.47.0
