### ISSUE TITLE
Option to preserve previous behavior for indent rule

### ISSUE THREAD

**Issue by calda** [nicklockwood/SwiftFormat#772]
`0.47` includes changes to the `indent` rule to match Xcode 12's default indentation:

```diff
  if let foo = foo,
-   let bar = bar
+    let bar = bar
  { ... }

  guard let foo = foo,
-  let bar = bar
+       let bar = bar
  else { ... }
```

I chatted about this with folks at Airbnb, and our stance is that our style guide prefers non-variable indentation (e.g. to [always indent by 2 spaces](https://github.com/airbnb/swift#spaces-over-tabs)).

Since the previous behavior is no longer supported, we've had to disable the `indent` rule for our codebase. It would be nice if there was an option to configure this behavior, so folks can continue using the old style.

**Comment by nicklockwood** [comment]
@calda sorry, I probably should have added such an option. The logic that controls this is fairly self-contained within the `linewrapIndent(at:)` method in `ParsingHelpers.swift`, so it should be simple enough to add a flag to disable it - do you want to tackle that?

Note: prior to 0.47.0 this alignment was already performed for wrapped switch case statements, so I don't know if you'd want to preserve that as a special case when disabling it for the rest, or maybe add some configuration to control which keywords to apply it to?

**Comment by calda** [comment]
> this alignment was already performed for wrapped switch case statements

can you share an example of this? can't picture what you mean off the of my head

**Comment by nicklockwood** [comment]
```swift
switch foo {
  case .bar,
       .baz: // aligned with .bar regardless of indent setting
}

**Comment by calda** [comment]
I think we've settled on preferring this style for multiline conditionals:

```swift
if
  let foo = foo,
  let bar = bar
{ ... }

guard
  let foo = foo,
  let bar = bar
{ ... }
```

We think this is better than the old style, since the old style now conflicts with default Xcode indentation behavior (meaning engineers have to actively fight Xcode to format their code like this now):

```swift
if let foo = foo,
  let bar = bar
{ ... }

guard let foo = foo,
  let bar = bar
{ ... }
```

So I think I'll put up a PR for a new `wrapMultilineConditional` rule that supports this wrapping behavior (this will let us keep the `indent` rule enabled without having to add back support for the old indentation style that now fights Xcode).

**Comment by calda** [comment]
Or do you think it would make sense to have this be an option for one of the existing rules? `wrapMultilineStatementBraces` and `indent` are both _related_ to this sort of behavior, but the existing names may not be a perfect fit.

**Comment by nicklockwood** [comment]
@calda I thing this behavior is most similar to the existing `wrapArguments` rule, which already has the following options:

```
--wraparguments    Wrap all arguments: "before-first", "after-first", "preserve"
--wrapcollections  Wrap array/dict: "before-first", "after-first", "preserve"
--wrapparameters   Wrap func params: "before-first", "after-first", "preserve"
```

So perhaps we could add something like:

```
--wrapconditions    Wrap conditions: "before-first", "after-first", "preserve"
```

The naming is a bit tricky though. A problem with using "conditions"/"conditionals" is that this also applies to regular let/var:

```swift
let foo = foo,
    let bar = bar,
    let baz = baz
```

Which isn't really anything to do with "conditions".

**Comment by nicklockwood** [comment]
There's another case to consider which is the wrapping of regular property declarations, which don't really fit into the "conditions"/"conditionals" naming:

```swift
let foo = bar,
    baz = quux
```

**Comment by nicklockwood** [comment]
I guess one solution to the above would be to explicitly forbid multiple variable assignments on one line, and rewrite:

```swift
let foo = bar,
    baz = quux
```

to

```swift
let foo = bar
let baz = quux
```

The same solution can also be applied to enum cases (and in fact the `wrapEnumCases` rule already does that).
