### ISSUE TITLE
Crash since updating to 0.47.0

### ISSUE THREAD

**Issue by adam-fowler** [nicklockwood/SwiftFormat#780]
Since updating to 0.47.0 swiftformat. I get a crash when running swiftformat on https://github.com/soto-project/soto. The crash seems to be an array index out of range in `parseDeclations` line 1287. https://github.com/nicklockwood/SwiftFormat/blob/30fe580f85d99108a6313caabcc41287dc90e1db/Sources/ParsingHelpers.swift#L1287

Steps to repro
1) git clone https://github.com/soto-project/soto
2) cd soto
3) swiftformat Source/Soto/Services/SNS/SNS_Shapes.swift

**Comment by nicklockwood** [comment]
Thanks for reporting - I'll take a look.

**Comment by nicklockwood** [comment]
Fixed in 0.47.1
