### ISSUE TITLE
Recent change is hoisting "private(set)" left past "static" which is 😿. 

### ISSUE THREAD

**Issue by haikusw** [nicklockwood/SwiftFormat#784]
I'm wondering if SwiftFormat is confusing `private(set)` with `private`?
This feels like a relatively recent change (1-3 versions ago it didn't do this).

---- 

Swift code we have:

```
class Fetcher: ObservableObject {
	static private(set) var shared = Fetcher()
       // ....
}
```	

SwiftFormat version 0.47.1 does this to it:

```
class Fetcher: ObservableObject {
	private(set) static var shared = Fetcher()
       // ....
}
```

And we would prefer it leave this alone.

our minimal `.swiftformat` file:

> --ifdef no-indent
> --indent tabs
> --disable blankLinesAroundMark,consecutiveSpaces,unusedArguments,redundantFileprivate
> --tabwidth 4

and `.swift-version`:

> 5.1

// we should increment that as we are using 5.3

---

Seems like we can override with a custom modifierOrder setting, but the current behavior doesn't seem like the intended default?  Docs not entirely clear, but first example is somewhat related:

> modifierOrder
> 
> Use consistent ordering for member modifiers.
> 
> Options:
> 
> --modifierorder    Comma-delimited list of modifiers in preferred order
> 
> Examples:
> 
> - lazy public weak private(set) var foo: UIView?
> + public private(set) lazy weak var foo: UIView?
> 
> ...

----

GitHub swift style guide doesn't have anything to say about this, but the [RayWenderlich one](https://github.com/raywenderlich/swift-style-guide#access-control) does:

> Use access control as the leading property specifier. **The only things that should come before access control are the static specifier** or attributes such as @IBAction (etc)

Thanks, as always, for SwiftFormat!

**Comment by nicklockwood** [comment]
@haikusw I don't think this was a recent change, but maybe a bug fix or some other change meant it's now being applied when it wasn't before? In any case, you configure it with the `--modifierorder` option as you guessed. The syntax is:

```
--modifierorder static,private,private(set)
```

`private` also applies to `public`, etc, so no need to specify every variant, but you may need to add others like `override` depending on where you want them to appear in the relative order.

**Comment by haikusw** [comment]
Thanks.  I'll override the current default using the info you shared, thanks.

As for this ticket - is the default behavior what you want SwiftFormat to do?
Doesn't seem like it to me (hence the bug report) but up to you, of course (feel free to close this if so).

**Comment by nicklockwood** [comment]
@haikusw yes, this is intended default (access modifiers first before everything else). It also matches the SwiftLint default: https://realm.github.io/SwiftLint/modifier_order.html

**Comment by haikusw** [comment]
Thanks for the reply.  

I don't know what the creators' of SwiftLint's reasoning is for that choice, but it doesn't make sense to me.  Programmer using the class needs to know if the property is accessible from an instance or a class in every case, but needs to know if a setter is accessible far less often (and even less often than that as an implementor or maintainer of the class).  Also, this default doesn't follow the convention of most other languages I've used (storage class specifier should be first), though admittedly that's anecdotal in the extreme :) 

Even the private field specifier added to JavaScript 2019 is written after the `static` (by language definition, not style guide).  ¯\_(ツ)_/¯ 

Anyway, your tool - you get to pick :)

I remain grateful for SwiftFormat and use it many times a day.
Happy there's a way to customize this so that it works the way it should ( 😂 ) so I can keep using it or at least can use it without being annoyed :)

cheers, and thanks again!
