### ISSUE TITLE
Regression since 0.47.2

### ISSUE THREAD

**Issue by JohnEstropia** [nicklockwood/SwiftFormat#789]
We've seen weird formatting like this after upgrading to 0.47.2
<img width="1499" alt="screen_shot_2020-11-05_at_15 20 02" src="https://user-images.githubusercontent.com/3029684/98205998-7be5de00-1f7c-11eb-9fec-804ee43cba8c.png">

Might be related to the changes made here? https://github.com/nicklockwood/SwiftFormat/issues/786

**Comment by nicklockwood** [comment]
@JohnEstropia thanks for reporting this, I'll get it fixed

**Comment by nicklockwood** [comment]
@JohnEstropia fixed in 0.47.3

**Comment by JohnEstropia** [comment]
@nicklockwood Thanks for the update!
Unfortunately, it looks like `guard case`s were fixed but missed some edge cases in `switch-case`:
<img width="501" alt="Screen Shot 2020-11-10 at 14 47 40" src="https://user-images.githubusercontent.com/3029684/98632873-b1673e80-2363-11eb-99ab-a49b42b16711.png">

**Comment by nicklockwood** [comment]
@JohnEstropia fixed in 0.47.4
