### ISSUE TITLE
weird unusedArguments replacement

### ISSUE THREAD

**Issue by charmaex** [nicklockwood/SwiftFormat#79]
Hi Nick,

using SwiftFormat 0.22 it replaced unused variable names in methods which I like in general.

But I find this a bit weird looking:

func x(name: String) to func x(name _: String)

func x(_ name: String) to func x(_: String) ist looking fine.

I'd appreciate if you change the upper behaviour to leave it as is :)

Thanks for your time

**Comment by nicklockwood** [comment]
Yeah, I agree that it does look a bit weird.

I'll consider adding an option to disable the feature for named arguments only.

In the meantime, you can disable the rule altogether by adding `--disable unusedArguments` to the command line.

**Comment by nicklockwood** [comment]
@charmaex in SwiftFormat 0.24 (just released), you can now use `--stripunusedargs unnamed-only` to get the effect you were asking for.
