### ISSUE TITLE
Opinionated Format

### ISSUE THREAD

**Issue by laktak** [nicklockwood/SwiftFormat#791]
Would it be possible to provide an opinionated format similar to what black does for python?

Not sure if you have heard about [black](https://github.com/psf/black) but this basically removes any arguments in the team about code styling - just use black.

**Comment by nicklockwood** [comment]
The opinionated format option is the default.

**Comment by nicklockwood** [comment]
@laktak apologies if my first reply seemed dismissive, but I meant it as a genuine answer. The settings I've selected as the default for SwiftFormat are the ones I use myself, and which I think are good.

Is there something else I can do to make the tool seem more opinionated? (besides removing configuration options, of course)

**Comment by laktak** [comment]
No problem. In the case of Python/black the format is defined by the community, not by the tools author. I am very new to Swift so I'm not sure such a thing exists (yet). If/when it does, a special "black" option could follow the guidelines without you having to change the defaults. It would also make sure that any config files are ignored.

Either way, maybe you could add a "Opinionated Format" section in your readme. It is getting common with other languages as well (e.g. see prettier).

**Comment by nicklockwood** [comment]
@laktak that makes sense. There's no definitive community standard AFAIK, but I've considered adding a `--styleguide` parameter that would be a shortcut for selecting a preset of existing, popular community styles like Google's or Ray Wenderlich's.

**Comment by laktak** [comment]
I'll be using the defaults for now but I think that's a good idea. Thanks!
