### ISSUE TITLE
Can I insert two lines by using blankLinesBetweenScopes rule?

### ISSUE THREAD

**Issue by yosshi4486** [nicklockwood/SwiftFormat#793]
Hello.

I usually use a style of inserting two lines between symbols for visibility. Can I format the style with SwiftFormat's rules?

**Comment by nicklockwood** [comment]
@yosshi4486 when you say "two lines", do you mean two consecutive return characters, or two whole blank lines?

**Comment by yosshi4486** [comment]
I mean two whole blank lines 😃

**Comment by nicklockwood** [comment]
@yosshi4486 this isn't something that SwiftFormat currently supports, sorry.

**Comment by yosshi4486** [comment]
OK. @nicklockwood Thank you for your quick and polite response!
