### ISSUE TITLE
[Header flag] header flag is not working as expected

### ISSUE THREAD

**Issue by mustiikhalil** [nicklockwood/SwiftFormat#798]
Good evening, first of all thanks for this amazing library! I am trying to use the `--header "copyright"` flag that is supposed to be working according to the readme.

 I've tried the following:

1- `swiftformat --config swift.swiftformat . --verbose --cache clear --header "{file}\nCopyright (c) {year} Foobar Industries\nCreated by John Smith on {created}."` 

2- 
```
--swiftversion 5.1

# format
--allman true
--indent 2
--maxwidth 100

# options
--self remove # redundantSelf
--importgrouping testable-bottom # sortedImports
--commas always # trailingCommas
--trimwhitespace always
--indentcase false
--ifdef no-indent #indent
--wraparguments before-first # wrapArguments
--wrapparameters before-first # wrapArguments
--wrapcollections before-first # wrapArguments
--closingparen same-line # wrapArguments
--funcattributes prev-line # wrapAttributes
--typeattributes prev-line # wrapAttributes
--structthreshold 20 # organizeDeclarations
--enumthreshold 20 # organizeDeclarations
--trailingclosures false

# rules
--rules todos,anyObjectProtocol,redundantParens,redundantReturn,redundantSelf,sortedImports,strongifiedSelf,trailingCommas,trailingSpace,wrapArguments,wrapMultilineStatementBraces,indent,wrapAttributes,organizeDeclarations,void
--disable trailingclosures

--exclude **/*_generated.swift
--exclude **/*.grpc.swift
```

some of the swift files didn't have the header, and others did, example:

```
import Foundation
```

```
//
// File.swift
//

import Foundation
```
however the output from the formatter is still the same for all the options that I mentioned above

```
-- no changes
Formatting /Users/mustii/flatbuffers/swift/Sources/FlatBuffers/Message.swift
-- no changes
Formatting /Users/mustii/flatbuffers/swift/Sources/FlatBuffers/FlatBuffersUtils.swift
-- no changes
Formatting /Users/mustii/flatbuffers/swift/Sources/FlatBuffers/ByteBuffer.swift
```

**Comment by nicklockwood** [comment]
@mustiikhalil in your list of `--rules` you don't have the `fileHeader` rule enabled. That's why the `--header` argument is being ignored.

(I should probably add a warning when you specify options for rules that are disabled).

**Comment by mustiikhalil** [comment]
@nicklockwood thanks! that was actually helpful! Maybe if you update the readme for the headers to include that the `--header` requires the `fileHeader` rule because I honestly thought its a rule by itself.

**Comment by nicklockwood** [comment]
@mustiikhalil I've added a warning for this in 0.47.4

**Comment by mustiikhalil** [comment]
Thanks!
