### ISSUE TITLE
Exclude path with whitespace

### ISSUE THREAD

**Issue by dogo** [nicklockwood/SwiftFormat#799]
Hi, I'm trying to set a specific folder as excluded, but the folder path has a whitespace eg:
```
# file options
--exclude Folder Space/Classes/Resources
```
How I should proceed? All the files inside this folder are changing and shouldn't

**Comment by nicklockwood** [comment]
@dogo it should work if you escape the space with a backslash:

```
--exclude Folder\ Space/Classes/Resources
```

Or if you put the path in quotes

```
--exclude "Folder Space/Classes/Resources"
```

**Comment by nicklockwood** [comment]
@dogo actually, in the context of a .swiftformat config file, it shouldn't be necessary to escape the spaces, so maybe something else is wrong?

Could you have a typo in the path? Or maybe the case doesn't match?

**Comment by dogo** [comment]
Thanks, @nicklockwood it's working fine escaping or using quotes.

**Comment by nicklockwood** [comment]
@dogo thanks for confirming, although I'm now slightly confused because from the implementation it looks like this shouldn't be necessary. I suspect there's a bug I need to investigate.

**Comment by dogo** [comment]
I have two folders with the same name but with diferent paths, maybe the code gets confused with this situation, thats why I should explicitly show the path?

**Comment by nicklockwood** [comment]
@dogo can you just check which version of SwiftFormat you have? (run it with --version)

**Comment by dogo** [comment]
I'm using mint to manage, this is my current version
`nicklockwood/SwiftFormat@0.47.2`

**Comment by nicklockwood** [comment]
@dogo hmm, that's close to the latest, so that can't be the problem. OK thanks, I'll keep digging.
