### ISSUE TITLE
-f option for Run Script in automate section of the README?

### ISSUE THREAD

**Issue by headcrash13** [nicklockwood/SwiftFormat#8]
**${SRCROOT}/path/to/swiftformat -f /path/to/your/swift/code/**

Results in a: **error: unknown argument: -f.**

Shouldn't the -f be removed? I wasn't sure if there was a "hidden" argument for a build environment..?

I removed the -f, and it seems to be functioning as intended.

**Comment by nicklockwood** [comment]
Yeah sorry, that's left over from an earlier version. I'll update the docs.

**Comment by nicklockwood** [comment]
Fixed in v0.5
