### ISSUE TITLE
markTypes incorrectly treating import statement as type definition

### ISSUE THREAD

**Issue by calda** [nicklockwood/SwiftFormat#801]
`markTypes` uses the `--groupedextension` MARK template when the type being extended was defined higher up within the same file, for example:

```swift
// MARK: - MyComponent

struct MyComponent { }

// MARK: Equatable

extension MyComponent: Equatable {
  // ..
}
```

It appears that `0.47.2` or `0.47.3` introduced a regression where `markTypes` would incorrectly treat an import statement as a type definition.

### Expected behavior / behavior in 0.47.1:

```swift
import MagazineLayout

// MARK: MagazineLayout + FooProtocol

extension MagazineLayout: FooProtocol {
  // ...
}

// MARK: MagazineLayout + BarProtocol

extension MagazineLayout: BarProtocol {
  // ...
}

```

### Actual behavior:

```swift
import MagazineLayout

// MARK: FooProtocol

extension MagazineLayout: FooProtocol {
  // ...
}

// MARK: BarProtocol

extension MagazineLayout: BarProtocol {
  // ...
}
```

**Comment by nicklockwood** [comment]
@calda your fix is included in version 0.47.4
