### ISSUE TITLE
Bug: "SwiftFormat for Xcode" does not work on Big Sur 11.0.1 and Xcode 12.2 (12B45b)

### ISSUE THREAD

**Issue by imWildCat** [nicklockwood/SwiftFormat#804]
The menu item is greyed out, in a disabled state:

<img width="251" alt="image" src="https://user-images.githubusercontent.com/2396817/99180513-bb24e380-2761-11eb-84a6-7dba4e0d4e9d.png">

Log:

```
default	16:44:17.778106+0800	SwiftFormat	Requesting container lookup; class = 4, identifier = <private>, temp = 0, create = 0, euid = 501, uid = 501, personaid = -1, type = NOPERSONA, name = <unknown>
default	16:44:17.778831+0800	SwiftFormat	container_create_or_lookup_for_platform: success
default	16:44:17.781037+0800	SwiftFormat	Hello, I'm launching as euid = 501, uid = 501, (persona not available)
default	16:44:17.787350+0800	SwiftFormat	Initializing connection
default	16:44:17.787420+0800	SwiftFormat	Removing all cached process handles
default	16:44:17.787460+0800	SwiftFormat	Sending handshake request attempt #1 to server
default	16:44:17.787484+0800	SwiftFormat	Creating connection to com.apple.runningboard
default	16:44:17.788121+0800	SwiftFormat	Handshake succeeded
default	16:44:17.788156+0800	SwiftFormat	Identity resolved as xpcservice<com.charcoaldesign.SwiftFormat-for-Xcode.SourceEditorExtension([app<application.com.apple.dt.Xcode.29526820.29553638(501)>:19276])(501)>
error	16:44:17.788882+0800	SwiftFormat	Bootstrapping; external subsystem UIKit_PKSubsystem refused setup
default	16:44:17.788923+0800	SwiftFormat	Bootstrapping; Bootstrap complete. Ready for handshake from host.
default	16:44:17.790302+0800	SwiftFormat	[u D30A2660-BB60-4B7C-9FDD-D8EE23ABA8FD] [(null)((null))] Prepare received as euid = 501, uid = 501, (persona not available)
default	16:44:17.791074+0800	SwiftFormat	[u 286C7234-9581-404B-9740-EF93D494333D] [<private>(<private>)] Set sole personality.
default	16:44:17.792705+0800	SwiftFormat	[u 286C7234-9581-404B-9740-EF93D494333D] [<private>(<private>)] Begin using received as euid = 501, uid = 501, (persona not available)
default	16:44:17.799238+0800	SwiftFormat	Loading XcodeKit failed: Error Domain=XCExtensionRendezvousErrorDomain Code=4 "(null)"
default	16:44:22.875324+0800	SwiftFormat	[u 286C7234-9581-404B-9740-EF93D494333D] [<private>(<private>)] Removed sole personality.
default	16:44:22.875474+0800	SwiftFormat	[u 286C7234-9581-404B-9740-EF93D494333D] [<private>(<private>)] host connection from pid 19276 invalidated
```

**Comment by nicklockwood** [comment]
@imWildCat can you try building the extension locally from source? I suspect some kind of permissions issue, but I don't have Big Sur yet to test on.

**Comment by imWildCat** [comment]
@nicklockwood Yeah. I found that, if I built it locally using Xcode 12.2, it can work:
<img width="459" alt="image" src="https://user-images.githubusercontent.com/2396817/99181303-94b67680-2768-11eb-943c-93e42a744731.png">

**Comment by nicklockwood** [comment]
@imWildCat I've rebuilt the extension with Xcode 12.2 - can you check if it now works for you?

**Comment by imWildCat** [comment]
@nickffox Do you mean `0.46.3`? Does not work
<img width="287" alt="sc" src="https://user-images.githubusercontent.com/2396817/99384089-e21e1980-2909-11eb-8b8b-67b778a2de42.png">

**Comment by nicklockwood** [comment]
@imWildCat no, I mean version 0.46.4 (released yesterday)

**Comment by imWildCat** [comment]
@nicklockwood I cannot find 0.46.4?

<img width="402" alt="image" src="https://user-images.githubusercontent.com/2396817/99549959-2afecc80-29f5-11eb-9b02-f3bd07cf5d58.png">

**Comment by nicklockwood** [comment]
@imWildCat I meant 0.47.4 (you said 0.46.3 so I got confused).

**Comment by imWildCat** [comment]
![image](https://user-images.githubusercontent.com/2396817/99747980-870d4200-2b16-11eb-9b5b-da044330e741.png)
Yeah I can confirm this fix!

Thanks for your help! And sorry for the delay.

**Comment by imWildCat** [comment]
Update: I reproduced this issue while upgrading Xcode from 12.4 to 12.5 by replacing the `Xcode.app` in the `Applications` folder.

After that, no matter what I do for the SwiftFormat for Xcode app, it cannot be fixed.

Today, I upgraded my system from 11.3.0 to 11.3.1. After the upgrade, Xcode asked me to install the command line tools again.

After that, this issue is fixed.

**Comment by imWildCat** [comment]
Another update: this should definitely be a bug from Apple:

<img width="149" alt="image" src="https://user-images.githubusercontent.com/2396817/127760409-6b78f3fa-45c4-4802-b55e-2d93cc32947a.png">

On M1 Mac mini with macOS 12.0 Beta (21A5294g), this bug can also be reproduced.

Solution: Rename the Xcode-beta.app name.

Submitted FB9437919

**Comment by imWildCat** [comment]
> This fixed my similar issue:
> Rename Xcode to Xcode10, launch Xcode10 then quite.
> Rename Xcode10 back to Xcode.
> 
> Actually after step 1, "System Prefs - > Extensions" back to normal, but I just want the default app name back.

Source: <https://developer.apple.com/forums/thread/110042>
