### ISSUE TITLE
Make actual "releases" on GitHub?

### ISSUE THREAD

**Issue by jessesquires** [nicklockwood/SwiftFormat#805]
Hey @nicklockwood 👋 

I wanted to request that the project make "proper" releases on GitHub (instead of just git tags), otherwise the "Watch Releases" notification setting on GH doesn't seem to work. Personally, I use this so I can stay up-to-date easily and always get notified.

For example / comparison:
- SwiftFormat "tag-only" releases: https://github.com/nicklockwood/SwiftFormat/releases
- SwiftLint "proper" releases: https://github.com/realm/SwiftLint/releases

For lack of a better term, "proper" releases [send a notification](https://github.blog/changelog/2018-11-27-watch-releases/) if you set the repo "Watch" setting to "Releases Only".

---

You can easily create releases from tags in the GitHub web UI, but it can also be scripted via the GH API.

If you are concerned about writing release notes there, that is also optional. (You could just link to the changelog every time.) I think only title is required, but that can just be the version number.

**Comment by nicklockwood** [comment]
Done - thanks for the suggestion!

**Comment by jessesquires** [comment]
it worked! 💯 

thanks @nicklockwood ! 🎉 

<img width="1183" alt="Screen Shot 2020-11-19 at 2 27 45 PM" src="https://user-images.githubusercontent.com/2301114/99731919-6cce5800-2a73-11eb-9ca2-683639ebd92d.png">
