### ISSUE TITLE
Reading files even if it's excluded

### ISSUE THREAD

**Issue by matheusalano** [nicklockwood/SwiftFormat#807]
Hey.

I was running SwiftFormat on a Linux environment and it was failing because our project has a symlink and the referenced file didn't exist. 

Even though I set this symlink as `--excluded` in the `.swiftformat` file, the error still occurs. 
It seems like SwiftFormat tries to read all files even when the file is in the excluded list. 

I believe that the files should be filtered by the excluded list first and then read.

**Comment by nicklockwood** [comment]
@matheusalano thanks for the report. Fixed in 0.47.5.
