### ISSUE TITLE
[Q] Console coloring

### ISSUE THREAD

**Issue by kdubb** [nicklockwood/SwiftFormat#81]
Is `swiftlint` coloring its output?  My console is so dark it's unreadable.

<img width="552" alt="screen shot 2017-01-12 at 1 45 17 pm" src="https://cloud.githubusercontent.com/assets/787655/21909618/ed566eb6-d8d5-11e6-8787-37b9c3f4d9b2.png">

**Comment by nicklockwood** [comment]
Yes, it's setting the color to black, which I assumed was the default, but it seems not.

**Comment by nicklockwood** [comment]
Fixed in 0.23.1
