### ISSUE TITLE
Binary size doubled

### ISSUE THREAD

**Issue by alexito4** [nicklockwood/SwiftFormat#812]
On 0.47.3 the CLI binary is 2.5mb. (increased a bit on the last few versions from 2MB). 
But then on 0.47.4 it went to 4.6 MB. 

I see the GitHub release page includes now assets for the binary itself. I checked that one and also the one committed in the source. Both are the same.

I'm not sure if this change is legit so I'm raising it. Seems that something changed.

**Comment by nicklockwood** [comment]
@alexito4 it now includes the arm64 slice for M1 Macs.

**Comment by alexito4** [comment]
> @alexito4 it now includes the arm64 slice for M1 Macs.

That makes sense. The future of the Mac is here ^^
