### ISSUE TITLE
InitCoderUnavailable Rule Enhancement Request

### ISSUE THREAD

**Issue by PompeiaPaetenari** [nicklockwood/SwiftFormat#813]
It has been requested and mentioned by a few on the team that, with this rule, we would like to have the full correction as the error is not needed at this point:

```swift
@available(*, unavailable)
required init?(coder _: NSCoder) { nil }
```

Can this be done? :D

**Comment by nicklockwood** [comment]
Implemented via the `--initcodernil` config option
