### ISSUE TITLE
Add explicit-type option for Redundant Type rule

### ISSUE THREAD

**Issue by namolnad** [nicklockwood/SwiftFormat#816]
As an alternative to the current Redundant Type rule default behavior added in #706, it would be nice if we could have SwiftFormat transform redundant types to keep the explicit type declaration and assign using `.init(`
### Current
`let frame: CGRect = CGRect` -> `let frame = CGRect(`
### Proposed
--redundant-type explicit-type
`let frame: CGRect = CGRect(` -> `let frame: CGRect = .init(`.

**Comment by nicklockwood** [comment]
@namolnad landed in 0.47.5. Thanks 👍
