### ISSUE TITLE
Transforming `private` into `fileprivate` making confusing sometimes

### ISSUE THREAD

**Issue by Ckitakishi** [nicklockwood/SwiftFormat#819]
Hi, my team is considering using `--extensionacl on-declarations` to help reformat extensions's  access control keywords.

```diff
- private extension Foo {
-     func bar() {}
  }

+ extension Foo {
+     fileprivate func bar() {}
  }
```

In this case, the `private` keyword will be transformed to `fileprivate`, `private` is equivalent to `fileprivate` here, but this behavior makes confusing sometimes, so we need to keep the keywords as they are.

Is it possible to add a new option? Or do you have any other idea?

**Comment by nicklockwood** [comment]
This might be handled by enabling the `redundantFileprivate` rule as well, but I'll check.

**Comment by Ckitakishi** [comment]
Thank you for your advice~!
But what we want is the modifiers can be kept as before after reformatting even if they are equivalent.

By the way, I tried enable `redundantFileprivate` + `--extensionacl on-declarations`, however the `private` keyword will still be transformed to `fileprivate`, I'm assuming it's because `redundantFileprivate` executed first?

**Comment by nicklockwood** [comment]
@Ckitakishi rules are supposed to be executed recursively to avoid ordering problems like that, so it might be a bug. It's also possible that SwiftFormat doesn't consider `private` and `fileprivate` to be semantically equivalent in this case (which may also be a bug).

**Comment by Ckitakishi** [comment]
Oh, I see, thank you for for explaining!

**Comment by nicklockwood** [comment]
@Ckitakishi fixed in 0.47.6

**Comment by nicklockwood** [comment]
@Ckitakishi I had to revert this change in 0.47.7 as I realized it was unsafe. `private` at file scope is not semantically equivalent to `private` inside an extension, except when accessed from inside other extensions on the same type.

I've kept the fix for `redundantFileprivate` however, so if you enable that rule as well then it should convert the `fileprivate` back to `private` in cases where it's safe to do so.

**Comment by Ckitakishi** [comment]
Sorry for late, I checked the changes, since `private` and `fileprivate` are not semantically equivalent inside extension, I agree the current solution is safe, also makes sense. 

Then I tried enable `redundantFileprivate` and add `--extensionacl on-declarations`, it works well now, thanks for your wonderful work!
