### ISSUE TITLE
FilePrivate Rule is Breaking an init()

### ISSUE THREAD

**Issue by PompeiaPaetenari** [nicklockwood/SwiftFormat#826]
We have an extension in a file that is basically:
```swift
extension People.Legacy {
  public init(…) { … }
  public init?(…) { … }
  fileprivate init(url: URL, …) { … }
}
```
And then at the bottom of the file.
```swift
extension People {
  public enum Member {
    public static func impression(url: URL, …) -> People.Legacy {
      return Legacy(url: url, …)
    }
  }
}
```
And when SwiftFormat comes through the file, it changes the `fileprivate` to `private` and then is unable to compile, talking about too many arguments and inability to map `url` to `PeopleTracking`.  Luckily, this is the only one of 148 files where it went wrong, but hopefully that is enough to go by for a fix?

Let me know!  Just going to disable that rule for this line for my SwiftFormat upgrade PR.

**Comment by nicklockwood** [comment]
@PompeiaPaetenari thanks for reporting. Fixed in 0.47.7.
