### ISSUE TITLE
[Question] Conditional Returns on newline

### ISSUE THREAD

**Issue by victorBaro** [nicklockwood/SwiftFormat#831]
I am trying to achieve (this)[https://realm.github.io/SwiftLint/conditional_returns_on_newline.html] using swiftformat but so far I have had no luck with the existing set of rules. 

Basic examples:

```swift
// original
guard true else { return }

// after formatting
guard true else { 
  return 
}
```

Main idea is to always return after `{` (essentially avoid one-liners)

**Comment by nicklockwood** [comment]
@victorBaro there's no such rule at the moment I'm afraid. Should be fairly simple to implement though.

**Comment by victorBaro** [comment]
I will look into that, maybe if I am successful even submit a PR. Thanks for the quick reply

**Comment by nicklockwood** [comment]
Implemented by the `wrapConditonalBodies` rule, implemented here: https://github.com/nicklockwood/SwiftFormat/pull/989
