### ISSUE TITLE
Prevent Automatic Formatting On Build

### ISSUE THREAD

**Issue by everythingaud** [nicklockwood/SwiftFormat#834]
I've installed SwiftFormat as a pod and added SwiftFormat as a run script in the build phase like so `"${PODS_ROOT}/SwiftFormat/CommandLineTool/swiftformat" $SWIFTFORMAT_MODE "$SRCROOT"`

I also have the SwiftFormat XCode extension installed to help me format files automatically. However, I find that my files are getting automatically formatted whenever I build. How do I prevent this from happening? I would like SwiftFormat to just throw errors and for me to fix these formatting issues myself unless I decide I need help.

**Comment by nicklockwood** [comment]
@everythingaud add the `--lint` argument to just report errors instead of fixing them.

**Comment by everythingaud** [comment]
@nicklockwood Hi thanks for answering so quickly! Do I add the `--lint` argument to the build phase?

**Comment by nicklockwood** [comment]
@everythingaud I'm not sure where the $SWIFTFORMAT_MODE in your script comes from, so maybe it should be added to that? But otherwise, this should work:

```
"${PODS_ROOT}/SwiftFormat/CommandLineTool/swiftformat" $SWIFTFORMAT_MODE "$SRCROOT" --lint
```
