### ISSUE TITLE
Disable a rule for a single line, a block of code etc.

### ISSUE THREAD

**Issue by AlexGustafsson** [nicklockwood/SwiftFormat#838]
In the code below, the `self.count == 0` comparison will be exchanged with `self.isEmpty` if the `isEmpty` rule is enabled. This is clearly not wanted in this case as it will cause a infinite loop of `self.isEmpty = self.isEmpty`.

```swift
public struct Queue<T> {
  private var array = [T?]()
  private var head = 0

  public var isEmpty: Bool {
    self.count == 0
  }

  public var count: Int {
    self.array.count - self.head
  }

 // ...
}
```

I'd therefore want to disable that rule for this particular line. I cannot find any previous issue or code regarding this in the repository, so I assume it's impossible for now.

I propose adding support for controlling linting / formatting with comments in the code, much like [how eslint does it](https://eslint.org/docs/2.13.1/user-guide/configuring#disabling-rules-with-inline-comments).

**Comment by nicklockwood** [comment]
@AlexGustafsson this is already supported. See https://github.com/nicklockwood/SwiftFormat#rules

**Comment by AlexGustafsson** [comment]
That’s great! Not sure how I missed that one. Closing.
