### ISSUE TITLE
Sensible defaults

### ISSUE THREAD

**Issue by shamilovtim** [nicklockwood/SwiftFormat#840]
Hello! I installed this package and formatted my code with all of the default options and it changed all of my parameters from explicit named to _unnamed. This broke multiple methods that were using named parameters. I don't think that this should be the default option for a public formatter, especially if it doesn't know whether it's breaking existing code.

**Comment by nicklockwood** [comment]
@shamilovtim you're right of course that it shouldn't break code by default, but I've not encountered this bug before.

Can you share some examples source files where SwiftFormat caused breaking changes? 

If you can't share the files publicly, please send them to support@charcoaldesign.co.uk

**Comment by nicklockwood** [comment]
@shamilovtim any update on this?
