### ISSUE TITLE
error: 'ranges' is not a formatting rule. Did you mean 'spaceAroundOperators'?

### ISSUE THREAD

**Issue by funzin** [nicklockwood/SwiftFormat#842]
I got the following error when run swiftformat.
> error: 'ranges' is not a formatting rule. Did you mean 'spaceAroundOperators'?

As of 0.47.1, it was a warning, but since 0.47.2, the error seems to be happening.
The error is output, but the formatting behavior is still there.
The following is the `.swiftformat` that I am using.

```.swiftformat
# disable
--disable wrapMultilineStatementBraces

# format options
--stripunusedargs closure-only
--self init-only
--commas inline
--extensionacl on-declarations
```

**Comment by nicklockwood** [comment]
@funzin it seems likely that you either have another .swiftformat file somewhere, or you are passing some arguments to the swiftformat command line tool. Is that possible?

Swiftformat logs all of the config files that it encounters while running in the console, if that helps.

**Comment by funzin** [comment]
The `.swiftformat` was also included under `Carthage/Checkout`😇
I was able to fix it by changing the path.

Thanks for the reply:pray:
