### ISSUE TITLE
Issue with multi-line expression in guard statement using --xcodeindentation enabled

### ISSUE THREAD

**Issue by malonehedges** [nicklockwood/SwiftFormat#848]
The red is what Xcode indents and the green is what SwiftFormat changes it to.

<img width="501" alt="image" src="https://user-images.githubusercontent.com/12092296/104219997-b4c68700-53f3-11eb-897a-7a915f723209.png">

(using v0.47.10)

**Comment by nicklockwood** [comment]
@malonehedges fixed in 0.47.11. Sorry for the wait!
