### ISSUE TITLE
Modifier order option syntax

### ISSUE THREAD

**Issue by shimon-azulay-healthy** [nicklockwood/SwiftFormat#849]
Hi 👋 
I couldn't find the full syntax for `--modifierorder` option. 
I am using SwiftLint as well and want to align it. 
SwiftLint modifier order is:         
```
            .override,
            .acl,
            .setterACL,
            .dynamic,
            .mutators,
            .lazy,
            .final,
            .required,
            .convenience,
            .typeMethods,
            .owned
```
It will be great to add an example to the doc.

Thanks!

**Comment by nicklockwood** [comment]
@shimazu2 SwiftFormat's modifier syntax should be  fully compatible with SwiftLint's. You can also just use the exact name of the modifier itself, e.g. `public`, `private`, etc.
