### ISSUE TITLE
Rule request: unneeded_parentheses_in_closure_argument

### ISSUE THREAD

**Issue by malonehedges** [nicklockwood/SwiftFormat#851]
[This rule from SwiftLint](https://github.com/realm/SwiftLint/pull/1684) would help me maintain consistency with when parentheses are used in closures. 

Example:
```swift
// good
let foo = { (bar: Int) in
    print(bar)
}

// bad
call(arg: { (bar2) in

})

// ❌ not acceptable
URLSession.shared.dataTask(with: request, completionHandler: { (sessionData, _, error) in
    // some code
}

// ✅ acceptable
URLSession.shared.dataTask(with: request, completionHandler: { sessionData, _, error in
    // some code
}

// ❌ not acceptable
viewsForEntries.forEach { (entry, view) in /* some code */ }

// ✅ acceptable
viewsForEntries.forEach { entry, view in /* some code */ }
```

**Comment by nicklockwood** [comment]
@malonehedges I think this is already implemented by SwiftFormat's `redundantParens` rule. Is that not working for you?

**Comment by malonehedges** [comment]
I'm sorry I must have missed that! It works for all the cases I described above. I could have sworn I searched for parens and tried all the options. 

Thanks, closing the issue
