### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by ALT-KIK** [nicklockwood/SwiftFormat#854]
I want to make use cases and class diagrams. Are there existing diagrams?

**Comment by nicklockwood** [comment]
I'm not sure I understand the question?

If you are asking whether SwiftFormat can generate class diagrams from your project, then no.

**Comment by ALT-KIK** [comment]
I want to contribute by making work mentioned above.

**Comment by nicklockwood** [comment]
You want to add the ability to make class diagrams as a SwiftFormat feature, or you want to create a diagram of the classes in SwiftFormat?

**Comment by ALT-KIK** [comment]
The second one

**Comment by nicklockwood** [comment]
That's not really something that would be useful I think, as SwiftFormat it mostly used as an application rather than a code library, and the code library only has a few public classes. There are probably other projects that would benefit more from this.

**Comment by ALT-KIK** [comment]
I thought that from these diagrams new contributors will better understand the code structure

**Comment by nicklockwood** [comment]
My concern is mainly that these will get out of date and nobody will want to update them.
