### ISSUE TITLE
private(set) seems to disable --rules wrapAttributes --varattributes prev-line

### ISSUE THREAD

**Issue by luka-zuanovic** [nicklockwood/SwiftFormat#856]
Hi,

I've recently formatted some code with, among others, having enabled:

> --rules wrapAttributes
--varattributes prev-line

and I've noticed that not all attributes (mainly `@objc`) were wrapped. 

This seems to happen only when there's a `private(set)` present. 

My full example:

```swift
@objc private(set) dynamic var myVar = MyClass()
```

Removing the `private(set)` and reformatting will yield expected result:

```swift
@objc
dynamic var myVar = MyClass()
```

Also, manually formatted code

```swift
@objc
private(set) dynamic var myVar = MyClass()
```

will stay the same, as expected.

**Comment by nicklockwood** [comment]
@luka-zuanovic fixed in 0.47.11
