### ISSUE TITLE
convenience seems to disable --rules wrapAttributes --funcattributes prev-line

### ISSUE THREAD

**Issue by luka-zuanovic** [nicklockwood/SwiftFormat#857]
Hi,

similarly to https://github.com/nicklockwood/SwiftFormat/issues/856, having `convenience` present prevents `@objc` beign wrapped. 

My example:

```swift
@objc public convenience init(arg1: Type1,
                              arg2: Type2,
                              arg3: Type3)
{
     // ...
}
```

Removing `convenience` and reformatting will put `@objc` on the previous line.

Manually formatted code in that manner will not be reverted to same line.

**Comment by nicklockwood** [comment]
@luka-zuanovic fixed in 0.47.11
