### ISSUE TITLE
unusedArguments removes necessary parameter types and names in closures

### ISSUE THREAD

**Issue by dennisweissmann** [nicklockwood/SwiftFormat#86]
In version 0.24.2, swiftformat removes some necessary parameter types and names from closures.

Example:

    let collector = { (_ stroke: inout Stroke, _ touch: UITouch, _ view: UIView, _ coalesced: Bool) in
    }

becomes 

    let collector = { (_ _: inout _, _ _: UITouch, _ _: UIView, _ _: Bool) in
    }

and does not compile anymore. This can be prevented by passing --disable unusedArguments

**Comment by nicklockwood** [comment]
Thanks, I'll look into it.

**Comment by nicklockwood** [comment]
Fixed in 0.24.3

**Comment by dennisweissmann** [comment]
You are awesome 🎉
