### ISSUE TITLE
A way to disable all rules by default?

### ISSUE THREAD

**Issue by meherkasam** [nicklockwood/SwiftFormat#862]
Each time I perform an upgrade of the library, new rules are enabled automatically, so I have to go through each new rule that's been added since the previous release and manually disable them. Is there a way to disable all the rules by default and run only specific ones in the `.swiftformat` file? I looked through the `README.md` file but I could not find a way to disable all rules by default.

**Comment by nicklockwood** [comment]
Yes, you can specify just the rules you want with `--rules rule1,rule2,etc`.

**Comment by meherkasam** [comment]
I assume that's when the tool is run via the command line?

I'll explain my situation a bit more. My `.swiftformat` file looks a bit like this (it's quite a bit larger, but I am condensing it here):

```
# Exclude paths
--exclude Pods
# ... other excluded paths

# Rule configurations
--operatorfunc spaced
--nospaceoperators ...,..<
--shortoptionals always
# ...other rule configurations

# Enabled rules
--enable todos # https://google.github.io/swift/#type-variable-and-function-declarations
--enable trailingClosures # https://google.github.io/swift/#trailing-closures
--enable trailingCommas # https://google.github.io/swift/#trailing-commas
# ...other enabled rules

# Disabled rules
--disable andOperator
--disable blankLinesAroundMark
--disable blankLinesAtEndOfScope
--disable blankLinesAtStartOfScope
--disable enumNamespaces
# ...many other disabled rules
```

I run the tool as follows on the root directory of the repo (and run incremental updates on files changed in CI):
`Pods/SwiftFormat/CommandLineTool/swiftformat .`

This way, I am able to keep track of changes I've made to the `.swiftformat` file as part of the git history, and also provide an explanatory comment for why each rule is enabled for other developers.

I was hoping to be able to add something like `--disable all` at the top of the file and then whitelist each rule individually below, rather than having to maintain a separate `Disabled rules` section.

Is there a better way to do this?

**Comment by nicklockwood** [comment]
The swiftformat config file uses the same syntax as the command line. In place of --enable and --disable in your swiftformat file, use --rules. If you include one or more --rules lines, any other rules will be automatically disabled.

**Comment by meherkasam** [comment]
That worked! I didn't realise `--rules` could be used on multiple lines in the configuration file. Thank you for your help!
