### ISSUE TITLE
Extend known tokens for  `preferKeyPath` 

### ISSUE THREAD

**Issue by Parabak** [nicklockwood/SwiftFormat#863]
Hi there,

I found that `preferKeyPath` doesn't apply to the `allSatisfy` scope. Is it on purpose or it's just a matter of adding it to that array of tokens in the guard? 

Best regards, 
Alex.

**Comment by nicklockwood** [comment]
@Parabak I think it's just a matter of adding the token. Currently only `map`, `flatMap` and `compactMap` are supported.

**Comment by nicklockwood** [comment]
@Parabak probably it would make sense to add a user-configurable list of functions.

**Comment by nicklockwood** [comment]
@Parabak I've added support for `allSatisfy`, `filter` and `contains` in 0.48.0

**Comment by Parabak** [comment]
@nicklockwood thanks a lot! I wanted to contribute but somehow didn't find time 🤷‍♂️
