### ISSUE TITLE
Add an option to print warning for specific rule in format mode too

### ISSUE THREAD

**Issue by Cyberbeni** [nicklockwood/SwiftFormat#865]
My specific use case is about the unusedArguments rule. I want to get a warning about unusedArguments but I don't want to format them, as I often hit build (which triggers formatting) during coding.

This can be worked around by having 2 swiftformat.yaml files and calling swiftformat in build phase twice but it would be nicer to only maintain 1 rules file.

**Comment by nicklockwood** [comment]
Yeah, I definitely want to add a --lintonly option for rules. If you want to have a stab at adding it yourself, be my guest.
