### ISSUE TITLE
Possible regression in closure parameters

### ISSUE THREAD

**Issue by alexito4** [nicklockwood/SwiftFormat#879]
I updated from 0.47.8 to 0.47.12 and the formatter did a change on the codebase (without any change on the config). I've updated version by version and found that it was introduced in **0.47.9**.

0.47.8:
```
Completable.createFromAPICall { [weak self] (completion: @escaping (Error?) -> Void) -> Operation? in
```

0.47.9+:
```
Completable.createFromAPICall { [weak self](completion: @escaping (Error?) -> Void) -> Operation? in
```

Note the removal of the space between the capture list and the parameters. 

BTW if I remove the `@escaping` the space is added again, but of course the compiler complains.

**Comment by nicklockwood** [comment]
@alexito4 fixed in 0.47.13.
