### ISSUE TITLE
allman style not working

### ISSUE THREAD

**Issue by kaizimmer** [nicklockwood/SwiftFormat#88]
Hello Nick,
first I'd like to say: **great job**. I highly appreciate your work!

Unfortunately the **allman** option doesn't seem to work. 

First I tried to set it via style inference (although it outputs "--allman true"):

```
swiftformat --inferoptions Template.swift
inferring swiftformat options from source file(s)...
options inferred from 1/1 files in 0.02s

--indent 8 --allman true --wraparguments afterfirst --removelines disabled --wrapelements disabled --exponentcase lowercase --stripunusedargs always --header ignore --insertlines disabled --binarygrouping none --empty void --ranges spaced --trimwhitespace always --hexliteralcase uppercase --linebreaks lf --decimalgrouping none --commas always --comments indent --ifdef indent --octalgrouping none --hexgrouping none --semicolons inline
```

Which didn't work.

Then I tried to set it directly:

`swiftformat --allman true`

Which also didn't work.

Version 0.24.3 (homebrew installation)

**Comment by nicklockwood** [comment]
@kaizimmer it seems to be working for me. Can you include a sample file that it's failing on?

**Comment by kaizimmer** [comment]
Hello @nicklockwood 

Here are two files with which I tried it once more. (Same result)

`» swiftformat --inferoptions StyleTemplateAllman.swift                                                         kai@valkyrie-mbp
inferring swiftformat options from source file(s)...
options inferred from 1/1 files in 0.02s

--indent 4 --allman true --wraparguments disabled --removelines disabled --wrapelements disabled --exponentcase lowercase --stripunusedargs always --header ignore --insertlines disabled --binarygrouping none --empty void --ranges spaced --trimwhitespace always --hexliteralcase uppercase --linebreaks lf --decimalgrouping none --commas always --comments indent --ifdef indent --octalgrouping none --hexgrouping none --semicolons inline`

`» swiftformat CurrencyLabel.swift
running swiftformat...
swiftformat completed. 1/1 files updated in 0.05s`


[StyleTemplateAllman.swift](https://github.com/nicklockwood/SwiftFormat/files/761187/StyleTemplateAllman.txt)

[CurrencyLabel.swift](https://github.com/nicklockwood/SwiftFormat/files/761189/CurrencyLabel.txt)

**Comment by nicklockwood** [comment]
@kaizimmer it seems like it worked correctly on CurrencyLabel.swift, except for the line

    var amount: NSNumber? {

Which was not correctly converted to allman. Does that match your experience?

**Comment by kaizimmer** [comment]
@nicklockwood Can you attach your formatted file please? In my case there were noch visible changes at all.

**Comment by nicklockwood** [comment]
Here. There are certainly some issues, but it sounds like you're seeing a different problem.

[CurrencyLabel.txt](https://github.com/nicklockwood/SwiftFormat/files/761688/CurrencyLabel.txt)

**Comment by kaizimmer** [comment]
Damn, this looks quite good! Perhaps I should try another installation type or compile it by myself. Anyway. Thx for the fast answer! 👍  :)

**Comment by nicklockwood** [comment]
@kaizimmer no worries. Very strange issue though.

I tried uninstalling swiftformat and reinstalling from homebrew, but it still works the same for me.

The specific command I used was:

`swiftformat --allman true ~/Downloads/CurrencyLabel.swift`

There's no --verbose option currently, but something you could try is:

`swiftformat --allman true CurrencyLabel.swift --output ModifiedCurrencyLabel.swift`

That will at least verify if it's actually writing a file.

**Comment by nicklockwood** [comment]
@kaizimmer ah, I think I may see the problem. swiftformat doesn't remember the CLI options that you set between runs - you need to include them each time you run it.

**Comment by kaizimmer** [comment]
@nicklockwood Awesome! Thank you for your support! :) 
Thought those settings would be consistent. So it would be nice if there would be a config file somewhere in the project folder (like that in swiftlint for example) that is automatically read and used by swiftformat.

**Comment by nicklockwood** [comment]
@kaizimmer yeah, a config file is planned eventually. In the meantime, you could just put the config options in a bash script and store it in the root directory.

The issue with "var amount: NSNumber? {" has been fixed in 0.24.4.

**Comment by kaizimmer** [comment]
There's one more issue regarding Allman Style. The curly braces following the guard statement aren't reformatted.

`guard let value = value, let stringValue = CurrencyLabel.numberFormatter.string(from: value) else { return }`

**Comment by nicklockwood** [comment]
@kaizimmer yes, that's deliberate. I don't automatically reformat one-line expressions (e.g. where both the opening and closing brace are on the same line) onto multiple lines.

I may add a rule for that in future, but it's not covered by any of the existing rules.

**Comment by kaizimmer** [comment]
Ah, good to know. Thank you for the information. :)
