### ISSUE TITLE
Rename `master` to `main` ?

### ISSUE THREAD

**Issue by PompeiaPaetenari** [nicklockwood/SwiftFormat#880]
We just got a company memo to do this... and as we pull in your repo, it means that the `master` branch is seen on the fork by their scanners.  Curious if you are able/willing to do this for SwiftFormat? :D. Not high priority, but it would be cool.

https://github.com/github/renaming

Thanks!!

**Comment by nicklockwood** [comment]
I actually tried this before, but found that it broke integration with Mint. I'll see if that's now been resolved.

**Comment by rastersize** [comment]
@nicklockwood I ran into the same issue with a repo of mine - that was created with a default branch named `main`. This PR https://github.com/yonaskolb/Mint/pull/204 needs to be merged into Mint for it to work. Along with a new version of Mint that is.

**Comment by gwynne** [comment]
@nicklockwood Can this be revisited? Mint apparently still hasn't shown the slightest interest, and every package that lets them get away with it is providing that much less incentive to put forth the fairly trivial effort involved. You can always just say `mint install nicklockwood/SwiftFormat@main` instead, [the way this package started advising its users to do](https://github.com/XcodeMigrate/XcodeMigrate/pull/30). (I am not a Mint user, admittedly; TBH I'd never heard of it until I read the discussion in this issue.)

**Comment by nicklockwood** [comment]
@gwynne agreed, they've had enough time. It's a breaking change so I'll leave it for a 0.x release, but I'll make a note to do this.

**Comment by nicklockwood** [comment]
I've renamed master to main, and added the suggested workaround for Mint in the README. I've done it in advance of the next release since it doesn't seem like anything in the actual code needs to change. There's a small possibility I may have to roll back if there are issues with the release, but everything seems OK so far.
