### ISSUE TITLE
Inappropriate behavior of "Override methods which only call super"

### ISSUE THREAD

**Issue by RomanTysiachnik** [nicklockwood/SwiftFormat#883]
## Description 
Hi!
I have that method in my class
```swift
  @discardableResult
  override func connectViewModel(_ viewModel: BaseViewModelProtocol?) -> Disposable {
    cast(viewModel, onSuccess: connect(root:)) ?? super.connectViewModel(viewModel)
  }
  
  private func connect(root: SomeSpecificViewModelProtocol) {
    //...
  }
 ```
 
 The purpose of that method is to cast the `viewModel` to `SomeSpecificViewModelProtocol` and if it is possible, execute `connect(root:)` method. If the model is nil or has a different type, it should use an implementation of it's parent.
 
 As a result, I recieve a warning, that this method is overriden only to execute parent's method.

**Comment by nicklockwood** [comment]
@RomanTysiachnik SwiftFormat has no rules relating to `override`. Did you meant to file an issue against SwiftLint instead?

**Comment by RomanTysiachnik** [comment]
Hell yeah.... Got confused a bit with my Danger output... Thanks for your notice and sorry for the inconvenience :)
