### ISSUE TITLE
[Feature Request] Wrapping of ternary operator when `--maxwidth` is used

### ISSUE THREAD

**Issue by rastersize** [nicklockwood/SwiftFormat#888]
Hi! I’d like to request an improvement to the formatting of ternary operators when line length wrapping is enabled.

For example given `--maxwidth 120` and the following code:

```swift
let editingInsets = clearButtonMode == .whileEditing ? UIEdgeInsets(top: 8, left: 16, bottom: 8, right: 26) : textInset
```

My expectation is that it would be formatted like this:

```swift
let editingInsets = clearButtonMode == .whileEditing
    ? UIEdgeInsets(top: 8, left: 16, bottom: 8, right: 26)
    : textInset
```

However right now it’s formatted like this, which I don’t find as nice and bit harder to read:
```swift
let editingInsets = clearButtonMode == .whileEditing ? UIEdgeInsets(top: 8, left: 16, bottom: 8, right: 26) :
    textInset
```

**Comment by nicklockwood** [comment]
Landed in 0.49.0
