### ISSUE TITLE
Support for JSON output

### ISSUE THREAD

**Issue by danyf90** [nicklockwood/SwiftFormat#890]
Hello 👋 
At the moment I think it is not possible to configure the `swiftformat --lint` output format.
Having the output in a more dev friendly format, would help when the output of the command need to be parsed (e.g. to report errors in CI).

Could you please let confirm that it is currently not supported?
Do you think it is a feature that could be added in the future?

For example, swiftlint can be executed as:
```
swiftlint lint  --reporter json
```
to obtain the warning and errors in JSON format, which can then be easily parsed to retrieve the list of warnings and errors.

Thank you,
Daniele

**Comment by nicklockwood** [comment]
@danyf90 SwiftFormat doesn't currently have a JSON output option. It would be fairly easy to add.

**Comment by danyf90** [comment]
@nicklockwood I have tried to implement the support [here](https://github.com/nicklockwood/SwiftFormat/pull/900), let me know if you have any question 🙌

**Comment by nicklockwood** [comment]
@danyf90 landed in 0.48.0
