### ISSUE TITLE
Cannot build this project in XCode

### ISSUE THREAD

**Issue by dylanb** [nicklockwood/SwiftFormat#891]
I am able to build this project using the command line

`xcodebuild -project SwiftFormat.xcodeproj -scheme "SwiftFormat (Framework)" -sdk macosx clean build test`

But when I try to build it in XCode, I get the following error

`Cannot load module 'swiftformat' as 'SwiftFormat'`

[Here](https://github.com/nicklockwood/SwiftFormat/blob/master/Tests/ArgumentsTests.swift#L33)

How do I build and debug the module in XCode?

**Comment by nicklockwood** [comment]
@dylanb what are you trying to do exactly? Do you want to make changes to SwiftFormat itself, or are you trying to use the SwiftFormat module in another application?

**Comment by nicklockwood** [comment]
@dylanb is your Mac set up with a case-sensitive filesystem by any chance?

**Comment by dylanb** [comment]
> @dylanb what are you trying to do exactly? Do you want to make changes to SwiftFormat itself, or are you trying to use the SwiftFormat module in another application?

I am trying to learn because it is using a bunch of features that are not well documented

> @dylanb is your Mac set up with a case-sensitive filesystem by any chance?

No, it is set up with non-case sensitive file system

```
touch File.txt
vi file.txt
```

Ends up editing File.txt with vi

**Comment by nicklockwood** [comment]
Hmm, well I'm not sure what the issue could be then. But the way I develop and test SwiftFormat is just to run the SwiftFormat library test suite. Running the command line app should build the app itself.

The error you are getting is confusing because it sounds like it's trying to test the swiftformat app instead of the SwiftFormat module, which I've never seen happen before.

**Comment by nicklockwood** [comment]
Sorry, to be clear, I run the tests from within Xcode, not on the command line.

**Comment by nicklockwood** [comment]
I wonder if by building with the command line first you may have created some files in the build directory that are confusing Xcode? Perhaps try clearing derived data?

**Comment by dylanb** [comment]
tried deleting derived data, recloned the project, only thing that works is to comment out the tests, closing the issue because I can get past it but you might want to see if you can repro on a brand new machine with a new version of XCode that does not have your history

**Comment by jjgp** [comment]
I think this problem occurs if you open the project from the root as if it were a Swift package (`open -a "Xcode" .`) as opposed to opening the provided Xcodeproj directly (`open -a "Xcode" SwiftFormat.xcodeproj`)?.. At least that's the trap I fell into 😄

**Comment by Lutzifer** [comment]
@jjgp what happens if you use `xed .` to open Xcode?

**Comment by jjgp** [comment]
Hey @Lutzifer I just cleared derived data and tried `xed .` and still see the load module error. Thanks for sharing as I hadn't known about `xed .` ha. For a couple more data points, I am on Xcode 14.0.1 and using the corresponding Swift 5.7 toolchain
