### ISSUE TITLE
fileHeader on SwiftFormat for Xcode

### ISSUE THREAD

**Issue by carlosefonseca** [nicklockwood/SwiftFormat#893]
It seems that fileHeader does not work when running via the Xcode Extension. An error appears at the top of the file saying "Failed to apply {file} template in header as file name was not provided".
Is this a bug or isn't fixable? If it's not fixable, could it be ignored so that other attempts (e.g. via command line) can fix it?

**Comment by nicklockwood** [comment]
The file name isn't available when running in extension mode, so if your header template includes file name it can't work in the extension.

There are a couple of ways I can solve it, either by silently disabling the rule when running in the extension, or by doing something smarter, like fuzzy-matching the existing file name if already present in the file.

In the meantime, a workaround would be for you to disable the fileHeader in the SwiftFormat for Xcode app. That won't prevent it from working via commandline.

**Comment by carlosefonseca** [comment]
That's what I was thinking. I'm using both the Xcode extension and a pre-commit and I want the settings to be the same, so I'm just gonna disable it all together.

Thanks

**Comment by nicklockwood** [comment]
@carlosefonseca fixed in 0.48.0

**Comment by fabianmuecke** [comment]
@nicklockwood Doesn't work for me in 0.50.3 and Xcode 14.1. 🤔

**Comment by cavhat** [comment]
@nicklockwood Still broken in 0.52.3 and Xcode 14.3.1.

**Comment by nicklockwood** [comment]
@fabianmuecke @cavhat the "fix" that was applied was this:

> Xcode Extension now silently ignores rules requiring file info that isn't available to extensions

It's not possible to actually make the fileHeader rule work in Xcode due to the sandboxing restriction that prevents me from reading the name or modification date for the current file.
