### ISSUE TITLE
Ability to copy-paste my `.swiftformat` config's contents into the Xcode editor, and have that "apply" all the checkboxes accordingly

### ISSUE THREAD

**Issue by tsheaff** [nicklockwood/SwiftFormat#894]
It's a bit tricky to give instructions to the team for every single checkbox to change in their Xcode plugin, expecially when it's not a one-to-one between the rule flags `--foo` in the config and the name of the rule it impacts — correlating these requires searching the full rules.md to correlate them.

It would be great if there were just a text field I could paste my entire `.swiftformat` file into, and the Xcode plugin would interpret that and set all of my checkboxes exactly the way that config specifies.

**Comment by nicklockwood** [comment]
It could maybe be clearer, but you can load your .swiftformat file from the file menu, and it will apply all the settings.

**Comment by VinceBurn** [comment]
The companion app can save all its settings to a .swiftformat file. You can then share the file. You can double click the .swiftformat file, it will open the app and load the content of the file.

**Comment by nicklockwood** [comment]
@tsheaff I forgot to mention, you can also drag a .swiftformat file onto the SwiftFormat for Xcode icon, and it will apply automatically. Does that solve your problem, or would a text field still be useful?

**Comment by tsheaff** [comment]
OK thanks for clarifying! Closing.
