### ISSUE TITLE
Indentation of empty lines different from Xcode default

### ISSUE THREAD

**Issue by maun** [nicklockwood/SwiftFormat#90]
In Xcode empty lines automatically have the previous indentation level.
This is removed by the trailing whitespace rule which generates a lot of changes.

Can this be changed or at least made configurable?

**Comment by nicklockwood** [comment]
@maun you can disabled this using `--trimwhitespace nonblank-lines`

Note that if you use `--inferoptions` to set up SwiftFormat for your project, it will detect this preference automatically.
