### ISSUE TITLE
fileHeader rule breaks swift scripts

### ISSUE THREAD

**Issue by VitoMatarazzo** [nicklockwood/SwiftFormat#901]
Hello, I'm having a small issue when applying SwiftFormat rules in a project: in the project folder, other than the normal source files, we have also a script file, written in swift, that we run once in a while from the command line for some project configuration. We have configured SwiftFormat with the `fileHeader` rule, so we have consistent header across files, and this applies of course to all `.swift` files.

The problem is that the script must start with the line:
`#!/usr/bin/swift` 
in order to be executed from the command line as other scripts (with the syntax `./fileName.swift`). After applying SwiftFormat rules the header line is added on top of the script file and so executing the script fails. We can always remove the header line every time we need to run the script, but of course it's not ideal.

Is there a way to avoid adding the file header on top of the `#!...` line, without excluding the script file from SwiftFormat (which we'd prefer to avoid). Do you see any other solution?
Thanks

**Comment by nicklockwood** [comment]
@VitoMatarazzo there isn't a great solution for this now other than to have a separate .swiftformat configuration file that disables the fileHeader rule just for that file. I'll look at changing the way fileHeader handles scripts.

**Comment by nicklockwood** [comment]
@VitoMatarazzo fixed in 0.48.0
