### ISSUE TITLE
Support Cocoapods Installation

### ISSUE THREAD

**Issue by simorgh3196** [nicklockwood/SwiftFormat#91]
Thank you for the great project :)

Is there any solution to install SwiftFormatter by CocoaPods?
I want to run formatter with SwiftFormat in `Run Script Build Phases`.
ex) [SwiftLint](https://github.com/realm/SwiftLint), [Swimat](https://github.com/Jintin/Swimat).

**Comment by nicklockwood** [comment]
You can install the SwiftFormat library via CocoaPods, but not the command line tool itself.

There are instructions in the README for running it via the run script build phase, but the suggested approach is to put a copy of the binary in your project directory and run it via the script.

**Comment by simorgh3196** [comment]
Thanks for the reply.

If copy binary to project, It is difficult to version maintenance of the lib.
Cocoapods CLI installation make to easier to maintenance.
I hope doing to easier.

Could you support CLI installation with Cocoapods?

**Comment by nicklockwood** [comment]
Added in 0.24.6
