### ISSUE TITLE
Option "wrapMultilineStatementBraces" don't work properly

### ISSUE THREAD

**Issue by tomiy-tomiylab** [nicklockwood/SwiftFormat#916]
I'm curious if it's an issue or intended behavior, but when I run SwiftFormat with wrapMultilineStatementBraces enable on that code :
```
// pattern1
if self.animationLabel == nil 
{
    print("keiskaran")
 }
```
It is formatted to:
```
// pattern2
if self.animationLabel == nil {
    print("keiskaran")
 }
```
and I try to  run SwiftFormat with wrapMultilineStatementBraces disable  on  pattern1, it is formatted pattern2.
I want to format to pattern1. what should I do?
Is this bug?

**Comment by nicklockwood** [comment]
@tomiy-tomiylab this change is applied by the `braces` rule, not `wrapMultilineStatementBraces`. You can either disable that rule with:

```
--disable braces
```

Or use

```
--allman true
```

to use brace-on-next-line style.
