### ISSUE TITLE
Using --filelist reads config per each file

### ISSUE THREAD

**Issue by karlpuusepp** [nicklockwood/SwiftFormat#917]
Our project setup includes autogenerated xcfilelists for each target which we use for custom build scripts. I figured I could also use it for the SwiftFormat command but the performance penalty is rough. From the script output it seems that the config is read for every single file in the list. I would expect performance to be at least on par with default execution (if not slightly better). Is this intended?

Normal invocation (with target directory):
```
Running SwiftFormat...
Reading config file at /Users/[...]/Sources/.swiftformat
SwiftFormat completed in 0.07s.
0/103 files formatted.
```

With `--filelist "${SCRIPT_INPUT_FILE_LIST_0}"`
```
Running SwiftFormat...
Reading config file at /Users/[...]/Sources/.swiftformat
Reading config file at /Users/[...]/Sources/.swiftformat
Reading config file at /Users/[...]/Sources/.swiftformat
Reading config file at /Users/[...]/Sources/.swiftformat

[...]

Reading config file at /Users/[...]/Sources/.swiftformat
Reading config file at /Users/[...]/Sources/.swiftformat
Reading config file at /Users/[...]/Sources/.swiftformat
Reading config file at /Users/[...]/Sources/.swiftformat
SwiftFormat completed in 1.05s.
0/103 files formatted.
```

**Comment by nicklockwood** [comment]
@karlpuusepp fixed in 0.48.1
