### ISSUE TITLE
redundantType rule causes build failure

### ISSUE THREAD

**Issue by calda** [nicklockwood/SwiftFormat#919]
We're adopting the `redundantType` rule, and noticed a case where it would cause a build failure:

### Before

```swift
var cancellations: [Void] = [Void]()
```

### After

```swift
// 🛑 variable 'cancellations' inferred to have type '[Void]', which may be unexpected
//    add an explicit type annotation to silence this warning
var cancellations = [Void]()
```

This error is easy to work around (by changing it to `var cancellations: [Void] = []`)

**Comment by nicklockwood** [comment]
@calda fixed in 0.48.1
