### ISSUE TITLE
No empty line before //MARK after class

### ISSUE THREAD

**Issue by H-G-Hristov** [nicklockwood/SwiftFormat#929]
I cannot an report to this issue:

![Screen Shot 2021-05-13 at 11 10 22 AM](https://user-images.githubusercontent.com/47526411/118097836-da808e80-b3db-11eb-8ac6-a83bceb0603b.png)

Empty lines are added before `// MARK` unless it is after a `class` declaration, which then results in:

```Swift
class B {
    // MARK: - d -

    var b: D?

   // MARK : - d -
   
   var d: D?
}
```

**Comment by nicklockwood** [comment]
You can fix this by adding `--disable blankLinesAtStartOfScope` to your config.

**Comment by H-G-Hristov** [comment]
But then you cannot have blank lines at the start of scope anywhere? Wouldn't it make sense that the option for MARK takes precedence over the blank lines?

**Comment by nicklockwood** [comment]
Disabling the rule doesn't prevent you adding blank lines, it just doesn't enforce them. In most style guides I've encountered the preference for no blank line at start takes precedence over the blank line before MARK.

I could add another option to control that, but there are so many possible permutations it's not really clear how to support them all.
