### ISSUE TITLE
Stripping used closure parameters (part 2)

### ISSUE THREAD

**Issue by mergesort** [nicklockwood/SwiftFormat#93]
This issue is similar to the one posted in #80. I confirmed it's still happening with the latest version (0.24.5).

This expression [unintentionally?] gets formatted from:

```
first().then { () -> Void in
    // blah blah blah
}.ignoreErrors()
```

To this:

```
first().then { () in
    // blah blah blah
}.ignoreErrors()
```

The return type is expected to be of type `AnyPromise` in this case, which telling it `() -> Void` overwrote, but now they're not semantically the same. You can reproduce this by trying this in any project with [PromiseKit](https://github.com/mxcl/PromiseKit) installed.

Thanks a lot! Lemme know if there's any more information I can provide to help.

**Comment by nicklockwood** [comment]
@mergesort fixed in 0.24.6.

This was actually a deliberate feature, but it was an overreach on my part - removing `-> Void` from regular function signatures is harmless, but doing it for closures can apparently change the meaning.
