### ISSUE TITLE
Generic attributes wrapped on generic clause with wrapAttributes --varattribbutes prev-line 

### ISSUE THREAD

**Issue by luka-zuanovic** [nicklockwood/SwiftFormat#934]
Hi,

very similar to #923 (sorry I did not notice that then as well).

If a property wrapper contains a generic specification

```swift
@OuterType.Generic<WrappedType> var myVar: WrappedType
```

it would get formatted like this: 

```swift
@OuterType.Generic
<WrappedType>
var myVar: WrappedType
```

I hope this will now cover all property wrapper cases.

**Comment by nicklockwood** [comment]
@luka-zuanovic fixed in 0.48.2
