### ISSUE TITLE
Nested switch statements

### ISSUE THREAD

**Issue by gatoAlfa** [nicklockwood/SwiftFormat#94]
Great utility.

I have a `switch` and one of the `case` options is another `switch`. My expectation is that the `case` options from the inner `switch` will be indented more that the `case` options for the outer `switch` but they are all indented at the level of the first `switch`

Maybe I'm missing something in the settings or in my expectations.

Thanks in advance for tour help or clarification.

--GA

**Comment by nicklockwood** [comment]
@gatoAlfa sounds like a bug. I'll look into it. Thanks!

**Comment by nicklockwood** [comment]
@gatoAlfa I've not been able to reproduce this - can you provide a code sample that demonstrates the problem?

**Comment by gatoAlfa** [comment]
sure, this is a fragment sanitized from a big pice of code,  not an example of good coding practices, but still shows the issue:

[caseTest.swift.txt](https://github.com/nicklockwood/SwiftFormat/files/800319/caseTest.swift.txt)

swiftformat, version 0.24.6
thanks again.

**Comment by nicklockwood** [comment]
Fixed in 0.24.7. Thanks!

**Comment by gatoAlfa** [comment]
Cool. Thank you. Then the problem was not the nested case but the `0..n` operator, funny side effect. Regards,

--ga

**Comment by nicklockwood** [comment]
@gatoAlfa yeah, basically that the parser thought the inner switch ended when it hit the `..<`, so it thought the subsequent `case` statements were part of the outer switch, which is why it indented them to match that one instead.
