### ISSUE TITLE
`typeSugar` rule breaks build when sugaring protocol composition

### ISSUE THREAD

**Issue by calda** [nicklockwood/SwiftFormat#941]
We're [adopting](https://github.com/airbnb/swift/pull/127) the `typeSugar` rule, and I encountered a case where it would cause the build to fail:

### Before

```
protocol Foo { }

let fooView: Optional<UIView & Foo> = nil
```

### After running `swiftformat . --rules typeSugar`

```
protocol Foo { }

let fooView: UIView & Foo? = nil
```

### Expected

```
protocol Foo { }

let fooView: (UIView & Foo)? = nil
```

**Comment by nicklockwood** [comment]
@calda fixed in 0.48.3
