### ISSUE TITLE
Possible bug in indent rule

### ISSUE THREAD

**Issue by meherkasam** [nicklockwood/SwiftFormat#946]
I observed this behaviour in 0.47.11 and the latest master.

Example code:

```
var myVariable: (someParam: SomeParamType)? {
    guard let foo = foo,
        case let .firstCase(someArg) = someVar,
        case let .secondCase(someOtherArg) = someOtherVar
    else {
        return nil
    }

    return something
}
```

Command run:

```
swiftformat --rules indent --indent 4 test.swift
```

I expected the code to remain the same. Instead, the file updates to the following:

```
var myVariable: (someParam: SomeParamType)? {
    guard let foo = foo,
          case let .firstCase(someArg) = someVar,
          case let .secondCase(someOtherArg) = someOtherVar
    else {
        return nil
    }

    return something
}
```

The change is that the tool adds 2 additional spaces of indentation to each of the `case` lines, making them offset by 6 spaces from the start of the `guard` line.

**Comment by nicklockwood** [comment]
@meherkasam this isn't a bug, this is the indentation style used since Xcode 12, where comma-delimited wrapped expressions are aligned vertically. SwiftFormat follows the same style, but if you want an option to disable this I can open a feature request for that.

**Comment by meherkasam-square** [comment]
Ohh that makes a lot of sense. Thank you for providing the clarification. Please feel free to resolve the issue.
