### ISSUE TITLE
Add `hoistTry` and `hoistAwait` rules

### ISSUE THREAD

**Issue by nicklockwood** [nicklockwood/SwiftFormat#948]
Similar to the `hoistPatternLet` rule, these would move repeated `try` or `await` keywords to the beginning of an expression, e.g.

```swift
greet(await name, await surname)
await greet(name, surname)
```

**Comment by pronebird** [comment]
Came here because CI snapped in a half. It's a bit counter-intuitive though because `greet()` is not throwing nor async. So why would I `try` a non-throwing function. Meh. Disabling this rule for now in my config.

**Comment by facumenzella** [comment]
Can you please elaborate more on the issue you're experiencing?

**Comment by nicklockwood** [comment]
@facumenzella There was a bug with try inside XCAssert functions (now fixed in 0.50.1)

**Comment by nicklockwood** [comment]
@pronebird it's sometimes helpful to be able to see which lines throw at a glance, but yes I can totally understand not wanting this enabled. I enable most rules by default because it aids discoverability, and reveals bugs quicker - it doesn't necessarily mean I think everyone should use them.

**Comment by revolter** [comment]
I feel like this rule was implemented incorrectly.

The reasoning mentioned "repeated `try` or `await` keywords" but the rule also flags cases where only one keyword is present.

If it would have only flagged cases where actually repeated (2+) keywords were used, it would have made more sense IMO.

**Comment by calda** [comment]
Somebody could add an option to have the rule behave that way. PRs welcome!
