### ISSUE TITLE
Spurious unscore added

### ISSUE THREAD

**Issue by garricn** [nicklockwood/SwiftFormat#95]
A spurious underscore is adding when running swiftformat on file.

File contains:

`let tag = 123123`

After running swiftformat with default settings on file:

Expected: `let tag = 123123`
Actual: `let tag = 123_123`

**Comment by garricn** [comment]
So my team told me that this is a feature not a bug :) What is the rule if we wanted to disable it?

**Comment by nicklockwood** [comment]
The option you want is `--decimalgrouping`, but I'd suggest running `swiftformat --inferoptions "/path/to/your/code/"` before doing anything else, then it will give you the options that best match your existing style.

**Comment by garricn** [comment]
@nicklockwood Thank you! However, I'm dealing with 200 legacy swift files that were written with no sense of style whatsoever!
