### ISSUE TITLE
Using arguments as a build phase in Xcode project

### ISSUE THREAD

**Issue by rx2130** [nicklockwood/SwiftFormat#97]
Hi, I'm wondering if there is any way to add ```swiftformat```  command-line argument as a build phase in my Xcode project. I do have the command-line tool installed. It works when I follow the instruction set the script as ```"swiftformat" "sourceCodeFolder"```. However, I couldn't pass in any argument in that case. So I tried to ```swiftformat --indent tabs --diable unusedArguments sourceCodeFolder``` but it's not formatting at all.

Can you add the proper way to add build phase arguments in the readme? Thanks!

**Comment by nicklockwood** [comment]
@rx2130 That should work, although you have a typo in "disable". Maybe try putting the path first, e.g.

    "path/to/swiftformat" "${SRCROOT}/sourceCodeFolder"  --indent tabs --disable unusedArguments

It's also fine to put the `--argument` in quotes if that helps:

    "path/to/swiftformat" "${SRCROOT}/sourceCodeFolder"  "--indent" tabs "--disable" unusedArguments

**Comment by rx2130** [comment]
Thanks for the quick reply. I was pasting the wrong command from terminal lol. Works like a charm now! Cheers!
