### ISSUE TITLE
Incorrectly removing parens from negated Bools since 0.48.7

### ISSUE THREAD

**Issue by Cyberbeni** [nicklockwood/SwiftFormat#971]
Also installed 0.48.8 but same results.
The parens get removed from this code resulting in compiler error:
```swift
var a = true
var b = (!a).description
```

**Comment by nicklockwood** [comment]
Ah, darn - this is a different bug 🤦‍♂️

**Comment by nicklockwood** [comment]
@Cyberbeni fixed in 0.48.9
