### ISSUE TITLE
Possibility to remove comments generated by organizeDeclarations & order

### ISSUE THREAD

**Issue by Jasperav** [nicklockwood/SwiftFormat#973]
I don't want the // MARK comments generated by the organizeDeclarations feature. I did set an empty option for categorymark, but that would generate an empty comment (//).

Furthermore the rule also places the private properties at the bottom of the type. Would it be possible to configure that? I would like to have the private properties below my public/internal properties.

**Comment by nicklockwood** [comment]
@Jasperav I don't think it's possible to do either of these yet (other than by disabling the `organizeDeclarations` rule altogther).

Having empty `--categorymark` remove the comment altogether is a good idea and should be simple to implement. Configuring property order is a little trickier as we'll need to come up with a way to specify the order in the arguments.

**Comment by calda** [comment]
Would the suggestion in #735 work for your use case @jasperav? 

> That means sorting by type first and then by category. That means all properties are at the top sorted from public-> internal -> private, then lifecycle methods and then instance methods.

Some sort of `--declarationorder by-category` (with support for specifying to category ordering) and `--declarationorder by-access-level` (the existing behavior) options would be a really reasonable extension within the existing implementation of this rule.

It also makes sense to have an option to disable the mark comments, great idea!

**Comment by Jasperav** [comment]
@calda Yes, if the --categorymark is empty, the mark shouldn't be there.

**Comment by calda** [comment]
#1016 adds support for a `--markcategories false` option, how does that look?

**Comment by Jasperav** [comment]
@calda That looks great! Thanks :)
