### ISSUE TITLE
shortoptionals breaks composite types

### ISSUE THREAD

**Issue by romikabi** [nicklockwood/SwiftFormat#980]
Code:
```swift
protocol A {}
protocol B {}

let a: Optional<A & B> = nil
```

Expected: no change, or
```swift
protocol A {}
protocol B {}

let a: (A & B)? = nil
```

Actual:
```swift
protocol A {}
protocol B {}

let a: A & B? = nil // does not compile
```

**Comment by nicklockwood** [comment]
@romikabi I'm not able to reproduce this in 0.48.11 with the example you've provided. Can you provide a standalone code sample that demonstrates the problem? Also if you are using any custom configuration settings, that may be relevant.

**Comment by romikabi** [comment]
I did a little more digging and was able to determine that error is no longer present in 0.48.11 and persists in my project because it uses 0.40.10. Sorry for the inconvenience!
