### ISSUE TITLE
`redundantSelf` breaks extensions of types with `@dynamicMemberLookup`

### ISSUE THREAD

**Issue by kylebshr** [nicklockwood/SwiftFormat#983]
extensions of types `@dynamicMemberLookup` still have `self` removed with the `redundantSelf` rule. e.g.:

```swift
@dynamicMemberLookup
public struct Foo { ... }

extension Foo {
    func bar() {
        print(self.baz) // this self is required, but removed
   }
}
```

**Comment by nicklockwood** [comment]
@kylebshr I've fixed (or at least improved) this in 0.48.12. It still won't work correctly in cases where the type and extension are in different files.
