### ISSUE TITLE
How to change decimalgrouping value?

### ISSUE THREAD

**Issue by Jasperav** [nicklockwood/SwiftFormat#985]
I think my .swiftformat is read incorrectly. This is my .swiftformat file:

```
--decimalgrouping 6,9
--enable isEmpty
--enable wrapSwitchCases
--enable wrapEnumCases
--disable wrapMultilineStatementBraces
--maxwidth 80
--wraparguments before-first
--wrapparameters before-first
--wrapcollections before-first
--wrapconditions before-first
```

When I run `swiftformat --inferoptions .`, this is the output:

```
Inferring swiftformat options from source file(s)...
Reading config file at /Users/me/Documents/Github/project/.swiftformat
Options inferred from 156/156 files in 0.13s.

--binarygrouping none --decimalgrouping 3,4 --hexgrouping none --octalgrouping none --wraparguments before-first --wrapcollections before-first --wrapparameters before-first
```

I was hoping the decimalgrouping would have the same value as I specified. I tried `none` and `ignore` as values, but the output remains `3,4).

**Comment by Jasperav** [comment]
@nicklockwood Welp, thanks!

**Comment by nicklockwood** [comment]
I guess that could be clearer in the docs, and also perhaps a `--currentoptions` command or something to do what you were expecting `--inferoptions` to do would be a useful addition - I'll add a feature request for it.
