### ISSUE TITLE
[Feature Request] “\(string)” -> string

### ISSUE THREAD

**Issue by Co2333** [nicklockwood/SwiftFormat#996]
It’s some what unknown magic put me to write code like `"\(toPath.path)"` on a really high frequency. I think we can do something in swiftformat right? 😭

**Comment by nicklockwood** [comment]
@Co2333 I don't understand what it being requested here?

**Comment by nicklockwood** [comment]
@Co2333 ah wait, I think I understand. You want to remove "\(...)" when it's redundant because the value is already a string?

**Comment by Co2333** [comment]
I mean `“\(string)”` can be replaced by `string`. Yes.

**Comment by nicklockwood** [comment]
@Co2333 unfortunately that's very hard for SwiftFormat to do, because it doesn't know the types of variables/properties. SwiftLint might be able to because it uses the compiler.

**Comment by Co2333** [comment]
I see. 😢
